export const hubPartners = [
  {
    id: "partner_workforce_001",
    name: "Franklin Workforce Partner",
    type: "Workforce Provider",
    sector: "workforce",
    serviceLanes: ["training", "job-placement", "case-support", "reporting"],
    geography: ["Franklin County", "Central Ohio"],
    capacity: 82,
    responseSpeed: 91,
    completionRate: 88,
    verifiedOutcomeRate: 84,
    pricingTier: "competitive",
    trustScore: 89,
    businessNeeds: ["employer partners", "transportation partners"],
    offers: ["training", "placement", "workforce reporting"],
    idealMatches: ["staffing", "transportation", "case-management", "recovery"],
  },
  {
    id: "partner_transport_001",
    name: "Central Mobility Services",
    type: "Transportation Partner",
    sector: "transportation",
    serviceLanes: ["transportation", "ride-coordination"],
    geography: ["Franklin County"],
    capacity: 68,
    responseSpeed: 86,
    completionRate: 81,
    verifiedOutcomeRate: 74,
    pricingTier: "competitive",
    trustScore: 82,
    businessNeeds: ["workforce programs", "healthcare programs"],
    offers: ["scheduled rides", "route support", "client transport"],
    idealMatches: ["workforce", "healthcare", "recovery"],
  },
  {
    id: "partner_staffing_001",
    name: "Central Staffing Group",
    type: "Staffing Agency",
    sector: "staffing",
    serviceLanes: ["employment", "placement", "employer-services", "screening"],
    geography: ["Central Ohio"],
    capacity: 76,
    responseSpeed: 89,
    completionRate: 84,
    verifiedOutcomeRate: 79,
    pricingTier: "premium",
    trustScore: 86,
    businessNeeds: ["trained workers", "credential programs"],
    offers: ["job placement", "employer relationships", "screening"],
    idealMatches: ["workforce", "training", "transportation"],
  },
  {
    id: "partner_recovery_001",
    name: "Kermit Recovery Support",
    type: "Recovery Support Program",
    sector: "recovery",
    serviceLanes: ["recovery-support", "case-support", "peer-support"],
    geography: ["Franklin County"],
    capacity: 71,
    responseSpeed: 78,
    completionRate: 80,
    verifiedOutcomeRate: 77,
    pricingTier: "standard",
    trustScore: 83,
    businessNeeds: ["housing partners", "transportation partners", "employment partners"],
    offers: ["peer support", "recovery navigation", "case support"],
    idealMatches: ["housing", "transportation", "workforce"],
  },
  {
    id: "partner_shs_reporting_001",
    name: "Silicon Heartland Solutions",
    type: "Reporting + Verification Layer",
    sector: "infrastructure",
    serviceLanes: ["reporting", "verification", "audit", "outcome-proof"],
    geography: ["Franklin County", "Central Ohio", "Statewide Ohio"],
    capacity: 94,
    responseSpeed: 92,
    completionRate: 91,
    verifiedOutcomeRate: 96,
    pricingTier: "infrastructure",
    trustScore: 95,
    businessNeeds: ["verified outcomes", "reporting demand", "infrastructure clients"],
    offers: ["outcome proof", "audit trail", "verified reporting", "command infrastructure"],
    idealMatches: ["workforce", "healthcare", "recovery", "transportation", "staffing"],
  },
];

export const hubOpportunities = [
  {
    id: "opp_001",
    title: "County Reentry Workforce Proposal",
    type: "Bundled Opportunity",
    stage: "Open",
    estimatedValue: 125000,
    urgency: "High",
    deadlineDays: 30,
    neededLanes: ["training", "transportation", "case-support", "job-placement", "reporting"],
    geography: "Franklin County",
    source: "Hub referral pattern",
    buyer: "Franklin County Workforce / Reentry",
    targetBuyer: "Franklin County Workforce / Reentry",
    riskTolerance: "Moderate",
    pricingStrategy: "Competitive",
    nextAction: "Build multi-partner proposal bundle",
  },
  {
    id: "opp_002",
    title: "Healthcare Workforce Transportation Support",
    type: "Cross-Sale Opportunity",
    stage: "Suggested Match",
    estimatedValue: 42000,
    urgency: "Medium",
    deadlineDays: 45,
    neededLanes: ["transportation", "workforce", "healthcare-support"],
    geography: "Central Ohio",
    source: "Partner capacity signal",
    buyer: "Healthcare Workforce Partner",
    targetBuyer: "Healthcare Workforce Partner",
    riskTolerance: "Low",
    pricingStrategy: "Competitive",
    nextAction: "Introduce transportation partner and workforce lead",
  },
  {
    id: "opp_003",
    title: "Employer Placement Pipeline",
    type: "Partner Relationship",
    stage: "Sales Review",
    estimatedValue: 68000,
    urgency: "Medium",
    deadlineDays: 60,
    neededLanes: ["training", "placement", "employer-services"],
    geography: "Central Ohio",
    source: "Growth signal intelligence",
    buyer: "Employer network",
    targetBuyer: "Employer network",
    riskTolerance: "Moderate",
    pricingStrategy: "Standard",
    nextAction: "Move to SHS sales team for relationship follow-up",
  },
  {
    id: "opp_004",
    title: "Recovery Support Transportation Bundle",
    type: "Bundled Opportunity",
    stage: "Proposal Building",
    estimatedValue: 54000,
    urgency: "High",
    deadlineDays: 21,
    neededLanes: ["recovery-support", "transportation", "case-support", "reporting"],
    geography: "Franklin County",
    source: "Unmet needs pattern",
    buyer: "Community support partner",
    targetBuyer: "Community support partner",
    riskTolerance: "Moderate",
    pricingStrategy: "Competitive",
    nextAction: "Confirm service coverage and pricing position",
  },
  {
    id: "opp_005",
    title: "Verified Outcome Reporting Pilot",
    type: "Pilot Opportunity",
    stage: "Won / Active",
    estimatedValue: 36000,
    urgency: "Low",
    deadlineDays: 90,
    neededLanes: ["reporting", "verification", "audit"],
    geography: "Statewide Ohio",
    source: "SHS infrastructure demand",
    buyer: "Program operator",
    targetBuyer: "Program operator",
    riskTolerance: "Low",
    pricingStrategy: "Infrastructure",
    nextAction: "Move into active reporting setup",
  },
];

export const hubBundles = [
  {
    id: "bundle_001",
    name: "Franklin Workforce Reentry Bundle",
    opportunityId: "opp_001",
    partners: [
      "partner_workforce_001",
      "partner_transport_001",
      "partner_staffing_001",
      "partner_recovery_001",
      "partner_shs_reporting_001",
    ],
    requiredLanes: ["training", "transportation", "case-support", "job-placement", "reporting"],
    pricingStrategy: "competitive",
    estimatedPrice: 118000,
    status: "Best Overall",
  },
  {
    id: "bundle_002",
    name: "Best-Value Workforce Support Bundle",
    opportunityId: "opp_001",
    partners: ["partner_workforce_001", "partner_transport_001", "partner_shs_reporting_001"],
    requiredLanes: ["training", "transportation", "job-placement", "reporting"],
    pricingStrategy: "low-cost",
    estimatedPrice: 92000,
    status: "Best Value",
  },
  {
    id: "bundle_003",
    name: "Highest-Confidence Reentry Bundle",
    opportunityId: "opp_001",
    partners: ["partner_workforce_001", "partner_staffing_001", "partner_recovery_001", "partner_shs_reporting_001"],
    requiredLanes: ["training", "case-support", "job-placement", "reporting"],
    pricingStrategy: "premium",
    estimatedPrice: 124000,
    status: "Highest Confidence",
  },
  {
    id: "bundle_004",
    name: "Fastest Delivery Workforce Bundle",
    opportunityId: "opp_001",
    partners: ["partner_workforce_001", "partner_staffing_001", "partner_shs_reporting_001"],
    requiredLanes: ["training", "job-placement", "reporting"],
    pricingStrategy: "standard",
    estimatedPrice: 104000,
    status: "Fastest Delivery",
  },
];

export const hubSalesPipeline = [
  {
    id: "sale_001",
    title: "Intro: Workforce Partner to Staffing Agency",
    stage: "Introduced",
    owner: "SHS Sales Team",
    estimatedValue: 68000,
    priority: "High",
    dueInDays: 4,
    relatedOpportunity: "Employer Placement Pipeline",
    relatedPartners: ["Franklin Workforce Partner", "Central Staffing Group"],
    nextAction: "Schedule employer placement meeting",
    notes: "Strong partner alignment. Staffing partner needs trained workers; workforce partner needs employer placements.",
  },
  {
    id: "sale_002",
    title: "County Reentry Bundle Proposal",
    stage: "Proposal Building",
    owner: "SHS Sales Team",
    estimatedValue: 125000,
    priority: "High",
    dueInDays: 7,
    relatedOpportunity: "County Reentry Workforce Proposal",
    relatedPartners: ["Franklin Workforce Partner", "Central Mobility Services", "Kermit Recovery Support", "SHS Reporting Layer"],
    nextAction: "Finalize service lanes, pricing position, and reporting role",
    notes: "Best-value bundle is ready for proposal packet generation.",
  },
  {
    id: "sale_003",
    title: "Transportation Support for Healthcare Workforce",
    stage: "Meeting Scheduled",
    owner: "SHS Sales Team",
    estimatedValue: 42000,
    priority: "Medium",
    dueInDays: 2,
    relatedOpportunity: "Healthcare Workforce Transportation Support",
    relatedPartners: ["Central Mobility Services", "Franklin Workforce Partner"],
    nextAction: "Confirm transportation capacity and route coverage",
    notes: "Useful cross-sale opportunity between workforce and mobility support.",
  },
  {
    id: "sale_004",
    title: "Recovery Support Transportation Bundle",
    stage: "Negotiation",
    owner: "SHS Sales Team",
    estimatedValue: 54000,
    priority: "High",
    dueInDays: 5,
    relatedOpportunity: "Recovery Support Transportation Bundle",
    relatedPartners: ["Kermit Recovery Support", "Central Mobility Services", "SHS Reporting Layer"],
    nextAction: "Confirm final price and service schedule",
    notes: "High urgency. Needs clear scope and proof/reporting lane.",
  },
  {
    id: "sale_005",
    title: "Verified Outcome Reporting Pilot",
    stage: "Won",
    owner: "SHS Sales Team",
    estimatedValue: 36000,
    priority: "Low",
    dueInDays: 0,
    relatedOpportunity: "Verified Outcome Reporting Pilot",
    relatedPartners: ["Silicon Heartland Solutions"],
    nextAction: "Move into active reporting setup",
    notes: "Won pilot. Convert into active implementation and proof workflow.",
  },
  {
    id: "sale_006",
    title: "Low-Fit Vendor Referral",
    stage: "Lost",
    owner: "SHS Sales Team",
    estimatedValue: 18000,
    priority: "Low",
    dueInDays: 0,
    relatedOpportunity: "Low-Fit Vendor Referral",
    relatedPartners: ["Unknown Vendor"],
    nextAction: "Archive as learning signal",
    notes: "Weak fit. Not aligned to Hub service lanes.",
  },
  {
    id: "sale_007",
    title: "Community Partner Follow-Up",
    stage: "Follow-Up Later",
    owner: "SHS Sales Team",
    estimatedValue: 28000,
    priority: "Medium",
    dueInDays: 14,
    relatedOpportunity: "Future Community Support Bundle",
    relatedPartners: ["Community Support Partner", "SHS Reporting Layer"],
    nextAction: "Follow up after partner capacity resets",
    notes: "Good relationship, but not ready this cycle.",
  },
];

export const hubOpportunityStages = [
  "Open",
  "Suggested Match",
  "Sales Review",
  "Proposal Building",
  "Won / Active",
  "Closed / Lost",
];

export const hubSalesStages = [
  "Identified",
  "Introduced",
  "Meeting Scheduled",
  "Proposal Building",
  "Negotiation",
  "Won",
  "Lost",
  "Follow-Up Later",
];
