import assert from "node:assert/strict";
import test from "node:test";
import { SHS_SECURITY_PERMISSIONS } from "../src/auth/security-permissions.js";
import { MonitoringAuditService } from "../src/domain/government-assurance/service/monitoring-audit-service.js";
const scope={organizationId:"org_monitor",tenantId:"tenant:org_monitor",userId:"monitor-1"};
const perms=Object.values(SHS_SECURITY_PERMISSIONS).filter((p)=>p.startsWith("government.assurance."));
const user={...scope,permissions:perms};
class Repo { rows:any[]=[]; historyRows:any[]=[]; async insert(t:string,v:any){this.rows.push({...v,__table:t});return v;} async get(_t:string,_f:string,id:string){return this.rows.find((r)=>Object.values(r).includes(id))||null;} async update(_t:string,_f:string,id:string,_s:any,v:any){const r=this.rows.find((x)=>Object.values(x).includes(id));if(r)Object.assign(r,v);return r;} async list(t:string){return this.rows.filter((r)=>r.__table===t);} async history(){return this.historyRows;}}
test("monitoring plan, evidence request, finding, corrective action, retest preserve oversight chain",async()=>{const repo=new Repo();const sut=new MonitoringAuditService(repo as any);const plan=await sut.createPlan(user,{monitoringPlanId:"plan-1",monitoringType:"COMPLIANCE_REVIEW",programReference:"program-1",providerReference:"provider-a"});assert.equal(plan.status,"DRAFT");await sut.createEvidenceRequest(user,{monitoringReference:"plan-1",evidenceType:"QUARTERLY_REPORT",dueAt:new Date()});const finding=await sut.createFinding(user,{findingId:"finding-1",monitoringReference:"plan-1",findingType:"EVIDENCE_DEFICIENCY",severity:"MEDIUM",description:"Missing report",evidenceReferences:[]});assert.equal(finding.status,"PROPOSED");const action=await sut.createAction(user,{correctiveActionId:"action-1",findingId:"finding-1",requiredAction:"Submit report",actionOwner:"provider-a",dueAt:new Date()});assert.equal(action.status,"REQUIRED");const retest=await sut.retest(user,{correctiveActionId:"action-1",evidenceReferences:["evidence-1"],result:"PASS"});assert.equal(retest.status,"COMPLETE");});
test("high-impact finding cannot be self-approved and finding is not fraud",async()=>{const repo=new Repo();const sut=new MonitoringAuditService(repo as any);await sut.createFinding(user,{findingId:"finding-high",findingType:"DUPLICATE_CANDIDATE",severity:"HIGH",materiality:"MATERIAL",description:"Duplicate candidate"});await assert.rejects(()=>sut.determineFinding(user,"finding-high",{status:"CONFIRMED",approverReference:"monitor-1"}),/SELF_APPROVAL_DENIED/);assert.equal(repo.rows.find((r)=>r.finding_id==="finding-high").finding_type,"DUPLICATE_CANDIDATE");});
test("fixed-seed random sampling is reproducible and seed changes selection",async()=>{const sut=new MonitoringAuditService(new Repo() as any);const input={auditEngagementId:"audit-1",method:"RANDOM",populationReferences:["a","b","c","d","e"],sampleSize:3,randomSeed:"seed-1",methodologyVersion:"1"};const a=await sut.createSample(user,input);const b=await sut.createSample(user,{...input,sampleId:"sample-2"});const c=await sut.createSample(user,{...input,sampleId:"sample-3",randomSeed:"seed-2"});assert.deepEqual(a.selected_record_references,b.selected_record_references);assert.notDeepEqual(a.selected_record_references,c.selected_record_references);});
test("investigation requires restricted purpose and recovery requires determination",async()=>{const sut=new MonitoringAuditService(new Repo() as any);await assert.rejects(()=>sut.createInvestigation(user,{purpose:"AUDIT",referralSource:"finding",allegationCategory:"PAYMENT"}),/INVESTIGATION_RESTRICTED/);const investigation=await sut.createInvestigation(user,{purpose:"INVESTIGATION",referralSource:"finding",allegationCategory:"PAYMENT"});assert.equal(investigation.classification,"HIGHLY_RESTRICTED");await assert.rejects(()=>sut.createRecovery(user,{determinedImproperAmount:100}),/DETERMINATION_REQUIRED/);});
test("AI cannot create institutional decisions",async()=>{const sut=new MonitoringAuditService(new Repo() as any);await assert.rejects(()=>sut.createDecision({...user,actor_type:"ai"},{decisionType:"SANCTION",authorityReference:"auth",subjectType:"FINDING",subjectReference:"finding",finalDisposition:{status:"REVIEW"}}),/DECISION_ACTOR_DENIED/);});
test("history projection is scoped and preserves ordered canonical audit events",async()=>{const repo=new Repo();repo.historyRows=[{action_type:"CREATED"},{action_type:"PROPOSED"},{action_type:"ISSUED"}];const sut=new MonitoringAuditService(repo as any);assert.deepEqual(await sut.history(user,"GPA_FINDING","finding-1",SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_FINDING_VIEW),repo.historyRows);});
test("monitoring detail actions remain canonical and retest does not silently resolve a finding",async()=>{const repo=new Repo();const sut=new MonitoringAuditService(repo as any);await sut.createFinding(user,{findingId:"finding-detail",findingType:"EVIDENCE_DEFICIENCY",severity:"MEDIUM",description:"Missing evidence"});const action=await sut.createAction(user,{correctiveActionId:"action-detail",findingId:"finding-detail",requiredAction:"Provide evidence",actionOwner:"provider-a"});const failed=await sut.retest(user,{correctiveActionId:action.corrective_action_id,evidenceReferences:["evidence-1"],result:"FAIL"});assert.equal(failed.status,"RETEST_PENDING");assert.equal(repo.rows.find((r)=>r.finding_id==="finding-detail").status,"PROPOSED");});
test("provider integrity hides restricted investigations while preserving bounded counts",async()=>{const repo=new Repo();repo.rows=[{__table:"gpa_monitoring_plans",provider_reference:"provider-a"},{__table:"gpa_findings",provider_reference:"provider-a",finding_id:"f-1",status:"ISSUED",severity:"HIGH"},{__table:"gpa_corrective_actions",provider_reference:"provider-a",corrective_action_id:"a-1",status:"OVERDUE"},{__table:"gpa_investigations",provider_reference:"provider-a",investigation_id:"i-1"}];const sut=new MonitoringAuditService(repo as any);const summary=await sut.providerIntegrity(user,"provider-a");assert.equal(summary.findings.issued,1);assert.equal(summary.correctiveActions.overdue,1);assert.equal(summary.investigations.state,"RESTRICTED_ITEM_PRESENT");assert.deepEqual(summary.investigations.references,undefined);});
