import assert from "node:assert/strict";
import test from "node:test";
import { PDFDocument } from "pdf-lib";
import { buildCivicSureR3Presentation } from "../src/domain/reporting/civicsure-r3-presentations.ts";
import { CivicSureRenderAdapter, hashBytes } from "../src/domain/reporting/report-renderer.ts";
import { ReportTemplateRegistry } from "../src/domain/reporting/report-template-registry.ts";

function report(reportType: string, subjectReference: string) {
  return {
    reportType,
    reportVersion: 1,
    generatedAt: "2026-09-07T12:00:00.000Z",
    classification: "INTERNAL",
    scope: { organizationId: "org-a", tenantId: "tenant:org-a", jurisdiction: "Franklin County", subjectReference, reportingPeriod: { label: "2026-H1" } },
    canonicalFacts: {
      funding: [{ funding_reference_id: "funding-1", program_reference: "program-1", provider_organization_reference: "provider-1", canonical_record_type: "AWARD", amount: 600000, status: "ACTIVE", source_system_id: "source-1", provenance_reference: "prov-1" }],
      truth: [{ truth_fact_id: "truth-1", subject_reference: "outcome-1", fact_type: "PLACEMENTS", fact_value: "72", verification_level: "V3", status: "ACCEPTED" }],
      findings: [{ finding_id: "finding-1", status: "OPEN", severity: "MEDIUM", provider_reference: "provider-1", description: "Evidence requires review." }],
      reconciliations: [{ reconciliation_case_id: "recon-1", status: "OPEN", conflict_type: "AMOUNT_CONFLICT" }],
      sources: [{ source_system_id: "source-1", current_freshness_state: "FRESH", status: "ACTIVE" }],
      lineageEdges: [{ from_reference: "funding-1", from_type: "FUNDING", to_reference: "program-1", to_type: "PROGRAM", relationship_type: "ALLOCATED", amount: 600000 }],
    },
    canonicalReferences: [{ type: "Funding", id: "funding-1" }, { type: "TruthFact", id: "truth-1" }],
  };
}

for (const [reportType, subject] of [["PROGRAM_ASSURANCE", "program-1"], ["PROVIDER_ASSURANCE", "provider-1"], ["FUNDING_LINEAGE", "funding-1"]] as const) {
  test(`R3 ${reportType} HTML uses a scoped CivicSure presentation`, () => {
    const source = report(reportType, subject);
    const template = new ReportTemplateRegistry().get(reportType, 1);
    const immutablePayload: any = { metadata: { reportType, classification: "INTERNAL" }, reportType, payload: source };
    immutablePayload.presentation = buildCivicSureR3Presentation(source);
    const rendered = new CivicSureRenderAdapter().render({ immutablePayload, template, format: "HTML" });
    const html = rendered.bytes.toString("utf8");
    assert.equal(template.rendererIdentifier, "civicsure-r3");
    assert.match(html, /CivicSure/);
    assert.match(html, /Evidence and Lineage Appendix/);
    assert.match(html, /600,000/);
    assert.match(html, /INTERNAL/);
    assert.doesNotMatch(html, /investigation-1/i);
    assert.equal(rendered.hash, hashBytes(rendered.bytes));
  });
}

for (const [reportType, subject] of [["PROGRAM_ASSURANCE", "program-1"], ["PROVIDER_ASSURANCE", "provider-1"], ["FUNDING_LINEAGE", "funding-1"]] as const) {
  test(`R3 ${reportType} PDF is generated by the shared renderer`, async () => {
    const source = report(reportType, subject);
    const template = new ReportTemplateRegistry().get(reportType, 1);
    const immutablePayload: any = { metadata: { reportType: source.reportType, classification: "INTERNAL" }, reportType: source.reportType, payload: source };
    immutablePayload.presentation = buildCivicSureR3Presentation(source);
    const rendered = await new CivicSureRenderAdapter().renderPdf({ immutablePayload, template });
    assert.equal(rendered.mimeType, "application/pdf");
    assert.equal(rendered.hash, hashBytes(rendered.bytes));
    assert.ok((await PDFDocument.load(rendered.bytes)).getPageCount() >= 2);
  });
}
