import { query } from "../../../db/client.js";

function scope(actor: any) {
  const organizationId = String(actor?.active_organization_id || actor?.organization_id || "").trim();
  const tenantId = String(actor?.tenant_id || `tenant:${organizationId}`).trim();
  if (!organizationId || tenantId !== `tenant:${organizationId}`) throw new Error("ORG_CONTEXT_REQUIRED");
  return { organizationId, tenantId, userId: actor?.user_id || actor?.id || null };
}

export class DocumentationInstanceRepository {
  constructor(private readonly executor: any = { query }) {}
  scope(actor: any) { return scope(actor); }

  async getTemplateVersion(templateVersionId: string, actor: any) {
    const s = scope(actor);
    const result = await this.executor.query(`SELECT tv.*, t.template_id, t.document_type_id, t.title AS template_title, t.owning_domain, t.service_key, dt.title AS document_type_title, dt.default_classification FROM dgal_template_versions tv JOIN dgal_document_templates t ON t.template_id=tv.template_id JOIN dgal_document_types dt ON dt.document_type_id=t.document_type_id WHERE tv.template_version_id=$1 AND (t.organization_id IS NULL OR (t.organization_id=$2 AND t.tenant_id=$3))`, [templateVersionId, s.organizationId, s.tenantId]);
    return result.rows[0] || null;
  }

  async findByIdempotency(key: string, actor: any) { const s = scope(actor); const r = await this.executor.query("SELECT * FROM dgal_document_instances WHERE generation_idempotency_key=$1 AND organization_id=$2 AND tenant_id=$3 LIMIT 1", [key, s.organizationId, s.tenantId]); return r.rows[0] || null; }
  async createInstance(input: any) { const r = await this.executor.query(`INSERT INTO dgal_document_instances (document_instance_id,document_type_id,template_id,template_version_id,owning_domain,organization_id,tenant_id,service_key,workflow_type,workflow_stage,resource_type,resource_id,subject_reference,title,classification,state,source_manifest,retention_policy_key,retention_start_at,legal_hold_reference,generation_idempotency_key,generated_by_user_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,'PENDING',$16::jsonb,$17,$18,$19,$20,$21,$22) RETURNING *`, [input.documentInstanceId,input.documentTypeId,input.templateId,input.templateVersionId,input.owningDomain,input.organizationId,input.tenantId,input.serviceKey||null,input.workflowType||null,input.workflowStage||null,input.resourceType||null,input.resourceId||null,input.subjectReference||null,input.title,input.classification,JSON.stringify(input.sourceManifest||{}),input.retentionPolicyKey||null,input.retentionStartAt||null,input.legalHoldReference||null,input.idempotencyKey||null,input.userId||null]); return r.rows[0]; }
  async finalize(id: string, actor: any, result: any, artifactReference: string) { const s = scope(actor); const r = await this.executor.query(`UPDATE dgal_document_instances SET state='GENERATED',artifact_reference=$1,artifact_mime_type=$2,artifact_byte_length=$3,content_hash=$4,renderer_id=$5,renderer_version=$6,generated_at=NOW(),updated_at=NOW() WHERE document_instance_id=$7 AND organization_id=$8 AND tenant_id=$9 AND state='PENDING' RETURNING *`, [artifactReference,result.mimeType,result.bytes.length,result.hash,result.rendererId,result.rendererVersion,id,s.organizationId,s.tenantId]); return r.rows[0] || null; }
  async createArtifactLink(input: any, actor: any) { const s = scope(actor); const r = await this.executor.query(`INSERT INTO dgal_artifact_links (artifact_link_id,document_instance_id,artifact_type,media_type,storage_reference,content_hash,byte_length,renderer_id,renderer_version) SELECT $1,document_instance_id,$2,$3,$4,$5,$6,$7,$8 FROM dgal_document_instances WHERE document_instance_id=$9 AND organization_id=$10 AND tenant_id=$11 RETURNING *`, [input.artifactLinkId,input.artifactType,input.mediaType,input.storageReference,input.contentHash,input.byteLength,input.rendererId,input.rendererVersion,input.documentInstanceId,s.organizationId,s.tenantId]); if (!r.rows[0]) throw new Error("DOCUMENT_INSTANCE_NOT_FOUND"); return r.rows[0]; }
  async fail(id: string, actor: any, message: string) { const s = scope(actor); const r = await this.executor.query("UPDATE dgal_document_instances SET state='FAILED',source_manifest=source_manifest || $1::jsonb,updated_at=NOW() WHERE document_instance_id=$2 AND organization_id=$3 AND tenant_id=$4 RETURNING *", [JSON.stringify({ renderError: message.slice(0, 240) }),id,s.organizationId,s.tenantId]); return r.rows[0] || null; }
  async get(id: string, actor: any) { const s = scope(actor); const r = await this.executor.query("SELECT * FROM dgal_document_instances WHERE document_instance_id=$1 AND organization_id=$2 AND tenant_id=$3", [id,s.organizationId,s.tenantId]); return r.rows[0] || null; }
  async linkEvidence(input: any, actor: any) { const s = scope(actor); const r = await this.executor.query(`INSERT INTO dgal_evidence_links (evidence_link_id,document_instance_id,evidence_reference,relationship_type,owning_domain,organization_id,tenant_id,linked_by_user_id,source_reference) SELECT $1,document_instance_id,$2,$3,$4,$5,$6,$7,$8 FROM dgal_document_instances WHERE document_instance_id=$9 AND organization_id=$5 AND tenant_id=$6 AND state='GENERATED' RETURNING *`, [input.evidenceLinkId,input.evidenceReference,input.relationshipType,input.owningDomain,s.organizationId,s.tenantId,s.userId,input.sourceReference,input.documentInstanceId]); if (!r.rows[0]) throw new Error("DOCUMENT_INSTANCE_NOT_FOUND_OR_NOT_GENERATED"); return r.rows[0]; }
  async createPacket(input: any) { const r = await this.executor.query(`INSERT INTO dgal_packet_instances (packet_instance_id,packet_definition_id,packet_key,title,owning_domain,organization_id,tenant_id,service_key,workflow_type,workflow_stage,resource_type,resource_id,classification,state,manifest,manifest_hash,retention_policy_key,retention_start_at,legal_hold_reference,created_by_user_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'PENDING',$14::jsonb,$15,$16,$17,$18,$19) RETURNING *`, [input.packetInstanceId,input.packetDefinitionId||null,input.packetKey,input.title,input.owningDomain,input.organizationId,input.tenantId,input.serviceKey||null,input.workflowType||null,input.workflowStage||null,input.resourceType||null,input.resourceId||null,input.classification,JSON.stringify(input.manifest),input.manifestHash,input.retentionPolicyKey||null,input.retentionStartAt||null,input.legalHoldReference||null,input.userId||null]); return r.rows[0]; }
  async finalizePacket(id: string, actor: any, state: string) { const s = scope(actor); const r = await this.executor.query("UPDATE dgal_packet_instances SET state=$1,updated_at=NOW() WHERE packet_instance_id=$2 AND organization_id=$3 AND tenant_id=$4 RETURNING *", [state,id,s.organizationId,s.tenantId]); return r.rows[0] || null; }
  async createPacketItems(packetId: string, items: any[], actor: any) { scope(actor); for (const item of items) await this.executor.query("INSERT INTO dgal_packet_instance_items (packet_instance_id,item_key,display_order,item_type,reference_id,source_owner,required,state,content_hash) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)", [packetId,item.itemKey,item.displayOrder,item.itemType,item.referenceId,item.sourceOwner,item.required,item.state,item.contentHash || null]); }
  async getPacket(id: string, actor: any) { const s = scope(actor); const r = await this.executor.query("SELECT * FROM dgal_packet_instances WHERE packet_instance_id=$1 AND organization_id=$2 AND tenant_id=$3", [id,s.organizationId,s.tenantId]); return r.rows[0] || null; }
}
