import { query } from "../../../db/client.js";
import { allowedSignatureTransition, type ElectronicSignatureStatus } from "../model/signature.js";

function scope(actor: any) {
  const organizationId = String(actor?.active_organization_id || actor?.organization_id || "").trim();
  const tenantId = String(actor?.tenant_id || `tenant:${organizationId}`).trim();
  if (!organizationId || tenantId !== `tenant:${organizationId}`) throw new Error("ORG_CONTEXT_REQUIRED");
  return { organizationId, tenantId, userId: actor?.user_id || actor?.id || null };
}

export class DocumentationSignatureRepository {
  constructor(private readonly executor: any = { query }) {}
  async getDocument(id: string, actor: any) { const s = scope(actor); const r = await this.executor.query("SELECT * FROM dgal_document_instances WHERE document_instance_id=$1 AND organization_id=$2 AND tenant_id=$3", [id, s.organizationId, s.tenantId]); return r.rows[0] || null; }
  async findIdempotent(key: string, actor: any) { const s = scope(actor); const r = await this.executor.query("SELECT * FROM documentation_signature_requests WHERE organization_id=$1 AND tenant_id=$2 AND idempotency_key=$3", [s.organizationId, s.tenantId, key]); return r.rows[0] || null; }
  async get(id: string, actor: any) { const s = scope(actor); const r = await this.executor.query("SELECT * FROM documentation_signature_requests WHERE signature_request_id=$1 AND organization_id=$2 AND tenant_id=$3", [id, s.organizationId, s.tenantId]); return r.rows[0] || null; }
  async getByProviderReference(providerKey: string, environment: string, reference: string) { const r = await this.executor.query("SELECT * FROM documentation_signature_requests WHERE provider_key=$1 AND provider_environment=$2 AND provider_request_reference=$3", [providerKey, environment, reference]); return r.rows[0] || null; }
  async create(input: any, actor: any) { const s = scope(actor); const r = await this.executor.query(`INSERT INTO documentation_signature_requests (signature_request_id,organization_id,tenant_id,owning_domain,requirement_rule_id,document_instance_id,template_version_id,content_hash,agreement_reference,agreement_version,signer_reference,signer_role,signer_capacity,represented_party_reference,provider_key,provider_environment,status,retention_policy_key,legal_hold_reference,created_by_user_id,idempotency_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,'DRAFT',$17,$18,$19,$20) RETURNING *`, [input.signatureRequestId,s.organizationId,s.tenantId,input.owningDomain,input.requirementRuleId||null,input.documentInstanceId,input.templateVersionId,input.contentHash,input.agreementReference||null,input.agreementVersion||null,input.signerReference,input.signerRole,input.signerCapacity||null,input.representedPartyReference||null,input.providerKey,input.providerEnvironment,input.retentionPolicyKey||null,input.legalHoldReference||null,s.userId,input.idempotencyKey||null]); return r.rows[0]; }
  async attachProviderRequest(id: string, provider: any, actor: any) { const s = scope(actor); const r = await this.executor.query("UPDATE documentation_signature_requests SET provider_request_reference=$1,provider_status=$2,provider_metadata=$3::jsonb,status=$4,sent_at=CASE WHEN $4='SENT' THEN NOW() ELSE sent_at END,failed_at=CASE WHEN $4='FAILED' THEN NOW() ELSE failed_at END WHERE signature_request_id=$5 AND organization_id=$6 AND tenant_id=$7 AND status='DRAFT' RETURNING *", [provider.providerRequestReference,provider.rawStatus,JSON.stringify(provider.metadata||{}),provider.status,id,s.organizationId,s.tenantId]); return r.rows[0] || null; }
  async recordProviderEvent(input: any) { const r = await this.executor.query(`INSERT INTO documentation_signature_provider_events (provider_event_id,provider_key,provider_environment,provider_event_reference,provider_request_reference,organization_id,tenant_id,normalized_status,raw_status,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb) ON CONFLICT (provider_key,provider_environment,provider_event_reference) DO NOTHING RETURNING *`, [input.providerEventId,input.providerKey,input.providerEnvironment,input.eventReference,input.requestReference,input.organizationId||null,input.tenantId||null,input.normalizedStatus,input.rawStatus,JSON.stringify(input.metadata||{})]); return r.rows[0] || null; }
  async transition(id: string, to: ElectronicSignatureStatus, event: any, actor: any) {
    const current = await this.get(id, actor); if (!current) throw new Error("SIGNATURE_REQUEST_NOT_FOUND");
    if (!allowedSignatureTransition(current.status, to)) {
      if (current.status === to) return current;
      if (["SIGNED", "DECLINED", "VOIDED", "EXPIRED"].includes(current.status)) return current;
      throw new Error("SIGNATURE_STATE_CONFLICT");
    }
    const s = scope(actor); const r = await this.executor.query("UPDATE documentation_signature_requests SET status=$1,provider_status=$2,provider_event_reference=$3,provider_metadata=provider_metadata || $4::jsonb,signed_at=CASE WHEN $1='SIGNED' THEN NOW() ELSE signed_at END,declined_at=CASE WHEN $1='DECLINED' THEN NOW() ELSE declined_at END,voided_at=CASE WHEN $1='VOIDED' THEN NOW() ELSE voided_at END,expired_at=CASE WHEN $1='EXPIRED' THEN NOW() ELSE expired_at END,failed_at=CASE WHEN $1='FAILED' THEN NOW() ELSE failed_at END,viewed_at=CASE WHEN $1='VIEWED' THEN NOW() ELSE viewed_at END WHERE signature_request_id=$5 AND organization_id=$6 AND tenant_id=$7 AND status=$8 RETURNING *", [to,event.rawStatus||null,event.eventReference||null,JSON.stringify(event.metadata||{}),id,s.organizationId,s.tenantId,current.status]); return r.rows[0] || current;
  }
  async attachArtifact(id: string, artifact: any, actor: any) { const s = scope(actor); const r = await this.executor.query("UPDATE documentation_signature_requests SET signed_artifact_reference=$1,signed_artifact_hash=$2,signed_artifact_media_type=$3,signed_artifact_byte_length=$4 WHERE signature_request_id=$5 AND organization_id=$6 AND tenant_id=$7 AND status='SIGNED' RETURNING *", [artifact.reference,artifact.hash,artifact.mediaType,artifact.byteLength,id,s.organizationId,s.tenantId]); return r.rows[0] || null; }
  async attachEvidence(id: string, input: any, actor: any) { const s = scope(actor); const r = await this.executor.query("UPDATE documentation_signature_requests SET evidence_reference=$1 WHERE signature_request_id=$2 AND organization_id=$3 AND tenant_id=$4 AND status='SIGNED' RETURNING *", [input.evidenceReference,id,s.organizationId,s.tenantId]); return r.rows[0] || null; }
}
