import { randomUUID } from "node:crypto";
import { hasPermission, SHS_SECURITY_PERMISSIONS } from "../../../auth/security-permissions.js";
import { assuranceScope, requireScope, type AssuranceActor } from "../model/government-assurance.js";
import { AssuranceCycleRepo } from "../repo/assurance-cycle-repo.js";
import { query } from "../../../db/client.js";

const actor = (input: any): AssuranceActor => ({ userId: String(input?.userId || input?.user_id || input?.id || ""), organizationId: String(input?.organizationId || input?.organization_id || input?.active_organization_id || ""), tenantId: String(input?.tenantId || input?.tenant_id || ""), permissions: input?.permissions || [], actor_type: input?.actor_type || input?.actorType || "user" });

export const deriveAssuranceStatus = (input: { failedVerifications?: number; openFindings?: number; openActions?: number; unresolvedReconciliation?: number; degradedSources?: number }) => {
  if ((input.openActions || 0) > 0) return { status: "CORRECTIVE_ACTION_OPEN", reasons: ["OPEN_CORRECTIVE_ACTION"] };
  if ((input.openFindings || 0) > 0) return { status: "REVIEW_NEEDED", reasons: ["OPEN_FINDING"] };
  if ((input.failedVerifications || 0) > 0 || (input.unresolvedReconciliation || 0) > 0 || (input.degradedSources || 0) > 0) return { status: "ELEVATED_ASSURANCE", reasons: [input.failedVerifications ? "FAILED_VERIFICATION" : input.unresolvedReconciliation ? "UNRESOLVED_RECONCILIATION" : "DEGRADED_SOURCE"] };
  return { status: "IN_GOOD_STANDING", reasons: [] };
};

function comparable(rows: any[]) {
  const definitions = new Set(rows.map((row) => `${row.metric_id}:${row.metric_version}`));
  if (!rows.length || definitions.size !== 1) return { comparable: false, status: "NOT COMPARABLE", reasons: ["CANONICAL_METRIC_OR_VERSION_MISMATCH"] };
  if (new Set(rows.map((row) => `${row.reporting_period_start || ""}:${row.reporting_period_end || ""}`)).size !== 1) return { comparable: false, status: "NOT COMPARABLE", reasons: ["REPORTING_PERIOD_MISMATCH"] };
  return { comparable: true, status: "COMPARABLE", reasons: [], metricReference: [...definitions][0], rows };
}

export class AssuranceCycleService {
  constructor(private repo = new AssuranceCycleRepo(), private dbQuery: typeof query = query) {}
  private context(input: any) { const a = actor(input); return { actor: a, scope: assuranceScope(a) }; }
  private permission(a: AssuranceActor, p: string) { if (!hasPermission(a.permissions || [], p)) throw new Error("GPA_PERMISSION_REQUIRED"); }
  private async aggregate(scope: any, cycle: any, providerReference?: string, programReference?: string) {
    const base = [scope.organizationId,scope.tenantId];
    const claimParams = [...base]; let claimFilter = "c.organization_id=$1 AND c.tenant_id=$2";
    if (programReference) { claimParams.push(programReference); claimFilter += ` AND c.program_reference=$${claimParams.length}`; }
    if (providerReference) { claimParams.push(providerReference); claimFilter += ` AND (c.claimant_reference=$${claimParams.length} OR c.subject_reference=$${claimParams.length} OR c.metadata->>'providerReference'=$${claimParams.length})`; }
    if (cycle) { claimParams.push(cycle.period_start,cycle.period_end); claimFilter += ` AND (c.reporting_period_start IS NULL OR c.reporting_period_start >= $${claimParams.length-1}) AND (c.reporting_period_end IS NULL OR c.reporting_period_end <= $${claimParams.length})`; }
    const c = await this.dbQuery(`SELECT COUNT(*)::int AS total, COUNT(*) FILTER (WHERE c.status IN ('VERIFIED','PARTIALLY_VERIFIED'))::int AS verified FROM gpa_claims c WHERE ${claimFilter}`, claimParams);
    const verificationParams = [...base]; let verificationFilter = "c.organization_id=$1 AND c.tenant_id=$2";
    if (programReference) { verificationParams.push(programReference); verificationFilter += ` AND c.program_reference=$${verificationParams.length}`; }
    if (providerReference) { verificationParams.push(providerReference); verificationFilter += ` AND (c.claimant_reference=$${verificationParams.length} OR c.subject_reference=$${verificationParams.length} OR c.metadata->>'providerReference'=$${verificationParams.length})`; }
    const v = await this.dbQuery(`SELECT COUNT(*) FILTER (WHERE vr.status='PASSED')::int AS passed, COUNT(*) FILTER (WHERE vr.status='FAILED')::int AS failed FROM gpa_verification_records vr JOIN gpa_claims c ON c.claim_id=vr.claim_id AND c.organization_id=vr.organization_id AND c.tenant_id=vr.tenant_id WHERE ${verificationFilter}`, verificationParams);
    const metricParams = [...base]; let metricFilter = "organization_id=$1 AND tenant_id=$2";
    if (providerReference) { metricParams.push(providerReference); metricFilter += ` AND provider_reference=$${metricParams.length}`; }
    if (programReference) { metricParams.push(programReference); metricFilter += ` AND program_reference=$${metricParams.length}`; }
    if (cycle) { metricParams.push(cycle.period_start,cycle.period_end); metricFilter += ` AND (reporting_period_start IS NULL OR reporting_period_start >= $${metricParams.length-1}) AND (reporting_period_end IS NULL OR reporting_period_end <= $${metricParams.length})`; }
    const m = await this.dbQuery(`SELECT metric_id,metric_version,provider_reference,reporting_period_start,reporting_period_end,calculated_value,calculation_hash FROM gpa_metric_results WHERE ${metricFilter} AND status IN ('CALCULATED','ACCEPTED') ORDER BY calculated_at DESC`, metricParams);
    const issueParams = [...base]; let issueFilter = "organization_id=$1 AND tenant_id=$2";
    if (providerReference) { issueParams.push(providerReference); issueFilter += ` AND provider_reference=$${issueParams.length}`; }
    if (programReference) { issueParams.push(programReference); issueFilter += ` AND program_reference=$${issueParams.length}`; }
    const f = await this.dbQuery(`SELECT COUNT(*)::int AS count FROM gpa_findings WHERE ${issueFilter} AND status NOT IN ('RESOLVED','CLOSED','WITHDRAWN','SUPERSEDED')`, issueParams);
    const a = await this.dbQuery(`SELECT COUNT(*)::int AS count FROM gpa_corrective_actions WHERE ${issueFilter} AND status NOT IN ('COMPLETE','CLOSED','REJECTED')`, issueParams);
    const r = await this.dbQuery("SELECT COUNT(*)::int AS count FROM gpa_reconciliation_cases WHERE organization_id=$1 AND tenant_id=$2 AND status NOT IN ('RESOLVED','CLOSED','RETRACTED')", [scope.organizationId,scope.tenantId]);
    const healthParams: any[] = [scope.organizationId, scope.tenantId]; let healthWhere = "h.organization_id=$1 AND h.tenant_id=$2";
    if (providerReference || programReference) { const reference = providerReference || programReference; healthParams.push(reference); const column = providerReference ? "provider_reference" : "program_reference"; healthWhere += ` AND EXISTS (SELECT 1 FROM gpa_source_assurance_dependencies d WHERE d.source_system_id=h.source_system_id AND d.organization_id=h.organization_id AND d.tenant_id=h.tenant_id AND d.${column}=$${healthParams.length})`; }
    const h = await this.dbQuery(`SELECT h.current_freshness_state,h.degraded_state,COUNT(*)::int AS count FROM gpa_source_health h WHERE ${healthWhere} GROUP BY h.current_freshness_state,h.degraded_state ORDER BY h.current_freshness_state,h.degraded_state`, healthParams);
    const degradedSources = h.rows.filter((row: any) => ["STALE", "DEGRADED"].includes(row.current_freshness_state) || row.degraded_state !== "HEALTHY").reduce((total: number, row: any) => total + Number(row.count || 0), 0);
    const status = deriveAssuranceStatus({ failedVerifications: v.rows[0]?.failed, openFindings: f.rows[0]?.count, openActions: a.rows[0]?.count, unresolvedReconciliation: r.rows[0]?.count, degradedSources });
    return { claimCount: c.rows[0]?.total || 0, verifiedClaimCount: c.rows[0]?.verified || 0, verificationPassCount: v.rows[0]?.passed || 0, verificationFailureCount: v.rows[0]?.failed || 0, metricResults: m.rows, openFindingCount: f.rows[0]?.count || 0, openCorrectiveActionCount: a.rows[0]?.count || 0, unresolvedReconciliationCount: r.rows[0]?.count || 0, sourceHealth: h.rows, assuranceStatus: status.status, statusReasons: status.reasons, confidence: { basis: "verification_evidence_reconciliation_rules", verificationPassRate: (v.rows[0]?.passed || 0) + (v.rows[0]?.failed || 0) ? (v.rows[0]?.passed || 0) / ((v.rows[0]?.passed || 0) + (v.rows[0]?.failed || 0)) : null } };
  }
  async createCycle(actorInput: any, input: any) { const { actor: a, scope: s } = this.context(actorInput); this.permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_PROGRAM_VIEW); requireScope(input, s); if (!input.cycleId || !input.programReference || !input.periodStart || !input.periodEnd) throw new Error("GPA_ASSURANCE_CYCLE_FIELDS_REQUIRED"); return this.repo.createCycle({ cycle_id: input.cycleId, organization_id: s.organizationId, tenant_id: s.tenantId, program_reference: input.programReference, jurisdiction_reference: input.jurisdictionReference, period_start: input.periodStart, period_end: input.periodEnd, status: input.status || "OPEN", evidence_rule_reference: input.evidenceRuleReference, metric_references: input.metricReferences, provenance: input.provenance || { source: "government_assurance" }, created_by: s.userId }); }
  async getCycle(actorInput: any, id: string) { const { actor: a, scope: s } = this.context(actorInput); this.permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_PROGRAM_VIEW); const cycle = await this.repo.getCycle(id,s); if (!cycle) throw new Error("GPA_ASSURANCE_CYCLE_NOT_FOUND"); return { ...cycle, scope: await this.repo.listScope(id,s) }; }
  async listCycles(actorInput: any, programReference?: string) { const { actor: a, scope: s } = this.context(actorInput); this.permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_PROGRAM_VIEW); return { items: await this.repo.listCycles(s,programReference) }; }
  async enroll(actorInput: any, cycleId: string, input: any) { const { actor: a, scope: s } = this.context(actorInput); this.permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_PROGRAM_VIEW); const cycle = await this.repo.getCycle(cycleId,s); if (!cycle || cycle.program_reference !== input.programReference) throw new Error("GPA_ASSURANCE_SCOPE_PROGRAM_MISMATCH"); if (!input.providerReference || !input.serviceReference) throw new Error("GPA_ASSURANCE_SCOPE_FIELDS_REQUIRED"); return this.repo.addScope({ scope_id: input.scopeId || `gpa_cycle_scope_${randomUUID()}`, cycle_id: cycleId, organization_id: s.organizationId, tenant_id: s.tenantId, provider_reference: input.providerReference, service_reference: input.serviceReference, funding_reference: input.fundingReference, effective_from: input.effectiveFrom, effective_to: input.effectiveTo, provenance: input.provenance || {}, created_by: s.userId }); }
  async profile(actorInput: any, type: "PROVIDER" | "PROGRAM", reference: string, cycleId?: string) { const { actor: a, scope: s } = this.context(actorInput); this.permission(a, type === "PROVIDER" ? SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_PROVIDER_VIEW : SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_PROGRAM_VIEW); const cycle = cycleId ? await this.repo.getCycle(cycleId,s) : null; if (cycleId && !cycle) throw new Error("GPA_ASSURANCE_CYCLE_NOT_FOUND"); if (cycle && type === "PROVIDER" && !(await this.repo.listScope(cycle.cycle_id,s)).some((row: any) => row.provider_reference === reference)) throw new Error("GPA_ASSURANCE_PROVIDER_OUT_OF_SCOPE"); const summary = await this.aggregate(s,cycle,type === "PROVIDER" ? reference : undefined,type === "PROGRAM" ? reference : cycle?.program_reference); return { profileType: type, subjectReference: reference, cycleId: cycle?.cycle_id || null, programReference: cycle?.program_reference || (type === "PROGRAM" ? reference : null), summary, source: "canonical_gpa_records", authoritative: false }; }
  async history(actorInput: any, type: "PROVIDER" | "PROGRAM", reference: string) { const { actor: a, scope: s } = this.context(actorInput); this.permission(a, type === "PROVIDER" ? SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_PROVIDER_VIEW : SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_PROGRAM_VIEW); return { items: await this.repo.listSnapshots(s,type,reference) }; }
  async closeCycle(actorInput: any, cycleId: string) { const { actor: a, scope: s } = this.context(actorInput); this.permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_PROGRAM_VIEW); const cycle = await this.repo.getCycle(cycleId,s); if (!cycle) throw new Error("GPA_ASSURANCE_CYCLE_NOT_FOUND"); if (cycle.status === "CLOSED" || cycle.status === "PUBLISHED") throw new Error("GPA_ASSURANCE_CYCLE_IMMUTABLE"); const scopeRows = await this.repo.listScope(cycleId,s); const providers: string[] = [...new Set<string>(scopeRows.map((row: any) => String(row.provider_reference)))]; for (const provider of providers) { const summary = await this.profile(actorInput,"PROVIDER",provider,cycleId); await this.repo.createSnapshot({ snapshot_id: `gpa_cycle_snapshot_${randomUUID()}`, cycle_id: cycleId, organization_id: s.organizationId, tenant_id: s.tenantId, profile_type: "PROVIDER", subject_reference: provider, summary: summary.summary, source_references: summary.summary.metricResults, provenance: { generatedBy: "assurance-cycle-service", immutable: true } }); } const program = await this.profile(actorInput,"PROGRAM",cycle.program_reference,cycleId); await this.repo.createSnapshot({ snapshot_id: `gpa_cycle_snapshot_${randomUUID()}`, cycle_id: cycleId, organization_id: s.organizationId, tenant_id: s.tenantId, profile_type: "PROGRAM", subject_reference: cycle.program_reference, summary: program.summary, source_references: program.summary.metricResults, provenance: { generatedBy: "assurance-cycle-service", immutable: true } }); return this.repo.updateCycle(cycleId,s,{ status: "CLOSED", closure_state: "CLOSED", review_state: "COMPLETE" }); }
  async compareProviders(actorInput: any, cycleId: string, providerReferences: string[]) { const { actor: a, scope: s } = this.context(actorInput); this.permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_PROGRAM_VIEW); const cycle = await this.repo.getCycle(cycleId,s); if (!cycle || providerReferences.length < 2) throw new Error("GPA_PROVIDER_COMPARISON_FIELDS_REQUIRED"); const rows = (await this.dbQuery("SELECT * FROM gpa_metric_results WHERE organization_id=$1 AND tenant_id=$2 AND provider_reference = ANY($3) AND program_reference=$4 AND reporting_period_start >= $5 AND reporting_period_end <= $6 AND status IN ('CALCULATED','ACCEPTED')", [s.organizationId,s.tenantId,providerReferences,cycle.program_reference,cycle.period_start,cycle.period_end])).rows; const present = new Set(rows.map((row: any) => row.provider_reference)); if (providerReferences.some((reference) => !present.has(reference))) return { cycleId, programReference: cycle.program_reference, providers: providerReferences, comparable: false, status: "NOT COMPARABLE", reasons: ["PROVIDER_RESULT_MISSING_FOR_SCOPE"] }; return { cycleId, programReference: cycle.program_reference, providers: providerReferences, ...comparable(rows) }; }
  async comparePrograms(actorInput: any, cycleId: string, programReferences: string[]) { const { actor: a, scope: s } = this.context(actorInput); this.permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_PROGRAM_VIEW); const cycle = await this.repo.getCycle(cycleId,s); if (!cycle || programReferences.length < 2) throw new Error("GPA_PROGRAM_COMPARISON_FIELDS_REQUIRED"); const rows = (await this.dbQuery("SELECT * FROM gpa_metric_results WHERE organization_id=$1 AND tenant_id=$2 AND program_reference = ANY($3) AND reporting_period_start >= $4 AND reporting_period_end <= $5 AND status IN ('CALCULATED','ACCEPTED')", [s.organizationId,s.tenantId,programReferences,cycle.period_start,cycle.period_end])).rows; const result = comparable(rows); return { cycleId, programs: programReferences, ...result, ...(result.comparable ? {} : { reasons: [...result.reasons, "PROGRAM_SERVICE_POPULATION_SEMANTICS_REQUIRE_REVIEW"] }) }; }
  async reviewQueue(actorInput: any) { const { actor: a, scope: s } = this.context(actorInput); this.permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_MONITORING_VIEW); const r = await this.dbQuery(`SELECT 'VERIFICATION' AS item_type,verification_id AS item_id,status,created_at FROM gpa_verification_records WHERE organization_id=$1 AND tenant_id=$2 AND status IN ('FAILED','INCONCLUSIVE','NEEDS_REVIEW') UNION ALL SELECT 'FINDING',finding_id,status,created_at FROM gpa_findings WHERE organization_id=$1 AND tenant_id=$2 AND status IN ('UNDER_REVIEW','PROPOSED','CORRECTIVE_ACTION_REQUIRED') UNION ALL SELECT 'CORRECTIVE_ACTION',corrective_action_id,status,created_at FROM gpa_corrective_actions WHERE organization_id=$1 AND tenant_id=$2 AND status IN ('REQUIRED','OVERDUE','RETEST_PENDING') UNION ALL SELECT 'RECONCILIATION',reconciliation_case_id,status,opened_at FROM gpa_reconciliation_cases WHERE organization_id=$1 AND tenant_id=$2 AND status IN ('OPEN','UNDER_REVIEW','UNRESOLVED') ORDER BY created_at DESC`, [s.organizationId,s.tenantId]); return { items: r.rows }; }
}
