import { randomUUID } from "node:crypto";
import { hasPermission, SHS_SECURITY_PERMISSIONS } from "../../../auth/security-permissions.js";
import { assuranceScope, requireScope, type AssuranceActor } from "../model/government-assurance.js";
import { GPA_FUNDING_CODES, GPA_FUNDING_RECORD_TYPES, GPA_FUNDING_RELATIONSHIPS } from "../model/funding-lineage.js";
import { FundingLineageRepo } from "../repo/funding-lineage-repo.js";

function actor(input: any): AssuranceActor { return { userId: String(input?.userId || input?.user_id || input?.id || ""), organizationId: String(input?.organizationId || input?.organization_id || input?.active_organization_id || ""), tenantId: String(input?.tenantId || input?.tenant_id || ""), permissions: input?.permissions || [], actor_type: input?.actor_type || input?.actorType || "user" }; }
function permission(a: AssuranceActor, p: string) { if (!hasPermission(a.permissions || [], p)) throw new Error("GPA_PERMISSION_REQUIRED"); }
export class FundingLineageService {
  constructor(private repo = new FundingLineageRepo()) {}
  private context(input: any) { const a = actor(input); return { actor: a, scope: assuranceScope(a) }; }
  async createReference(actorInput: any, input: any) { const { actor: a, scope: s } = this.context(actorInput); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_FUNDING_LINK); requireScope(input, s); if (!GPA_FUNDING_RECORD_TYPES.includes(input.canonicalRecordType as any)) throw new Error(GPA_FUNDING_CODES.FUNDING_REFERENCE_MISSING); if (!input.canonicalRecordId || !input.provenanceReference || !input.sourceSystemId || !input.sourceRecordId) throw new Error(GPA_FUNDING_CODES.PAYMENT_PROVENANCE_MISSING); return this.repo.createReference({ funding_reference_id: input.fundingReferenceId || `gpa_funding_ref_${randomUUID()}`, organization_id: s.organizationId, tenant_id: s.tenantId, canonical_record_type: input.canonicalRecordType, canonical_record_id: input.canonicalRecordId, funder_organization_reference: input.funderOrganizationReference, recipient_organization_reference: input.recipientOrganizationReference, provider_organization_reference: input.providerOrganizationReference, program_reference: input.programReference, jurisdiction_reference: input.jurisdictionReference, amount: input.amount, currency: input.currency, period_start: input.periodStart, period_end: input.periodEnd, status: input.status || "REPORTED", source_system_id: input.sourceSystemId, source_record_id: input.sourceRecordId, provenance_reference: input.provenanceReference, supersedes_reference_id: input.supersedesReferenceId, created_by: s.userId, metadata: input.metadata }); }
  async link(actorInput: any, input: any) { const { actor: a, scope: s } = this.context(actorInput); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_FUNDING_LINK); requireScope(input, s); if (!GPA_FUNDING_RELATIONSHIPS.includes(input.relationshipType as any)) throw new Error("GPA_FUNDING_RELATIONSHIP_INVALID"); if (!input.fromType || !input.fromReference || !input.toType || !input.toReference || !input.provenanceReference) throw new Error(GPA_FUNDING_CODES.FUNDING_REFERENCE_MISSING); if (["ALLOCATED", "AGGREGATED", "SHARED_COST"].includes(input.relationshipType) && !input.allocationMethodReference) throw new Error(GPA_FUNDING_CODES.ALLOCATION_METHOD_MISSING); const edges = await this.repo.listEdges(s, { reference: input.fromReference }); if (input.sourceRecordId && edges.some((edge: any) => edge.source_record_id === input.sourceRecordId && edge.from_reference === input.fromReference && edge.to_reference === input.toReference)) throw new Error(GPA_FUNDING_CODES.DUPLICATE_SOURCE_RECORD); return this.repo.createEdge({ lineage_edge_id: input.lineageEdgeId || `gpa_funding_edge_${randomUUID()}`, organization_id: s.organizationId, tenant_id: s.tenantId, from_type: input.fromType, from_reference: input.fromReference, to_type: input.toType, to_reference: input.toReference, relationship_type: input.relationshipType, amount: input.amount, currency: input.currency, allocation_method_reference: input.allocationMethodReference, period_start: input.periodStart, period_end: input.periodEnd, source_system_id: input.sourceSystemId, source_record_id: input.sourceRecordId, provenance_reference: input.provenanceReference, created_by: s.userId, metadata: input.metadata }); }
  async readiness(actorInput: any, input: any) { const { actor: a, scope: s } = this.context(actorInput); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_FINANCIAL_LINEAGE_VIEW); const edges = await this.repo.listEdges(s, { reference: input.reference }); const blockers: string[] = []; if (!input.reference) blockers.push(GPA_FUNDING_CODES.FUNDING_REFERENCE_MISSING); if (!edges.length) blockers.push(GPA_FUNDING_CODES.SERVICE_LINK_MISSING); if (input.requiresOutcome && !edges.some((edge: any) => edge.relationship_type === "VERIFIED" || edge.to_type === "OUTCOME")) blockers.push(GPA_FUNDING_CODES.OUTCOME_LINK_MISSING); if (input.requiresVerifiedExpenditure && !edges.some((edge: any) => edge.from_type === "EXPENDITURE" && edge.metadata?.verificationStatus === "VERIFIED")) blockers.push(GPA_FUNDING_CODES.EXPENDITURE_UNVERIFIED); return { ready: blockers.length === 0, blockers, edgeCount: edges.length }; }
  async providerSummary(actorInput: any, provider: string) { const { actor: a, scope: s } = this.context(actorInput); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_PROVIDER_VIEW); const refs = await this.repo.listReferences(s); const edges = await this.repo.listEdges(s, { reference: provider }); const related = refs.filter((row: any) => row.provider_organization_reference === provider); const totals = (type: string) => related.filter((row: any) => row.canonical_record_type === type).reduce((sum: number, row: any) => sum + Number(row.amount || 0), 0); return this.repo.createProviderProjection({ projection_id: `gpa_provider_projection_${randomUUID()}`, organization_id: s.organizationId, tenant_id: s.tenantId, provider_organization_reference: provider, summary: { totalAwarded: totals("AWARD"), totalObligated: totals("OBLIGATION"), totalPaidOrReported: totals("PAYMENT") + totals("EXPENDITURE"), relatedReferences: related.length, lineageEdges: edges.length }, source_references: related.map((row: any) => row.funding_reference_id), provenance: { generatedBy: s.userId, source: "gpa-funding-lineage" } }); }
  async programSummary(actorInput: any, program: string) { const { actor: a, scope: s } = this.context(actorInput); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_PROGRAM_VIEW); const refs = (await this.repo.listReferences(s)).filter((row: any) => row.program_reference === program); const edges = await this.repo.listEdges(s, { reference: program }); return this.repo.createProgramProjection({ projection_id: `gpa_program_projection_${randomUUID()}`, organization_id: s.organizationId, tenant_id: s.tenantId, program_reference: program, summary: { totalAwarded: refs.filter((r: any) => r.canonical_record_type === "AWARD").reduce((n: number, r: any) => n + Number(r.amount || 0), 0), totalObligated: refs.filter((r: any) => r.canonical_record_type === "OBLIGATION").reduce((n: number, r: any) => n + Number(r.amount || 0), 0), totalPaidOrReported: refs.filter((r: any) => ["PAYMENT", "EXPENDITURE"].includes(r.canonical_record_type)).reduce((n: number, r: any) => n + Number(r.amount || 0), 0), references: refs.length, lineageEdges: edges.length }, source_references: refs.map((r: any) => r.funding_reference_id), provenance: { generatedBy: s.userId, source: "gpa-funding-lineage" } }); }
  async lineage(actorInput: any, reference: string) { const { actor: a, scope: s } = this.context(actorInput); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_FINANCIAL_LINEAGE_VIEW); return { reference, edges: await this.repo.listEdges(s, { reference }), references: await this.repo.listReferences(s) }; }
}
