import { createHash, randomUUID } from "node:crypto";
import { hasPermission, SHS_SECURITY_PERMISSIONS } from "../../../auth/security-permissions.js";
import { writeAuditEvent } from "../../audit/service/audit-helper.js";
import { IntegrationOutboxRepo } from "../../trusted-reporting/outbox-repo.js";
import { buildGovernmentAssuranceTruthDeterminationOutboxEvent } from "../../trusted-reporting/outbox.js";
import { assuranceScope, requireScope, type AssuranceActor } from "../model/government-assurance.js";
import { GPA_LINEAGE_CODES, GPA_METRIC_TYPES, verificationLevelAtLeast } from "../model/metric-truth.js";
import { ClaimVerificationRepo } from "../repo/claim-verification-repo.js";
import { GovernmentAssuranceRepo } from "../repo/government-assurance-repo.js";
import { createTruthSpineHandoff } from "../adapters/truth-spine-boundary.js";
import { metricRegistryMetadata, PlatformMetricRegistryAdapter } from "../adapters/metric-registry-boundary.js";

function actor(input: any): AssuranceActor { return { userId: String(input?.userId || input?.user_id || input?.id || ""), organizationId: String(input?.organizationId || input?.organization_id || input?.active_organization_id || ""), tenantId: String(input?.tenantId || input?.tenant_id || ""), permissions: input?.permissions || [], actor_type: input?.actor_type || input?.actorType || "user" }; }
function value(input: any, camel: string, snake = camel) { return input?.[camel] ?? input?.[snake]; }
function permission(a: AssuranceActor, p: string) { if (!hasPermission(a.permissions || [], p)) throw new Error("GPA_PERMISSION_REQUIRED"); }
function json(valueInput: unknown) { return JSON.stringify(valueInput ?? {}); }

export class MetricTruthService {
  constructor(private repo = new GovernmentAssuranceRepo(), private verificationRepo = new ClaimVerificationRepo(), private auditWriter: typeof writeAuditEvent | null = writeAuditEvent, private outbox: IntegrationOutboxRepo | null = null, private metricRegistry: PlatformMetricRegistryAdapter | null = null) {}
  private context(input: any) { const a = actor(input); return { actor: a, scope: assuranceScope(a) }; }
  private async audit(a: AssuranceActor, s: any, type: string, id: string, action: string, previous: any, next: any, reason?: string) { if (!this.auditWriter) return; await this.auditWriter({ audit_event_id: `gpa_metric_truth_audit_${randomUUID()}`, organization_id: s.organizationId, actor_user_id: a.userId, target_object_type: type, target_object_id: id, action_type: action, previous_state_json: previous, new_state_json: next, reason_code: reason || null, correlation_id: `gpa_metric_truth_${randomUUID()}`, source_channel: "government_assurance" }); }

  async createMetric(actorInput: any, input: any) {
    const { actor: a, scope: s } = this.context(actorInput); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_METRIC_MANAGE); requireScope(input, s);
    const type = String(input.metricType || input.metric_type || "CUSTOM"); if (!GPA_METRIC_TYPES.includes(type as any)) throw new Error("GPA_METRIC_TYPE_INVALID");
    const metadata = this.metricRegistry ? this.metricRegistry.registrationMetadata({ metric_id: input.metricId || input.metric_id, version: input.version, metadata: input.metadata }) : metricRegistryMetadata({ metric_id: input.metricId || input.metric_id, version: input.version, metadata: input.metadata });
    return this.repo.createMetric({ metric_id: String(input.metricId || input.metric_id), version: Number(input.version || 1), organization_id: s.organizationId, tenant_id: s.tenantId, program_reference: input.programReference || input.program_reference, canonical_name: String(input.canonicalName || input.canonical_name), definition: String(input.definition), unit_value_type: String(input.unitValueType || input.unit_value_type), metric_type: type, numerator_definition: input.numeratorDefinition || input.numerator_definition, denominator_definition: input.denominatorDefinition || input.denominator_definition, formula_reference: input.formulaReference || input.formula_reference, inclusion_criteria: input.inclusionCriteria || input.inclusion_criteria, exclusion_criteria: input.exclusionCriteria || input.exclusion_criteria, population_definition: input.populationDefinition || input.population_definition, required_evidence_classes: input.requiredEvidenceClasses || input.required_evidence_classes, minimum_verification_level: input.minimumVerificationLevel || input.minimum_verification_level || "V2", source_authority_requirements: input.sourceAuthorityRequirements || input.source_authority_requirements, reporting_period_rules: input.reportingPeriodRules || input.reporting_period_rules, jurisdiction_reference: input.jurisdictionReference || input.jurisdiction_reference, effective_from: input.effectiveFrom || input.effective_from || new Date(), effective_to: input.effectiveTo || input.effective_to, status: input.status || "DRAFT", authority_owner_reference: input.authorityOwnerReference || input.authority_owner_reference, supersedes_metric_version: input.supersedesMetricVersion || input.supersedes_metric_version, approval_reference: input.approvalReference || input.approval_reference, provenance: input.provenance, created_by: s.userId, metadata });
  }

  async readiness(actorInput: any, input: any) {
    const { actor: a, scope: s } = this.context(actorInput); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_METRIC_VIEW);
    const metric = await this.repo.getMetric(String(value(input, "metricId", "metric_id")), Number(value(input, "metricVersion", "metric_version") || 1), s); const blockers: string[] = [];
    if (!metric) blockers.push(GPA_LINEAGE_CODES.METRIC_NOT_FOUND); else { const now = new Date(); if (metric.status !== "ACTIVE") blockers.push(GPA_LINEAGE_CODES.METRIC_NOT_ACTIVE); if (new Date(metric.effective_from) > now || (metric.effective_to && new Date(metric.effective_to) <= now)) blockers.push(GPA_LINEAGE_CODES.METRIC_VERSION_NOT_EFFECTIVE); }
    for (const item of input.inputs || []) { if (item.organizationId && item.organizationId !== s.organizationId || item.tenantId && item.tenantId !== s.tenantId) blockers.push("GPA_LINEAGE_SCOPE_MISMATCH"); if (!item.verificationId || !item.provenanceReference) blockers.push(GPA_LINEAGE_CODES.PROVENANCE_INCOMPLETE); if (item.verificationLevel && metric && !verificationLevelAtLeast(item.verificationLevel, metric.minimum_verification_level)) blockers.push(GPA_LINEAGE_CODES.VERIFICATION_LEVEL_TOO_LOW); if (item.sourceFreshnessState === "STALE" || item.stale || item.evidenceRetracted || item.evidenceSuperseded) blockers.push("GPA_SOURCE_STALE"); if (item.dataQualityCriticalFailure) blockers.push("GPA_CRITICAL_DATA_QUALITY_FAILURE"); if (["AMBIGUOUS", "UNRESOLVED"].includes(item.entityResolutionStatus)) blockers.push("GPA_ENTITY_MATCH_AMBIGUOUS"); if (item.duplicateConfirmed) blockers.push("GPA_DUPLICATE_INPUT_INVALID"); if (item.reconciliationUnresolved) blockers.push("GPA_RECONCILIATION_UNRESOLVED"); }
    return { ready: blockers.length === 0, blockers, metricId: input.metricId || input.metric_id, metricVersion: input.metricVersion || input.metric_version || 1 };
  }

  async calculate(actorInput: any, input: any) {
    const { actor: a, scope: s } = this.context(actorInput); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_METRIC_CALCULATE); requireScope(input, s);
    const metric = await this.repo.getMetric(String(value(input, "metricId", "metric_id")), Number(value(input, "metricVersion", "metric_version") || 1), s); if (!metric) throw new Error(GPA_LINEAGE_CODES.METRIC_NOT_FOUND);
    const now = new Date(); if (metric.status !== "ACTIVE") throw new Error(GPA_LINEAGE_CODES.METRIC_NOT_ACTIVE); if (new Date(metric.effective_from) > now || (metric.effective_to && new Date(metric.effective_to) <= now)) throw new Error(GPA_LINEAGE_CODES.METRIC_VERSION_NOT_EFFECTIVE);
    const inputs = Array.isArray(input.inputs) ? input.inputs : []; if (!inputs.length) throw new Error(GPA_LINEAGE_CODES.INPUT_MISSING);
    const required = String(metric.minimum_verification_level || "V2"); for (const item of inputs) { if (item.organizationId && item.organizationId !== s.organizationId || item.tenantId && item.tenantId !== s.tenantId) throw new Error("GPA_LINEAGE_SCOPE_MISMATCH"); if (!item.provenanceReference) throw new Error(GPA_LINEAGE_CODES.PROVENANCE_INCOMPLETE); if (!item.verificationLevel || !verificationLevelAtLeast(item.verificationLevel, required)) throw new Error(GPA_LINEAGE_CODES.VERIFICATION_LEVEL_TOO_LOW); if (item.contradictionUnresolved || item.reconciliationUnresolved) throw new Error(GPA_LINEAGE_CODES.CONTRADICTION_UNRESOLVED); if (item.sourceFreshnessState === "STALE" || item.stale || item.evidenceRetracted || item.evidenceSuperseded) throw new Error("GPA_SOURCE_STALE"); if (item.dataQualityCriticalFailure) throw new Error("GPA_CRITICAL_DATA_QUALITY_FAILURE"); if (["AMBIGUOUS", "UNRESOLVED"].includes(item.entityResolutionStatus)) throw new Error("GPA_ENTITY_MATCH_AMBIGUOUS"); if (item.duplicateConfirmed) throw new Error("GPA_DUPLICATE_INPUT_INVALID"); }
    const values = inputs.map((item: any) => Number(item.value)); if (values.some((item) => !Number.isFinite(item))) throw new Error(GPA_LINEAGE_CODES.INPUT_MISSING);
    const numerator = input.numerator ?? (metric.metric_type === "COUNT" ? values.length : values.reduce((sum, item) => sum + item, 0));
    const denominator = input.denominator ?? (metric.metric_type === "RATE" || metric.metric_type === "PERCENTAGE" || metric.metric_type === "RATIO" ? Number(input.denominatorValue) : null);
    let calculated: number | boolean = numerator; if (denominator !== null) { if (!Number.isFinite(denominator) || denominator === 0) throw new Error(GPA_LINEAGE_CODES.INPUT_MISSING); calculated = numerator / denominator; if (metric.metric_type === "PERCENTAGE") calculated *= 100; } else if (metric.metric_type === "AVERAGE") calculated = numerator / values.length; else if (metric.metric_type === "BOOLEAN") calculated = Boolean(input.booleanValue);
    const references = inputs.map((item: any) => ({ claimId: item.claimId, verificationId: item.verificationId, evidenceReferences: item.evidenceReferences || [], sourceProvenanceReference: item.provenanceReference, sourceAuthorityReference: item.sourceAuthorityReference }));
    const calculationVersion = String(input.calculationVersion || `gpa-calculation-${metric.metric_id}-${metric.version}`); const calculationHash = createHash("sha256").update(json({ metricId: metric.metric_id, version: metric.version, inputs: references, numerator, denominator, calculated })).digest("hex");
    const result = await this.repo.createMetricResult({ metric_result_id: String(input.metricResultId || input.metric_result_id || `gpa_metric_result_${randomUUID()}`), metric_id: metric.metric_id, metric_version: metric.version, organization_id: s.organizationId, tenant_id: s.tenantId, program_reference: input.programReference || input.program_reference || metric.program_reference, provider_reference: input.providerReference || input.provider_reference, jurisdiction_reference: input.jurisdictionReference || input.jurisdiction_reference, reporting_period_start: input.reportingPeriodStart || input.reporting_period_start, reporting_period_end: input.reportingPeriodEnd || input.reporting_period_end, population_reference: input.populationReference || input.population_reference, numerator, denominator, calculated_value: calculated, unit_value_type: metric.unit_value_type, input_references: references, input_verification_levels: inputs.map((item: any) => item.verificationLevel), calculation_version: calculationVersion, calculation_hash: calculationHash, calculated_by: s.userId, status: "CALCULATED", provenance: { metricDefinition: `${metric.metric_id}:${metric.version}`, calculatedBy: s.userId, source: "canonical-government-assurance-service" } });
    await this.audit(a, s, "GPA_METRIC_RESULT", result.metric_result_id, "METRIC_CALCULATED", null, result); return result;
  }

  async determineTruth(actorInput: any, input: any) {
    const { actor: a, scope: s } = this.context(actorInput); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_TRUTH_DETERMINE); requireScope(input, s);
    if (["ai", "agent", "reporting", "oracle"].includes(String(a.actor_type).toLowerCase())) throw new Error(GPA_LINEAGE_CODES.TRUTH_ACTOR_DENIED);
    const result = await this.repo.getMetricResult(String(value(input, "metricResultId", "metric_result_id")), s); if (!result) throw new Error(GPA_LINEAGE_CODES.METRIC_RESULT_NOT_FOUND); if (result.status !== "CALCULATED" && result.status !== "ACCEPTED") throw new Error(GPA_LINEAGE_CODES.TRUTH_LINEAGE_REQUIRED);
    const metric = await this.repo.getMetric(result.metric_id, result.metric_version, s); if (!metric) throw new Error(GPA_LINEAGE_CODES.METRIC_NOT_FOUND);
    const refs = Array.isArray(result.input_references) ? result.input_references : []; if (!refs.length || refs.some((item: any) => !item.claimId || !item.verificationId || !item.sourceProvenanceReference)) throw new Error(GPA_LINEAGE_CODES.PROVENANCE_INCOMPLETE);
    for (const ref of refs) { const verification = await this.verificationRepo.getVerification(ref.verificationId, s); if (!verification || verification.status !== "PASSED" || !verificationLevelAtLeast(verification.achieved_level, metric.minimum_verification_level)) throw new Error(GPA_LINEAGE_CODES.TRUTH_VERIFICATION_REQUIRED); if (verification.claim_id !== ref.claimId) throw new Error(GPA_LINEAGE_CODES.TRUTH_LINEAGE_REQUIRED); const contradictions = await this.verificationRepo.listContradictions(ref.verificationId, s); if (contradictions.some((item: any) => item.status === "OPEN" && item.materiality === "BLOCKING")) throw new Error(GPA_LINEAGE_CODES.CONTRADICTION_UNRESOLVED); }
    const reconciliationCaseId = input.reconciliationCaseId || input.reconciliation_case_id;
    if (reconciliationCaseId && this.repo.getReconciliationCase) { const reconciliation = await this.repo.getReconciliationCase(String(reconciliationCaseId), s); if (!reconciliation || reconciliation.status !== "RESOLVED") throw new Error("GPA_RECONCILIATION_UNRESOLVED"); }
    const truthFactId = String(input.truthFactId || input.truth_fact_id || `gpa_truth_${randomUUID()}`);
    const determinationId = `gpa_truth_determination_${randomUUID()}`;
    const handoff = createTruthSpineHandoff({ truthFactId, determinationId, organizationId: s.organizationId, tenantId: s.tenantId, decision: "ACCEPTED", verificationStatus: "PASSED", claimReference: refs[0].claimId, verificationReference: refs[0].verificationId, provenanceReference: refs[0].sourceProvenanceReference });
    const provenance = { metricResultId: result.metric_result_id, metric: `${metric.metric_id}:${metric.version}`, determination: "explicit-gated-lineage", truthSpineHandoff: handoff };
    const fact = await this.repo.createTruthFact({ truth_fact_id: truthFactId, organization_id: s.organizationId, tenant_id: s.tenantId, fact_type: input.factType || "METRIC_RESULT", subject_type: input.subjectType || "METRIC", subject_reference: input.subjectReference || result.metric_result_id, claim_id: refs[0].claimId, verification_id: refs[0].verificationId, source_references: refs, fact_value: result.calculated_value, status: "ACCEPTED", provenance, supersedes_truth_fact_id: input.supersedesTruthFactId || input.supersedes_truth_fact_id, determined_by: s.userId, created_by: s.userId, metric_result_id: result.metric_result_id, unit_value_type: result.unit_value_type, reporting_period_start: result.reporting_period_start, reporting_period_end: result.reporting_period_end, accepted_at: new Date(), verification_level: metric.minimum_verification_level, authority_level: input.authorityLevel || "CANONICAL_SOURCE_VERIFIED", public_approval_status: "NOT_REVIEWED", confidence: input.confidence, reconciliation_case_id: reconciliationCaseId, determination_metadata: { authorizationReference: input.authorizationReference || "explicit-truth-determine-permission", truthSpineAuthority: handoff.authority } });
    const determination = { determination_id: determinationId, truth_fact_id: fact.truth_fact_id, organization_id: s.organizationId, tenant_id: s.tenantId, decision: "ACCEPTED", determining_actor: s.userId, authorization_reference: input.authorizationReference || "explicit-truth-determine-permission", claim_reference: refs[0].claimId, verification_reference: refs[0].verificationId, metric_result_reference: result.metric_result_id, evidence_references: refs.flatMap((ref: any) => ref.evidenceReferences || []), source_authority_references: refs.map((ref: any) => ref.sourceAuthorityReference).filter(Boolean), reconciliation_references: reconciliationCaseId ? [reconciliationCaseId] : [], reason: String(input.reason || "Metric result passed canonical lineage gate"), policy_version_reference: input.policyVersionReference, correlation_id: `gpa_truth_corr_${randomUUID()}`, provenance };
    await this.repo.createTruthDetermination(determination);
    if (this.outbox) await this.outbox.enqueue(buildGovernmentAssuranceTruthDeterminationOutboxEvent(determination, handoff, determination.correlation_id));
    await this.audit(a, s, "GPA_TRUTH_FACT", fact.truth_fact_id, "TRUTH_ACCEPTED", null, fact); return fact;
  }

  async listMetrics(actorInput: any) { const { actor: a, scope: s } = this.context(actorInput); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_METRIC_VIEW); return this.repo.listMetrics(s); }
  async listResults(actorInput: any) { const { actor: a, scope: s } = this.context(actorInput); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_METRIC_VIEW); return this.repo.listMetricResults(s); }
  async getTruthFact(actorInput: any, id: string) { const { actor: a, scope: s } = this.context(actorInput); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_TRUTH_VIEW); return this.repo.getTruthFact(id, s); }
  async getLineage(actorInput: any, id: string) { const { actor: a, scope: s } = this.context(actorInput); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_LINEAGE_VIEW); const row = await this.repo.listMetricResultLineage(id, s); if (!row) throw new Error(GPA_LINEAGE_CODES.METRIC_RESULT_NOT_FOUND); return row; }
  async supersedeTruth(actorInput: any, truthFactId: string, input: any) {
    const { actor: a, scope: s } = this.context(actorInput); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_TRUTH_SUPERSEDE);
    const prior = await this.repo.getTruthFact(truthFactId, s); if (!prior) throw new Error(GPA_LINEAGE_CODES.TRUTH_NOT_FOUND);
    const replacement = await this.repo.createTruthFact({ ...prior, truth_fact_id: String(input.truthFactId || input.truth_fact_id || `gpa_truth_${randomUUID()}`), status: "ACCEPTED", supersedes_truth_fact_id: truthFactId, fact_value: input.factValue ?? prior.fact_value, provenance: { ...(prior.provenance || {}), supersedes: truthFactId, reason: input.reason || "Correction" }, determined_by: s.userId, created_by: s.userId, accepted_at: new Date() });
    await this.repo.updateTruthStatus(truthFactId, s, "SUPERSEDED"); await this.repo.createTruthDetermination({ determination_id: `gpa_truth_determination_${randomUUID()}`, truth_fact_id: replacement.truth_fact_id, organization_id: s.organizationId, tenant_id: s.tenantId, decision: "SUPERSEDED", determining_actor: s.userId, authorization_reference: input.authorizationReference || "truth.supersede", reason: String(input.reason || "Superseded by corrected fact"), correlation_id: `gpa_truth_corr_${randomUUID()}`, provenance: replacement.provenance }); await this.audit(a, s, "GPA_TRUTH_FACT", replacement.truth_fact_id, "TRUTH_SUPERSEDED", prior, replacement); return replacement;
  }
  async retractTruth(actorInput: any, truthFactId: string, input: any) {
    const { actor: a, scope: s } = this.context(actorInput); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_TRUTH_RETRACT);
    const prior = await this.repo.getTruthFact(truthFactId, s); if (!prior) throw new Error(GPA_LINEAGE_CODES.TRUTH_NOT_FOUND); const result = await this.repo.updateTruthStatus(truthFactId, s, "RETRACTED", String(input.reason || "Retraction required")); await this.repo.createTruthDetermination({ determination_id: `gpa_truth_determination_${randomUUID()}`, truth_fact_id: truthFactId, organization_id: s.organizationId, tenant_id: s.tenantId, decision: "RETRACTED", determining_actor: s.userId, authorization_reference: input.authorizationReference || "truth.retract", reason: String(input.reason || "Retraction required"), correlation_id: `gpa_truth_corr_${randomUUID()}`, provenance: { priorTruthFactId: truthFactId } }); await this.audit(a, s, "GPA_TRUTH_FACT", truthFactId, "TRUTH_RETRACTED", prior, result); return result;
  }
}
