import { randomUUID } from "node:crypto";
import { hasPermission, SHS_SECURITY_PERMISSIONS } from "../../../auth/security-permissions.js";
import { assuranceScope, requireScope, type AssuranceActor } from "../model/government-assurance.js";
import { GPA_CONFLICT_TYPES, GPA_DUPLICATE_CLASSIFICATIONS, GPA_DQ_DIMENSIONS, GPA_DQ_STATES, GPA_MATCH_METHODS, GPA_MATCH_STATUSES, GPA_RECONCILIATION_CODES, GPA_RECONCILIATION_STATUSES } from "../model/reconciliation-quality.js";
import { ReconciliationQualityRepo } from "../repo/reconciliation-quality-repo.js";

function actor(i: any): AssuranceActor { return { userId: String(i?.userId || i?.user_id || i?.id || ""), organizationId: String(i?.organizationId || i?.organization_id || i?.active_organization_id || ""), tenantId: String(i?.tenantId || i?.tenant_id || ""), permissions: i?.permissions || [], actor_type: i?.actor_type || i?.actorType || "user" }; }
function permission(a: AssuranceActor, p: string) { if (!hasPermission(a.permissions || [], p)) throw new Error("GPA_PERMISSION_REQUIRED"); }
function ctx(i: any) { const a = actor(i); return { actor: a, scope: assuranceScope(a) }; }
export class ReconciliationQualityService {
  constructor(private repo = new ReconciliationQualityRepo()) {}
  async createCase(i: any, input: any) { const { actor: a, scope: s } = ctx(i); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_RECONCILIATION_MANAGE); requireScope(input, s); if (!input.subjectType || !input.subjectReference || !input.conflictReason) throw new Error(GPA_RECONCILIATION_CODES.CASE_FIELDS_REQUIRED); if (!GPA_CONFLICT_TYPES.includes(String(input.conflictType || "VALUE_MISMATCH") as any)) throw new Error(GPA_RECONCILIATION_CODES.CONFLICT_TYPE_INVALID); return this.repo.createCase({ reconciliation_case_id: input.reconciliationCaseId || `gpa_reconciliation_${randomUUID()}`, organization_id: s.organizationId, tenant_id: s.tenantId, subject_type: input.subjectType, subject_reference: input.subjectReference, competing_source_references: input.competingSourceReferences || [], competing_claim_references: input.competingClaimReferences || [], conflict_reason: input.conflictReason, source_authority_references: input.sourceAuthorityReferences || [], status: "OPEN", created_by: s.userId, metadata: input.metadata || {}, conflict_type: input.conflictType || "VALUE_MISMATCH", conflicting_record_references: input.conflictingRecordReferences || [], current_authority_ranking: input.currentAuthorityRanking || {}, materiality: input.materiality || "NON_MATERIAL", severity: input.severity || "MEDIUM", assigned_reviewer: input.assignedReviewer, opened_at: input.openedAt || new Date(), provenance: input.provenance || {} }); }
  async listCases(i: any) { const { actor: a, scope: s } = ctx(i); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_RECONCILIATION_VIEW); return this.repo.listCases(s); }
  async getCase(i: any, id: string) { const { actor: a, scope: s } = ctx(i); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_RECONCILIATION_VIEW); const row = await this.repo.getCase(id, s); if (!row) throw new Error(GPA_RECONCILIATION_CODES.CASE_NOT_FOUND); return row; }
  async listDuplicates(i: any) { const { actor: a, scope: s } = ctx(i); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_RECONCILIATION_VIEW); return this.repo.listDuplicates(s); }
  async listSchemaObservations(i: any) { const { actor: a, scope: s } = ctx(i); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_DATA_QUALITY_VIEW); return this.repo.listSchemaObservations(s); }
  async listRejectedRecords(i: any) { const { actor: a, scope: s } = ctx(i); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_DATA_QUALITY_VIEW); return this.repo.listRejectedRecords(s); }
  async determineCase(i: any, id: string, input: any) { const { actor: a, scope: s } = ctx(i); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_RECONCILIATION_DETERMINE); const prior = await this.repo.getCase(id, s); if (!prior) throw new Error(GPA_RECONCILIATION_CODES.CASE_NOT_FOUND); const material = ["HIGH", "CRITICAL"].includes(String(prior.severity).toUpperCase()) || String(prior.materiality).toUpperCase() === "MATERIAL"; if (material && (!input.reviewerReference || String(input.reviewerReference) === a.userId || String(input.authorityReference || "") === a.userId)) throw new Error(GPA_RECONCILIATION_CODES.SELF_REVIEW_DENIED); const status = String(input.status || "RESOLVED"); if (!GPA_RECONCILIATION_STATUSES.includes(status as any)) throw new Error("GPA_RECONCILIATION_STATUS_INVALID"); if (status === "RESOLVED" && !input.determination) throw new Error("GPA_RECONCILIATION_DETERMINATION_REQUIRED"); return this.repo.determineCase(id, s, { status, reviewer_reference: input.reviewerReference, authority_reference: input.authorityReference, determination: input.determination, resolution_method: input.resolutionMethod, rationale: input.rationale, downstream_impact_references: input.downstreamImpactReferences || [], provenance: { ...(input.provenance || {}), determinedBy: a.userId } }); }
  async createQualityRule(i: any, input: any) { const { actor: a, scope: s } = ctx(i); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_DATA_QUALITY_EVALUATE); requireScope(input, s); if (!input.ruleId || !input.logicReference || !GPA_DQ_DIMENSIONS.includes(String(input.dimension) as any)) throw new Error(GPA_RECONCILIATION_CODES.QUALITY_RULE_REQUIRED); return this.repo.createQualityRule({ rule_id: input.ruleId, version: input.version || 1, organization_id: s.organizationId, tenant_id: s.tenantId, source_system_id: input.sourceSystemId, data_domain: input.dataDomain, record_type: input.recordType, dimension: input.dimension, severity: input.severity || "MEDIUM", logic_reference: input.logicReference, effective_from: input.effectiveFrom || new Date(), effective_to: input.effectiveTo, status: input.status || "DRAFT", owner_reference: input.ownerReference, approval_reference: input.approvalReference, provenance: input.provenance || {}, created_by: s.userId }); }
  async evaluateQuality(i: any, input: any) { const { actor: a, scope: s } = ctx(i); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_DATA_QUALITY_EVALUATE); requireScope(input, s); if (!input.subjectType || !input.subjectReference || !GPA_DQ_DIMENSIONS.includes(String(input.dimension) as any) || !GPA_DQ_STATES.includes(String(input.state) as any)) throw new Error("GPA_DATA_QUALITY_FIELDS_REQUIRED"); return this.repo.createQualityEvaluation({ quality_evaluation_id: input.qualityEvaluationId || `gpa_quality_${randomUUID()}`, organization_id: s.organizationId, tenant_id: s.tenantId, source_system_id: input.sourceSystemId, subject_type: input.subjectType, subject_reference: input.subjectReference, dimension: input.dimension, rule_id: input.ruleId, rule_version: input.ruleVersion, state: input.state, score: input.score, reason_codes: input.reasonCodes || [], evaluated_by: s.userId, provenance: input.provenance || {} }); }
  async qualityReadiness(i: any, input: any) { const { actor: a, scope: s } = ctx(i); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_DATA_QUALITY_VIEW); requireScope(input, s); const evaluations = await this.repo.listQualityEvaluations(s); const relevant = evaluations.filter((e: any) => !input.subjectReference || e.subject_reference === input.subjectReference); const blockers = relevant.filter((e: any) => e.state === "FAIL" && ["HIGH", "CRITICAL"].includes(String(e.severity || input.severity || "HIGH").toUpperCase())).map((e: any) => `GPA_QUALITY_${e.dimension}_FAIL`); return { ready: blockers.length === 0, blockers, evaluations: relevant }; }
  async listQualityRules(i: any) { const { actor: a, scope: s } = ctx(i); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_DATA_QUALITY_VIEW); return this.repo.listQualityRules(s); }
  async listQualityEvaluations(i: any) { const { actor: a, scope: s } = ctx(i); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_DATA_QUALITY_VIEW); return this.repo.listQualityEvaluations(s); }
  async evaluateEntity(i: any, input: any) { const { actor: a, scope: s } = ctx(i); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_ENTITY_RESOLUTION_VIEW); requireScope(input, s); if (!input.entityType || !input.sourceSystemId || !input.sourceRecordId || !GPA_MATCH_METHODS.includes(String(input.matchMethod) as any)) throw new Error(GPA_RECONCILIATION_CODES.ENTITY_FIELDS_REQUIRED); const candidates = input.candidateEntityReferences || []; const status = input.status || (input.matchMethod === "DETERMINISTIC" && candidates.length === 1 ? "MATCHED" : candidates.length > 1 ? "AMBIGUOUS" : "UNRESOLVED"); if (status === "MATCHED" && input.matchMethod !== "DETERMINISTIC" && !input.reviewerReference) throw new Error(GPA_RECONCILIATION_CODES.AMBIGUOUS_MATCH); return this.repo.createEntityResolution({ resolution_id: input.resolutionId || `gpa_resolution_${randomUUID()}`, organization_id: s.organizationId, tenant_id: s.tenantId, entity_type: input.entityType, source_system_id: input.sourceSystemId, source_record_id: input.sourceRecordId, candidate_entity_references: candidates, match_method: input.matchMethod, match_attributes: input.matchAttributes || {}, confidence: input.confidence, status, reviewer_reference: input.reviewerReference, determination: input.determination, provenance: input.provenance || {}, created_by: s.userId }); }
  async listEntities(i: any) { const { actor: a, scope: s } = ctx(i); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_ENTITY_RESOLUTION_VIEW); return this.repo.listEntityResolutions(s); }
  async determineEntity(i: any, id: string, input: any) { const { actor: a, scope: s } = ctx(i); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_ENTITY_RESOLUTION_DETERMINE); const status = String(input.status || "MATCHED"); if (!GPA_MATCH_STATUSES.includes(status as any)) throw new Error("GPA_ENTITY_STATUS_INVALID"); if (["MATCHED", "REJECTED"].includes(status) && !input.determination) throw new Error("GPA_ENTITY_DETERMINATION_REQUIRED"); return this.repo.determineEntity(id, s, { status, reviewer_reference: input.reviewerReference || a.userId, determination: { ...(input.determination || {}), determinedBy: a.userId } }); }
  async createDuplicate(i: any, input: any) { const { actor: a, scope: s } = ctx(i); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_RECONCILIATION_MANAGE); requireScope(input, s); if (!input.subjectType || !input.leftReference || !input.rightReference) throw new Error(GPA_RECONCILIATION_CODES.DUPLICATE_FIELDS_REQUIRED); const classification = input.classification || "POSSIBLE_DUPLICATE"; if (!GPA_DUPLICATE_CLASSIFICATIONS.includes(classification as any)) throw new Error("GPA_DUPLICATE_CLASSIFICATION_INVALID"); return this.repo.createDuplicate({ duplicate_candidate_id: input.duplicateCandidateId || `gpa_duplicate_${randomUUID()}`, organization_id: s.organizationId, tenant_id: s.tenantId, subject_type: input.subjectType, left_reference: input.leftReference, right_reference: input.rightReference, classification, reconciliation_case_id: input.reconciliationCaseId, evidence_references: input.evidenceReferences || [], created_by: s.userId }); }
  async createSchemaObservation(i: any, input: any) { const { actor: a, scope: s } = ctx(i); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_DATA_QUALITY_EVALUATE); requireScope(input, s); return this.repo.createSchemaObservation({ observation_id: input.observationId || `gpa_schema_${randomUUID()}`, organization_id: s.organizationId, tenant_id: s.tenantId, source_system_id: input.sourceSystemId, observed_schema_version: input.observedSchemaVersion, observed_signature: input.observedSignature, expected_mapping_version: input.expectedMappingVersion, drift_classification: input.driftClassification, affected_mapping_references: input.affectedMappingReferences || [], status: input.status || "OPEN", remediation_reference: input.remediationReference, provenance: input.provenance || {}, created_by: s.userId }); }
  async rejectRecord(i: any, input: any) { const { actor: a, scope: s } = ctx(i); permission(a, SHS_SECURITY_PERMISSIONS.GOVERNMENT_ASSURANCE_DATA_QUALITY_EVALUATE); requireScope(input, s); if (!input.sourceSystemId || !input.failureReason) throw new Error("GPA_REJECTED_RECORD_FIELDS_REQUIRED"); return this.repo.createRejectedRecord({ rejected_record_id: input.rejectedRecordId || `gpa_rejected_${randomUUID()}`, organization_id: s.organizationId, tenant_id: s.tenantId, source_system_id: input.sourceSystemId, source_record_id: input.sourceRecordId, batch_reference: input.batchReference, rule_id: input.ruleId, failure_reason: input.failureReason, remediation_status: input.remediationStatus || "OPEN", provenance: input.provenance || {}, created_by: s.userId }); }
}
