import { query } from "../../../db/client.js";

export type Executor = { query: (sql: string, params?: unknown[]) => Promise<any> };

export class McpRepo {
  constructor(private dbQuery: typeof query = query) {}
  async createServer(input: any, executor: Executor = { query: this.dbQuery }) { return (await executor.query(`INSERT INTO mcp_servers (mcp_server_id,organization_id,tenant_id,display_name,provider_identifier,endpoint_reference,transport_type,trust_status,lifecycle_status,credential_reference,created_by,metadata_json) VALUES ($1,$2,$3,$4,$5,$6,$7,'LOCAL_CONFIGURED','PENDING',$8,$9,$10) RETURNING *`, [input.server_id,input.organization_id,input.tenant_id,input.display_name,input.provider_identifier,input.endpoint_reference,input.transport_type,input.credential_reference || null,input.created_by,JSON.stringify(input.metadata_json || {})])).rows[0]; }
  async getServer(id: string, organizationId: string, tenantId: string, executor: Executor = { query: this.dbQuery }) { return (await executor.query("SELECT * FROM mcp_servers WHERE mcp_server_id=$1 AND (organization_id=$2 OR organization_id IS NULL) AND (tenant_id=$3 OR tenant_id IS NULL)",[id,organizationId,tenantId])).rows[0] || null; }
  async listServers(organizationId: string, tenantId: string, executor: Executor = { query: this.dbQuery }) { return (await executor.query("SELECT * FROM mcp_servers WHERE (organization_id=$1 OR organization_id IS NULL) AND (tenant_id=$2 OR tenant_id IS NULL) ORDER BY created_at DESC",[organizationId,tenantId])).rows; }
  async setLifecycle(input: any, executor: Executor = { query: this.dbQuery }) { return (await executor.query("UPDATE mcp_servers SET lifecycle_status=$4, trust_status=CASE WHEN $4='ACTIVE' THEN 'ADMIN_APPROVED' ELSE trust_status END, approved_by=CASE WHEN $4 IN ('APPROVED','ACTIVE') THEN $3 ELSE approved_by END, approved_at=CASE WHEN $4 IN ('APPROVED','ACTIVE') THEN NOW() ELSE approved_at END, disabled_by=CASE WHEN $4='DISABLED' THEN $3 ELSE disabled_by END, disabled_at=CASE WHEN $4='DISABLED' THEN NOW() ELSE disabled_at END, revoked_by=CASE WHEN $4='REVOKED' THEN $3 ELSE revoked_by END, revoked_at=CASE WHEN $4='REVOKED' THEN NOW() ELSE revoked_at END, updated_at=NOW() WHERE mcp_server_id=$1 AND (organization_id=$2 OR organization_id IS NULL) RETURNING *",[input.server_id,input.organization_id,input.actor_id,input.status])).rows[0] || null; }
  async upsertTool(input: any, executor: Executor = { query: this.dbQuery }) { return (await executor.query(`INSERT INTO mcp_tools (mcp_tool_id,mcp_server_id,tool_key,display_name,description,input_schema_json,output_schema_json,side_effect_class,risk_level,required_approval_profile,discovery_version,metadata_json) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT (mcp_server_id,tool_key) DO UPDATE SET display_name=EXCLUDED.display_name,description=EXCLUDED.description,input_schema_json=EXCLUDED.input_schema_json,output_schema_json=EXCLUDED.output_schema_json,side_effect_class=EXCLUDED.side_effect_class,risk_level=EXCLUDED.risk_level,required_approval_profile=EXCLUDED.required_approval_profile,discovery_version=EXCLUDED.discovery_version,discovered_at=NOW(),enabled=TRUE,metadata_json=EXCLUDED.metadata_json RETURNING *`,[input.tool_id,input.server_id,input.tool_key,input.display_name,input.description || "",JSON.stringify(input.input_schema || {}),JSON.stringify(input.output_schema || {}),input.side_effect_class,input.risk_level,input.required_approval_profile,input.discovery_version || null,JSON.stringify(input.metadata_json || {})])).rows[0]; }
  async upsertResource(input: any, executor: Executor = { query: this.dbQuery }) { return (await executor.query(`INSERT INTO mcp_resources (mcp_resource_id,mcp_server_id,resource_uri,resource_type,display_name,media_type,external_classification_hint,bos_classification,organization_id,tenant_id,provenance_json) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT (mcp_server_id,resource_uri) DO UPDATE SET resource_type=EXCLUDED.resource_type,display_name=EXCLUDED.display_name,media_type=EXCLUDED.media_type,external_classification_hint=EXCLUDED.external_classification_hint,provenance_json=EXCLUDED.provenance_json,discovered_at=NOW(),enabled=TRUE RETURNING *`,[input.resource_id,input.server_id,input.resource_uri,input.resource_type,input.display_name || "",input.media_type || null,input.external_classification_hint || null,input.bos_classification || null,input.organization_id || null,input.tenant_id || null,JSON.stringify(input.provenance_json || {})])).rows[0]; }
  async listTools(serverId: string, executor: Executor = { query: this.dbQuery }) { return (await executor.query("SELECT * FROM mcp_tools WHERE mcp_server_id=$1 AND enabled=TRUE ORDER BY tool_key",[serverId])).rows; }
  async listResources(serverId: string, executor: Executor = { query: this.dbQuery }) { return (await executor.query("SELECT * FROM mcp_resources WHERE mcp_server_id=$1 AND enabled=TRUE ORDER BY resource_uri",[serverId])).rows; }
  async getTool(toolId: string, serverId: string, executor: Executor = { query: this.dbQuery }) { return (await executor.query("SELECT * FROM mcp_tools WHERE mcp_tool_id=$1 AND mcp_server_id=$2 AND enabled=TRUE",[toolId,serverId])).rows[0] || null; }
  async getResource(resourceId: string, serverId: string, executor: Executor = { query: this.dbQuery }) { return (await executor.query("SELECT * FROM mcp_resources WHERE mcp_resource_id=$1 AND mcp_server_id=$2 AND enabled=TRUE",[resourceId,serverId])).rows[0] || null; }
  async upsertPolicy(input: any, executor: Executor = { query: this.dbQuery }) { return (await executor.query(`INSERT INTO mcp_tool_policies (mcp_tool_policy_id,mcp_server_id,mcp_tool_id,organization_id,tenant_id,agent_identifier,purpose,allowed,live_read_allowed,classification_ceiling,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT (organization_id,tenant_id,mcp_tool_id,agent_identifier,purpose) DO UPDATE SET allowed=EXCLUDED.allowed,live_read_allowed=EXCLUDED.live_read_allowed,classification_ceiling=EXCLUDED.classification_ceiling,updated_at=NOW() RETURNING *`,[input.policy_id,input.server_id,input.tool_id,input.organization_id,input.tenant_id,input.agent_identifier || null,input.purpose || null,input.allowed === true,input.live_read_allowed === true,input.classification_ceiling || "INTERNAL",input.created_by])).rows[0]; }
  async getPolicy(input: any, executor: Executor = { query: this.dbQuery }) { return (await executor.query("SELECT * FROM mcp_tool_policies WHERE mcp_tool_id=$1 AND organization_id=$2 AND tenant_id=$3 AND allowed=TRUE AND (agent_identifier IS NULL OR agent_identifier=$4) AND (purpose IS NULL OR purpose=$5) ORDER BY agent_identifier NULLS LAST, purpose NULLS LAST LIMIT 1",[input.tool_id,input.organization_id,input.tenant_id,input.agent_identifier || null,input.purpose || null])).rows[0] || null; }
  async createInvocation(input: any, executor: Executor = { query: this.dbQuery }) { return (await executor.query(`INSERT INTO mcp_invocations (mcp_invocation_id,mcp_server_id,mcp_tool_id,mcp_resource_id,simulation_id,conductor_request_id,session_id,delegation_id,principal_user_id,organization_id,tenant_id,purpose,requested_action,side_effect_class,authority_allowed,authority_code,policy_allowed,policy_code,classification,security_code,approval_required,status,execution_mode,input_json,provenance_json) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25) RETURNING *`,[input.invocation_id,input.server_id,input.tool_id || null,input.resource_id || null,input.simulation_id || null,input.conductor_request_id || null,input.session_id || null,input.delegation_id || null,input.principal_user_id,input.organization_id,input.tenant_id,input.purpose,input.requested_action,input.side_effect_class,input.authority_allowed === true,input.authority_code || null,input.policy_allowed === true,input.policy_code || null,input.classification || null,input.security_code || null,input.approval_required === true,input.status,input.execution_mode || "SIMULATED",JSON.stringify(input.input_json || {}),JSON.stringify(input.provenance_json || {})])).rows[0]; }
  async createReadResult(input: any, executor: Executor = { query: this.dbQuery }) { return (await executor.query(`INSERT INTO mcp_read_results (mcp_read_result_id,mcp_invocation_id,mcp_server_id,mcp_tool_id,mcp_resource_id,principal_user_id,agent_identifier,session_id,delegation_id,organization_id,tenant_id,source_identity,content_type,response_sha256,response_bytes,response_status,security_scan_id,context_admission_id,admission_status,failure_code,duration_ms,provenance_json) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22) RETURNING *`,[input.read_result_id,input.invocation_id,input.server_id,input.tool_id,input.resource_id || null,input.principal_user_id,input.agent_identifier || null,input.session_id || null,input.delegation_id || null,input.organization_id,input.tenant_id,input.source_identity,input.content_type || null,input.response_sha256,input.response_bytes || 0,input.response_status || null,input.security_scan_id || null,input.context_admission_id || null,input.admission_status,input.failure_code || null,input.duration_ms || null,JSON.stringify(input.provenance_json || {})])).rows[0]; }
  async updateInvocationRead(input: any, executor: Executor = { query: this.dbQuery }) { return (await executor.query(`UPDATE mcp_invocations SET result_admission_status=$2,duration_ms=$3,response_status=$4,provenance_reference=$5,security_code=$6,provenance_json=$7 WHERE mcp_invocation_id=$1 RETURNING *`,[input.invocation_id,input.result_admission_status || null,input.duration_ms || null,input.response_status || null,input.provenance_reference || null,input.security_code || null,JSON.stringify(input.provenance_json || {})])).rows[0] || null; }
}
