import { createHash, randomUUID } from "node:crypto";
import { withTransaction } from "../../../db/transaction.js";
import { hasPermission, SHS_SECURITY_PERMISSIONS } from "../../../auth/security-permissions.js";
import { IntegrationOutboxRepo } from "../../trusted-reporting/outbox-repo.js";
import { AiGovernanceService } from "../../ai-governance/service/ai-governance-service.js";
import { InputSecurityService } from "../../input-security/service/input-security-service.js";
import { AgentSimulationService } from "../../agent-simulation/service/agent-simulation-service.js";
import { EnvironmentMcpCredentialResolver, type McpCredentialResolver } from "../credential-resolver.js";
import { McpRepo, type Executor } from "../repo/mcp-repo.js";
import { HttpMcpTransport } from "../transport/http-mcp-transport.js";
import { type McpTransport } from "../transport/mcp-transport.js";
import { approvalForSideEffect, MCP_DENIAL_CODES, MCP_RISK_LEVELS, MCP_SERVER_STATES, MCP_SIDE_EFFECTS, toInvocationResponse, toReadResultResponse, toResourceResponse, toServerResponse, toToolResponse } from "../model/mcp.js";

type Actor = { user_id?: string; id?: string; active_organization_id?: string; organization_id?: string; tenant_id?: string; permissions?: string[] };
function actorScope(actor: Actor) { const userId = String(actor.user_id || actor.id || ""); const organizationId = String(actor.active_organization_id || actor.organization_id || ""); const tenantId = String(actor.tenant_id || `tenant:${organizationId}`); if (!userId || !organizationId || tenantId !== `tenant:${organizationId}`) throw new McpError("MCP_ORG_CONTEXT_REQUIRED", "Organization and tenant context are required.", 400); return { userId, organizationId, tenantId }; }
function requirePermission(actor: Actor, permission: string) { if (!hasPermission(actor.permissions || [], permission)) throw new McpError("MCP_PERMISSION_REQUIRED", "MCP permission is required.", 403); }
function normalizeSideEffect(value: any) { const side = String(value || "READ_ONLY").toUpperCase(); if (!(MCP_SIDE_EFFECTS as readonly string[]).includes(side)) throw new McpError("MCP_SIDE_EFFECT_INVALID", "Unsupported MCP side-effect classification."); return side; }
function normalizeRisk(value: any, sideEffect: string) { const risk = String(value || (["READ_ONLY"].includes(sideEffect) ? "LOW" : ["DESTRUCTIVE", "DEPLOYMENT", "SECURITY_SENSITIVE", "FINANCIAL"].includes(sideEffect) ? "CRITICAL" : "HIGH")).toUpperCase(); if (!(MCP_RISK_LEVELS as readonly string[]).includes(risk)) throw new McpError("MCP_RISK_INVALID", "Unsupported MCP risk level."); return risk; }

export class McpError extends Error { constructor(public code: string, message = code, public statusCode = 400) { super(message); } }

export class McpService {
  constructor(private repo = new McpRepo(), private transaction: typeof withTransaction = withTransaction, private outbox = new IntegrationOutboxRepo(), private aiGovernance = new AiGovernanceService(), private inputSecurity = new InputSecurityService(), private simulations = new AgentSimulationService(), private transport: McpTransport = new HttpMcpTransport(), private credentials: McpCredentialResolver = new EnvironmentMcpCredentialResolver()) {}

  private async emit(executor: Executor | null, type: string, subjectType: string, subjectId: string, scope: any, payload: any = {}) { const event = { producer_id: "shs-api.mcp-gateway", event_type: type, subject_type: subjectType, subject_id: subjectId, organization_id: scope.organizationId, tenant_id: scope.tenantId, originating_actor_id: scope.userId, originating_actor_type: "user", occurred_at: new Date().toISOString(), idempotency_key: `${type}:${subjectId}`, correlation_id: `mcp:${subjectId}`, destination: "shs-agent-fabric", payload: { ...payload, activity_kind: payload.activity_kind || "SIMULATED" } }; if (executor) return this.outbox.enqueue(event, executor); return this.outbox.enqueue(event); }

  async registerServer(actor: Actor, body: any) { requirePermission(actor, SHS_SECURITY_PERMISSIONS.AI_MCP_ADMIN); const scope = actorScope(actor); const displayName = String(body.displayName || body.display_name || "").trim(); const provider = String(body.providerIdentifier || body.provider_identifier || "").trim(); const endpoint = String(body.endpointReference || body.endpoint_reference || "").trim(); if (!displayName || !provider || !endpoint) throw new McpError("MCP_SERVER_FIELDS_REQUIRED", "Server display name, provider, and endpoint reference are required."); if (body.credential || body.secret || body.token) throw new McpError(MCP_DENIAL_CODES.SECRET_NOT_ALLOWED, "Secrets must use a credential reference, not request payload or database storage.", 400); const row = await this.transaction(async db => { const created = await this.repo.createServer({ server_id: `mcp_server_${randomUUID()}`, organization_id: scope.organizationId, tenant_id: scope.tenantId, display_name: displayName, provider_identifier: provider, endpoint_reference: endpoint, transport_type: String(body.transportType || body.transport_type || "INERT").toUpperCase(), credential_reference: body.credentialReference || body.credential_reference || null, created_by: scope.userId, metadata_json: body.metadata || {} }, db); await this.emit(db, "mcp.server.registered", "mcp_server", created.mcp_server_id, scope, { trust_status: created.trust_status }); return created; }); return toServerResponse(row); }

  async listServers(actor: Actor) { requirePermission(actor, SHS_SECURITY_PERMISSIONS.AI_MCP_READ); const scope = actorScope(actor); return (await this.repo.listServers(scope.organizationId, scope.tenantId)).map(toServerResponse); }
  async getServer(actor: Actor, id: string) { requirePermission(actor, SHS_SECURITY_PERMISSIONS.AI_MCP_READ); const scope = actorScope(actor); const row = await this.repo.getServer(id, scope.organizationId, scope.tenantId); if (!row) throw new McpError(MCP_DENIAL_CODES.SERVER_NOT_FOUND, "MCP server was not found.", 404); return toServerResponse(row); }

  async setServerLifecycle(actor: Actor, id: string, status: string) { requirePermission(actor, SHS_SECURITY_PERMISSIONS.AI_MCP_ADMIN); const scope = actorScope(actor); const next = String(status).toUpperCase(); if (!(MCP_SERVER_STATES as readonly string[]).includes(next)) throw new McpError("MCP_SERVER_STATE_INVALID", "Unsupported MCP server state."); const row = await this.transaction(async db => { const updated = await this.repo.setLifecycle({ server_id: id, organization_id: scope.organizationId, actor_id: scope.userId, status: next }, db); if (!updated) throw new McpError(MCP_DENIAL_CODES.SERVER_NOT_FOUND, "MCP server was not found.", 404); await this.emit(db, `mcp.server.${next.toLowerCase()}`, "mcp_server", id, scope, { lifecycle_status: next }); return updated; }); return toServerResponse(row); }

  private async approvedServer(scope: any, serverId: string) { const server = await this.repo.getServer(serverId, scope.organizationId, scope.tenantId); if (!server) throw new McpError(MCP_DENIAL_CODES.SERVER_NOT_FOUND, "MCP server was not found.", 404); if (server.lifecycle_status === "DISABLED") throw new McpError(MCP_DENIAL_CODES.SERVER_DISABLED, "MCP server is disabled.", 403); if (server.lifecycle_status === "REVOKED") throw new McpError(MCP_DENIAL_CODES.SERVER_REVOKED, "MCP server is revoked.", 403); if (!["APPROVED", "ACTIVE"].includes(server.lifecycle_status)) throw new McpError(MCP_DENIAL_CODES.SERVER_NOT_APPROVED, "MCP server is not approved.", 403); return server; }

  async discover(actor: Actor, serverId: string, body: any = {}) { requirePermission(actor, SHS_SECURITY_PERMISSIONS.AI_MCP_DISCOVER); const scope = actorScope(actor); const server = await this.approvedServer(scope, serverId); const tools = Array.isArray(body.tools) ? body.tools : await this.transport.discoverTools(server); const resources = Array.isArray(body.resources) ? body.resources : await this.transport.discoverResources(server); const result = await this.transaction(async db => { const toolRows = []; for (const descriptor of tools) { const side = normalizeSideEffect(descriptor.sideEffectClass || descriptor.side_effect_class); const tool = await this.repo.upsertTool({ tool_id: descriptor.toolId || descriptor.tool_id || `mcp_tool_${randomUUID()}`, server_id: serverId, tool_key: String(descriptor.toolKey || descriptor.tool_key || descriptor.name || "").trim(), display_name: String(descriptor.displayName || descriptor.display_name || descriptor.name || "").trim(), description: String(descriptor.description || ""), input_schema: descriptor.inputSchema || descriptor.input_schema || {}, output_schema: descriptor.outputSchema || descriptor.output_schema || {}, side_effect_class: side, risk_level: normalizeRisk(descriptor.riskLevel || descriptor.risk_level, side), required_approval_profile: approvalForSideEffect(side).profile, discovery_version: descriptor.discoveryVersion || descriptor.discovery_version || null, metadata_json: { source: "mcp_discovery", server_claimed_risk: descriptor.riskLevel || descriptor.risk_level || null } }, db); toolRows.push(tool); } const resourceRows = []; for (const descriptor of resources) resourceRows.push(await this.repo.upsertResource({ resource_id: descriptor.resourceId || descriptor.resource_id || `mcp_resource_${randomUUID()}`, server_id: serverId, resource_uri: String(descriptor.resourceUri || descriptor.resource_uri || descriptor.uri || "").trim(), resource_type: String(descriptor.resourceType || descriptor.resource_type || "external").trim(), display_name: descriptor.displayName || descriptor.display_name || descriptor.name || "", media_type: descriptor.mediaType || descriptor.media_type || null, external_classification_hint: descriptor.externalClassificationHint || descriptor.external_classification_hint || null, bos_classification: descriptor.bosClassification || descriptor.bos_classification || null, provenance_json: { server_id: serverId, discovered_at: new Date().toISOString() } }, db)); await this.emit(db, "mcp.tools.discovered", "mcp_server", serverId, scope, { tool_count: toolRows.length, resource_count: resourceRows.length }); return { tools: toolRows, resources: resourceRows }; }); return { tools: result.tools.map(toToolResponse), resources: result.resources.map(toResourceResponse), simulated: true }; }
  async listTools(actor: Actor, serverId: string) { requirePermission(actor, SHS_SECURITY_PERMISSIONS.AI_MCP_READ); const scope = actorScope(actor); await this.approvedServer(scope, serverId); return (await this.repo.listTools(serverId)).map(toToolResponse); }
  async listResources(actor: Actor, serverId: string) { requirePermission(actor, SHS_SECURITY_PERMISSIONS.AI_MCP_READ); const scope = actorScope(actor); await this.approvedServer(scope, serverId); return (await this.repo.listResources(serverId)).map(toResourceResponse); }
  async setToolPolicy(actor: Actor, body: any) { requirePermission(actor, SHS_SECURITY_PERMISSIONS.AI_MCP_ADMIN); const scope = actorScope(actor); if (body.organizationId && body.organizationId !== scope.organizationId) throw new McpError(MCP_DENIAL_CODES.ORGANIZATION_MISMATCH, "Organization mismatch.", 403); const row = await this.repo.upsertPolicy({ policy_id: `mcp_policy_${randomUUID()}`, server_id: body.serverId || body.server_id, tool_id: body.toolId || body.tool_id, organization_id: scope.organizationId, tenant_id: scope.tenantId, agent_identifier: body.agentIdentifier || body.agent_identifier || null, purpose: body.purpose || null, allowed: body.allowed === true, live_read_allowed: body.liveReadAllowed === true || body.live_read_allowed === true, classification_ceiling: String(body.classificationCeiling || body.classification_ceiling || "INTERNAL").toUpperCase(), created_by: scope.userId }); return row; }

  async evaluateMcpAccess(actor: Actor, body: any) { requirePermission(actor, SHS_SECURITY_PERMISSIONS.AI_MCP_SIMULATE); const scope = actorScope(actor); const server = await this.approvedServer(scope, String(body.serverId || body.server_id || "")); const toolId = String(body.toolId || body.tool_id || ""); const tool = await this.repo.getTool(toolId, server.mcp_server_id); if (!tool) return { allowed: false, denialCode: MCP_DENIAL_CODES.TOOL_NOT_FOUND, serverId: server.mcp_server_id }; const policy = await this.repo.getPolicy({ tool_id: tool.mcp_tool_id, organization_id: scope.organizationId, tenant_id: scope.tenantId, agent_identifier: body.agentIdentifier || body.agent_identifier, purpose: body.purpose }); if (!policy) return { allowed: false, denialCode: MCP_DENIAL_CODES.TOOL_NOT_ALLOWLISTED, serverId: server.mcp_server_id, toolId: tool.mcp_tool_id }; const classification = String(body.classification || "INTERNAL").toUpperCase(); if (!["PUBLIC", "INTERNAL", "SENSITIVE", "RESTRICTED"].includes(classification)) return { allowed: false, denialCode: MCP_DENIAL_CODES.CLASSIFICATION_DENIED }; if (["SENSITIVE", "RESTRICTED"].includes(classification) && classification !== policy.classification_ceiling && policy.classification_ceiling === "INTERNAL") return { allowed: false, denialCode: MCP_DENIAL_CODES.CLASSIFICATION_DENIED }; const authority = await this.aiGovernance.evaluateAgentAuthority({ principalUserId: scope.userId, organizationId: scope.organizationId, tenantId: scope.tenantId, agentIdentifier: body.agentIdentifier || body.agent_identifier, sessionId: body.sessionId || body.session_id, delegationId: body.delegationId || body.delegation_id, purpose: body.purpose, resource: body.resource || { resourceType: "mcp_tool", resourceId: tool.mcp_tool_id }, action: body.action || body.requestedAction || tool.tool_key, model: body.model || {} }); const approval = approvalForSideEffect(tool.side_effect_class); return { allowed: authority.allowed && tool.enabled && policy.allowed, denialCode: !authority.allowed ? MCP_DENIAL_CODES.AUTHORITY_DENIED : !policy.allowed ? MCP_DENIAL_CODES.TOOL_NOT_ALLOWLISTED : null, authority, policyAllowed: policy.allowed, liveReadAllowed: policy.live_read_allowed === true, tool: toToolResponse(tool), server: toServerResponse(server), approvalRequired: approval.required, approvalType: approval.profile, approvalReason: approval.reason, classification, sideEffectClass: tool.side_effect_class };
  }

  async simulateInvocation(actor: Actor, body: any) { requirePermission(actor, SHS_SECURITY_PERMISSIONS.AI_MCP_SIMULATE); const scope = actorScope(actor); const evaluation = await this.evaluateMcpAccess(actor, body); const approval = approvalForSideEffect(evaluation.sideEffectClass || "READ_ONLY"); const status = !evaluation.allowed ? "DENIED" : approval.required ? "APPROVAL_REQUIRED" : "SIMULATED"; const row = await this.repo.createInvocation({ invocation_id: `mcp_invocation_${randomUUID()}`, server_id: body.serverId || body.server_id, tool_id: body.toolId || body.tool_id, resource_id: body.resourceId || body.resource_id || null, simulation_id: body.simulationId || body.simulation_id || null, conductor_request_id: body.conductorRequestId || body.conductor_request_id || null, session_id: body.sessionId || body.session_id || null, delegation_id: body.delegationId || body.delegation_id || null, principal_user_id: scope.userId, organization_id: scope.organizationId, tenant_id: scope.tenantId, purpose: body.purpose || "mcp simulation", requested_action: body.action || body.requestedAction || "mcp.tool.simulate", side_effect_class: evaluation.sideEffectClass || "READ_ONLY", authority_allowed: evaluation.authority?.allowed === true, authority_code: evaluation.authority?.denialCode || null, policy_allowed: evaluation.policyAllowed === true, policy_code: evaluation.allowed ? null : evaluation.denialCode, classification: evaluation.classification || null, security_code: body.securityCode || null, approval_required: evaluation.approvalRequired === true, status, input_json: body.input || {}, provenance_json: { simulated: true, server_id: body.serverId || body.server_id, tool_id: body.toolId || body.tool_id } }); await this.emit(null, status === "DENIED" ? "mcp.access.denied" : status === "APPROVAL_REQUIRED" ? "mcp.approval_required" : "mcp.invocation.simulated", "mcp_invocation", row.mcp_invocation_id, scope, { server_id: row.mcp_server_id, tool_id: row.mcp_tool_id, side_effect_class: row.side_effect_class, status }); return toInvocationResponse(row); }

  async readResource(actor: Actor, body: any = {}) {
    requirePermission(actor, SHS_SECURITY_PERMISSIONS.AI_MCP_READ_RESOURCE);
    const scope = actorScope(actor);
    const server = await this.approvedServer(scope, String(body.serverId || body.server_id || ""));
    if (server.lifecycle_status !== "ACTIVE") throw new McpError(MCP_DENIAL_CODES.SERVER_NOT_APPROVED, "Live MCP reads require an active server.", 403);
    const tool = await this.repo.getTool(String(body.toolId || body.tool_id || ""), server.mcp_server_id);
    if (!tool) throw new McpError(MCP_DENIAL_CODES.TOOL_NOT_FOUND, "MCP tool was not found.", 404);
    if (tool.side_effect_class !== "READ_ONLY") throw new McpError(MCP_DENIAL_CODES.TOOL_NOT_READ_ONLY, "Only BOS-classified READ_ONLY tools may execute live.", 403);
    const evaluation = await this.evaluateMcpAccess(actor, { ...body, action: body.action || tool.tool_key });
    if (!evaluation.allowed) throw new McpError(evaluation.denialCode || MCP_DENIAL_CODES.LIVE_READ_NOT_ALLOWED, "MCP read authorization was denied.", 403);
    if (!evaluation.liveReadAllowed) throw new McpError(MCP_DENIAL_CODES.LIVE_READ_NOT_ALLOWED, "The MCP tool policy does not explicitly permit live reads.", 403);
    if (typeof this.transport.invokeReadOnly !== "function") throw new McpError(MCP_DENIAL_CODES.LIVE_INVOCATION_DISABLED, "No live read transport is configured.", 403);

    const startedAt = Date.now();
    const invocation = await this.repo.createInvocation({
      invocation_id: `mcp_invocation_${randomUUID()}`, server_id: server.mcp_server_id, tool_id: tool.mcp_tool_id,
      resource_id: body.resourceId || body.resource_id || null, simulation_id: body.simulationId || body.simulation_id || null, conductor_request_id: body.conductorRequestId || body.conductor_request_id || null, session_id: body.sessionId || body.session_id || null,
      delegation_id: body.delegationId || body.delegation_id || null, principal_user_id: scope.userId,
      organization_id: scope.organizationId, tenant_id: scope.tenantId, purpose: body.purpose,
      requested_action: body.action || tool.tool_key, side_effect_class: tool.side_effect_class,
      authority_allowed: evaluation.authority?.allowed === true, authority_code: evaluation.authority?.denialCode || null,
      policy_allowed: evaluation.policyAllowed === true, policy_code: null, classification: evaluation.classification,
      approval_required: false, status: "REAL_READ", execution_mode: "REAL_READ", input_json: body.input || {},
      provenance_json: { real_read: true, server_id: server.mcp_server_id, tool_id: tool.mcp_tool_id },
    });

    let response: any;
    let sourceIdentity = server.provider_identifier;
    let responseHash = "";
    let responseBytes = 0;
    let responseStatus: number | null = null;
    try {
      const credential = await this.credentials.resolve(server.credential_reference, { serverId: server.mcp_server_id, organizationId: scope.organizationId, tenantId: scope.tenantId });
      response = await this.transport.invokeReadOnly(server, tool, body.input || {}, credential);
      sourceIdentity = response.sourceIdentity;
      responseStatus = response.responseStatus;
      const serialized = typeof response.content === "string" ? response.content : JSON.stringify(response.content);
      responseHash = createHash("sha256").update(serialized).digest("hex");
      responseBytes = Buffer.byteLength(serialized);
      const scan = await this.inputSecurity.scanInput(actor, { content: serialized, contentType: response.contentType, sourceKind: "MCP_RESULT", sourceRef: invocation.mcp_invocation_id, resourceType: body.resource?.resourceType || body.resource?.resource_type || "mcp_tool", resourceId: body.resource?.resourceId || body.resource?.resource_id || tool.mcp_tool_id });
      const admission = await this.inputSecurity.evaluateContextAdmission(actor, { scanId: scan.scanId, intendedUse: body.intendedUse || body.purpose || "mcp read result", resourceType: body.resource?.resourceType || body.resource?.resource_type || "mcp_tool", resourceId: body.resource?.resourceId || body.resource?.resource_id || tool.mcp_tool_id, sessionId: body.sessionId || body.session_id, delegationId: body.delegationId || body.delegation_id, agentIdentifier: body.agentIdentifier || body.agent_identifier, purpose: body.purpose, model: body.model || {} });
      const admissionStatus = admission.admitted ? "ADMITTED" : admission.decision === "QUARANTINE" ? "QUARANTINED" : admission.decision === "REQUIRE_REVIEW" ? "REVIEW_REQUIRED" : "BLOCKED";
      const result = await this.repo.createReadResult({ read_result_id: `mcp_read_result_${randomUUID()}`, invocation_id: invocation.mcp_invocation_id, server_id: server.mcp_server_id, tool_id: tool.mcp_tool_id, resource_id: body.resourceId || body.resource_id || null, principal_user_id: scope.userId, agent_identifier: body.agentIdentifier || body.agent_identifier || null, session_id: body.sessionId || body.session_id || null, delegation_id: body.delegationId || body.delegation_id || null, organization_id: scope.organizationId, tenant_id: scope.tenantId, source_identity: sourceIdentity, content_type: response.contentType, response_sha256: responseHash, response_bytes: responseBytes, response_status: responseStatus, security_scan_id: scan.scanId, context_admission_id: admission.admissionId, admission_status: admissionStatus, duration_ms: Date.now() - startedAt, provenance_json: { server_id: server.mcp_server_id, tool_id: tool.mcp_tool_id, resource_id: body.resourceId || body.resource_id || null, received_at: new Date().toISOString(), untrusted: true } });
      await this.repo.updateInvocationRead({ invocation_id: invocation.mcp_invocation_id, result_admission_status: admissionStatus, duration_ms: Date.now() - startedAt, response_status: responseStatus, provenance_reference: result.mcp_read_result_id, security_code: admission.admitted ? null : admission.decisionCode, provenance_json: { real_read: true, read_result_id: result.mcp_read_result_id } });
      await this.emit(null, "mcp.result.received", "mcp_read_result", result.mcp_read_result_id, scope, { activity_kind: "REAL_READ", admission_status: admissionStatus, response_sha256: responseHash });
      await this.emit(null, admission.admitted ? "mcp.result.admitted" : admissionStatus === "QUARANTINED" ? "mcp.result.quarantined" : "mcp.result.security_blocked", "mcp_read_result", result.mcp_read_result_id, scope, { activity_kind: "REAL_READ", admission_status: admissionStatus, decision_code: admission.decisionCode });
      if (!admission.admitted) throw new McpError(MCP_DENIAL_CODES.RESPONSE_NOT_ADMITTED, "External MCP content was not admitted to AI context.", 403);
      return toReadResultResponse(result, response.content);
    } catch (error: any) {
      if (error instanceof McpError && error.code === MCP_DENIAL_CODES.RESPONSE_NOT_ADMITTED) throw error;
      const code = error?.code || MCP_DENIAL_CODES.CREDENTIAL_UNAVAILABLE;
      const result = await this.repo.createReadResult({ read_result_id: `mcp_read_result_${randomUUID()}`, invocation_id: invocation.mcp_invocation_id, server_id: server.mcp_server_id, tool_id: tool.mcp_tool_id, resource_id: body.resourceId || body.resource_id || null, principal_user_id: scope.userId, agent_identifier: body.agentIdentifier || body.agent_identifier || null, session_id: body.sessionId || body.session_id || null, delegation_id: body.delegationId || body.delegation_id || null, organization_id: scope.organizationId, tenant_id: scope.tenantId, source_identity: sourceIdentity, content_type: null, response_sha256: responseHash || createHash("sha256").update("").digest("hex"), response_bytes: responseBytes, response_status: responseStatus, admission_status: "FAILED", failure_code: code, duration_ms: Date.now() - startedAt, provenance_json: { real_read: true, failed: true } });
      await this.repo.updateInvocationRead({ invocation_id: invocation.mcp_invocation_id, result_admission_status: "FAILED", duration_ms: Date.now() - startedAt, response_status: responseStatus, provenance_reference: result.mcp_read_result_id, security_code: code, provenance_json: { real_read: true, read_result_id: result.mcp_read_result_id } });
      await this.emit(null, "mcp.read.failed", "mcp_read_result", result.mcp_read_result_id, scope, { activity_kind: "REAL_READ", failure_code: code });
      if (error instanceof McpError) throw error;
      throw new McpError(code, "MCP read failed safely.", 502);
    }
  }
}
