import { fail, ok } from "../../../api/response-envelope.js";
import { requirePermission } from "../../../auth/permission-guard.js";
import { SHS_SECURITY_PERMISSIONS as P } from "../../../auth/security-permissions.js";
import * as service from "../service/accommodation-service.js";
function handle(res: any, error: any) { return res.status(error?.statusCode || 400).json(fail(error?.code || "ACCESSIBILITY_ACCOMMODATION_FAILED", error?.message || "Accommodation operation failed.")); }
export function registerAccessibilityAccommodationRoutes(app: any) {
  app.post("/accessibility/accommodations/drafts", requirePermission(P.ACCESSIBILITY_ACCOMMODATION_REQUEST), async (req: any, res: any) => { try { return res.status(201).json(ok(await service.createDraft(req.body || {}, req.user))); } catch (e) { return handle(res, e); } });
  app.post("/accessibility/accommodations/:id/submit", requirePermission(P.ACCESSIBILITY_ACCOMMODATION_REQUEST), async (req: any, res: any) => { try { return res.json(ok(await service.submitRequest(req.params.id, req.user))); } catch (e) { return handle(res, e); } });
  app.get("/accessibility/accommodations/me/:id", requirePermission(P.ACCESSIBILITY_ACCOMMODATION_REQUEST), async (req: any, res: any) => { try { const item = await service.getOwnCase(req.params.id, req.user); return item ? res.json(ok(item)) : res.status(404).json(fail("NOT_FOUND", "Accommodation request not found.")); } catch (e) { return handle(res, e); } });
  app.get("/accessibility/accommodations", requirePermission(P.ACCESSIBILITY_ACCOMMODATION_REVIEW), async (req: any, res: any) => { try { return res.json(ok({ items: await service.listAuthorizedCases(req.user) })); } catch (e) { return handle(res, e); } });
  app.post("/accessibility/accommodations/:id/review", requirePermission(P.ACCESSIBILITY_ACCOMMODATION_REVIEW), async (req: any, res: any) => { try { return res.json(ok(await service.startReview(req.params.id, req.user))); } catch (e) { return handle(res, e); } });
  app.post("/accessibility/accommodations/:id/information-requested", requirePermission(P.ACCESSIBILITY_ACCOMMODATION_REVIEW), async (req: any, res: any) => { try { return res.json(ok(await service.requestInformation(req.params.id, req.user))); } catch (e) { return handle(res, e); } });
  app.post("/accessibility/accommodations/:id/approve", requirePermission(P.ACCESSIBILITY_ACCOMMODATION_APPROVE), async (req: any, res: any) => { try { return res.json(ok(await service.approve(req.params.id, req.body || {}, req.user))); } catch (e) { return handle(res, e); } });
  app.post("/accessibility/accommodations/:id/decline", requirePermission(P.ACCESSIBILITY_ACCOMMODATION_APPROVE), async (req: any, res: any) => { try { return res.json(ok(await service.decline(req.params.id, req.body || {}, req.user))); } catch (e) { return handle(res, e); } });
  app.post("/accessibility/accommodations/:id/activate", requirePermission(P.ACCESSIBILITY_ACCOMMODATION_APPROVE), async (req: any, res: any) => { try { return res.json(ok(await service.activate(req.params.id, req.user))); } catch (e) { return handle(res, e); } });
  app.post("/accessibility/accommodations/:id/withdraw", requirePermission(P.ACCESSIBILITY_ACCOMMODATION_REQUEST), async (req: any, res: any) => { try { return res.json(ok(await service.withdraw(req.params.id, req.user))); } catch (e) { return handle(res, e); } });
  app.post("/accessibility/accommodations/:id/expire", requirePermission(P.ACCESSIBILITY_ACCOMMODATION_APPROVE), async (req: any, res: any) => { try { return res.json(ok(await service.expire(req.params.id, req.user))); } catch (e) { return handle(res, e); } });
  app.post("/accessibility/accommodations/:id/supersede", requirePermission(P.ACCESSIBILITY_ACCOMMODATION_APPROVE), async (req: any, res: any) => { try { return res.json(ok(await service.supersede(req.params.id, req.user))); } catch (e) { return handle(res, e); } });
  app.patch("/accessibility/accommodations/:id/requirements/:requirementId/fulfillment", requirePermission(P.ACCESSIBILITY_ACCOMMODATION_FULFILL), async (req: any, res: any) => { try { return res.json(ok(await service.updateRequirementFulfillment(req.params.id, req.params.requirementId, String(req.body?.fulfillmentStatus || ""), req.user))); } catch (e) { return handle(res, e); } });
  app.get("/accessibility/accommodations/:id/projection", requirePermission(P.ACCESSIBILITY_ACCOMMODATION_REVIEW), async (req: any, res: any) => { try { const item = await service.getMinimumNecessaryProjection(req.params.id, req.user); return item ? res.json(ok(item)) : res.status(404).json(fail("NOT_FOUND", "Accommodation not found.")); } catch (e) { return handle(res, e); } });
}
