import React, { useEffect, useState } from "react";
import PageHeader from "../../components/PageHeader";
import StatusChip from "../../components/StatusChip";
import { API_BASE as SHS_API_BASE } from "@/lib/apiClient.js";

const API = SHS_API_BASE;
const token = () => window.localStorage.getItem("shfOperatorToken") || "";
async function request(path, options = {}) {
  const response = await fetch(`${API}${path}`, { ...options, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token()}`, ...(options.headers || {}) }, body: options.body === undefined ? undefined : JSON.stringify(options.body) });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body?.error?.message || "Accessibility operations request failed.");
  return body.data;
}

export default function AccessibilityOperations() {
  const [health, setHealth] = useState(null); const [issues, setIssues] = useState([]); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function refresh() { try { setError(""); const [nextHealth, nextIssues] = await Promise.all([request("/accessibility/operations/health"), request("/accessibility/operations/issues")]); setHealth(nextHealth); setIssues(nextIssues.items || []); } catch (e) { setError(e.message); } }
  useEffect(() => { refresh(); }, []);
  async function update(issueId, body, message) { try { await request(`/accessibility/operations/issues/${encodeURIComponent(issueId)}`, { method: "PATCH", body }); setNotice(message); await refresh(); } catch (e) { setError(e.message); } }
  return <div><PageHeader title="Accessibility Operations" subtitle="Governed accessibility findings, remediation, retest, and human support escalation." />{error ? <p role="alert">{error}</p> : null}{notice ? <p role="status" aria-live="polite">{notice}</p> : null}<section aria-labelledby="health-heading"><h2 id="health-heading">Accessibility health</h2><p role="status">{health?.health || "Loading"}</p>{health ? <dl><dt>Open issues</dt><dd>{health.metrics.openIssues}</dd><dt>Blocking issues</dt><dd>{health.metrics.blockingIssues}</dd><dt>Regressions</dt><dd>{health.metrics.regressions}</dd><dt>Human review pending</dt><dd>{health.metrics.humanReviewPending}</dd></dl> : null}</section><section aria-labelledby="queue-heading"><h2 id="queue-heading">Issue queue</h2>{issues.length ? <div>{issues.map((item) => <article key={item.issueId} style={{ border: "1px solid #ddd", padding: 16, marginBottom: 12 }}><h3>{item.category} <StatusChip value={item.status} /></h3><p>{item.description}</p><dl><dt>Severity</dt><dd>{item.severity}</dd><dt>Origin</dt><dd>{item.origin}</dd><dt>Source</dt><dd>{item.sourceType}{item.sourceId ? `: ${item.sourceId}` : ""}</dd><dt>Owner</dt><dd>{item.ownerUserId || "Unassigned"}</dd></dl><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>{!item.ownerUserId ? <button type="button" onClick={() => update(item.issueId, { ownerUserId: "current-operator" }, "Issue assigned.")}>Assign to me</button> : null}{["NEW", "TRIAGED", "ASSIGNED"].includes(item.status) ? <button type="button" onClick={() => update(item.issueId, { status: "IN_REMEDIATION" }, "Issue moved to remediation.")}>Start remediation</button> : null}{item.status === "IN_REMEDIATION" ? <button type="button" onClick={() => update(item.issueId, { status: "READY_FOR_RETEST", retestStatus: "READY" }, "Issue queued for retest.")}>Request retest</button> : null}{item.humanReviewRequired ? <span role="status">Human review required</span> : null}</div></article>)}</div> : <p role="status">No accessibility issues are currently available.</p>}</section><section aria-labelledby="support-heading"><h2 id="support-heading">Request human accessibility help</h2><p>Support requests are private, consent-bound, and separate from accommodation decisions.</p><SupportForm onCreated={(item) => setNotice(`Support request ${item.supportRequestId} opened.`)} /></section></div>;
}

function SupportForm({ onCreated }) { const [summary, setSummary] = useState(""); const [consent, setConsent] = useState(false); const [busy, setBusy] = useState(false); async function submit(event) { event.preventDefault(); setBusy(true); try { const body = await request("/accessibility/support/requests", { method: "POST", body: { requestType: "ACCESS_BARRIER", summary, routeContext: window.location.hash, consentToShareContext: consent, sharedContext: consent ? { route: window.location.hash } : {} } }); setSummary(""); onCreated(body); } finally { setBusy(false); } } return <form onSubmit={submit} style={{ display: "grid", gap: 8, maxWidth: 560 }}><label htmlFor="support-summary">What access help is needed?</label><textarea id="support-summary" required value={summary} onChange={(e) => setSummary(e.target.value)} /><label><input type="checkbox" checked={consent} onChange={(e) => setConsent(e.target.checked)} /> Share this page context with accessibility support</label><button type="submit" disabled={busy}>{busy ? "Opening request..." : "Request human help"}</button></form>; }
