import React, { useEffect, useMemo, useState } from "react";
import LifecycleHistory from "./components/LifecycleHistory.jsx";
import { getProgramAssurance, getProgramOversight, getProviderIntegrity, getProviderAssurance, getFundingLineage, getFundingReadiness, getFundingReferences, getClaims, getMetricResults, getTruthFacts, getProviderResponse, getAudit, getAuditHistory, getAuditPacket } from "../../services/government-assurance-client";

const value = (input) => input == null || input === "" ? "—" : typeof input === "object" ? JSON.stringify(input) : String(input);
const ref = (row, ...keys) => keys.map((key) => row?.[key]).find((item) => item != null && item !== "") || "—";
function Panel({ title, children }) { return <section className="gpa-portfolio-panel"><h2>{title}</h2>{children}</section>; }
function Table({ caption, headers, rows }) { return <div className="gpa-table-wrap"><table><caption className="sr-only">{caption}</caption><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.length ? rows : <tr><td colSpan={headers.length}>No canonical records are available.</td></tr>}</tbody></table></div>; }
function Detail({ record }) { return <dl>{Object.entries(record || {}).filter(([key]) => !["provenance", "metadata"].includes(key)).slice(0, 30).map(([key, item]) => <div key={key}><dt>{key.replaceAll("_", " ")}</dt><dd>{value(item)}</dd></div>)}</dl>; }

export default function GovernmentAssurancePortfolioDetail({ kind, id }) {
  const [state, setState] = useState({ loading: true, error: "", primary: null, related: [], oversight: null, packet: null, history: [], readiness: null });
  async function load() {
    setState((current) => ({ ...current, loading: true, error: "" }));
    try {
      if (kind === "program") {
        const [primary, oversight, refs, claims, metrics, truths] = await Promise.all([getProgramAssurance(id), getProgramOversight(id), getFundingReferences(), getClaims(), getMetricResults(), getTruthFacts()]);
        setState({ loading: false, error: "", primary, related: (refs.items || refs || []).filter((row) => row.programReference === id || row.program_reference === id), oversight, packet: { claims: claims.items || claims || [], metrics: metrics.items || metrics || [], truths: truths.items || truths || [] }, history: [], readiness: null });
      } else if (kind === "provider") {
        const [primary, refs, claims, metrics, truths] = await Promise.all([getProviderIntegrity(id), getFundingReferences(), getClaims(), getMetricResults(), getTruthFacts()]);
        setState({ loading: false, error: "", primary, related: (refs.items || refs || []).filter((row) => row.providerOrganizationReference === id || row.provider_organization_reference === id), oversight: null, packet: { claims: claims.items || claims || [], metrics: metrics.items || metrics || [], truths: truths.items || truths || [] }, history: [], readiness: null });
      } else if (kind === "funding") {
        const [primary, readiness, funding] = await Promise.all([getFundingLineage(id), getFundingReadiness({ reference: id, requiresOutcome: true }), getFundingReferences()]);
        setState({ loading: false, error: "", primary, related: (funding.items || funding || []).filter((row) => row.funding_reference_id === id || row.canonical_record_id === id), oversight: null, packet: null, history: [], readiness });
      } else {
        const [primary, packet, history] = await Promise.all([getAudit(id), getAuditPacket(id), getAuditHistory(id)]);
        setState({ loading: false, error: "", primary, related: [], oversight: null, packet, history: history?.items || history || [], readiness: null });
      }
    } catch (error) { setState((current) => ({ ...current, loading: false, error: error.message })); }
  }
  useEffect(() => { load(); }, [kind, id]);
  const title = kind === "program" ? "Program Assurance" : kind === "provider" ? "Provider Assurance" : kind === "funding" ? "Funding Assurance" : "Audit Engagement";
  const filtered = useMemo(() => { const rows = state.packet?.claims || []; return kind === "program" ? rows.filter((row) => row.programReference === id || row.program_reference === id) : kind === "provider" ? rows.filter((row) => row.claimantReference === id || row.claimant_reference === id) : rows; }, [state.packet, kind, id]);
  if (state.loading) return <section><h1>{title}</h1><p role="status">Loading canonical {title.toLowerCase()}…</p></section>;
  if (state.error) return <section><h1>{title}</h1><div role="alert">{state.error}</div><button type="button" onClick={load}>Retry</button></section>;
  if (!state.primary) return <section><h1>{title}</h1><p>Not found in the current organization and tenant scope.</p></section>;
  if (kind === "audit") return <div className="gpa-portfolio-detail"><h1>Audit Engagement {id}</h1><Panel title="Engagement"><Detail record={state.primary} /></Panel><Panel title="Workpapers"><Table caption="Audit workpapers" headers={["Workpaper", "Procedure", "Preparer", "Reviewer", "Status"]} rows={(state.packet?.workpapers || []).filter((row) => row.audit_engagement_id === id).map((row) => <tr key={row.workpaper_id}><td>{value(row.workpaper_id)}</td><td>{value(row.procedures || row.audit_step)}</td><td>{value(row.preparer_reference)}</td><td>{value(row.reviewer_reference)}</td><td>{value(row.status)}</td></tr>)}/></Panel><Panel title="Samples and results"><Table caption="Audit samples" headers={["Sample", "Method", "Population", "Size", "Seed"]} rows={(state.packet?.samples || []).filter((row) => row.audit_engagement_id === id).map((row) => <tr key={row.sample_id}><td>{value(row.sample_id)}</td><td>{value(row.method)}</td><td>{value(row.population_size)}</td><td>{value(row.sample_size)}</td><td>{value(row.random_seed)}</td></tr>)}/></Panel><Panel title="Audit packet"><Detail record={state.packet?.provenance} /><p>Canonical packet references: {value(state.packet?.findings?.length)} findings, {value(state.packet?.sampleResults?.length)} sample results.</p></Panel><Panel title="Lifecycle history"><LifecycleHistory items={state.history} /></Panel></div>;
  if (kind === "funding") return <div className="gpa-portfolio-detail"><h1>Funding Assurance {id}</h1><Panel title="Funding lineage"><Table caption="Funding lineage" headers={["From", "Relationship", "To", "Amount", "Period", "Provenance"]} rows={(state.primary.edges || []).map((row) => <tr key={row.lineage_edge_id}><td>{value(row.from_reference)}</td><td>{value(row.relationship_type)}</td><td>{value(row.to_reference)}</td><td>{value(row.amount)} {value(row.currency)}</td><td>{value(row.period_start)} → {value(row.period_end)}</td><td>{value(row.provenance_reference)}</td></tr>)}/></Panel><Panel title="Funding references"><Table caption="Canonical funding references" headers={["Reference", "Type", "Amount", "Provider", "Program", "Status"]} rows={state.related.map((row) => <tr key={row.funding_reference_id}><td>{value(row.funding_reference_id)}</td><td>{value(row.canonical_record_type)}</td><td>{value(row.amount)} {value(row.currency)}</td><td>{value(row.provider_organization_reference)}</td><td>{value(row.program_reference)}</td><td>{value(row.status)}</td></tr>)}/></Panel><Panel title="Readiness"><p role="status">{state.readiness?.ready ? "Funding lineage is ready." : "Funding lineage has canonical blockers."}</p><ul>{(state.readiness?.blockers || []).map((item) => <li key={item}>{item}</li>)}</ul></Panel></div>;
  const assurance = state.primary.summary || state.primary;
  return <div className="gpa-portfolio-detail"><h1>{title} {id}</h1><Panel title="Canonical identity"><dl><div><dt>Reference</dt><dd>{id}</dd></div><div><dt>Freshness</dt><dd>{value(state.primary.freshnessTimestamp)}</dd></div></dl></Panel><Panel title="Assurance summary"><Detail record={assurance} /></Panel><Panel title="Funding references"><Table caption="Related funding" headers={["Reference", "Type", "Amount", "Program", "Provider", "Status"]} rows={state.related.map((row) => <tr key={row.funding_reference_id}><td>{value(row.funding_reference_id)}</td><td>{value(row.canonical_record_type)}</td><td>{value(row.amount)} {value(row.currency)}</td><td>{value(row.program_reference)}</td><td>{value(row.provider_organization_reference)}</td><td>{value(row.status)}</td></tr>)}/></Panel><Panel title="Claims / Metrics / Truth"><Table caption="Related assurance references" headers={["Type", "Reference", "Status", "Value"]} rows={[...filtered.map((row) => <tr key={`claim-${row.claimId || row.claim_id}`}><td>Claim</td><td><a href={`#/operator/government-assurance/claims/${encodeURIComponent(row.claimId || row.claim_id)}`}>{value(row.claimId || row.claim_id)}</a></td><td>{value(row.status)}</td><td>{value(row.assertedValue || row.asserted_value)}</td></tr>), ...(state.packet?.metrics || []).filter((row) => row.programReference === id || row.program_reference === id || row.providerReference === id || row.provider_reference === id).map((row) => <tr key={`metric-${row.metric_result_id}`}><td>Metric Result</td><td><a href={`#/operator/government-assurance/lineage/metric/${encodeURIComponent(row.metric_result_id)}`}>{value(row.metric_result_id)}</a></td><td>{value(row.status)}</td><td>{value(row.calculated_value)}</td></tr>), ...(state.packet?.truths || []).filter((row) => row.subjectReference === id || row.subject_reference === id || row.metricResultId || row.metric_result_id).map((row) => <tr key={`truth-${row.truth_fact_id}`}><td>Truth Fact</td><td><a href={`#/operator/government-assurance/lineage/truth/${encodeURIComponent(row.truth_fact_id)}`}>{value(row.truth_fact_id)}</a></td><td>{value(row.status)}</td><td>{value(row.fact_value)}</td></tr>)]}/></Panel><Panel title="Oversight"><Detail record={state.oversight || {}} /></Panel></div>;
}
