import React, { useEffect, useState } from "react";
import LifecycleHistory from "./components/LifecycleHistory.jsx";
import { getSource, getSourceAuthorities, getDataUsePolicies, getSourceHealth, getSemanticMappings, getSchemaObservations, getRejectedRecords, getQualityEvaluations, getReconciliationCases } from "../../services/government-assurance-client";

const text = (value) => value == null || value === "" ? "—" : typeof value === "object" ? JSON.stringify(value) : String(value);
const belongs = (row, id) => !row || !id || row.sourceSystemId === id || row.source_system_id === id;
function Panel({ title, children }) { return <section className="gpa-source-panel"><h2>{title}</h2>{children}</section>; }
function List({ caption, headers, rows }) { return <div className="gpa-table-wrap"><table><caption className="sr-only">{caption}</caption><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.length ? rows : <tr><td colSpan={headers.length}>No canonical records are available.</td></tr>}</tbody></table></div>; }

export default function GovernmentAssuranceSourceDetail({ id }) {
  const [state, setState] = useState({ loading: true, error: "", source: null, authorities: [], policies: [], health: [], mappings: [], schema: [], rejected: [], quality: [], cases: [] });
  async function load() {
    setState((current) => ({ ...current, loading: true, error: "" }));
    try {
      const [source, authorities, policies, health, mappings, schema, rejected, quality, cases] = await Promise.all([getSource(id), getSourceAuthorities(), getDataUsePolicies(), getSourceHealth(), getSemanticMappings(), getSchemaObservations(), getRejectedRecords(), getQualityEvaluations(), getReconciliationCases()]);
      if (!source) throw new Error("Source system was not found in the current organization and tenant scope.");
      setState({ loading: false, error: "", source, authorities: (authorities.items || authorities || []).filter((row) => belongs(row, id)), policies: (policies.items || policies || []).filter((row) => belongs(row, id)), health: (health.items || health || []).filter((row) => belongs(row, id)), mappings: (mappings.items || mappings || []).filter((row) => belongs(row, id)), schema: (schema.items || schema || []).filter((row) => belongs(row, id)), rejected: (rejected.items || rejected || []).filter((row) => belongs(row, id)), quality: (quality.items || quality || []).filter((row) => belongs(row, id)), cases: (cases.items || cases || []).filter((row) => (row.competingSourceReferences || row.competing_source_references || []).includes(id)) });
    } catch (error) { setState((current) => ({ ...current, loading: false, error: error.message })); }
  }
  useEffect(() => { load(); }, [id]);
  if (state.loading) return <section><h1>Source system</h1><p role="status">Loading canonical source data…</p></section>;
  if (state.error) return <section><h1>Source system</h1><div role="alert">{state.error}</div><button type="button" onClick={load}>Retry</button></section>;
  const source = state.source;
  return <div className="gpa-source-detail">
    <h1>Source System {text(source.sourceSystemId || source.source_system_id)}</h1><p className="gpa-note">Credentials are never displayed. Only canonical references and scoped operational metadata are shown.</p>
    <Panel title="Source identity"><dl>{[["Name", source.canonicalName || source.canonical_name],["Owner", source.sourceOwnerReference || source.source_owner_reference],["Vendor", source.providerVendor || source.provider_vendor],["Jurisdiction", source.jurisdictionId || source.jurisdiction_id],["Environment", source.environment],["Type", source.systemType || source.system_type],["Domains", source.dataDomains || source.data_domains],["Record types", source.recordTypes || source.record_types],["Authority role", source.authorityRole || source.authority_role],["Precedence", source.authorityPrecedence || source.authority_precedence],["Classification", source.dataClassification || source.data_classification],["Integration", source.integrationMode || source.integration_mode],["Credential", source.credentialReference ? "REFERENCE PRESENT" : "Not provided"],["Lifecycle", source.status],["Metadata verified", source.lastVerifiedMetadataAt || source.last_verified_metadata_at]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{text(value)}</dd></div>)}</dl></Panel>
    <Panel title="Source Authority"><List caption="Source authorities" headers={["Authority", "Role", "Domain", "Record type", "Precedence", "Effective"]} rows={state.authorities.map((row) => <tr key={row.sourceAuthorityId || row.source_authority_id}><td>{text(row.sourceAuthorityId || row.source_authority_id)}</td><td>{text(row.authorityRole || row.authority_role)}</td><td>{text(row.dataDomain || row.data_domain)}</td><td>{text(row.recordType || row.record_type)}</td><td>{text(row.precedence)}</td><td>{text(row.effectiveFrom || row.effective_from)}</td></tr>)}/></Panel>
    <Panel title="Data Use Policy"><List caption="Data use policies" headers={["Policy", "Version", "Purposes", "Actions", "Classification ceiling", "Status"]} rows={state.policies.map((row) => <tr key={(row.policyId || row.policy_id) + row.version}><td>{text(row.policyId || row.policy_id)}</td><td>{text(row.version)}</td><td>{text(row.allowedPurposes || row.allowed_purposes)}</td><td>{text(row.allowedActions || row.allowed_actions)}</td><td>{text(row.classificationCeiling || row.classification_ceiling)}</td><td>{text(row.status)}</td></tr>)}/></Panel>
    <Panel title="Source Health"><List caption="Source health" headers={["Freshness", "Threshold", "Stale after", "Last success", "Last attempt", "Schema", "Authentication", "Degraded"]} rows={state.health.map((row) => <tr key={row.sourceSystemId || row.source_system_id}><td>{text(row.currentFreshnessState || row.current_freshness_state)}</td><td>{text(row.freshnessThresholdSeconds || row.freshness_threshold_seconds)}</td><td>{text(row.staleAfter || row.stale_after)}</td><td>{text(row.lastSuccessfulSync || row.last_successful_sync)}</td><td>{text(row.lastAttemptedSync || row.last_attempted_sync)}</td><td>{text(row.lastSchemaVerification || row.last_schema_verification)}</td><td>{text(row.authenticationState || row.authentication_state)}</td><td>{text(row.degradedState || row.degraded_state)}</td></tr>)}/></Panel>
    <Panel title="Data Quality"><List caption="Source quality evaluations" headers={["Subject", "Dimension", "State", "Rule", "Reason"]} rows={state.quality.map((row) => <tr key={row.qualityEvaluationId || row.quality_evaluation_id}><td>{text(row.subjectReference || row.subject_reference)}</td><td>{text(row.dimension)}</td><td>{text(row.state)}</td><td>{text(row.ruleId || row.rule_id)}</td><td>{text(row.reasonCodes || row.reason_codes)}</td></tr>)}/></Panel>
    <Panel title="Semantic Mappings"><List caption="Semantic mappings" headers={["Mapping", "Source record type", "Canonical type", "Version", "Status"]} rows={state.mappings.map((row) => <tr key={row.mappingId || row.mapping_id}><td>{text(row.mappingId || row.mapping_id)}</td><td>{text(row.sourceRecordType || row.source_record_type)}</td><td>{text(row.canonicalType || row.canonical_type)}</td><td>{text(row.version)}</td><td>{text(row.status)}</td></tr>)}/></Panel>
    <Panel title="Schema Drift"><List caption="Schema observations" headers={["Observation", "Observed", "Expected mapping", "Classification", "Status", "Detected"]} rows={state.schema.map((row) => <tr key={row.observationId || row.observation_id}><td>{text(row.observationId || row.observation_id)}</td><td>{text(row.observedSchemaVersion || row.observed_schema_version)} / {text(row.observedSignature || row.observed_signature)}</td><td>{text(row.expectedMappingVersion || row.expected_mapping_version)}</td><td>{text(row.driftClassification || row.drift_classification)}</td><td>{text(row.status)}</td><td>{text(row.detectedAt || row.detected_at)}</td></tr>)}/></Panel>
    <Panel title="Rejected Records"><List caption="Rejected source records" headers={["Rejected record", "Source record", "Batch", "Rule", "Failure", "Remediation", "Rejected"]} rows={state.rejected.map((row) => <tr key={row.rejectedRecordId || row.rejected_record_id}><td>{text(row.rejectedRecordId || row.rejected_record_id)}</td><td>{text(row.sourceRecordId || row.source_record_id)}</td><td>{text(row.batchReference || row.batch_reference)}</td><td>{text(row.ruleId || row.rule_id)}</td><td>{text(row.failureReason || row.failure_reason)}</td><td>{text(row.remediationStatus || row.remediation_status)}</td><td>{text(row.rejectedAt || row.rejected_at)}</td></tr>)}/></Panel>
    <Panel title="Linked Reconciliation"><List caption="Linked reconciliation cases" headers={["Case", "Conflict", "Status", "Severity"]} rows={state.cases.map((row) => <tr key={row.reconciliationCaseId || row.reconciliation_case_id}><td>{text(row.reconciliationCaseId || row.reconciliation_case_id)}</td><td>{text(row.conflictType || row.conflict_type)}</td><td>{text(row.status)}</td><td>{text(row.severity)}</td></tr>)}/></Panel>
    <Panel title="Lifecycle history"><LifecycleHistory items={[]} /></Panel>
  </div>;
}
