export const GPA_FUNDING_RECORD_TYPES = ["FUNDING_SOURCE", "GRANT", "AWARD", "AGREEMENT", "CONTRACT", "OBLIGATION", "PAYMENT", "EXPENDITURE", "INVOICE"] as const;
export const GPA_FUNDING_RELATIONSHIPS = ["FUNDS", "AWARDS", "AGREES", "OBLIGATES", "PAYS", "EXPENDS", "DELIVERS", "SERVES", "PRODUCES", "CLAIMS", "VERIFIES", "CALCULATES", "PROMOTES", "DIRECT", "ALLOCATED", "AGGREGATED", "SHARED_COST", "ASSOCIATED", "ATTRIBUTED", "VERIFIED"] as const;
export const GPA_FUNDING_CODES = {
  FUNDING_REFERENCE_MISSING: "GPA_FUNDING_REFERENCE_MISSING",
  AGREEMENT_MISSING: "GPA_AGREEMENT_MISSING",
  PROVIDER_SCOPE_MISMATCH: "GPA_PROVIDER_SCOPE_MISMATCH",
  PROGRAM_SCOPE_MISMATCH: "GPA_PROGRAM_SCOPE_MISMATCH",
  OBLIGATION_MISSING: "GPA_OBLIGATION_MISSING",
  PAYMENT_PROVENANCE_MISSING: "GPA_PAYMENT_PROVENANCE_MISSING",
  EXPENDITURE_UNVERIFIED: "GPA_EXPENDITURE_UNVERIFIED",
  SERVICE_LINK_MISSING: "GPA_SERVICE_LINK_MISSING",
  OUTCOME_LINK_MISSING: "GPA_OUTCOME_LINK_MISSING",
  PERIOD_MISMATCH: "GPA_FUNDING_PERIOD_MISMATCH",
  CURRENCY_MISMATCH: "GPA_CURRENCY_MISMATCH",
  ALLOCATION_METHOD_MISSING: "GPA_ALLOCATION_METHOD_MISSING",
  DUPLICATE_SOURCE_RECORD: "GPA_DUPLICATE_FUNDING_SOURCE_RECORD",
  OVER_ALLOCATED: "GPA_FUNDING_OVER_ALLOCATED",
} as const;
