export const GPA_METRIC_TYPES = ["COUNT", "RATE", "PERCENTAGE", "CURRENCY", "DURATION", "AVERAGE", "MEDIAN", "RATIO", "BOOLEAN", "INDEX", "CUSTOM"] as const;
export const GPA_METRIC_RESULT_STATUSES = ["PREVIEW", "CALCULATED", "ACCEPTED", "STALE", "REVIEW_REQUIRED", "SUPERSEDED", "REJECTED"] as const;
export const GPA_TRUTH_PUBLIC_STATES = ["NOT_REVIEWED", "RESTRICTED", "PUBLIC_ELIGIBLE", "PUBLIC_APPROVED", "PUBLIC_DENIED"] as const;

export const GPA_LINEAGE_CODES = {
  METRIC_NOT_FOUND: "GPA_METRIC_NOT_FOUND",
  METRIC_NOT_ACTIVE: "GPA_METRIC_NOT_ACTIVE",
  METRIC_VERSION_NOT_EFFECTIVE: "GPA_METRIC_VERSION_NOT_EFFECTIVE",
  INPUT_MISSING: "GPA_METRIC_INPUT_MISSING",
  INPUT_UNVERIFIED: "GPA_METRIC_INPUT_UNVERIFIED",
  VERIFICATION_LEVEL_TOO_LOW: "GPA_VERIFICATION_LEVEL_TOO_LOW",
  SOURCE_AUTHORITY_INSUFFICIENT: "GPA_SOURCE_AUTHORITY_INSUFFICIENT",
  PERIOD_MISMATCH: "GPA_METRIC_PERIOD_MISMATCH",
  PROGRAM_MISMATCH: "GPA_METRIC_PROGRAM_MISMATCH",
  JURISDICTION_MISMATCH: "GPA_METRIC_JURISDICTION_MISMATCH",
  PROVENANCE_INCOMPLETE: "GPA_LINEAGE_PROVENANCE_INCOMPLETE",
  CONTRADICTION_UNRESOLVED: "GPA_CONTRADICTION_UNRESOLVED",
  TRUTH_VERIFICATION_REQUIRED: "GPA_TRUTH_VERIFICATION_REQUIRED",
  TRUTH_LINEAGE_REQUIRED: "GPA_TRUTH_LINEAGE_REQUIRED",
  TRUTH_ACTOR_DENIED: "GPA_TRUTH_ACTOR_DENIED",
  TRUTH_NOT_FOUND: "GPA_TRUTH_NOT_FOUND",
  METRIC_RESULT_NOT_FOUND: "GPA_METRIC_RESULT_NOT_FOUND",
} as const;

export const VERIFICATION_LEVEL_RANK: Record<string, number> = { V0: 0, V1: 1, V2: 2, V3: 3, V4: 4, V5: 5 };
export function verificationLevelAtLeast(actual: string | null | undefined, required: string | null | undefined) {
  return (VERIFICATION_LEVEL_RANK[String(actual || "V0")] ?? -1) >= (VERIFICATION_LEVEL_RANK[String(required || "V0")] ?? 99);
}
