export const GPA_CONFLICT_TYPES = ["VALUE_MISMATCH", "DATE_MISMATCH", "DUPLICATE_RECORD", "SOURCE_AUTHORITY_CONFLICT", "ENTITY_IDENTITY_CONFLICT", "ELIGIBILITY_CONFLICT", "FUNDING_CONFLICT", "PAYMENT_CONFLICT", "SERVICE_CONFLICT", "OUTCOME_CONFLICT", "CLASSIFICATION_CONFLICT", "VERSION_CONFLICT"] as const;
export const GPA_RECONCILIATION_STATUSES = ["OPEN", "TRIAGE", "UNDER_REVIEW", "NEEDS_INFORMATION", "READY_FOR_DECISION", "RESOLVED", "UNRESOLVED", "SUPERSEDED", "CLOSED"] as const;
export const GPA_DQ_DIMENSIONS = ["COMPLETENESS", "VALIDITY", "UNIQUENESS", "CONSISTENCY", "TIMELINESS", "REFERENTIAL_INTEGRITY", "SOURCE_AUTHORITY", "FRESHNESS"] as const;
export const GPA_DQ_STATES = ["PASS", "WARNING", "FAIL", "UNKNOWN", "NOT_APPLICABLE"] as const;
export const GPA_MATCH_METHODS = ["DETERMINISTIC", "MANUAL", "PROBABILISTIC"] as const;
export const GPA_MATCH_STATUSES = ["UNRESOLVED", "CANDIDATE", "MATCHED", "REJECTED", "AMBIGUOUS", "MERGE_REVIEW_REQUIRED", "SUPERSEDED"] as const;
export const GPA_DUPLICATE_CLASSIFICATIONS = ["POSSIBLE_DUPLICATE", "LIKELY_DUPLICATE", "CONFIRMED_DUPLICATE", "NOT_DUPLICATE"] as const;

export const GPA_RECONCILIATION_CODES = {
  CASE_FIELDS_REQUIRED: "GPA_RECONCILIATION_FIELDS_REQUIRED",
  CASE_NOT_FOUND: "GPA_RECONCILIATION_CASE_NOT_FOUND",
  CONFLICT_TYPE_INVALID: "GPA_CONFLICT_TYPE_INVALID",
  MATERIAL_REVIEW_REQUIRED: "GPA_MATERIAL_REVIEW_REQUIRED",
  SELF_REVIEW_DENIED: "GPA_RECONCILIATION_SELF_REVIEW_DENIED",
  QUALITY_RULE_REQUIRED: "GPA_QUALITY_RULE_REQUIRED",
  QUALITY_FAILURE: "GPA_CRITICAL_DATA_QUALITY_FAILURE",
  ENTITY_FIELDS_REQUIRED: "GPA_ENTITY_RESOLUTION_FIELDS_REQUIRED",
  AMBIGUOUS_MATCH: "GPA_ENTITY_MATCH_AMBIGUOUS",
  DUPLICATE_FIELDS_REQUIRED: "GPA_DUPLICATE_FIELDS_REQUIRED",
  DUPLICATE_NOT_FRAUD: "GPA_DUPLICATE_IS_NOT_FRAUD_DETERMINATION",
} as const;
