export const COORDINATE_FAMILIES = Object.freeze({
  REAL_WORLD: "REAL_WORLD",
  METAVERSE: "METAVERSE",
});

export const SPATIAL_INTERACTION_TYPES = Object.freeze({
  SELECT: "SELECT",
  DESELECT: "DESELECT",
  FOCUS: "FOCUS",
  HIGHLIGHT: "HIGHLIGHT",
  OPEN_RECORD: "OPEN_RECORD",
  REQUEST_ROUTE: "REQUEST_ROUTE",
  FOLLOW_ROUTE: "FOLLOW_ROUTE",
  INSPECT_EVIDENCE: "INSPECT_EVIDENCE",
  REQUEST_DOMAIN_ACTION: "REQUEST_DOMAIN_ACTION",
});

export const SPATIAL_STATES = Object.freeze({
  NORMAL: "NORMAL",
  SELECTED: "SELECTED",
  NEXT: "NEXT",
  SCHEDULED: "SCHEDULED",
  EVENT_SOON: "EVENT_SOON",
  EVENT_LIVE: "EVENT_LIVE",
  MISSION_ACTIVE: "MISSION_ACTIVE",
  EMERGENCY: "EMERGENCY",
  RESTRICTED: "RESTRICTED",
  CLOSED: "CLOSED",
  COMPLETED: "COMPLETED",
  UNAVAILABLE: "UNAVAILABLE",
});

export const TEMPORAL_STATES = Object.freeze({
  CURRENT: "current",
  UPCOMING: "upcoming",
  SOON: "soon",
  LIVE: "live",
  ENDED: "ended",
  SCHEDULED_LATER: "scheduled_later",
});

export const PUBLICATION_ELIGIBILITY_LEVELS = Object.freeze({
  PUBLIC: "PUBLIC",
  AUTHENTICATED: "AUTHENTICATED",
  ORGANIZATION: "ORGANIZATION",
  OPERATOR: "OPERATOR",
  ADMIN: "ADMIN",
  RESTRICTED: "RESTRICTED",
  NOT_PUBLISHED: "NOT_PUBLISHED",
});

export const VERIFICATION_STATES = Object.freeze({
  UNKNOWN: "UNKNOWN",
  UNVERIFIED: "UNVERIFIED",
  VERIFIED: "VERIFIED",
  REJECTED: "REJECTED",
});

export const TRANSFORM_AVAILABILITY = Object.freeze({
  NONE: "NONE",
  REGISTERED: "REGISTERED",
});

export const SPATIAL_LAYER_LIFECYCLE_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  ACTIVE_BUT_DEGRADED: "ACTIVE_BUT_DEGRADED",
  DISCONNECTED: "DISCONNECTED",
  UNMOUNTED: "UNMOUNTED",
  ARCHIVED: "ARCHIVED",
  FROZEN: "FROZEN",
  EXPERIMENTAL: "EXPERIMENTAL",
  RESTORATION_CANDIDATE: "RESTORATION_CANDIDATE",
  RETIREMENT_CANDIDATE: "RETIREMENT_CANDIDATE",
  UNKNOWN: "UNKNOWN",
});

export function enumValues(enumObject) {
  return Object.freeze(Object.values(enumObject));
}

export const COORDINATE_FAMILY_VALUES = enumValues(COORDINATE_FAMILIES);
export const SPATIAL_INTERACTION_TYPE_VALUES = enumValues(SPATIAL_INTERACTION_TYPES);
export const SPATIAL_STATE_VALUES = enumValues(SPATIAL_STATES);
export const TEMPORAL_STATE_VALUES = enumValues(TEMPORAL_STATES);
export const PUBLICATION_ELIGIBILITY_VALUES = enumValues(PUBLICATION_ELIGIBILITY_LEVELS);
export const VERIFICATION_STATE_VALUES = enumValues(VERIFICATION_STATES);
export const SPATIAL_LAYER_LIFECYCLE_VALUES = enumValues(SPATIAL_LAYER_LIFECYCLE_STATUS);
