export const COORDINATE_FAMILIES = Object.freeze({
  REAL_WORLD: "REAL_WORLD",
  METAVERSE: "METAVERSE",
});

export const SPATIAL_INTERACTION_TYPES = Object.freeze({
  SELECT: "SELECT",
  DESELECT: "DESELECT",
  FOCUS: "FOCUS",
  HIGHLIGHT: "HIGHLIGHT",
  OPEN_RECORD: "OPEN_RECORD",
  REQUEST_ROUTE: "REQUEST_ROUTE",
  FOLLOW_ROUTE: "FOLLOW_ROUTE",
  INSPECT_EVIDENCE: "INSPECT_EVIDENCE",
  REQUEST_DOMAIN_ACTION: "REQUEST_DOMAIN_ACTION",
});

export const SPATIAL_STATES = Object.freeze({
  NORMAL: "NORMAL",
  SELECTED: "SELECTED",
  NEXT: "NEXT",
  SCHEDULED: "SCHEDULED",
  EVENT_SOON: "EVENT_SOON",
  EVENT_LIVE: "EVENT_LIVE",
  MISSION_ACTIVE: "MISSION_ACTIVE",
  EMERGENCY: "EMERGENCY",
  RESTRICTED: "RESTRICTED",
  CLOSED: "CLOSED",
  COMPLETED: "COMPLETED",
  UNAVAILABLE: "UNAVAILABLE",
});

export const TEMPORAL_STATES = Object.freeze({
  CURRENT: "current",
  UPCOMING: "upcoming",
  SOON: "soon",
  LIVE: "live",
  ENDED: "ended",
  SCHEDULED_LATER: "scheduled_later",
});

export const PUBLICATION_ELIGIBILITY_LEVELS = Object.freeze({
  PUBLIC: "PUBLIC",
  AUTHENTICATED: "AUTHENTICATED",
  ORGANIZATION: "ORGANIZATION",
  OPERATOR: "OPERATOR",
  ADMIN: "ADMIN",
  RESTRICTED: "RESTRICTED",
  NOT_PUBLISHED: "NOT_PUBLISHED",
});

export const VERIFICATION_STATES = Object.freeze({
  UNKNOWN: "UNKNOWN",
  UNVERIFIED: "UNVERIFIED",
  VERIFIED: "VERIFIED",
  REJECTED: "REJECTED",
});

export const TRANSFORM_AVAILABILITY = Object.freeze({
  NONE: "NONE",
  REGISTERED: "REGISTERED",
});

export const SPATIAL_LAYER_LIFECYCLE_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  ACTIVE_BUT_DEGRADED: "ACTIVE_BUT_DEGRADED",
  DISCONNECTED: "DISCONNECTED",
  UNMOUNTED: "UNMOUNTED",
  ARCHIVED: "ARCHIVED",
  FROZEN: "FROZEN",
  EXPERIMENTAL: "EXPERIMENTAL",
  RESTORATION_CANDIDATE: "RESTORATION_CANDIDATE",
  RETIREMENT_CANDIDATE: "RETIREMENT_CANDIDATE",
  UNKNOWN: "UNKNOWN",
});

// GEO-1 Wave 3B layer policy (GEO1-WAVE3B-DEC-015). Absent stalePolicy behaves as MARK_STALE; absent maskMode means HIDE.
export const SPATIAL_LAYER_STALE_POLICIES = Object.freeze({
  MARK_STALE: "MARK_STALE",
  SUPPRESS: "SUPPRESS",
  UNAVAILABLE: "UNAVAILABLE",
});

export const SPATIAL_LAYER_MASK_MODES = Object.freeze({
  HIDE: "HIDE",
  NOTICE: "NOTICE",
  GENERALIZED: "GENERALIZED",
});

// Structured validation issue codes (GEO1-WAVE3B-DEC-010). Every validator `issues[i]` twins `errors[i]`.
export const VALIDATION_ISSUE_CODES = Object.freeze({
  OBJECT_REQUIRED: "OBJECT_REQUIRED",
  FIELD_REQUIRED: "FIELD_REQUIRED",
  FIELD_INVALID_ENUM: "FIELD_INVALID_ENUM",
  FIELD_INVALID_TIMESTAMP: "FIELD_INVALID_TIMESTAMP",
  FIELD_INVALID_TYPE: "FIELD_INVALID_TYPE",
  FEATURE_ID_INVALID_FORMAT: "FEATURE_ID_INVALID_FORMAT",
  PROVENANCE_REQUIRED: "PROVENANCE_REQUIRED",
  PROVENANCE_FIELD_REQUIRED: "PROVENANCE_FIELD_REQUIRED",
  PROVENANCE_TIMESTAMP_INVALID: "PROVENANCE_TIMESTAMP_INVALID",
  PUBLICATION_ELIGIBILITY_REQUIRED: "PUBLICATION_ELIGIBILITY_REQUIRED",
  PUBLICATION_ELIGIBILITY_INVALID: "PUBLICATION_ELIGIBILITY_INVALID",
  UNKNOWN_COORDINATE_SPACE: "UNKNOWN_COORDINATE_SPACE",
  COORDINATE_FAMILY_MISMATCH: "COORDINATE_FAMILY_MISMATCH",
  UNSUPPORTED_COORDINATE_SPACE: "UNSUPPORTED_COORDINATE_SPACE",
  UNKNOWN_LAYER: "UNKNOWN_LAYER",
  LAYER_COORDINATE_SPACE_UNSUPPORTED: "LAYER_COORDINATE_SPACE_UNSUPPORTED",
  TRANSFORM_AUTHORITY_REQUIRED: "TRANSFORM_AUTHORITY_REQUIRED",
  NO_REGISTERED_TRANSFORM: "NO_REGISTERED_TRANSFORM",
  LAYER_POLICY_INVALID: "LAYER_POLICY_INVALID",
});

export const VALIDATION_ISSUE_DETAIL_KEYS = Object.freeze(["expectedCoordinateFamily", "receivedCoordinateFamily"]);

export function enumValues(enumObject) {
  return Object.freeze(Object.values(enumObject));
}

export const COORDINATE_FAMILY_VALUES = enumValues(COORDINATE_FAMILIES);
export const SPATIAL_INTERACTION_TYPE_VALUES = enumValues(SPATIAL_INTERACTION_TYPES);
export const SPATIAL_STATE_VALUES = enumValues(SPATIAL_STATES);
export const TEMPORAL_STATE_VALUES = enumValues(TEMPORAL_STATES);
export const PUBLICATION_ELIGIBILITY_VALUES = enumValues(PUBLICATION_ELIGIBILITY_LEVELS);
export const VERIFICATION_STATE_VALUES = enumValues(VERIFICATION_STATES);
export const SPATIAL_LAYER_LIFECYCLE_VALUES = enumValues(SPATIAL_LAYER_LIFECYCLE_STATUS);
export const SPATIAL_LAYER_STALE_POLICY_VALUES = enumValues(SPATIAL_LAYER_STALE_POLICIES);
export const SPATIAL_LAYER_MASK_MODE_VALUES = enumValues(SPATIAL_LAYER_MASK_MODES);
