import { randomUUID } from "node:crypto";
import { query } from "../../../db/client.js";
import { writeAuditEvent } from "../../audit/service/audit-helper.js";
import { hasPermission } from "../../../auth/security-permissions.js";
import { deriveHealth, ISSUE_ORIGINS, ISSUE_STATUSES, SUPPORT_STATUSES, SUPPORT_TYPES } from "../model/operations.js";

const id = (prefix: string) => `${prefix}_${randomUUID()}`;
function scope(actor: any) { const organizationId = String(actor?.active_organization_id || actor?.organization_id || ""); const userId = String(actor?.user_id || actor?.id || ""); const tenantId = String(actor?.tenant_id || `tenant:${organizationId}`); if (!organizationId || !userId || tenantId !== `tenant:${organizationId}`) throw Object.assign(new Error("Organization context required."), { statusCode: 400, code: "ORG_CONTEXT_REQUIRED" }); return { organizationId, tenantId, userId }; }
function allow(actor: any, permission: string) { if (!hasPermission(actor?.permissions || [], permission)) throw Object.assign(new Error("Accessibility operations permission required."), { statusCode: 403, code: "FORBIDDEN" }); }
async function audit(actor: any, organizationId: string, targetType: string, targetId: string, action: string, next: any) { await writeAuditEvent({ audit_event_id: id("audit"), organization_id: organizationId, actor_user_id: scope(actor).userId, target_object_type: targetType, target_object_id: targetId, action_type: action, new_state_json: next, reason_text: action, correlation_id: id("corr"), source_channel: "accessibility-operations" }); }
function issue(row: any) { return { issueId: row.issue_id, organizationId: row.organization_id, sourceType: row.source_type, sourceId: row.source_id, sourceRoute: row.source_route, experience: row.experience, category: row.category, severity: row.severity, origin: row.origin, findingId: row.finding_id, ownerUserId: row.owner_user_id, status: row.status, priority: row.priority, description: row.description, impact: row.impact, remediationNotes: row.remediation_notes, retestStatus: row.retest_status, verificationStatus: row.verification_status, humanReviewRequired: row.verification_status === "REQUIRED", createdAt: row.created_at, updatedAt: row.updated_at }; }
function support(row: any, privateView = true) { return { supportRequestId: row.support_request_id, routeContext: row.route_context, requestType: row.request_type, summary: row.summary, consentToShareContext: row.consent_to_share_context, status: row.status, assignedOwnerUserId: row.assigned_owner_user_id, route: row.route, resolutionType: row.resolution_type, linkedIssueId: row.linked_issue_id, linkedAccommodationCaseId: row.linked_accommodation_case_id, createdAt: row.created_at, updatedAt: row.updated_at, ...(privateView ? { sharedContext: row.shared_context_json || {} } : {}) }; }

export async function listIssues(actor: any) { allow(actor, "accessibility.operations.view"); const s = scope(actor); const result = await query("SELECT * FROM accessibility_operation_issues WHERE organization_id=$1 AND tenant_id=$2 ORDER BY updated_at DESC", [s.organizationId, s.tenantId]); return result.rows.map(issue); }
export async function getIssue(actor: any, issueId: string) { allow(actor, "accessibility.operations.view"); const s = scope(actor); const result = await query("SELECT * FROM accessibility_operation_issues WHERE issue_id=$1 AND organization_id=$2 AND tenant_id=$3", [issueId, s.organizationId, s.tenantId]); return result.rows[0] ? issue(result.rows[0]) : null; }
export async function ingestFinding(actor: any, input: any) { allow(actor, "accessibility.operations.manage"); const s = scope(actor); if (!input?.findingId || !ISSUE_ORIGINS.includes(String(input.origin) as any)) throw Object.assign(new Error("Valid finding identity and origin required."), { statusCode: 400, code: "INVALID_FINDING" }); const result = await query(`INSERT INTO accessibility_operation_issues (issue_id,organization_id,tenant_id,source_type,source_id,source_route,experience,category,severity,origin,finding_id,description,impact,verification_status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT (organization_id,tenant_id,finding_id,source_route,source_id) DO UPDATE SET last_seen_at=NOW(),updated_at=NOW(),status=CASE WHEN accessibility_operation_issues.status IN ('VERIFIED','RESOLVED','CLOSED') THEN 'REGRESSION' ELSE accessibility_operation_issues.status END,origin=CASE WHEN accessibility_operation_issues.status IN ('VERIFIED','RESOLVED','CLOSED') THEN 'REGRESSION' ELSE EXCLUDED.origin END RETURNING *`, [id("ax6_issue"), s.organizationId, s.tenantId, input.sourceType || "AX5", input.sourceId || null, input.sourceRoute || null, input.experience || null, input.category || "ACCESSIBILITY", input.severity || "MODERATE", input.origin, input.findingId, input.description || "Accessibility finding requires attention.", input.impact || null, input.humanReviewRequired ? "REQUIRED" : "NOT_REQUIRED"]); const row = issue(result.rows[0]); await audit(actor, s.organizationId, "accessibility_operation_issue", row.issueId, "accessibility.issue.ingested", row); return row; }
export async function updateIssue(actor: any, issueId: string, input: any) { allow(actor, "accessibility.operations.manage"); const s = scope(actor); const fields: string[] = []; const values: any[] = []; for (const [column, value] of [["owner_user_id", input.ownerUserId === "current-operator" ? s.userId : input.ownerUserId], ["status", input.status], ["priority", input.priority], ["remediation_notes", input.remediationNotes], ["retest_status", input.retestStatus]] as const) if (value !== undefined) { fields.push(`${column}=$${values.length + 1}`); values.push(value); } if (!fields.length) return getIssue(actor, issueId); if (input.status && !ISSUE_STATUSES.includes(input.status)) throw Object.assign(new Error("Invalid issue status."), { statusCode: 400, code: "INVALID_STATUS" }); values.push(issueId, s.organizationId, s.tenantId); const result = await query(`UPDATE accessibility_operation_issues SET ${fields.join(",")},updated_at=NOW(),version=version+1 WHERE issue_id=$${values.length-2} AND organization_id=$${values.length-1} AND tenant_id=$${values.length} RETURNING *`, values); if (!result.rows[0]) throw Object.assign(new Error("Issue not found."), { statusCode: 404, code: "NOT_FOUND" }); const row = issue(result.rows[0]); await audit(actor, s.organizationId, "accessibility_operation_issue", issueId, "accessibility.issue.updated", row); return row; }
export async function health(actor: any) { const items = await listIssues(actor); return { health: deriveHealth(items), metrics: { openIssues: items.filter((i) => !["VERIFIED", "RESOLVED", "CLOSED"].includes(i.status)).length, blockingIssues: items.filter((i) => i.severity === "CRITICAL" || i.status === "BLOCKED").length, regressions: items.filter((i) => i.status === "REGRESSION").length, humanReviewPending: items.filter((i) => i.humanReviewRequired && i.verificationStatus !== "COMPLETED").length } }; }
export async function createSupport(actor: any, input: any) { const s = scope(actor); const type = String(input?.requestType || "").toUpperCase(); if (!SUPPORT_TYPES.includes(type as any) || !input?.summary) throw Object.assign(new Error("Valid accessibility support request required."), { statusCode: 400, code: "INVALID_SUPPORT_REQUEST" }); const context = input.consentToShareContext ? (input.sharedContext || {}) : {}; const result = await query("INSERT INTO accessibility_support_requests (support_request_id,organization_id,tenant_id,user_id,route_context,request_type,summary,consent_to_share_context,shared_context_json) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb) RETURNING *", [id("ax6_support"), s.organizationId, s.tenantId, s.userId, input.routeContext || null, type, input.summary, Boolean(input.consentToShareContext), JSON.stringify(context)]); const row = support(result.rows[0]); await audit(actor, s.organizationId, "accessibility_support_request", row.supportRequestId, "accessibility.support.requested", { status: row.status, requestType: row.requestType }); return row; }
export async function getOwnSupport(actor: any, supportId: string) { const s = scope(actor); const result = await query("SELECT * FROM accessibility_support_requests WHERE support_request_id=$1 AND organization_id=$2 AND tenant_id=$3 AND user_id=$4", [supportId, s.organizationId, s.tenantId, s.userId]); return result.rows[0] ? support(result.rows[0]) : null; }
export async function listSupport(actor: any) { allow(actor, "accessibility.support.manage"); const s = scope(actor); const result = await query("SELECT * FROM accessibility_support_requests WHERE organization_id=$1 AND tenant_id=$2 ORDER BY updated_at DESC", [s.organizationId, s.tenantId]); return result.rows.map((row) => support(row, false)); }
export async function updateSupport(actor: any, supportId: string, input: any) { allow(actor, "accessibility.support.manage"); const s = scope(actor); if (!SUPPORT_STATUSES.includes(String(input.status) as any)) throw Object.assign(new Error("Invalid support status."), { statusCode: 400, code: "INVALID_STATUS" }); const result = await query("UPDATE accessibility_support_requests SET status=$1,assigned_owner_user_id=COALESCE($2,assigned_owner_user_id),route=COALESCE($3,route),resolution_type=COALESCE($4,resolution_type),resolved_at=CASE WHEN $1='RESOLVED' THEN NOW() ELSE resolved_at END,updated_at=NOW() WHERE support_request_id=$5 AND organization_id=$6 AND tenant_id=$7 RETURNING *", [input.status, input.assignedOwnerUserId || null, input.route || null, input.resolutionType || null, supportId, s.organizationId, s.tenantId]); if (!result.rows[0]) throw Object.assign(new Error("Support request not found."), { statusCode: 404, code: "NOT_FOUND" }); const row = support(result.rows[0], false); await audit(actor, s.organizationId, "accessibility_support_request", supportId, "accessibility.support.updated", row); return row; }
