import { createHash, randomUUID } from "node:crypto";
import { withTransaction } from "../../../db/transaction.js";
import { hasPermission, SHS_SECURITY_PERMISSIONS } from "../../../auth/security-permissions.js";
import { IntegrationOutboxRepo } from "../../trusted-reporting/outbox-repo.js";
import { AragRepo } from "../repo/arag-repo.js";
import { LocalMockAragReleaseProvider, type AragReleaseProvider } from "../provider/arag-provider.js";
import { DefaultAragPolicyEvaluator, type AragPolicyEvaluator } from "../policy/arag-policy.js";
import { ARAG_DECISION_CODES, toPacketResponse, toReleaseResponse } from "../model/arag.js";
import { AiGovernanceService } from "../../ai-governance/service/ai-governance-service.js";

type Actor = { user_id?: string; id?: string; active_organization_id?: string; organization_id?: string; tenant_id?: string; permissions?: string[]; roles?: string[] };

export class AragError extends Error { constructor(public code: string, message = code, public statusCode = 400) { super(message); } }

function scopeOf(actor: Actor) {
  const userId = String(actor.user_id || actor.id || "");
  const organizationId = String(actor.active_organization_id || actor.organization_id || "");
  const tenantId = String(actor.tenant_id || `tenant:${organizationId}`);
  if (!userId || !organizationId || tenantId !== `tenant:${organizationId}`) throw new AragError("ORG_CONTEXT_REQUIRED", "Organization and tenant context are required.", 400);
  return { userId, organizationId, tenantId };
}

function requirePermission(actor: Actor, permission: string) { if (!hasPermission(actor.permissions || [], permission)) throw new AragError("ARAG_PERMISSION_REQUIRED", "ARAG-1 permission is required.", 403); }
function subjectHash(input: any) { return createHash("sha256").update(JSON.stringify({ projectId: input.projectId, deliveryRecordId: input.deliveryRecordId, workspaceRevision: Number(input.workspaceRevision), packageHash: input.packageHash, providerKey: input.providerKey, targetEnvironment: input.targetEnvironment })).digest("hex"); }

export class AragService {
  private policy: AragPolicyEvaluator;
  constructor(private repo = new AragRepo(), private provider: AragReleaseProvider = new LocalMockAragReleaseProvider(), private transaction: typeof withTransaction = withTransaction, private outbox = new IntegrationOutboxRepo(), policy?: AragPolicyEvaluator, private aiGovernance = new AiGovernanceService()) { this.policy = policy || new DefaultAragPolicyEvaluator(this.repo); }

  private async emit(type: string, id: string, scope: any, payload: Record<string, unknown> = {}) {
    await this.outbox.enqueue({ producer_id: "shs-api.arag-1", event_type: type, subject_type: "arag_release", subject_id: id, organization_id: scope.organizationId, tenant_id: scope.tenantId, originating_actor_id: scope.userId, originating_actor_type: "user", occurred_at: new Date().toISOString(), idempotency_key: `${type}:${id}`, correlation_id: `arag:${id}`, destination: "shs-release-assurance", payload });
  }

  async request(actor: Actor, body: any = {}) {
    requirePermission(actor, SHS_SECURITY_PERMISSIONS.ARAG_RELEASE_REQUEST); const scope = scopeOf(actor);
    const required = ["projectId", "deliveryRecordId", "workspaceRevision", "packageHash", "repositoryReference", "providerKey", "targetEnvironment", "workOrderReference", "qaRunId", "reviewSubmissionId", "reviewDecisionId", "simulationId"];
    if (required.some((key) => body[key] === undefined || body[key] === null || String(body[key]).trim() === "")) throw new AragError("RELEASE_REQUIRED_FIELDS", "Release subject, policy, QA, review, and simulation references are required.");
    const actingAgentIdentifier = String(body.actingAgentIdentifier || body.acting_agent_identifier || "").trim() || null;
    if (actingAgentIdentifier && (!(body.agentSessionId || body.agent_session_id) || !(body.delegationId || body.delegation_id) || !String(body.authorityPurpose || body.authority_purpose || "").trim())) throw new AragError(ARAG_DECISION_CODES.AUTHORITY_DENIED, "Agent-assisted release requires session, delegation, and purpose references.", 400);
    const normalized = { ...body, project_id: body.projectId, delivery_record_id: body.deliveryRecordId, workspace_revision: Number(body.workspaceRevision), package_hash: body.packageHash, repository_reference: body.repositoryReference, provider_key: body.providerKey, target_environment: body.targetEnvironment, organization_id: scope.organizationId, tenant_id: scope.tenantId, requested_by: scope.userId, acting_agent_identifier: actingAgentIdentifier, agent_session_id: body.agentSessionId || body.agent_session_id || null, delegation_id: body.delegationId || body.delegation_id || null, work_order_reference: body.workOrderReference, authority_purpose: body.authorityPurpose || body.authority_purpose || null, model_provider: body.modelProvider || body.model_provider || null, model_identifier: body.modelIdentifier || body.model_identifier || null, qa_run_id: body.qaRunId, review_submission_id: body.reviewSubmissionId, review_decision_id: body.reviewDecisionId, simulation_id: body.simulationId, policy_decision: "UNKNOWN", workspaceRevision: Number(body.workspaceRevision), release_request_id: `arag_release_${randomUUID()}`, subject_hash: subjectHash(body) };
    if (!Number.isInteger(normalized.workspaceRevision) || normalized.workspaceRevision < 1) throw new AragError("RELEASE_REVISION_INVALID", "Release revision must be a positive integer.");
    const row = await this.repo.createReleaseRequest(normalized); await this.emit("arag.release.requested", row.release_request_id, scope, { subject_hash: row.subject_hash, provider_key: row.provider_key, target: row.target_environment }); return toReleaseResponse(row);
  }

  async list(actor: Actor) { requirePermission(actor, SHS_SECURITY_PERMISSIONS.ARAG_RELEASE_READ); const scope = scopeOf(actor); return (await this.repo.listReleaseRequests(scope.organizationId, scope.tenantId)).map(toReleaseResponse); }
  async get(actor: Actor, id: string) { requirePermission(actor, SHS_SECURITY_PERMISSIONS.ARAG_RELEASE_READ); const scope = scopeOf(actor); const row = await this.repo.getReleaseRequest(id, scope.organizationId, scope.tenantId); if (!row) throw new AragError("RELEASE_NOT_FOUND", "Release request was not found.", 404); return toReleaseResponse(row); }

  private async load(actor: Actor, id: string) { const scope = scopeOf(actor); const row = await this.repo.getReleaseRequest(id, scope.organizationId, scope.tenantId); if (!row) throw new AragError("RELEASE_NOT_FOUND", "Release request was not found.", 404); return { scope, row, inputs: await this.repo.getAssuranceInputs(row) }; }

  async evaluate(actor: Actor, id: string) {
    requirePermission(actor, SHS_SECURITY_PERMISSIONS.ARAG_RELEASE_EVALUATE); const { scope, row, inputs } = await this.load(actor, id); const blocking: string[] = [];
    if (!inputs.qa) blocking.push(ARAG_DECISION_CODES.QA_MISSING); else if (inputs.qa.status !== "PASSED") blocking.push(inputs.qa.status === "FAILED" || inputs.qa.status === "ERROR" ? ARAG_DECISION_CODES.QA_FAILED : ARAG_DECISION_CODES.QA_MISSING); else if (Number(inputs.qa.workspace_revision) !== Number(row.workspace_revision)) blocking.push(ARAG_DECISION_CODES.QA_REVISION_MISMATCH);
    if (!inputs.review) blocking.push(ARAG_DECISION_CODES.REVIEW_MISSING); else if (inputs.review.status !== "APPROVED" || inputs.review.decision !== "APPROVED") blocking.push(ARAG_DECISION_CODES.REVIEW_REJECTED); else if (Number(inputs.review.workspace_revision) !== Number(row.workspace_revision)) blocking.push(ARAG_DECISION_CODES.REVIEW_REVISION_MISMATCH);
    if (!inputs.simulation) blocking.push(ARAG_DECISION_CODES.SIMULATION_MISSING); else if (!["READY", "COMPLETED"].includes(inputs.simulation.status) || (inputs.simulation.metadata_json?.subjectHash && inputs.simulation.metadata_json.subjectHash !== row.subject_hash)) blocking.push(ARAG_DECISION_CODES.SIMULATION_STALE);
    const policyDecision = await this.policy.evaluate({ request: row, organizationId: scope.organizationId, tenantId: scope.tenantId, actorUserId: scope.userId, actorRoles: actor.roles || [] });
    await this.repo.updatePolicyDecision({ release_request_id: id, organization_id: scope.organizationId, tenant_id: scope.tenantId, policy_decision: policyDecision.decision, policy_version: policyDecision.policy?.policy_version || null, policy_provenance: policyDecision.policy?.policy_provenance || {} });
    if (policyDecision.decision !== "ALLOW") blocking.push(policyDecision.code || ARAG_DECISION_CODES.POLICY_DENIED);
    if (inputs.securityBlocked) blocking.push(ARAG_DECISION_CODES.SECURITY_BLOCKED);
    const providerTarget = await this.provider.validateTarget({ projectId: row.project_id, revision: Number(row.workspace_revision), packageHash: row.package_hash, providerKey: row.provider_key, target: row.target_environment });
    if (!providerTarget.allowed) blocking.push(providerTarget.code || ARAG_DECISION_CODES.PROVIDER_NOT_APPROVED);
    if (row.acting_agent_identifier) {
      const authority = await this.aiGovernance.evaluateAgentAuthority({ principalUserId: row.requested_by, organizationId: scope.organizationId, tenantId: scope.tenantId, agentIdentifier: row.acting_agent_identifier, sessionId: row.agent_session_id, delegationId: row.delegation_id, purpose: row.authority_purpose, action: "release.execute", resource: { organizationId: scope.organizationId, tenantId: scope.tenantId, resourceType: "studio_delivery_record", resourceId: row.delivery_record_id }, model: { providerIdentifier: row.model_provider, modelIdentifier: row.model_identifier } });
      if (!authority.allowed) blocking.push(authority.denialCode || ARAG_DECISION_CODES.AUTHORITY_DENIED);
    }
    if (!inputs.approval || inputs.approval.decision !== "APPROVED" || inputs.approval.subject_hash !== row.subject_hash) blocking.push(ARAG_DECISION_CODES.APPROVAL_REQUIRED);
    const status = blocking.length ? (blocking.includes(ARAG_DECISION_CODES.QA_MISSING) || blocking.includes(ARAG_DECISION_CODES.QA_FAILED) || blocking.includes(ARAG_DECISION_CODES.QA_REVISION_MISMATCH) ? "QA_REQUIRED" : blocking.includes(ARAG_DECISION_CODES.REVIEW_MISSING) || blocking.includes(ARAG_DECISION_CODES.REVIEW_REJECTED) || blocking.includes(ARAG_DECISION_CODES.REVIEW_REVISION_MISMATCH) ? "REVIEW_REQUIRED" : blocking.includes(ARAG_DECISION_CODES.APPROVAL_REQUIRED) ? "APPROVAL_REQUIRED" : "BLOCKED") : "ASSURANCE_READY";
    const updated = await this.repo.updateStatus({ release_request_id: id, organization_id: scope.organizationId, tenant_id: scope.tenantId, status, blocking_codes: blocking });
    await this.emit(blocking.length ? "arag.assurance.blocked" : "arag.assurance.started", id, scope, { blocking_codes: blocking, status });
    return { allowed: blocking.length === 0, releaseDecision: blocking.length ? "BLOCKED" : "ASSURANCE_READY", decisionCodes: blocking, blockingConditions: blocking, approvalRequired: blocking.includes(ARAG_DECISION_CODES.APPROVAL_REQUIRED), providerProductionCapable: this.provider.productionCapable, policyDecision: policyDecision.decision, release: toReleaseResponse(updated || row) };
  }

  async approve(actor: Actor, id: string, body: any = {}) {
    requirePermission(actor, SHS_SECURITY_PERMISSIONS.ARAG_RELEASE_APPROVE); const { scope, row } = await this.load(actor, id); if (row.requested_by === scope.userId) throw new AragError(ARAG_DECISION_CODES.APPROVAL_INVALID, "The requester cannot approve the same release.", 403); if (body.subjectHash !== row.subject_hash) throw new AragError(ARAG_DECISION_CODES.SUBJECT_CHANGED, "Approval must bind to the exact release subject.", 409);
    const approval = await this.repo.createApproval({ approval_id: `arag_approval_${randomUUID()}`, release_request_id: id, organization_id: scope.organizationId, tenant_id: scope.tenantId, subject_hash: row.subject_hash, approver_user_id: scope.userId, decision: String(body.decision || "APPROVED").toUpperCase(), rationale: body.rationale || "", expires_at: new Date(Date.now() + 15 * 60 * 1000) }); await this.emit("arag.approval.required", id, scope, { decision: approval.decision, subject_hash: row.subject_hash }); return approval;
  }

  async authorize(actor: Actor, id: string) {
    requirePermission(actor, SHS_SECURITY_PERMISSIONS.ARAG_RELEASE_EVALUATE); const evaluation = await this.evaluate(actor, id); if (!evaluation.allowed) throw new AragError(evaluation.decisionCodes[0] || ARAG_DECISION_CODES.EVIDENCE_INCOMPLETE, "Release assurance is not ready.", 403); const { scope, row } = await this.load(actor, id); const authorization = await this.repo.createAuthorization({ authorization_id: `arag_auth_${randomUUID()}`, release_request_id: id, organization_id: scope.organizationId, tenant_id: scope.tenantId, subject_hash: row.subject_hash, provider_key: row.provider_key, target_environment: row.target_environment, authorized_by: scope.userId, expires_at: new Date(Date.now() + 5 * 60 * 1000) }); await this.repo.updateStatus({ release_request_id: id, organization_id: scope.organizationId, tenant_id: scope.tenantId, status: "AUTHORIZED", blocking_codes: [] }); await this.emit("arag.release.authorized", id, scope, { authorization_id: authorization.authorization_id, subject_hash: row.subject_hash }); return authorization;
  }

  async revokeAuthorization(actor: Actor, id: string) {
    requirePermission(actor, SHS_SECURITY_PERMISSIONS.ARAG_RELEASE_EVALUATE); const scope = scopeOf(actor); const revoked = await this.repo.revokeAuthorization(id, scope.organizationId, scope.tenantId); if (!revoked) throw new AragError(ARAG_DECISION_CODES.REPLAY_DENIED, "Authorization is already used, revoked, expired, or outside scope.", 409); await this.emit("arag.release.authorization_revoked", revoked.release_request_id, scope, { authorization_id: id }); return revoked;
  }

  async release(actor: Actor, id: string, body: any = {}) {
    requirePermission(actor, SHS_SECURITY_PERMISSIONS.ARAG_RELEASE_EXECUTE); const { scope, row } = await this.load(actor, id); if (!this.provider.productionCapable) throw new AragError(ARAG_DECISION_CODES.EXECUTION_DISABLED, "No production-capable ARAG provider is configured.", 503); const authorization = await this.repo.getAuthorization(String(body.authorizationId || ""), scope.organizationId, scope.tenantId); if (!authorization || authorization.release_request_id !== id || authorization.subject_hash !== row.subject_hash || authorization.provider_key !== row.provider_key || authorization.target_environment !== row.target_environment || authorization.expires_at <= new Date() || authorization.used_at || authorization.revoked_at) throw new AragError(ARAG_DECISION_CODES.REPLAY_DENIED, "Release authorization is expired, revoked, used, or subject-mismatched.", 403); const claimed = await this.repo.claimAuthorization(authorization.authorization_id, scope.organizationId, scope.tenantId); if (!claimed) throw new AragError(ARAG_DECISION_CODES.REPLAY_DENIED, "Release authorization could not be claimed.", 403);
    const startedAt = new Date(); await this.repo.updateStatus({ release_request_id: id, organization_id: scope.organizationId, tenant_id: scope.tenantId, status: "RELEASING", blocking_codes: [] }); await this.emit("arag.release.started", id, scope, { authorization_id: claimed.authorization_id });
    try { const result = await this.provider.release({ projectId: row.project_id, revision: Number(row.workspace_revision), packageHash: row.package_hash, providerKey: row.provider_key, target: row.target_environment }, id); const saved = await this.repo.createResult({ release_result_id: `arag_result_${randomUUID()}`, release_request_id: id, authorization_id: claimed.authorization_id, organization_id: scope.organizationId, tenant_id: scope.tenantId, provider_key: row.provider_key, provider_release_id: result.providerReleaseId, target_environment: row.target_environment, subject_hash: row.subject_hash, status: "RELEASED", started_at: startedAt, completed_at: new Date(), rollback_available: result.rollbackAvailable, response_metadata: result.responseMetadata }); await this.repo.updateStatus({ release_request_id: id, organization_id: scope.organizationId, tenant_id: scope.tenantId, status: "RELEASED", blocking_codes: [] }); const packet = await this.createPacket(scope, row, claimed, saved); await this.emit("arag.release.succeeded", id, scope, { release_result_id: saved.release_result_id }); return { release: saved, assurancePacket: packet };
    } catch (error: any) { const saved = await this.repo.createResult({ release_result_id: `arag_result_${randomUUID()}`, release_request_id: id, authorization_id: claimed.authorization_id, organization_id: scope.organizationId, tenant_id: scope.tenantId, provider_key: row.provider_key, target_environment: row.target_environment, subject_hash: row.subject_hash, status: "FAILED", started_at: startedAt, completed_at: new Date(), failure_code: ARAG_DECISION_CODES.FAILED, failure_message: String(error?.message || "provider failure").slice(0, 500), rollback_available: false, response_metadata: {} }); await this.repo.updateStatus({ release_request_id: id, organization_id: scope.organizationId, tenant_id: scope.tenantId, status: "FAILED", blocking_codes: [ARAG_DECISION_CODES.FAILED] }); await this.emit("arag.release.failed", id, scope, { release_result_id: saved.release_result_id }); throw new AragError(ARAG_DECISION_CODES.FAILED, "Provider release failed.", 502); }
  }

  private async createPacket(scope: any, row: any, authorization: any, result: any) { const packetJson = { packetClass: "ARAG_ASSURANCE_PACKET", releaseRequestId: row.release_request_id, organizationId: scope.organizationId, tenantId: scope.tenantId, actors: { requestedBy: row.requested_by, actingAgent: row.acting_agent_identifier || null, agentSession: row.agent_session_id || null, delegation: row.delegation_id || null, authorizedBy: authorization.authorized_by }, exactSubject: { projectId: row.project_id, deliveryRecordId: row.delivery_record_id, workspaceRevision: Number(row.workspace_revision), packageHash: row.package_hash, providerKey: row.provider_key, target: row.target_environment, subjectHash: row.subject_hash }, policy: { workOrderReference: row.work_order_reference, version: row.policy_version || null, provenance: row.policy_provenance || {}, decision: row.policy_decision }, qa: { qaRunId: row.qa_run_id }, review: { reviewSubmissionId: row.review_submission_id, reviewDecisionId: row.review_decision_id }, simulation: { simulationId: row.simulation_id }, approval: { authorizationId: authorization.authorization_id, authorizedBy: authorization.authorized_by, validFrom: authorization.valid_from, expiresAt: authorization.expires_at }, result: { releaseResultId: result.release_result_id, status: result.status, providerReleaseId: result.provider_release_id || null, rollbackAvailable: result.rollback_available === true }, semantics: "This packet records the governed release process; it does not certify software quality, legal compliance, or business outcomes." }; const packetHash = createHash("sha256").update(JSON.stringify(packetJson)).digest("hex"); return toPacketResponse(await this.repo.createPacket({ packet_id: `arag_packet_${randomUUID()}`, release_request_id: row.release_request_id, organization_id: scope.organizationId, tenant_id: scope.tenantId, packet_hash: packetHash, packet_json: packetJson })); }

  async packet(actor: Actor, id: string) { requirePermission(actor, SHS_SECURITY_PERMISSIONS.ARAG_RELEASE_READ); const scope = scopeOf(actor); const row = await this.repo.getLatestPacket(id, scope.organizationId, scope.tenantId); if (!row) throw new AragError("RELEASE_PACKET_NOT_FOUND", "Assurance packet was not found.", 404); return toPacketResponse(row); }

  async rollback(actor: Actor, id: string) { requirePermission(actor, SHS_SECURITY_PERMISSIONS.ARAG_RELEASE_ROLLBACK); const { scope, row } = await this.load(actor, id); const result = await this.repo.getLatestResult(id, scope.organizationId, scope.tenantId); if (!result?.provider_release_id || !result.rollback_available) throw new AragError("ROLLBACK_UNAVAILABLE", "Provider rollback is unavailable.", 409); const rollback = await this.provider.rollback(result.provider_release_id, { projectId: row.project_id, revision: Number(row.workspace_revision), packageHash: row.package_hash, providerKey: row.provider_key, target: row.target_environment }, id); const updated = await this.repo.updateResult({ release_result_id: result.release_result_id, organization_id: scope.organizationId, tenant_id: scope.tenantId, status: rollback.status, rollback_status: rollback.status, response_metadata: rollback.responseMetadata }); await this.repo.updateStatus({ release_request_id: id, organization_id: scope.organizationId, tenant_id: scope.tenantId, status: rollback.status === "ROLLED_BACK" ? "ROLLED_BACK" : "ROLLBACK_REQUIRED", blocking_codes: rollback.status === "ROLLED_BACK" ? [] : [ARAG_DECISION_CODES.ROLLBACK_REQUIRED] }); await this.emit(rollback.status === "ROLLED_BACK" ? "arag.rollback.succeeded" : "arag.rollback.failed", id, scope, { release_result_id: updated.release_result_id }); return updated;
  }
}
