import React from "react";
import {
  safeReportValue,
  SHS_PREMIUM_INTERIOR_TEMPLATE,
} from "../shsPremiumReportData";
import ShsClientProfileInfoCard from "./ShsClientProfileInfoCard.jsx";
import ShsClientProfileModuleList from "./ShsClientProfileModuleList.jsx";
import ShsClientProfileSourceReadiness from "./ShsClientProfileSourceReadiness.jsx";
import ShsProfileControlStatusPanel from "./ShsProfileControlStatusPanel.jsx";
import { ShsPremiumReportInteriorPage } from "./ShsPremiumReportShared.jsx";

export default function ShsClientOrganizationProfilePage({ report }) {
  const profile = report?.subjectProfile || {};

  const clientRows = [
    ["Client / Organization", profile.clientName || report?.subjectName],
    ["Client Type", profile.clientType],
    ["Support Tier", profile.supportTier],
    ["Subject Record ID", profile.clientId || report?.subjectId || report?.reportId],
    ["Reporting Period", report?.reportingPeriodLabel],
  ];

  const systemRows = [
    ["Report Type", report?.reportType],
    ["Data Mode", report?.dataMode],
    ["Lifecycle Status", report?.lifecycleStatus],
    ["System Environment", profile.systemEnvironment],
    ["Generated By", report?.generatedBy],
    ["Template Version", report?.templateVersion || SHS_PREMIUM_INTERIOR_TEMPLATE.version],
  ];

  return (
    <ShsPremiumReportInteriorPage
      report={report}
      pageNumber={3}
      title="Client / Organization Profile"
      subtitle="A system-level profile of the report subject, active operating modules, reporting context, and infrastructure connection."
      sidePanel={<ShsProfileControlStatusPanel report={report} />}
    >
      <section className="shs-profile-grid" aria-label="Client profile information">
        <ShsClientProfileInfoCard
          eyebrow="Report Subject"
          title="Client / Organization Information"
          rows={clientRows}
        />
        <ShsClientProfileInfoCard
          eyebrow="System Context"
          title="System Profile"
          rows={systemRows}
        />
      </section>

      <ShsClientProfileModuleList report={report} />
      <ShsClientProfileSourceReadiness report={report} />

      <section className="shs-profile-summary-callout">
        <span aria-hidden="true">◎</span>
        <div>
          <p className="shs-premium-kicker">Report Subject Summary</p>
          <h2>Report Subject Summary</h2>
          <p>{safeReportValue(profile.profileSummary)}</p>
        </div>
      </section>
    </ShsPremiumReportInteriorPage>
  );
}
