import React from "react";
import { evaluateReportReadiness } from "@/data/shsReports/shsReportReadiness";
import { SHS_PREMIUM_INTERIOR_TEMPLATE } from "@/data/shsReports/shsReportTemplates";
import { displayDataStatus, displayLifecycleStatus, displayVisibilityMode } from "@/data/shsReports/shsReportTypes";

export default function ShsExportMetadataPanel({ report }) {
  const readiness = evaluateReportReadiness(report);
  const rows = [
    ["Report ID", report?.reportId],
    ["Generated By", report?.generatedBy],
    ["Prepared By", report?.preparedBy],
    ["Generated Date", report?.generatedDate],
    ["Export Date", report?.exportMetadata?.exportedAt || "Missing"],
    ["Export Format", report?.exportMetadata?.exportFormat || "pdf"],
    ["Report Version", report?.reportVersion],
    ["Template Version", report?.templateVersion],
    ["Visibility", displayVisibilityMode(report?.visibility)],
    ["Lifecycle Status", displayLifecycleStatus(report?.lifecycleStatus)],
    ["Data Mode", displayDataStatus(report?.dataMode)],
    ["Locked Status", report?.isLocked ? "Locked Exported Record" : "Unlocked Draft"],
    ["Source Readiness", `${readiness.summary.verified} verified / ${readiness.summary.approved} approved / ${readiness.summary.missing} missing`],
    ["Missing Data Warnings", report?.missingDataWarnings?.length ? report.missingDataWarnings.join("; ") : "None recorded"],
    ["Audit Exceptions", report?.auditExceptions?.length ? `${report.auditExceptions.length} recorded` : "None recorded"],
    ["Print Instruction", report?.exportMetadata?.printInstruction || SHS_PREMIUM_INTERIOR_TEMPLATE.printInstruction],
  ];

  return (
    <section className="shs-report-panel">
      <div className="shs-report-panel__header">
        <p>Export Metadata</p>
        <h2>Report Export Record</h2>
        <span>Export metadata is preserved separately from editable draft content.</span>
      </div>
      <dl className="shs-export-metadata-grid">
        {rows.map(([label, value]) => (
          <div key={label}>
            <dt>{label}</dt>
            <dd>{value || "Missing"}</dd>
          </div>
        ))}
      </dl>
    </section>
  );
}
