import React from "react";
import {
  normalizeLifecycleStatus,
  normalizeShsStatus,
  normalizeVisibility,
  safeReportValue,
  SHS_PREMIUM_INTERIOR_TEMPLATE,
} from "../shsPremiumReportData";

export function ShsReportDataStatusBadge({ status }) {
  const label = normalizeShsStatus(status);
  return (
    <span className={`shs-report-badge shs-report-badge--${label.toLowerCase()}`}>
      {label}
    </span>
  );
}

export function ShsReportLifecycleBadge({ status }) {
  const label = normalizeLifecycleStatus(status);
  return (
    <span className={`shs-report-badge shs-report-badge--lifecycle shs-report-badge--${label.toLowerCase().replace(/\s+/g, "-")}`}>
      {label}
    </span>
  );
}

export function ShsReportVisibilityBadge({ visibility }) {
  const label = normalizeVisibility(visibility);
  return (
    <span className="shs-report-badge shs-report-badge--visibility">
      {label}
    </span>
  );
}

export function ShsPoweredByOsBadge() {
  return (
    <div className="shs-powered-badge">
      <span className="shs-powered-badge__mark">SH</span>
      <span>
        <strong>Silicon Heartland OS</strong>
        <em>Powered by Silicon Heartland Solutions</em>
      </span>
    </div>
  );
}

export function ShsReportMetadataFooter({ report, pageNumber = 1 }) {
  const footerItems = [
    ["Report ID", safeReportValue(report?.reportId)],
    ["Generated By", safeReportValue(report?.generatedBy, "Silicon Heartland OS")],
    ["Prepared By", safeReportValue(report?.preparedBy, "Silicon Heartland Solutions")],
    ["Date", safeReportValue(report?.generatedDate)],
    ["Data Mode", safeReportValue(report?.dataMode)],
    ["Report Mode", safeReportValue(report?.reportType)],
    ["Template Version", safeReportValue(report?.templateVersion, SHS_PREMIUM_INTERIOR_TEMPLATE.version)],
  ];

  return (
    <footer className="shs-premium-page__footer">
      <div className="shs-premium-page__footer-art" aria-hidden="true" />
      <div className="shs-premium-page__footer-grid">
        {footerItems.map(([label, value]) => (
          <span key={label}>
            <em>{label}</em>
            <strong>{value}</strong>
          </span>
        ))}
      </div>
      <strong className="shs-premium-page__page-number">
        Page {pageNumber} of {SHS_PREMIUM_INTERIOR_TEMPLATE.totalPages}
      </strong>
    </footer>
  );
}

export function ShsPremiumReportInteriorPage({
  report,
  pageNumber,
  title,
  subtitle,
  children,
  sidePanel,
}) {
  return (
    <article className="shs-premium-page" data-template-version={SHS_PREMIUM_INTERIOR_TEMPLATE.version}>
      <header className="shs-premium-page__header">
        <div>
          <ShsPoweredByOsBadge />
        </div>
        <div className="shs-premium-page__header-art" aria-hidden="true">
          <span />
          <span />
          <span />
        </div>
        <div className="shs-premium-page__motto">Command. Verify. Perform.</div>
      </header>

      <div className="shs-premium-page__divider" />

      <div className="shs-premium-page__content">
        <main className="shs-premium-page__main">
          <section className="shs-premium-page__title-block">
            <p className="shs-premium-page__template-name">{SHS_PREMIUM_INTERIOR_TEMPLATE.displayName}</p>
            <h1>{title}</h1>
            <p>{subtitle}</p>
            <span className="shs-premium-page__title-rule" aria-hidden="true" />
          </section>
          {children}
        </main>
        {sidePanel ? <aside className="shs-premium-page__side">{sidePanel}</aside> : null}
      </div>

      <ShsReportMetadataFooter report={report} pageNumber={pageNumber} />
    </article>
  );
}
