/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type RegistryEntity = AgentEntity | AppEntity;
export type AgentEntity = BaseEntity & {
  kind: "agent";
  agentId?: string;
};
export type LifecycleStatus = "active" | "deprecated" | "retired";
export type AppEntity = BaseEntity & {
  kind: "app";
  entry?: string;
  home?: string;
  capabilities?: string[];
};

export interface SHFRegistryEntityUpsertPayload {
  reason: string;
  entity: RegistryEntity;
}
export interface BaseEntity {
  kind: string;
  id: string;
  name: string;
  title?: string;
  layer: string;
  lifecycle: Lifecycle;
  policy?: Policy;
  legal: Legal;
}
export interface Lifecycle {
  status: LifecycleStatus;
}
export interface Policy {
  humanApproval?: boolean;
  maxSteps?: number;
  notes?: string;
  [k: string]: unknown;
}
export interface Legal {
  classification: string;
  /**
   * @minItems 1
   */
  dataCategory: [string, ...string[]];
  authority: Authority;
  jurisdiction: string;
  termsRef: string;
  disclaimerRef: string;
  retention: Retention;
  attestations: unknown[];
}
export interface Authority {
  approvedBy: string;
  basis: string;
  approvedAt?: string;
}
export interface Retention {
  artifactsDays: number;
  auditLogsDays: number;
  deletionPolicy: string;
}
