import React from "react";
import { ARCADE_RUNTIME_EVENT_TYPES, useArcadeRuntimeTelemetry } from "@/shared/arcade/runtime/useArcadeRuntimeTelemetry.js";
import { useArcadeRuntimeSaveState } from "@/shared/arcade/runtime/useArcadeRuntimeSaveState.js";
import { useArcadeRuntimeSession } from "@/shared/arcade/runtime/useArcadeRuntimeSession.js";
import "@/styles/arcade-runtime-dev.css";

const DEFAULT_SAVE = '{\n  "checkpoint": 1\n}';
const DEFAULT_EVENT_PAYLOAD = '{\n  "checkpoint": 1\n}';
const pretty = (value) => JSON.stringify(value, null, 2);

function parseObject(text, label) {
  let parsed;
  try { parsed = JSON.parse(text); } catch { throw new Error(`${label} must contain valid JSON.`); }
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error(`${label} must be a JSON object.`);
  return parsed;
}

function formatError(error) {
  return error ? `${error.code ? `${error.code}: ` : ""}${error.message}` : "";
}

export default function ArcadeRuntimeDevHarness() {
  const [lastResponse, setLastResponse] = React.useState(null);
  const [family, setFamily] = React.useState("classic");
  const [experienceId, setExperienceId] = React.useState("");
  const [activityId, setActivityId] = React.useState("");
  const [sessionType, setSessionType] = React.useState("game");
  const [idempotencyKey, setIdempotencyKey] = React.useState("");
  const [lookupId, setLookupId] = React.useState("");
  const [saveJson, setSaveJson] = React.useState(DEFAULT_SAVE);
  const [eventType, setEventType] = React.useState("CHECKPOINT_REACHED");
  const [eventJson, setEventJson] = React.useState(DEFAULT_EVENT_PAYLOAD);
  const [occurredAt, setOccurredAt] = React.useState(() => new Date().toISOString());
  const [formError, setFormError] = React.useState("");
  const onResponse = React.useCallback((response) => setLastResponse(response), []);
  const runtime = useArcadeRuntimeSession({ onResponse });
  const sessionId = runtime.session?.id || "";
  const saveState = useArcadeRuntimeSaveState(sessionId, { onResponse });
  const telemetry = useArcadeRuntimeTelemetry(sessionId, { onResponse });
  const status = runtime.session?.status;
  const terminal = ["COMPLETED", "ABANDONED", "EXPIRED"].includes(status);
  const serverError = runtime.error || saveState.error || telemetry.error;

  React.useEffect(() => {
    if (!sessionId) return;
    saveState.reload().catch(() => {});
    telemetry.reload().catch(() => {});
  }, [sessionId]);

  async function perform(action) {
    setFormError("");
    runtime.clearError();
    saveState.clearError();
    telemetry.clearError();
    try { return await action(); } catch (error) { setFormError(formatError(error)); return null; }
  }

  async function startSession(event) {
    event.preventDefault();
    if (!experienceId.trim()) {
      setFormError("Enter an experience ID. No identifier is generated by this harness.");
      return;
    }
    const body = {
      family,
      experienceId: experienceId.trim(),
      sessionType,
      ...(family === "learning" && activityId.trim() ? { activityId: activityId.trim() } : {}),
      ...(idempotencyKey.trim() ? { idempotencyKey: idempotencyKey.trim() } : {}),
    };
    const created = await perform(() => runtime.start(body));
    if (created?.id) setLookupId(created.id);
  }

  async function loadSession(event) {
    event.preventDefault();
    await perform(() => runtime.reload(lookupId.trim()));
  }

  async function savePayload(expectedRevision) {
    const saved = await perform(() => saveState.save(parseObject(saveJson, "Save state"), expectedRevision));
    if (saved?.payload) setSaveJson(pretty(saved.payload));
  }

  async function appendEvent(sequenceOverride) {
    const event = await perform(() => telemetry.append(
      eventType,
      parseObject(eventJson, "Telemetry payload"),
      occurredAt,
      sequenceOverride,
    ));
    if (event) setOccurredAt(new Date().toISOString());
  }

  return (
    <div className="ar-runtime-dev">
      <header className="ar-runtime-dev__header">
        <p className="ar-runtime-dev__eyebrow">DEVELOPMENT / TEST HARNESS</p>
        <h1>Arcade Runtime Console</h1>
        <p>Exercise authenticated runtime APIs. This console is not a game and does not create institutional outcomes.</p>
      </header>

      {(formError || serverError) && (
        <div className="ar-runtime-dev__alert" role="alert">
          <div>{serverError ? formatError(serverError) : formError}</div>
          {serverError?.status && <div>HTTP {serverError.status}</div>}
          {serverError?.correlationId && <div>Correlation ID: {serverError.correlationId}</div>}
          {serverError && Object.keys(serverError.details || {}).length > 0 &&
            <pre>{pretty(serverError.details)}</pre>}
        </div>
      )}

      <section className="ar-runtime-dev__section" aria-labelledby="runtime-session-heading">
        <h2 id="runtime-session-heading">Session Controls</h2>
        <form className="ar-runtime-dev__form" onSubmit={startSession}>
          <label>Family<select value={family} onChange={(event) => setFamily(event.target.value)}>
            <option value="classic">Classic</option><option value="learning">Learning</option>
          </select></label>
          <label>Experience ID<input value={experienceId} onChange={(event) => setExperienceId(event.target.value)} required /></label>
          {family === "learning" && <label>Canonical Arcade Activity ID (optional)
            <input value={activityId} onChange={(event) => setActivityId(event.target.value)} />
          </label>}
          <label>Session type<select value={sessionType} onChange={(event) => setSessionType(event.target.value)}>
            {["game", "simulation", "mission", "challenge", "practice"].map((type) => <option key={type}>{type}</option>)}
          </select></label>
          <label>Idempotency key (optional)<input value={idempotencyKey} onChange={(event) => setIdempotencyKey(event.target.value)} /></label>
          <button type="submit" disabled={runtime.busy}>Start Session</button>
        </form>
        <form className="ar-runtime-dev__inline-form" onSubmit={loadSession}>
          <label htmlFor="runtime-session-lookup">Load session ID</label>
          <input id="runtime-session-lookup" value={lookupId} onChange={(event) => setLookupId(event.target.value)} />
          <button type="submit" disabled={!lookupId.trim() || runtime.loading}>Load</button>
          <button type="button" onClick={() => perform(() => runtime.reload())} disabled={!sessionId || runtime.loading}>Reload</button>
        </form>
        {runtime.session && <dl className="ar-runtime-dev__facts">
          <div><dt>Session ID</dt><dd><code>{runtime.session.id}</code></dd></div>
          <div><dt>Status</dt><dd>{status}</dd></div>
          <div><dt>Family / type</dt><dd>{runtime.session.family} / {runtime.session.sessionType}</dd></div>
          <div><dt>Experience</dt><dd>{runtime.session.experienceId}</dd></div>
          <div><dt>Activity reference</dt><dd>{runtime.session.arcadeActivityId || "None"}</dd></div>
          <div><dt>Started</dt><dd>{runtime.session.startedAt}</dd></div>
          <div><dt>Last activity</dt><dd>{runtime.session.lastActivityAt}</dd></div>
          <div><dt>Version</dt><dd>{runtime.session.version}</dd></div>
        </dl>}
        <div className="ar-runtime-dev__actions" aria-label="Runtime session lifecycle">
          <button type="button" onClick={() => perform(runtime.pause)} disabled={status !== "ACTIVE" || runtime.busy}>Pause</button>
          <button type="button" onClick={() => perform(runtime.resume)} disabled={status !== "PAUSED" || runtime.busy}>Resume</button>
          <button type="button" onClick={() => perform(runtime.complete)} disabled={!['ACTIVE', 'PAUSED'].includes(status) || runtime.busy}>Complete Runtime</button>
          <button type="button" onClick={() => perform(runtime.abandon)} disabled={!['ACTIVE', 'PAUSED'].includes(status) || runtime.busy}>Abandon</button>
          {terminal && <span>Terminal sessions cannot be changed.</span>}
        </div>
      </section>

      <section className="ar-runtime-dev__section" aria-labelledby="runtime-save-heading">
        <h2 id="runtime-save-heading">Save State</h2>
        <p>Server-persisted continuity data. Revision <strong>{saveState.revision}</strong>; this is not verified progress.</p>
        <label htmlFor="runtime-save-json">JSON object</label>
        <textarea id="runtime-save-json" rows="7" spellCheck="false" value={saveJson} onChange={(event) => setSaveJson(event.target.value)} />
        <div className="ar-runtime-dev__actions">
          <button type="button" onClick={() => perform(saveState.reload)} disabled={!sessionId || saveState.loading}>Load Server State</button>
          <button type="button" onClick={() => savePayload(saveState.revision)} disabled={!sessionId || saveState.saving || terminal}>Save</button>
          <button type="button" onClick={() => savePayload(Math.max(0, saveState.revision - 1))} disabled={!sessionId || saveState.revision === 0 || saveState.saving || terminal}>Use Stale Revision</button>
        </div>
      </section>

      <section className="ar-runtime-dev__section" aria-labelledby="runtime-telemetry-heading">
        <h2 id="runtime-telemetry-heading">Runtime Telemetry</h2>
        <p>Allowlisted operational observations. Telemetry does not change session lifecycle or establish evidence.</p>
        <div className="ar-runtime-dev__form">
          <label>Event type<select value={eventType} onChange={(event) => setEventType(event.target.value)}>
            {ARCADE_RUNTIME_EVENT_TYPES.map((type) => <option key={type}>{type}</option>)}
          </select></label>
          <label>Next proposed sequence<input readOnly value={telemetry.nextSequence} /></label>
          <label>Occurred at (client time)<input value={occurredAt} onChange={(event) => setOccurredAt(event.target.value)} /></label>
          <label className="ar-runtime-dev__wide">Payload JSON
            <textarea rows="5" spellCheck="false" value={eventJson} onChange={(event) => setEventJson(event.target.value)} />
          </label>
        </div>
        <div className="ar-runtime-dev__actions">
          <button type="button" onClick={() => appendEvent()} disabled={!sessionId || telemetry.appending || status !== "ACTIVE"}>Append Event</button>
          <button type="button" onClick={() => perform(telemetry.reload)} disabled={!sessionId || telemetry.loading}>Reload Events</button>
          <button type="button" onClick={() => appendEvent(telemetry.events.at(-1)?.sequence)} disabled={!sessionId || telemetry.events.length === 0 || telemetry.appending || status !== "ACTIVE"}>Use Duplicate Sequence</button>
        </div>
        <div className="ar-runtime-dev__table-wrap">
          <table>
            <caption>Server-returned events in sequence order</caption>
            <thead><tr><th>Sequence</th><th>Type</th><th>Occurred at</th><th>Received at</th><th>Payload</th></tr></thead>
            <tbody>{telemetry.events.map((item) => <tr key={item.id}>
              <td>{item.sequence}</td><td>{item.eventType}</td><td>{item.occurredAt}</td><td>{item.serverReceivedAt}</td>
              <td><code>{pretty(item.payload)}</code></td>
            </tr>)}</tbody>
          </table>
          {!telemetry.events.length && <p>No runtime telemetry events loaded.</p>}
        </div>
      </section>

      <section className="ar-runtime-dev__authority" aria-labelledby="runtime-boundary-heading">
        <h2 id="runtime-boundary-heading">Authority Boundaries</h2>
        <ul>
          <li>Runtime Session preserves gameplay continuity.</li>
          <li>Save State is operational continuity data.</li>
          <li>Telemetry is a bounded operational observation.</li>
          <li>None establish mastery, Results, evidence, rewards, credentials, or Truth Spine facts.</li>
          <li>Runtime completion does not submit an Arcade Result.</li>
        </ul>
      </section>

      <details className="ar-runtime-dev__inspector">
        <summary>Last server response (no credential headers shown)</summary>
        <pre>{lastResponse ? pretty(lastResponse) : "No request made in this view."}</pre>
      </details>
    </div>
  );
}
