// Regression protection for the SHF Curriculum Phase 1 restoration
// (2026-08-25): reconnecting real, previously-orphaned Instructor/Master/
// AdminCompare/StudentUnit routes; repairing lesson media rendering
// (media.url/src, not the old media.embed that no real content ever used)
// via a normalized MediaRow path; wiring real lesson completion into the
// existing shared progressClient; and restoring reachable (but
// intentionally non-connecting) Zoom/live-session UI. See the SHF
// Curriculum / Zoom / Media Infrastructure Audit for full evidence.
import { test, expect } from "@playwright/test";

const BASE = "http://localhost:5173/curriculum.html";

// SHF Student Lesson Guided Experience — Phase 1 (2026-08-27): canonical
// student lessons (/curriculum/lessons/:slug) now render through a guided
// stage rail — media only mounts once the "Learn" stage is active. See
// the same helper/rationale in tests/ui/curriculum-phase2b-learning-
// experience.spec.mjs.
async function gotoStage(page, label) {
  await page.getByRole("tab", { name: label }).click();
}

test.describe("Curriculum: restored routes", () => {
  test.use({ viewport: { width: 1440, height: 900 } });

  test("student dashboard still loads (unaffected)", async ({ page }) => {
    const errors = [];
    page.on("pageerror", (e) => errors.push(String(e)));
    await page.goto(`${BASE}#/curriculum/asl/dashboard`, { waitUntil: "networkidle" });
    await expect(page.locator("body")).toContainText("Dashboard");
    expect(errors).toEqual([]);
  });

  test("instructor index loads with real units and real per-unit links", async ({ page }) => {
    await page.goto(`${BASE}#/curriculum/instructor`, { waitUntil: "networkidle" });
    await expect(page.locator("body")).toContainText("Instructor Guide");
    const links = page.locator("li a[href*='/curriculum/instructor/']");
    expect(await links.count()).toBeGreaterThan(0);
  });

  test("instructor lesson detail is reachable and renders real content", async ({ page }) => {
    await page.goto(`${BASE}#/curriculum/instructor`, { waitUntil: "networkidle" });
    const href = await page.locator("li a[href*='/curriculum/instructor/']").first().getAttribute("href");
    await page.goto(`http://localhost:5173/curriculum.html${href}`, { waitUntil: "networkidle" });
    await expect(page.locator("h1.h1")).not.toHaveText("");
  });

  test("master index loads and its own links are not dead", async ({ page }) => {
    await page.goto(`${BASE}#/curriculum/master`, { waitUntil: "networkidle" });
    await expect(page.locator("body")).toContainText("Master Index");
    const href = await page.locator("a[href*='/master/']").first().getAttribute("href");
    expect(href).toBeTruthy();
    await page.goto(`http://localhost:5173/curriculum.html${href}`, { waitUntil: "networkidle" });
    await expect(page.locator("body")).toContainText("Modules");
    await expect(page.locator("body")).not.toContainText("No master unit found");
  });

  test("Admin Compare loads via MasterUnit's own real link", async ({ page }) => {
    await page.goto(`${BASE}#/curriculum/master`, { waitUntil: "networkidle" });
    const masterHref = await page.locator("a[href*='/master/']").first().getAttribute("href");
    await page.goto(`http://localhost:5173/curriculum.html${masterHref}`, { waitUntil: "networkidle" });
    const adminHref = await page.getByRole("link", { name: "Admin Compare" }).getAttribute("href");
    await page.goto(`http://localhost:5173/curriculum.html${adminHref}`, { waitUntil: "networkidle" });
    await expect(page.locator("body")).toContainText("Admin Compare");
  });

  test("bare /:curriculum/... links (as generated by Master/Instructor/AdminCompare internally) bridge-redirect correctly", async ({ page }) => {
    await page.goto(`${BASE}#/asl/master`, { waitUntil: "networkidle" });
    await page.waitForURL(/\/curriculum\/master$/);
    await expect(page.locator("body")).toContainText("Master Index");

    await page.goto(`${BASE}#/asl/instructor`, { waitUntil: "networkidle" });
    await page.waitForURL(/\/curriculum\/instructor$/);
    await expect(page.locator("body")).toContainText("Instructor Guide");
  });

  test("invalid slugs fail gracefully, no crash", async ({ page }) => {
    const errors = [];
    page.on("pageerror", (e) => errors.push(String(e)));

    await page.goto(`${BASE}#/curriculum/master/does-not-exist-xyz`, { waitUntil: "networkidle" });
    await expect(page.locator("body")).toContainText("No master unit found");

    await page.goto(`${BASE}#/curriculum/instructor/does-not-exist-xyz`, { waitUntil: "networkidle" });
    await expect(page.locator("body")).toContainText(/not found/i);

    expect(errors).toEqual([]);
  });

  test("existing localStorage-backed student routes still work (unaffected)", async ({ page }) => {
    await page.goto(`${BASE}#/curriculum/lessons`, { waitUntil: "networkidle" });
    await expect(page.locator("body")).toContainText("My Lessons");
    await page.goto(`${BASE}#/curriculum/asl/calendar`, { waitUntil: "networkidle" });
    await expect(page.locator("body")).toBeVisible();
  });
});

test.describe("Media: repaired rendering", () => {
  test.use({ viewport: { width: 1440, height: 900 } });

  test("real canonical student lesson (StudentUnit) is now reachable", async ({ page }) => {
    await page.goto(`${BASE}#/curriculum/lessons/student.asl-01`, { waitUntil: "networkidle" });
    await expect(page.locator("body")).toContainText(/Fingerspelling|Alphabet/);
  });

  test("a lesson with real media.url attempts the correct field (not the old media.embed)", async ({ page }) => {
    const warnings = [];
    page.on("console", (m) => { if (m.type() === "warning") warnings.push(m.text()); });
    await page.goto(`${BASE}#/curriculum/lessons/student.asl-01`, { waitUntil: "networkidle" });
    await gotoStage(page, "Learn");
    await page.waitForTimeout(1200);
    expect(warnings.some((w) => w.includes("[MediaRow]") && w.includes("/media/asl/alphabet-drill.mp4"))).toBe(true);
  });

  test("missing media asset fails gracefully (no crash, no console error)", async ({ page }) => {
    const errors = [];
    page.on("pageerror", (e) => errors.push(String(e)));
    page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
    await page.goto(`${BASE}#/curriculum/lessons/student.asl-01`, { waitUntil: "networkidle" });
    await gotoStage(page, "Learn");
    await page.waitForTimeout(1200);
    await expect(page.locator(".sh-mediaUnavailable").first()).toBeVisible();
    expect(errors).toEqual([]);
  });

  test("a different real student lesson (image-based media) still loads", async ({ page }) => {
    await page.goto(`${BASE}#/curriculum/lessons/student.asl-11`, { waitUntil: "networkidle" });
    const body = await page.locator("body").innerText();
    expect(body.length).toBeGreaterThan(100);
  });

  test("mobile layout has no horizontal overflow with real media present", async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(`${BASE}#/curriculum/lessons/student.asl-01`, { waitUntil: "networkidle" });
    await gotoStage(page, "Learn");
    const overflow = await page.evaluate(() => document.body.scrollWidth > window.innerWidth + 1);
    expect(overflow).toBe(false);
  });
});

test.describe("Progress: wired to the shared progressClient", () => {
  test.use({ viewport: { width: 1440, height: 900 } });

  test("Mark as Complete writes a real record via progressClient.markLessonComplete", async ({ page }) => {
    await page.goto(`${BASE}#/curriculum/lessons/student.asl-01`, { waitUntil: "networkidle" });
    await page.evaluate(() => localStorage.removeItem("progress:records:v1"));
    await page.reload({ waitUntil: "networkidle" });

    // Fidelity-correction pass (2026-08-27): the Completion Check button's
    // visible label changed from reward-framed "Mark as Complete (+5)" to
    // "Mark Lesson Complete" (see CompletionCheckPanel.jsx) — the
    // underlying markLessonComplete() call this test actually guards is
    // unchanged.
    await page.getByRole("button", { name: /Mark Lesson Complete/ }).click();
    const stored = await page.evaluate(() => JSON.parse(localStorage.getItem("progress:records:v1") || "[]"));
    expect(stored.length).toBe(1);
    expect(stored[0].curriculum).toBe("asl");
    expect(stored[0].slug).toBe("student.asl-01");
    await expect(page.getByRole("button", { name: /Lesson Complete/ })).toBeVisible();
  });
});

test.describe("Zoom / Live Sessions: restored UI, no real connection", () => {
  test.use({ viewport: { width: 1440, height: 900 } });

  test("Live Sessions page is reachable from the sidebar and states honesty about connection status", async ({ page }) => {
    await page.goto(`${BASE}#/curriculum/asl/dashboard`, { waitUntil: "networkidle" });
    // Shared Footer Implementation pass (2026-08-27): the new
    // CurriculumFooter also links to Live Sessions, so an unscoped
    // locator is now ambiguous — scope to the sidebar nav specifically
    // (aria-label="Curriculum", distinct from the footer's
    // aria-label="Curriculum links").
    await page.getByLabel("Curriculum", { exact: true }).getByRole("link", { name: "Live Sessions" }).click();
    await expect(page.locator("body")).toContainText("Live Sessions");
    await expect(page.locator("body")).toContainText("pending secure connection");
  });

  test("request -> admin approve -> student sees approved, with no real external launch at any point", async ({ page }) => {
    await page.goto(`${BASE}#/curriculum/live-sessions`, { waitUntil: "networkidle" });
    await page.evaluate(() => {
      for (const k of Object.keys(localStorage)) if (k.startsWith("zoom:")) localStorage.removeItem(k);
    });
    await page.reload({ waitUntil: "networkidle" });

    await page.getByRole("button", { name: "Request access" }).click();
    const before = page.url();
    await page.getByRole("button", { name: "Check in for this session" }).click();
    expect(page.url()).toBe(before); // no navigation to any external/meeting URL

    await page.goto(`${BASE}#/curriculum/live-sessions/admin`, { waitUntil: "networkidle" });
    await expect(page.locator("body")).toContainText("Pending Approvals");
    await page.getByRole("button", { name: "Approve" }).first().click();

    await page.goto(`${BASE}#/curriculum/live-sessions`, { waitUntil: "networkidle" });
    await expect(page.locator("body")).toContainText("Approved");
  });

  test("admin access queue is reachable via the sidebar", async ({ page }) => {
    await page.goto(`${BASE}#/curriculum/asl/dashboard`, { waitUntil: "networkidle" });
    await page.getByRole("link", { name: "Live Session Access" }).click();
    await expect(page.locator("body")).toContainText("Zoom Access");
  });
});
