import type { DomainNextAction, OrientationActor, OrientationCatalogEntry, OrientationResolution, OrientationResolverHints, ResolverDependencies, ResolverState, ResolverSourceStatus } from "../model/orientation-resolver.js";

// Server-readable selection projection of the OGL-1 contracts. It contains
// only selection, source, and safe-target metadata; it never replaces the
// frontend contract definitions or any domain authority.
const SALES_ORIENTATION: OrientationCatalogEntry = { orientationId: "orientation:sales:pipeline", destinationId: "sales", owningService: "sales", version: 1, lifecycle: "ACTIVE", visibility: "ROLE_SCOPED", roles: ["client", "client_admin"], permissions: [], title: "Sales pipeline", purpose: "Understand sales follow-up and the next supported pipeline action.", tier: "TIER_B", tourId: "tour:sales:pipeline", accessibleAlternativeRef: { kind: "GUIDANCE_ARTICLE", id: "guidance:sales:pipeline-steps" }, dgalReferences: [], companionTopics: [], safeActions: { openPipeline: { destinationId: "sales", routeId: "sales.pipeline" } }, reorientation: { policy: "OPTIONAL", changeClassification: "TOUR_STEP" } };

export const SERVER_ORIENTATION_CATALOG: OrientationCatalogEntry[] = [
  { orientationId: "orientation:shs-bos:executive-command", destinationId: "shs-bos-executive-command", owningService: "shs-bos", version: 1, lifecycle: "ACTIVE", visibility: "ROLE_SCOPED", roles: ["shs_admin", "operator", "auditor"], permissions: ["audit.view"], title: "SHS BOS Executive Command", purpose: "Understand governed executive summaries and review priorities.", tier: "TIER_A", tourId: "tour:shs-bos:executive-command", accessibleAlternativeRef: { kind: "GUIDANCE_ARTICLE", id: "guidance:shs-bos:executive-command-steps" }, dgalReferences: [], companionTopics: ["executive summary", "review priorities", "governance boundaries"], safeActions: { openCommandCenter: { destinationId: "shs-bos-executive-command", routeId: "shs.bos.executive-command" } }, reorientation: { policy: "RECOMMENDED", changeClassification: "WORKFLOW_SIGNIFICANT" } },
  { orientationId: "orientation:hub:workspace", destinationId: "bos", owningService: "hub", version: 1, lifecycle: "ACTIVE", visibility: "ROLE_SCOPED", roles: ["instructor", "org_admin", "shs_admin"], permissions: [], title: "SHS Hub workspace", purpose: "Understand the Hub workspace and the next operational steps.", tier: "TIER_A", tourId: "hub:workspace", accessibleAlternativeRef: { kind: "GUIDANCE_ARTICLE", id: "guidance:hub:workspace-steps" }, dgalReferences: [], companionTopics: ["Hub workspace", "next operational step"], safeActions: { openWorkspace: { destinationId: "bos", routeId: "hub.workspace" } }, reorientation: { policy: "OPTIONAL", changeClassification: "TOUR_STEP" } },
  { orientationId: "orientation:curriculum:student-dashboard", destinationId: "curriculum", owningService: "curriculum", version: 1, lifecycle: "ACTIVE", visibility: "ROLE_SCOPED", roles: ["student"], permissions: ["assignment.view"], title: "Student learning workspace", purpose: "Understand your learning path and next assignment.", tier: "TIER_A", tourId: "tour:curriculum:student-dashboard", accessibleAlternativeRef: { kind: "GUIDANCE_ARTICLE", id: "guidance:curriculum:student-dashboard-steps" }, dgalReferences: [{ kind: "DGAL_GUIDANCE", id: "curriculum:student-dashboard" }], companionTopics: ["current assignment", "learning path"], safeActions: { openDestination: { destinationId: "curriculum", routeId: "curriculum.dashboard" } }, reorientation: { policy: "RECOMMENDED", changeClassification: "TOUR_STEP" } },
  { orientationId: "orientation:curriculum:instructor-operations", destinationId: "curriculum", owningService: "curriculum", version: 1, lifecycle: "ACTIVE", visibility: "ROLE_SCOPED", roles: ["instructor"], permissions: ["cohort.view", "assignment.view"], title: "Instructor operational workspace", purpose: "Understand cohort, assignment, and learner-progress work.", tier: "TIER_A", tourId: "tour:curriculum:instructor-operations", accessibleAlternativeRef: { kind: "GUIDANCE_ARTICLE", id: "guidance:curriculum:instructor-operations-steps" }, dgalReferences: [], companionTopics: ["cohort progress", "assignment review", "learner progress"], safeActions: { openWorkspace: { destinationId: "curriculum", routeId: "curriculum.instructor.operations" } }, reorientation: { policy: "RECOMMENDED", changeClassification: "WORKFLOW_SIGNIFICANT" } },
  { orientationId: "orientation:civicsure:operator", destinationId: "civic", owningService: "civicsure", version: 1, lifecycle: "ACTIVE", visibility: "ROLE_SCOPED", roles: ["operator", "reviewer_verifier"], permissions: ["verification.view"], title: "CivicSure operator review workspace", purpose: "Understand assurance review state and the next review step.", tier: "TIER_A", tourId: "tour:civicsure:operator", accessibleAlternativeRef: { kind: "GUIDANCE_ARTICLE", id: "guidance:civicsure:operator-steps" }, dgalReferences: [{ kind: "DGAL_GUIDANCE", id: "civicsure:operator:review" }], companionTopics: ["verification readiness", "review blockers", "provider evidence context"], safeActions: { openReviewQueue: { destinationId: "civic", routeId: "civicsure.operator.verification" } }, reorientation: { policy: "RECOMMENDED", changeClassification: "WORKFLOW_SIGNIFICANT" } },
  { orientationId: "orientation:civicsure:provider", destinationId: "civic", owningService: "civicsure", version: 1, lifecycle: "ACTIVE", visibility: "ROLE_SCOPED", roles: ["provider"], permissions: ["government.assurance.provider.self_service.view"], title: "CivicSure provider workspace", purpose: "Understand provider evidence work and what happens next.", tier: "TIER_A", tourId: "tour:civicsure:provider", accessibleAlternativeRef: { kind: "DGAL_GUIDANCE", id: "civicsure:provider:orientation" }, dgalReferences: [{ kind: "DGAL_GUIDANCE", id: "civicsure:provider:evidence" }, { kind: "DGAL_DOCUMENT", id: "civicsure:provider-packet" }], companionTopics: ["why evidence is required", "what happens after submission"], safeActions: { openWorkspace: { destinationId: "civic", routeId: "civicsure.provider.workspace" } }, reorientation: { policy: "RECOMMENDED", changeClassification: "WORKFLOW_SIGNIFICANT" } },
  { orientationId: "orientation:agent-fabric:operator", destinationId: "agent-fabric", owningService: "agent-fabric", version: 1, lifecycle: "ACTIVE", visibility: "ROLE_SCOPED", roles: ["operator", "reviewer"], permissions: ["audit.view", "ai.governance.view"], title: "Governed agent operations", purpose: "Understand policy, work orders, and human approval boundaries.", tier: "TIER_A", tourId: "tour:agent-fabric:operator", accessibleAlternativeRef: { kind: "DGAL_GUIDANCE", id: "agent-fabric:operator-boundaries" }, dgalReferences: [{ kind: "DGAL_GUIDANCE", id: "agent-fabric:operator-boundaries" }, { kind: "DGAL_DOCUMENT", id: "agent-fabric:controlled-pilot-packet" }], companionTopics: ["approved scope", "human approval"], safeActions: { openWorkspace: { destinationId: "agent-fabric", routeId: "agent-fabric.operator.workspace" } }, reorientation: { policy: "REQUIRED", changeClassification: "POLICY_RELATED" } },
  SALES_ORIENTATION,
  { orientationId: "orientation:career:learner", destinationId: "career", owningService: "career", version: 1, lifecycle: "DRAFT", visibility: "AUTHENTICATED", roles: ["student"], permissions: ["careerEvent.view"], title: "Career pathway workspace", purpose: "Find pathway guidance and the next career action.", tier: "TIER_B", tourId: "tour:career:learner", accessibleAlternativeRef: { kind: "GUIDANCE_ARTICLE", id: "guidance:career:pathway" }, dgalReferences: [{ kind: "DGAL_GUIDANCE", id: "career:pathway" }], companionTopics: ["pathway", "career readiness"], safeActions: { openWorkspace: { destinationId: "career", routeId: "career.dashboard" } }, reorientation: { policy: "OPTIONAL", changeClassification: "COPY_ONLY" } },
  { orientationId: "orientation:ogl-acceptance:cross-route", destinationId: "ogl-acceptance-cross-route", owningService: "ogl-acceptance", version: 1, lifecycle: "ACTIVE", visibility: "ROLE_SCOPED", roles: ["instructor"], permissions: [], title: "OGL route continuation acceptance", purpose: "Verify safe continuation between two development-only routes.", tier: "TIER_C", tourId: "ogl-acceptance:cross-route", accessibleAlternativeRef: { kind: "GUIDANCE_ARTICLE", id: "ogl-acceptance:cross-route-steps" }, dgalReferences: [], companionTopics: [], safeActions: { routeB: { destinationId: "ogl-acceptance-cross-route", routeId: "ogl.acceptance.route-b" } }, reorientation: { policy: "NONE", changeClassification: "COPY_ONLY" }, testOnly: true },
  { orientationId: "orientation:ogl-acceptance:delayed", destinationId: "ogl-acceptance-delayed-target", owningService: "ogl-acceptance", version: 1, lifecycle: "ACTIVE", visibility: "ROLE_SCOPED", roles: ["instructor"], permissions: [], title: "OGL delayed target acceptance", purpose: "Verify bounded readiness for a delayed semantic target.", tier: "TIER_C", tourId: "ogl-acceptance:delayed-target", accessibleAlternativeRef: { kind: "GUIDANCE_ARTICLE", id: "ogl-acceptance:delayed-target-steps" }, dgalReferences: [], companionTopics: [], safeActions: {}, reorientation: { policy: "NONE", changeClassification: "COPY_ONLY" }, testOnly: true },
];

export function isDevelopmentAcceptanceCatalogEnabled() {
  return String(process.env.SHS_AUTH_ENV || process.env.NODE_ENV || "development").toLowerCase() !== "production" && String(process.env.SHS_DEV_DATABASE_IDENTITY_ENABLED || "0") === "1";
}

function isCatalogVisible(contract: OrientationCatalogEntry) {
  return !contract.testOnly || isDevelopmentAcceptanceCatalogEnabled();
}

const CATEGORY_RANK: Record<ResolverState, number> = { BLOCKED: 0, REQUIRED: 1, WAITING: 2, OPTIONAL: 3, REFERENCE: 4, COMPLETED: 5 };
function activeOrganization(actor: OrientationActor) {
  const organizationId = String(actor.active_organization_id || actor.organization_id || "").trim();
  const tenantId = String(actor.tenant_id || "").trim();
  if (!actor.user_id || !organizationId || !tenantId || tenantId !== `tenant:${organizationId}`) throw new Error("ORG_CONTEXT_REQUIRED");
  return { organizationId, tenantId };
}
function matchesAudience(contract: OrientationCatalogEntry, actor: OrientationActor) {
  const roleMatch = contract.roles.length > 0 && contract.roles.some((role) => actor.roles.includes(role));
  const permissionMatch = contract.permissions.length > 0 && contract.permissions.some((permission) => actor.permissions.includes(permission));
  return (contract.roles.length === 0 && contract.permissions.length === 0) || roleMatch || permissionMatch;
}
function experienceLevel(hints: OrientationResolverHints) { return hints.experienceLevel || (hints.priorOrientationVersion ? "RETURNING" : "NEW"); }
function reorientation(contract: OrientationCatalogEntry, priorVersion?: number) {
  const changed = Number.isInteger(priorVersion) && Number(priorVersion) < contract.version;
  return { policy: changed ? contract.reorientation.policy : "NONE", priorVersion: Number.isInteger(priorVersion) ? Number(priorVersion) : null, currentVersion: contract.version, changed, changeClassification: changed ? contract.reorientation.changeClassification : null };
}
function sortActions(actions: DomainNextAction[]) { return [...actions].sort((a, b) => (CATEGORY_RANK[a.state] - CATEGORY_RANK[b.state]) || ((a.priority ?? 100) - (b.priority ?? 100)) || a.id.localeCompare(b.id)); }
function toChecklist(actions: DomainNextAction[]) { return sortActions(actions).slice(0, 8).map((action) => ({ ...action, category: action.state, completionSource: action.source.sourceDomain === "DGAL" ? "DGAL_REQUIREMENT" : "DOMAIN_STATE" })); }
function deduplicateGuidance(items: any[]) {
  const selected = new Map<string, any>();
  for (const item of items) {
    const key = item.canonicalKey || item.guidanceId || item.sourceId || item.id || item.title;
    const current = selected.get(key);
    if (!current || (item.priority ?? 100) < (current.priority ?? 100)) selected.set(key, item);
    else if (current.sourceReferences && item.sourceReferences) current.sourceReferences = [...new Set([...current.sourceReferences, ...item.sourceReferences])];
  }
  return [...selected.values()].sort((a, b) => ((a.priority ?? 100) - (b.priority ?? 100)) || String(a.guidanceId || a.sourceId || a.id || "").localeCompare(String(b.guidanceId || b.sourceId || b.id || ""))).slice(0, 12);
}

export class OrientationContextService {
  constructor(private readonly catalog: OrientationCatalogEntry[] = SERVER_ORIENTATION_CATALOG) {}
  async resolve(actor: OrientationActor, hints: OrientationResolverHints = {}, dependencies: ResolverDependencies): Promise<OrientationResolution> {
    const scope = activeOrganization(actor);
    const destinationId = String(hints.destinationId || "").trim();
    const routeId = hints.routeId ? String(hints.routeId).trim() : null;
    const sourceStatus: Record<string, ResolverSourceStatus> = { authorization: "AVAILABLE", orientation: "AVAILABLE", dgal: "UNAVAILABLE", nextActions: "NOT_APPLICABLE", companion: "AVAILABLE" };
    if (!destinationId) return this.unavailable(actor, scope, hints, "NOT_FOUND", sourceStatus);
    const candidates = this.catalog.filter((contract) => isCatalogVisible(contract) && contract.destinationId === destinationId && contract.lifecycle === "ACTIVE");
    if (!candidates.length) return this.unavailable(actor, scope, hints, "NOT_FOUND", sourceStatus);
    // Route identity disambiguates authorized role variants sharing a
    // destination; it never grants access by itself.
    const routeCandidates = routeId ? candidates.filter((candidate) => Object.values(candidate.safeActions).some((target) => target.routeId === routeId)) : [];
    const orderedCandidates = [...routeCandidates, ...candidates].filter((candidate, index, list) => list.findIndex((item) => item.orientationId === candidate.orientationId) === index);
    const contract = orderedCandidates.find((candidate) => matchesAudience(candidate, actor));
    if (!contract) return this.unavailable(actor, scope, hints, "FORBIDDEN", sourceStatus);
    const context = { ...scope, destinationId, routeId, serviceKey: contract.owningService, requestedServiceKey: hints.serviceKey || null, workflowType: hints.workflowType || null, workflowStage: hints.workflowStage || null, resourceType: hints.resourceType || null, resourceId: hints.resourceId || null };
    let dgal: any = { status: "UNKNOWN", items: [], unavailableSources: ["dgal"], unresolved: ["dgal:not_loaded"] };
    try { dgal = await dependencies.resolveDgal(actor, context); sourceStatus.dgal = dgal.status === "UNKNOWN" || dgal.status === "SOURCE_UNAVAILABLE" ? "UNAVAILABLE" : "AVAILABLE"; } catch { sourceStatus.dgal = "UNAVAILABLE"; }
    let nextActions: DomainNextAction[] = [];
    if (dependencies.resolveNextActions) { try { nextActions = sortActions(await dependencies.resolveNextActions(actor, context)); sourceStatus.nextActions = "AVAILABLE"; } catch { sourceStatus.nextActions = "PARTIAL"; } }
    const actionGuidance = nextActions.map((item) => ({ ...item, guidanceId: item.id, sourceReferences: [item.source.sourceId], canonicalKey: item.id }));
    const combinedGuidance = deduplicateGuidance([...(dgal.items || []), ...actionGuidance]);
    const reorientationState = reorientation(contract, hints.priorOrientationVersion);
    if (reorientationState.changed && reorientationState.policy !== "NONE") combinedGuidance.unshift({ guidanceId: `reorientation:${contract.orientationId}`, title: "What's changed", explanation: `This orientation changed from version ${reorientationState.priorVersion} to ${reorientationState.currentVersion}.`, category: reorientationState.policy === "REQUIRED" ? "REQUIRED_NOW" : "OPTIONAL", required: reorientationState.policy === "REQUIRED", priority: -1, sourceReferences: [contract.orientationId], actionTarget: contract.safeActions.openWorkspace });
    const partial = Object.values(sourceStatus).includes("UNAVAILABLE") || Object.values(sourceStatus).includes("PARTIAL");
    const dgalChecklist = (dgal.items || []).map((item: any) => ({ id: item.guidanceId, title: item.title, explanation: item.explanation, state: item.category === "BLOCKED" ? "BLOCKED" : item.category === "WAITING_ON_SOMEONE_ELSE" ? "WAITING" : item.required ? "REQUIRED" : "OPTIONAL", responsibility: item.actorResponsibility, source: { sourceId: item.guidanceId, sourceDomain: item.sourceDomain }, actionTarget: item.actionTarget, required: item.required, priority: item.priority } as DomainNextAction));
    const presentation = hints.priorOrientationVersion === undefined ? "FIRST_TIME_ORIENTATION" : reorientationState.changed ? "REORIENTATION" : "CONTEXTUAL_GUIDANCE";
    return { status: partial ? "PARTIAL" : "RESOLVED", context: { actorId: actor.user_id, organizationId: scope.organizationId, tenantId: scope.tenantId, destinationId, routeId, serviceKey: String(context.serviceKey || ""), workflowType: context.workflowType, workflowStage: context.workflowStage, experienceLevel: experienceLevel(hints) }, orientation: { orientationId: contract.orientationId, version: contract.version, title: contract.title, purpose: contract.purpose, tourId: contract.tourId, accessibleAlternativeRef: contract.accessibleAlternativeRef, companionTopics: contract.companionTopics, safeActions: contract.safeActions, source: { sourceId: contract.orientationId, sourceDomain: "OGL" }, presentation }, contextualGuidance: combinedGuidance, checklist: toChecklist([...nextActions, ...dgalChecklist]), documentation: { references: contract.dgalReferences, status: sourceStatus.dgal }, companion: { enabled: true, suggestedTopics: contract.companionTopics, status: sourceStatus.companion }, nextActions, reorientation: reorientationState, sourceStatus, trace: { orientationId: contract.orientationId, orientationVersion: contract.version, sources: ["OGL", ...(dgal.items || []).map((item: any) => item.sourceDomain || "DGAL"), ...nextActions.map((item) => item.source.sourceDomain)] } };
  }
  private unavailable(actor: OrientationActor, scope: { organizationId: string; tenantId: string }, hints: OrientationResolverHints, status: "NOT_FOUND" | "FORBIDDEN", sourceStatus: Record<string, ResolverSourceStatus>): OrientationResolution {
    return { status, context: { actorId: actor.user_id, organizationId: scope.organizationId, tenantId: scope.tenantId, destinationId: String(hints.destinationId || ""), routeId: hints.routeId || null, serviceKey: hints.serviceKey || null, workflowType: hints.workflowType || null, workflowStage: hints.workflowStage || null, experienceLevel: experienceLevel(hints) }, orientation: null, contextualGuidance: [], checklist: [], documentation: { references: [], status: "NOT_APPLICABLE" }, companion: { enabled: false, suggestedTopics: [], status: "NOT_APPLICABLE" }, nextActions: [], reorientation: { policy: "NONE", priorVersion: hints.priorOrientationVersion || null, currentVersion: null, changed: false, changeClassification: null }, sourceStatus, trace: { orientationId: null, orientationVersion: null, sources: [] } };
  }
}
