import { query } from "../../../db/client.js";
export type Executor = { query: (sql: string, params?: unknown[]) => Promise<any> };
const json = (value: unknown) => JSON.stringify(value ?? {});
export class FundingLineageRepo {
  constructor(private dbQuery: typeof query = query) {}
  private executor(executor?: Executor): Executor { return executor || { query: this.dbQuery }; }
  async createReference(input: any, executor?: Executor) { const r = await this.executor(executor).query(`INSERT INTO gpa_funding_references (funding_reference_id,organization_id,tenant_id,canonical_record_type,canonical_record_id,funder_organization_reference,recipient_organization_reference,provider_organization_reference,program_reference,jurisdiction_reference,amount,currency,period_start,period_end,status,source_system_id,source_record_id,provenance_reference,supersedes_reference_id,created_by,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21) RETURNING *`, [input.funding_reference_id,input.organization_id,input.tenant_id,input.canonical_record_type,input.canonical_record_id,input.funder_organization_reference,input.recipient_organization_reference,input.provider_organization_reference,input.program_reference,input.jurisdiction_reference,input.amount,input.currency,input.period_start,input.period_end,input.status || "REPORTED",input.source_system_id,input.source_record_id,input.provenance_reference,input.supersedes_reference_id,input.created_by,json(input.metadata)]); return r.rows[0]; }
  async listReferences(scope: any, executor?: Executor) { return (await this.executor(executor).query("SELECT * FROM gpa_funding_references WHERE organization_id=$1 AND tenant_id=$2 ORDER BY created_at DESC", [scope.organizationId,scope.tenantId])).rows; }
  async createEdge(input: any, executor?: Executor) { const r = await this.executor(executor).query(`INSERT INTO gpa_funding_lineage_edges (lineage_edge_id,organization_id,tenant_id,from_type,from_reference,to_type,to_reference,relationship_type,amount,currency,allocation_method_reference,period_start,period_end,source_system_id,source_record_id,provenance_reference,status,created_by,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19) RETURNING *`, [input.lineage_edge_id,input.organization_id,input.tenant_id,input.from_type,input.from_reference,input.to_type,input.to_reference,input.relationship_type,input.amount,input.currency,input.allocation_method_reference,input.period_start,input.period_end,input.source_system_id,input.source_record_id,input.provenance_reference,input.status || "ACTIVE",input.created_by,json(input.metadata)]); return r.rows[0]; }
  async listEdges(scope: any, filter: any = {}, executor?: Executor) { const params = [scope.organizationId,scope.tenantId]; let sql = "SELECT * FROM gpa_funding_lineage_edges WHERE organization_id=$1 AND tenant_id=$2 AND status='ACTIVE'"; if (filter.reference) { params.push(filter.reference); sql += ` AND (from_reference=$${params.length} OR to_reference=$${params.length})`; } return (await this.executor(executor).query(`${sql} ORDER BY created_at`, params)).rows; }
  async createProviderProjection(input: any, executor?: Executor) { const r = await this.executor(executor).query(`INSERT INTO gpa_provider_assurance_projections (projection_id,organization_id,tenant_id,provider_organization_reference,summary,source_references,provenance) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (organization_id,tenant_id,provider_organization_reference) DO UPDATE SET generated_at=NOW(),summary=EXCLUDED.summary,source_references=EXCLUDED.source_references,provenance=EXCLUDED.provenance RETURNING *`, [input.projection_id,input.organization_id,input.tenant_id,input.provider_organization_reference,json(input.summary),json(input.source_references),json(input.provenance)]); return r.rows[0]; }
  async createProgramProjection(input: any, executor?: Executor) { const r = await this.executor(executor).query(`INSERT INTO gpa_program_assurance_projections (projection_id,organization_id,tenant_id,program_reference,summary,source_references,provenance) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (organization_id,tenant_id,program_reference) DO UPDATE SET generated_at=NOW(),summary=EXCLUDED.summary,source_references=EXCLUDED.source_references,provenance=EXCLUDED.provenance RETURNING *`, [input.projection_id,input.organization_id,input.tenant_id,input.program_reference,json(input.summary),json(input.source_references),json(input.provenance)]); return r.rows[0]; }
}
