import { query } from "../../../db/client.js";
import { randomUUID } from "node:crypto";
import { writeAuditEvent } from "../../audit/service/audit-helper.js";
export type Executor = { query: (sql: string, params?: unknown[]) => Promise<any> };
const json = (v: unknown) => JSON.stringify(v ?? {});
export class MonitoringAuditRepo {
  constructor(private dbQuery: typeof query = query, private auditWriter: typeof writeAuditEvent | null = null) {}
  private e(x?: Executor): Executor { return x || { query: this.dbQuery }; }
  private targetType(table: string) { return table.replace(/^gpa_/, "GPA_").replace(/s$/, "").toUpperCase(); }
  private async audit(table: string, action: string, previous: any, next: any) { if (!this.auditWriter || !next?.organization_id || !next?.created_by) return; const ids: Record<string,string> = { gpa_requirements: "requirement_id", gpa_controls: "control_id", gpa_monitoring_plans: "monitoring_plan_id", gpa_monitoring_activities: "activity_id", gpa_evidence_requests: "evidence_request_id", gpa_findings: "finding_id", gpa_provider_responses: "response_id", gpa_corrective_actions: "corrective_action_id", gpa_audit_engagements: "audit_engagement_id", gpa_audit_workpapers: "workpaper_id", gpa_samples: "sample_id", gpa_sample_results: "sample_result_id", gpa_investigations: "investigation_id", gpa_recovery_cases: "recovery_case_id", gpa_decisions: "decision_id", gpa_control_executions: "control_execution_id" }; const targetId=next[ids[table]]; if (!targetId) return; await this.auditWriter({ audit_event_id: `gpa_monitoring_repo_${randomUUID()}`, organization_id: next.organization_id, actor_user_id: next.created_by, target_object_type: this.targetType(table), target_object_id: String(targetId), action_type: action, previous_state_json: previous, new_state_json: next, reason_code: null, correlation_id: `gpa_monitoring_repo_${randomUUID()}`, source_channel: "government_assurance" }); }
  async insert(table: string, fields: Record<string, any>, x?: Executor) { const names = Object.keys(fields); const values = names.map((n) => fields[n]); const sql = `INSERT INTO ${table} (${names.join(",")}) VALUES (${names.map((_, i) => `$${i + 1}`).join(",")}) RETURNING *`; const r = await this.e(x).query(sql, values); await this.audit(table, "CREATED", null, r.rows[0]); return r.rows[0]; }
  async list(table: string, s: any, x?: Executor) { return (await this.e(x).query(`SELECT * FROM ${table} WHERE organization_id=$1 AND tenant_id=$2`, [s.organizationId, s.tenantId])).rows; }
  async get(table: string, idField: string, id: string, s: any, x?: Executor) { return (await this.e(x).query(`SELECT * FROM ${table} WHERE ${idField}=$1 AND organization_id=$2 AND tenant_id=$3`, [id, s.organizationId, s.tenantId])).rows[0] || null; }
  async effectiveRequirement(requirementId: string, at: string | Date, s: any, x?: Executor) { return (await this.e(x).query("SELECT * FROM gpa_requirements WHERE requirement_id=$1 AND organization_id=$2 AND tenant_id=$3 AND effective_from<= $4 AND (effective_to IS NULL OR effective_to>$4) AND status='ACTIVE' ORDER BY version DESC LIMIT 1", [requirementId, s.organizationId, s.tenantId, at])).rows[0] || null; }
  async history(targetType: string, targetId: string, s: any, x?: Executor) { return (await this.e(x).query("SELECT * FROM audit_events WHERE organization_id=$1 AND target_object_type=$2 AND target_object_id=$3 ORDER BY event_timestamp ASC, created_at ASC", [s.organizationId, targetType, targetId])).rows; }
  async update(table: string, idField: string, id: string, s: any, fields: Record<string, any>, x?: Executor) { const executor=this.e(x); const prior=(await executor.query(`SELECT * FROM ${table} WHERE ${idField}=$1 AND organization_id=$2 AND tenant_id=$3`,[id,s.organizationId,s.tenantId])).rows[0]||null; const names = Object.keys(fields); const values = names.map((n) => fields[n]); const r = await executor.query(`UPDATE ${table} SET ${names.map((n, i) => `${n}=$${i + 4}`).join(",")} WHERE ${idField}=$1 AND organization_id=$2 AND tenant_id=$3 RETURNING *`, [id,s.organizationId,s.tenantId,...values]); const next=r.rows[0]||null; if(next) await this.audit(table, "UPDATED", prior, next); return next; }
  static json = json;
}
