import { query } from "../../../db/client.js";
export type Executor = { query: (sql: string, params?: unknown[]) => Promise<any> };
const json = (value: unknown) => JSON.stringify(value ?? {});
export class ReconciliationQualityRepo {
  constructor(private dbQuery: typeof query = query) {}
  private e(executor?: Executor): Executor { return executor || { query: this.dbQuery }; }
  async createCase(i: any, x?: Executor) { const r = await this.e(x).query(`INSERT INTO gpa_reconciliation_cases (reconciliation_case_id,organization_id,tenant_id,subject_type,subject_reference,competing_source_references,competing_claim_references,conflict_reason,source_authority_references,status,created_by,metadata,conflict_type,conflicting_record_references,current_authority_ranking,materiality,severity,assigned_reviewer,opened_at,resolution_method,rationale,supersedes_case_id,downstream_impact_references,provenance) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24) RETURNING *`, [i.reconciliation_case_id,i.organization_id,i.tenant_id,i.subject_type,i.subject_reference,json(i.competing_source_references),json(i.competing_claim_references),i.conflict_reason,json(i.source_authority_references),i.status,i.created_by,json(i.metadata),i.conflict_type,json(i.conflicting_record_references),json(i.current_authority_ranking),i.materiality,i.severity,i.assigned_reviewer,i.opened_at,i.resolution_method,i.rationale,i.supersedes_case_id,json(i.downstream_impact_references),json(i.provenance)]); return r.rows[0]; }
  async listCases(s: any, x?: Executor) { return (await this.e(x).query("SELECT * FROM gpa_reconciliation_cases WHERE organization_id=$1 AND tenant_id=$2 ORDER BY opened_at DESC", [s.organizationId,s.tenantId])).rows; }
  async getCase(id: string, s: any, x?: Executor) { return (await this.e(x).query("SELECT * FROM gpa_reconciliation_cases WHERE reconciliation_case_id=$1 AND organization_id=$2 AND tenant_id=$3", [id,s.organizationId,s.tenantId])).rows[0] || null; }
  async listDuplicates(s: any, x?: Executor) { return (await this.e(x).query("SELECT * FROM gpa_duplicate_candidates WHERE organization_id=$1 AND tenant_id=$2 ORDER BY created_at DESC", [s.organizationId,s.tenantId])).rows; }
  async getDuplicate(id: string, s: any, x?: Executor) { return (await this.e(x).query("SELECT * FROM gpa_duplicate_candidates WHERE duplicate_candidate_id=$1 AND organization_id=$2 AND tenant_id=$3", [id,s.organizationId,s.tenantId])).rows[0] || null; }
  async listSchemaObservations(s: any, x?: Executor) { return (await this.e(x).query("SELECT * FROM gpa_schema_observations WHERE organization_id=$1 AND tenant_id=$2 ORDER BY detected_at DESC", [s.organizationId,s.tenantId])).rows; }
  async getSchemaObservation(id: string, s: any, x?: Executor) { return (await this.e(x).query("SELECT * FROM gpa_schema_observations WHERE observation_id=$1 AND organization_id=$2 AND tenant_id=$3", [id,s.organizationId,s.tenantId])).rows[0] || null; }
  async listRejectedRecords(s: any, x?: Executor) { return (await this.e(x).query("SELECT * FROM gpa_rejected_records WHERE organization_id=$1 AND tenant_id=$2 ORDER BY rejected_at DESC", [s.organizationId,s.tenantId])).rows; }
  async getRejectedRecord(id: string, s: any, x?: Executor) { return (await this.e(x).query("SELECT * FROM gpa_rejected_records WHERE rejected_record_id=$1 AND organization_id=$2 AND tenant_id=$3", [id,s.organizationId,s.tenantId])).rows[0] || null; }
  async determineCase(id: string, s: any, i: any, x?: Executor) { const r = await this.e(x).query("UPDATE gpa_reconciliation_cases SET status=$4,reviewer_reference=$5,authority_reference=$6,determination=$7,resolved_at=NOW(),resolution_method=$8,rationale=$9,downstream_impact_references=$10,provenance=$11 WHERE reconciliation_case_id=$1 AND organization_id=$2 AND tenant_id=$3 RETURNING *", [id,s.organizationId,s.tenantId,i.status,i.reviewer_reference,i.authority_reference,json(i.determination),i.resolution_method,i.rationale,json(i.downstream_impact_references),json(i.provenance)]); return r.rows[0] || null; }
  async createQualityRule(i: any, x?: Executor) { const r = await this.e(x).query(`INSERT INTO gpa_data_quality_rules (rule_id,version,organization_id,tenant_id,source_system_id,data_domain,record_type,dimension,severity,logic_reference,effective_from,effective_to,status,owner_reference,approval_reference,provenance,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) RETURNING *`, [i.rule_id,i.version,i.organization_id,i.tenant_id,i.source_system_id,i.data_domain,i.record_type,i.dimension,i.severity,i.logic_reference,i.effective_from,i.effective_to,i.status,i.owner_reference,i.approval_reference,json(i.provenance),i.created_by]); return r.rows[0]; }
  async listQualityRules(s: any, x?: Executor) { return (await this.e(x).query("SELECT * FROM gpa_data_quality_rules WHERE organization_id=$1 AND tenant_id=$2 ORDER BY rule_id,version DESC", [s.organizationId,s.tenantId])).rows; }
  async createQualityEvaluation(i: any, x?: Executor) { const r = await this.e(x).query(`INSERT INTO gpa_data_quality_evaluations (quality_evaluation_id,organization_id,tenant_id,source_system_id,subject_type,subject_reference,dimension,rule_id,rule_version,state,score,reason_codes,evaluated_by,provenance) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) RETURNING *`, [i.quality_evaluation_id,i.organization_id,i.tenant_id,i.source_system_id,i.subject_type,i.subject_reference,i.dimension,i.rule_id,i.rule_version,i.state,i.score,json(i.reason_codes),i.evaluated_by,json(i.provenance)]); return r.rows[0]; }
  async listQualityEvaluations(s: any, x?: Executor) { return (await this.e(x).query("SELECT * FROM gpa_data_quality_evaluations WHERE organization_id=$1 AND tenant_id=$2 ORDER BY evaluated_at DESC", [s.organizationId,s.tenantId])).rows; }
  async createEntityResolution(i: any, x?: Executor) { const r = await this.e(x).query(`INSERT INTO gpa_entity_resolution_cases (resolution_id,organization_id,tenant_id,entity_type,source_system_id,source_record_id,candidate_entity_references,match_method,match_attributes,confidence,status,reviewer_reference,determination,provenance,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *`, [i.resolution_id,i.organization_id,i.tenant_id,i.entity_type,i.source_system_id,i.source_record_id,json(i.candidate_entity_references),i.match_method,json(i.match_attributes),i.confidence,i.status,i.reviewer_reference,json(i.determination),json(i.provenance),i.created_by]); return r.rows[0]; }
  async listEntityResolutions(s: any, x?: Executor) { return (await this.e(x).query("SELECT * FROM gpa_entity_resolution_cases WHERE organization_id=$1 AND tenant_id=$2 ORDER BY created_at DESC", [s.organizationId,s.tenantId])).rows; }
  async determineEntity(id: string, s: any, i: any, x?: Executor) { const r = await this.e(x).query("UPDATE gpa_entity_resolution_cases SET status=$4,reviewer_reference=$5,determination=$6,resolved_at=NOW() WHERE resolution_id=$1 AND organization_id=$2 AND tenant_id=$3 RETURNING *", [id,s.organizationId,s.tenantId,i.status,i.reviewer_reference,json(i.determination)]); return r.rows[0] || null; }
  async createDuplicate(i: any, x?: Executor) { const r = await this.e(x).query(`INSERT INTO gpa_duplicate_candidates (duplicate_candidate_id,organization_id,tenant_id,subject_type,left_reference,right_reference,classification,reconciliation_case_id,evidence_references,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT (organization_id,tenant_id,subject_type,left_reference,right_reference) DO UPDATE SET classification=EXCLUDED.classification,reconciliation_case_id=EXCLUDED.reconciliation_case_id,evidence_references=EXCLUDED.evidence_references RETURNING *`, [i.duplicate_candidate_id,i.organization_id,i.tenant_id,i.subject_type,i.left_reference,i.right_reference,i.classification,i.reconciliation_case_id,json(i.evidence_references),i.created_by]); return r.rows[0]; }
  async createSchemaObservation(i: any, x?: Executor) { const r = await this.e(x).query(`INSERT INTO gpa_schema_observations (observation_id,organization_id,tenant_id,source_system_id,observed_schema_version,observed_signature,expected_mapping_version,drift_classification,affected_mapping_references,status,remediation_reference,provenance,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`, [i.observation_id,i.organization_id,i.tenant_id,i.source_system_id,i.observed_schema_version,i.observed_signature,i.expected_mapping_version,i.drift_classification,json(i.affected_mapping_references),i.status,i.remediation_reference,json(i.provenance),i.created_by]); return r.rows[0]; }
  async createRejectedRecord(i: any, x?: Executor) { const r = await this.e(x).query(`INSERT INTO gpa_rejected_records (rejected_record_id,organization_id,tenant_id,source_system_id,source_record_id,batch_reference,rule_id,failure_reason,remediation_status,provenance,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`, [i.rejected_record_id,i.organization_id,i.tenant_id,i.source_system_id,i.source_record_id,i.batch_reference,i.rule_id,i.failure_reason,i.remediation_status,json(i.provenance),i.created_by]); return r.rows[0]; }
}
