from __future__ import annotations

from services.extension_kernel.constants import (
    APPROVAL_TYPES,
    CAPABILITY_TYPES,
    EVENT_TYPES,
    KERNEL_SCHEMA_VERSION,
    LIFECYCLE_STATES,
    TRUST_LEVELS,
    ExtensionApprovalType,
    ExtensionCapabilityType,
    ExtensionEventType,
    ExtensionLifecycleState,
    ExtensionTrustLevel,
)
from services.extension_kernel.diagnostics import diagnostics_for_manifest
from services.extension_kernel.errors import (
    ExtensionKernelCompatibilityError,
    ExtensionKernelError,
    ExtensionKernelRegistrationError,
    ExtensionKernelValidationError,
)
from services.extension_kernel.events import define_event, event_catalog
from services.extension_kernel.lifecycle import allowed_next_states, can_transition, require_transition
from services.extension_kernel.models import (
    ExtensionActivationRequest,
    ExtensionApprovalRequest,
    ExtensionCapabilityContract,
    ExtensionConfiguration,
    ExtensionDependency,
    ExtensionDescriptor,
    ExtensionHealth,
    ExtensionKernelEvent,
    ExtensionKernelIssue,
    ExtensionKernelResult,
    ExtensionManifest,
    ExtensionMetadata,
    ExtensionRegistrationRecord,
    ExtensionRollbackMetadata,
    ExtensionSecurityContract,
)
from services.extension_kernel.owner_onboarding import (
    OWNER_ONBOARDING_CONTRACT_VERSION,
    OWNER_ONBOARDING_EVIDENCE_CONTRACT,
    OWNER_ONBOARDING_FAILURE_CODES,
    OWNER_ONBOARDING_REGISTRATION_VERSION,
    OwnerCapabilityDeclaration,
    OwnerDependencyDeclaration,
    OwnerOnboardingDeclaration,
    manifest_for_owner_declaration,
    onboarding_evidence,
    register_owner_declaration,
    registration_record_for_owner_declaration,
    validate_owner_declaration,
)
from services.extension_kernel.registry import InMemoryExtensionRegistry
from services.extension_kernel.runtime_owner_closure import (
    AUTHORIZED_ACCEPTANCE_CRITERIA,
    AUTHORIZED_BATCH_03_CAPABILITIES,
    AUTHORIZED_EVIDENCE_REQUIREMENTS,
    DETERMINISTIC_EVIDENCE_STATE,
    RUNTIME_OWNER_CLOSURE_CONTRACT_VERSION,
    RUNTIME_OWNER_CLOSURE_EVIDENCE_CONTRACT,
    RUNTIME_OWNER_CLOSURE_FAILURE_CODES,
    EvidenceEnvelopeInput,
    IntegrationBoundaryRequest,
    RuntimeMinimalismRequest,
    evaluate_integration_boundary,
    evaluate_owner_activation_readiness,
    evaluate_runtime_minimalism,
    produce_evidence_trust_envelope,
)
from services.extension_kernel.serialization import require_json_object, to_json, to_plain_dict
from services.extension_kernel.utilities import is_stable_identifier, normalize_labels
from services.extension_kernel.validation import validate_manifest
from services.extension_kernel.versioning import SemanticVersion, is_compatible_version, is_deprecated, parse_semantic_version

__all__ = [
    "APPROVAL_TYPES",
    "CAPABILITY_TYPES",
    "EVENT_TYPES",
    "KERNEL_SCHEMA_VERSION",
    "LIFECYCLE_STATES",
    "TRUST_LEVELS",
    "ExtensionActivationRequest",
    "ExtensionApprovalRequest",
    "ExtensionApprovalType",
    "ExtensionCapabilityContract",
    "ExtensionCapabilityType",
    "ExtensionConfiguration",
    "ExtensionDependency",
    "ExtensionDescriptor",
    "ExtensionEventType",
    "ExtensionHealth",
    "ExtensionKernelCompatibilityError",
    "ExtensionKernelError",
    "ExtensionKernelEvent",
    "ExtensionKernelIssue",
    "ExtensionKernelRegistrationError",
    "ExtensionKernelResult",
    "ExtensionKernelValidationError",
    "ExtensionLifecycleState",
    "ExtensionManifest",
    "ExtensionMetadata",
    "ExtensionRegistrationRecord",
    "ExtensionRollbackMetadata",
    "ExtensionSecurityContract",
    "ExtensionTrustLevel",
    "InMemoryExtensionRegistry",
    "OWNER_ONBOARDING_CONTRACT_VERSION",
    "OWNER_ONBOARDING_EVIDENCE_CONTRACT",
    "OWNER_ONBOARDING_FAILURE_CODES",
    "OWNER_ONBOARDING_REGISTRATION_VERSION",
    "OwnerCapabilityDeclaration",
    "OwnerDependencyDeclaration",
    "OwnerOnboardingDeclaration",
    "AUTHORIZED_ACCEPTANCE_CRITERIA",
    "AUTHORIZED_BATCH_03_CAPABILITIES",
    "AUTHORIZED_EVIDENCE_REQUIREMENTS",
    "SemanticVersion",
    "DETERMINISTIC_EVIDENCE_STATE",
    "EvidenceEnvelopeInput",
    "IntegrationBoundaryRequest",
    "RUNTIME_OWNER_CLOSURE_CONTRACT_VERSION",
    "RUNTIME_OWNER_CLOSURE_EVIDENCE_CONTRACT",
    "RUNTIME_OWNER_CLOSURE_FAILURE_CODES",
    "RuntimeMinimalismRequest",
    "allowed_next_states",
    "can_transition",
    "define_event",
    "diagnostics_for_manifest",
    "evaluate_integration_boundary",
    "evaluate_owner_activation_readiness",
    "evaluate_runtime_minimalism",
    "event_catalog",
    "is_compatible_version",
    "is_deprecated",
    "is_stable_identifier",
    "manifest_for_owner_declaration",
    "normalize_labels",
    "onboarding_evidence",
    "parse_semantic_version",
    "produce_evidence_trust_envelope",
    "register_owner_declaration",
    "registration_record_for_owner_declaration",
    "require_json_object",
    "require_transition",
    "to_json",
    "to_plain_dict",
    "validate_owner_declaration",
    "validate_manifest",
]
