import { query } from "../../../db/client.js";

export type Executor = { query: (sql: string, params?: unknown[]) => Promise<any> };

export class AragRepo {
  constructor(private dbQuery: typeof query = query) {}
  async createReleaseRequest(input: any, db: Executor = { query: this.dbQuery }) { return (await db.query(`INSERT INTO arag_release_requests (release_request_id,organization_id,tenant_id,project_id,delivery_record_id,workspace_revision,package_hash,repository_reference,provider_key,target_environment,requested_by,acting_agent_identifier,agent_session_id,delegation_id,work_order_reference,authority_purpose,model_provider,model_identifier,policy_decision,qa_run_id,review_submission_id,review_decision_id,simulation_id,subject_hash,status,blocking_codes) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,'CREATED','[]') RETURNING *`, [input.release_request_id,input.organization_id,input.tenant_id,input.project_id,input.delivery_record_id,input.workspace_revision,input.package_hash,input.repository_reference,input.provider_key,input.target_environment,input.requested_by,input.acting_agent_identifier || null,input.agent_session_id || null,input.delegation_id || null,input.work_order_reference,input.authority_purpose || null,input.model_provider || null,input.model_identifier || null,input.policy_decision || "UNKNOWN",input.qa_run_id,input.review_submission_id,input.review_decision_id,input.simulation_id,input.subject_hash])).rows[0]; }
  async getReleaseRequest(id: string, organizationId: string, tenantId: string, db: Executor = { query: this.dbQuery }) { return (await db.query("SELECT * FROM arag_release_requests WHERE release_request_id=$1 AND organization_id=$2 AND tenant_id=$3", [id, organizationId, tenantId])).rows[0] || null; }
  async listReleaseRequests(organizationId: string, tenantId: string, db: Executor = { query: this.dbQuery }) { return (await db.query("SELECT * FROM arag_release_requests WHERE organization_id=$1 AND tenant_id=$2 ORDER BY created_at DESC", [organizationId, tenantId])).rows; }
  async updateStatus(input: any, db: Executor = { query: this.dbQuery }) { return (await db.query("UPDATE arag_release_requests SET status=$4,blocking_codes=$5,updated_at=NOW() WHERE release_request_id=$1 AND organization_id=$2 AND tenant_id=$3 RETURNING *", [input.release_request_id,input.organization_id,input.tenant_id,input.status,JSON.stringify(input.blocking_codes || [])])).rows[0] || null; }
  async updatePolicyDecision(input: any, db: Executor = { query: this.dbQuery }) { return (await db.query("UPDATE arag_release_requests SET policy_decision=$4,policy_version=$5,policy_provenance=$6,updated_at=NOW() WHERE release_request_id=$1 AND organization_id=$2 AND tenant_id=$3 RETURNING *", [input.release_request_id,input.organization_id,input.tenant_id,input.policy_decision,input.policy_version || null,JSON.stringify(input.policy_provenance || {})])).rows[0] || null; }
  async getActiveWorkOrderPolicy(reference: string, organizationId: string, tenantId: string, db: Executor = { query: this.dbQuery }) { return (await db.query("SELECT * FROM arag_work_order_policies WHERE work_order_reference=$1 AND organization_id=$2 AND tenant_id=$3 ORDER BY policy_version DESC LIMIT 1", [reference, organizationId, tenantId])).rows[0] || null; }
  async getAssuranceInputs(request: any, db: Executor = { query: this.dbQuery }) {
    const [qa, review, simulation, approval, security] = await Promise.all([
      db.query("SELECT * FROM studio_qa_runs WHERE qa_run_id=$1 AND project_id=$2 AND organization_id=$3 AND tenant_id=$4", [request.qa_run_id, request.project_id, request.organization_id, request.tenant_id]),
      db.query("SELECT s.*,d.decision,d.reviewed_by_user_id,d.reviewed_at FROM studio_review_submissions s LEFT JOIN studio_review_decisions d ON d.review_submission_id=s.review_submission_id WHERE s.review_submission_id=$1 AND s.project_id=$2 AND s.organization_id=$3 AND s.tenant_id=$4", [request.review_submission_id, request.project_id, request.organization_id, request.tenant_id]),
      db.query("SELECT * FROM ai_agent_simulations WHERE simulation_id=$1 AND organization_id=$2 AND tenant_id=$3", [request.simulation_id, request.organization_id, request.tenant_id]),
      db.query("SELECT * FROM arag_release_approvals WHERE release_request_id=$1 AND organization_id=$2 AND tenant_id=$3 AND (expires_at IS NULL OR expires_at > NOW()) ORDER BY created_at DESC LIMIT 1", [request.release_request_id, request.organization_id, request.tenant_id]),
      db.query("SELECT 1 FROM ai_input_security_scans WHERE organization_id=$1 AND tenant_id=$2 AND scan_status IN ('BLOCKED','QUARANTINED','REVIEW_REQUIRED') LIMIT 1", [request.organization_id, request.tenant_id]),
    ]);
    return { qa: qa.rows[0] || null, review: review.rows[0] || null, simulation: simulation.rows[0] || null, approval: approval.rows[0] || null, securityBlocked: Boolean(security.rows[0]) };
  }
  async createApproval(input: any, db: Executor = { query: this.dbQuery }) { return (await db.query("INSERT INTO arag_release_approvals (approval_id,release_request_id,organization_id,tenant_id,subject_hash,approver_user_id,decision,rationale,expires_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *", [input.approval_id,input.release_request_id,input.organization_id,input.tenant_id,input.subject_hash,input.approver_user_id,input.decision,input.rationale || "",input.expires_at || new Date(Date.now() + 15 * 60 * 1000)])).rows[0]; }
  async getAuthorization(id: string, organizationId: string, tenantId: string, db: Executor = { query: this.dbQuery }) { return (await db.query("SELECT * FROM arag_release_authorizations WHERE authorization_id=$1 AND organization_id=$2 AND tenant_id=$3", [id, organizationId, tenantId])).rows[0] || null; }
  async createAuthorization(input: any, db: Executor = { query: this.dbQuery }) { return (await db.query("INSERT INTO arag_release_authorizations (authorization_id,release_request_id,organization_id,tenant_id,subject_hash,provider_key,target_environment,authorized_by,valid_from,expires_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,NOW(),$9) RETURNING *", [input.authorization_id,input.release_request_id,input.organization_id,input.tenant_id,input.subject_hash,input.provider_key,input.target_environment,input.authorized_by,input.expires_at])).rows[0]; }
  async revokeAuthorization(id: string, organizationId: string, tenantId: string, db: Executor = { query: this.dbQuery }) { return (await db.query("UPDATE arag_release_authorizations SET revoked_at=NOW() WHERE authorization_id=$1 AND organization_id=$2 AND tenant_id=$3 AND used_at IS NULL AND revoked_at IS NULL RETURNING *", [id, organizationId, tenantId])).rows[0] || null; }
  async claimAuthorization(id: string, organizationId: string, tenantId: string, db: Executor = { query: this.dbQuery }) { return (await db.query("UPDATE arag_release_authorizations SET used_at=NOW() WHERE authorization_id=$1 AND organization_id=$2 AND tenant_id=$3 AND used_at IS NULL AND revoked_at IS NULL AND expires_at > NOW() RETURNING *", [id, organizationId, tenantId])).rows[0] || null; }
  async createResult(input: any, db: Executor = { query: this.dbQuery }) { return (await db.query("INSERT INTO arag_release_results (release_result_id,release_request_id,authorization_id,organization_id,tenant_id,provider_key,provider_release_id,target_environment,subject_hash,status,started_at,completed_at,failure_code,failure_message,rollback_available,rollback_status,response_metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) RETURNING *", [input.release_result_id,input.release_request_id,input.authorization_id || null,input.organization_id,input.tenant_id,input.provider_key,input.provider_release_id || null,input.target_environment,input.subject_hash,input.status,input.started_at,input.completed_at || null,input.failure_code || null,input.failure_message || null,input.rollback_available === true,input.rollback_status || null,JSON.stringify(input.response_metadata || {})])).rows[0]; }
  async getLatestResult(releaseRequestId: string, organizationId: string, tenantId: string, db: Executor = { query: this.dbQuery }) { return (await db.query("SELECT * FROM arag_release_results WHERE release_request_id=$1 AND organization_id=$2 AND tenant_id=$3 ORDER BY created_at DESC LIMIT 1", [releaseRequestId, organizationId, tenantId])).rows[0] || null; }
  async updateResult(input: any, db: Executor = { query: this.dbQuery }) { return (await db.query("UPDATE arag_release_results SET status=$4,rollback_status=$5,completed_at=NOW(),response_metadata=$6 WHERE release_result_id=$1 AND organization_id=$2 AND tenant_id=$3 RETURNING *", [input.release_result_id,input.organization_id,input.tenant_id,input.status,input.rollback_status || null,JSON.stringify(input.response_metadata || {})])).rows[0] || null; }
  async createPacket(input: any, db: Executor = { query: this.dbQuery }) { return (await db.query("INSERT INTO arag_assurance_packets (packet_id,release_request_id,organization_id,tenant_id,packet_version,packet_hash,packet_json) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *", [input.packet_id,input.release_request_id,input.organization_id,input.tenant_id,input.packet_version || 1,input.packet_hash,JSON.stringify(input.packet_json)])).rows[0]; }
  async getPacket(id: string, organizationId: string, tenantId: string, db: Executor = { query: this.dbQuery }) { return (await db.query("SELECT * FROM arag_assurance_packets WHERE packet_id=$1 AND organization_id=$2 AND tenant_id=$3", [id, organizationId, tenantId])).rows[0] || null; }
  async getLatestPacket(releaseRequestId: string, organizationId: string, tenantId: string, db: Executor = { query: this.dbQuery }) { return (await db.query("SELECT * FROM arag_assurance_packets WHERE release_request_id=$1 AND organization_id=$2 AND tenant_id=$3 ORDER BY packet_version DESC LIMIT 1", [releaseRequestId, organizationId, tenantId])).rows[0] || null; }
}
