import { query } from "../../../db/client.js";

export type Executor = { query: (sql: string, params?: unknown[]) => Promise<any> };

export class OperationalAwarenessRepo {
  constructor(private dbQuery: typeof query = query) {}

  async collectSignals(organizationId: string, tenantId: string, start: Date, executor: Executor = { query: this.dbQuery }) {
    const [security, approvals, agentExceptions, reads, outcomes, activity, operations, releases] = await Promise.all([
      executor.query(`SELECT scan_id, resource_type, resource_id, scan_status, decision, risk_level, finding_count, created_at FROM ai_input_security_scans WHERE organization_id=$1 AND tenant_id=$2 AND created_at >= $3 AND scan_status IN ('BLOCKED','QUARANTINED','REVIEW_REQUIRED','SUSPICIOUS') ORDER BY created_at DESC LIMIT 50`, [organizationId, tenantId, start]),
      executor.query(`SELECT conductor_task_id, conductor_request_id, description, capability, status, approval_reason, created_at FROM bos_conductor_tasks WHERE organization_id=$1 AND tenant_id=$2 AND created_at >= $3 AND status IN ('APPROVAL_REQUIRED','BLOCKED','DENIED') ORDER BY created_at DESC LIMIT 50`, [organizationId, tenantId, start]),
      executor.query(`SELECT authority_code, security_code, COUNT(*)::int AS count, MAX(created_at) AS last_seen FROM mcp_invocations WHERE organization_id=$1 AND tenant_id=$2 AND created_at >= $3 AND status IN ('DENIED','SECURITY_DENIED') GROUP BY authority_code, security_code ORDER BY count DESC LIMIT 50`, [organizationId, tenantId, start]),
      executor.query(`SELECT mcp_read_result_id, mcp_server_id, mcp_tool_id, admission_status, source_identity, created_at FROM mcp_read_results WHERE organization_id=$1 AND tenant_id=$2 AND created_at >= $3 ORDER BY created_at DESC LIMIT 50`, [organizationId, tenantId, start]),
      executor.query(`SELECT truth_fact_id, fact_type, source_type, source_record_id, occurred_at FROM curriculum_truth_facts WHERE organization_id=$1 AND occurred_at >= $2 ORDER BY occurred_at DESC LIMIT 50`, [organizationId, start]),
      executor.query(`SELECT COUNT(*)::int AS simulation_count, COUNT(*) FILTER (WHERE status IN ('DENIED','FAILED'))::int AS failed_count, MAX(created_at) AS last_activity FROM ai_agent_activity_ledger WHERE organization_id=$1 AND tenant_id=$2 AND created_at >= $3`, [organizationId, tenantId, start]),
      executor.query(`SELECT COUNT(*) FILTER (WHERE ps.status IN ('SUBMITTED','NEEDS_REVISION'))::int AS review_count, COUNT(*) FILTER (WHERE a.due_at < NOW() AND a.status NOT IN ('cancelled','retired'))::int AS overdue_assignment_count FROM organizations o LEFT JOIN project_submissions ps ON ps.organization_id=o.organization_id LEFT JOIN assignments a ON a.organization_id=o.organization_id WHERE o.organization_id=$1`, [organizationId]),
      executor.query(`SELECT release_request_id, project_id, workspace_revision, status, blocking_codes, updated_at FROM arag_release_requests WHERE organization_id=$1 AND tenant_id=$2 AND updated_at >= $3 AND status IN ('BLOCKED','QA_REQUIRED','REVIEW_REQUIRED','APPROVAL_REQUIRED','FAILED','ROLLBACK_REQUIRED','RELEASED','ROLLED_BACK') ORDER BY updated_at DESC LIMIT 50`, [organizationId, tenantId, start]),
    ]);
    return { security: security.rows, approvals: approvals.rows, agentExceptions: agentExceptions.rows, reads: reads.rows, outcomes: outcomes.rows, activity: activity.rows[0] || {}, operations: operations.rows[0] || {}, releases: releases.rows };
  }

  async createFinding(input: any, executor: Executor = { query: this.dbQuery }) { return (await executor.query(`INSERT INTO operational_awareness_findings (finding_id,organization_id,tenant_id,dedupe_key,finding_type,category,severity,priority,title,summary,source_type,source_refs,evidence_refs,truth_refs,metric_refs,external_source_refs,confidence,verification_class,first_observed_at,last_observed_at,status,generated_by,metadata_json) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,NOW(),NOW(),'OPEN',$19,$20) ON CONFLICT (organization_id,tenant_id,dedupe_key) DO UPDATE SET summary=EXCLUDED.summary,last_observed_at=NOW(),severity=EXCLUDED.severity,priority=EXCLUDED.priority,title=EXCLUDED.title,source_refs=EXCLUDED.source_refs,updated_at=NOW() RETURNING *`, [input.finding_id,input.organization_id,input.tenant_id,input.dedupe_key,input.finding_type,input.category,input.severity,input.priority,input.title,input.summary,input.source_type,JSON.stringify(input.source_refs || []),JSON.stringify(input.evidence_refs || []),JSON.stringify(input.truth_refs || []),JSON.stringify(input.metric_refs || []),JSON.stringify(input.external_source_refs || []),input.confidence ?? null,input.verification_class,input.generated_by || "deterministic-awareness-v1",JSON.stringify(input.metadata_json || {})])).rows[0]; }
  async listFindings(organizationId: string, tenantId: string, status?: string, executor: Executor = { query: this.dbQuery }) { return (await executor.query(`SELECT * FROM operational_awareness_findings WHERE organization_id=$1 AND tenant_id=$2 AND ($3::text IS NULL OR status=$3) ORDER BY CASE priority WHEN 'URGENT' THEN 1 WHEN 'HIGH' THEN 2 WHEN 'NORMAL' THEN 3 ELSE 4 END, last_observed_at DESC`, [organizationId, tenantId, status || null])).rows; }
  async getFinding(findingId: string, organizationId: string, tenantId: string, executor: Executor = { query: this.dbQuery }) { return (await executor.query(`SELECT * FROM operational_awareness_findings WHERE finding_id=$1 AND organization_id=$2 AND tenant_id=$3`, [findingId, organizationId, tenantId])).rows[0] || null; }
  async updateFindingStatus(input: any, executor: Executor = { query: this.dbQuery }) { return (await executor.query(`UPDATE operational_awareness_findings SET status=$4,acknowledged_at=CASE WHEN $4='ACKNOWLEDGED' THEN NOW() ELSE acknowledged_at END,acknowledged_by=CASE WHEN $4='ACKNOWLEDGED' THEN $5 ELSE acknowledged_by END,resolved_at=CASE WHEN $4 IN ('RESOLVED','DISMISSED') THEN NOW() ELSE resolved_at END,resolved_by=CASE WHEN $4 IN ('RESOLVED','DISMISSED') THEN $5 ELSE resolved_by END,updated_at=NOW() WHERE finding_id=$1 AND organization_id=$2 AND tenant_id=$3 RETURNING *`, [input.finding_id,input.organization_id,input.tenant_id,input.status,input.actor_id])).rows[0] || null; }
  async createBrief(input: any, executor: Executor = { query: this.dbQuery }) { return (await executor.query(`INSERT INTO daily_operating_briefs (brief_id,organization_id,tenant_id,reporting_period_start,reporting_period_end,generated_for,source_window,finding_refs,verified_outcome_refs,agent_activity_refs,external_observation_refs,brief_json,version) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`, [input.brief_id,input.organization_id,input.tenant_id,input.reporting_period_start,input.reporting_period_end,input.generated_for,JSON.stringify(input.source_window),JSON.stringify(input.finding_refs || []),JSON.stringify(input.verified_outcome_refs || []),JSON.stringify(input.agent_activity_refs || []),JSON.stringify(input.external_observation_refs || []),JSON.stringify(input.brief_json),input.version || 1])).rows[0]; }
  async getLatestBrief(organizationId: string, tenantId: string, executor: Executor = { query: this.dbQuery }) { return (await executor.query(`SELECT * FROM daily_operating_briefs WHERE organization_id=$1 AND tenant_id=$2 ORDER BY generated_at DESC,version DESC LIMIT 1`, [organizationId, tenantId])).rows[0] || null; }
  async getBrief(briefId: string, organizationId: string, tenantId: string, executor: Executor = { query: this.dbQuery }) { return (await executor.query(`SELECT * FROM daily_operating_briefs WHERE brief_id=$1 AND organization_id=$2 AND tenant_id=$3`, [briefId, organizationId, tenantId])).rows[0] || null; }
  async listBriefs(organizationId: string, tenantId: string, executor: Executor = { query: this.dbQuery }) { return (await executor.query(`SELECT * FROM daily_operating_briefs WHERE organization_id=$1 AND tenant_id=$2 ORDER BY generated_at DESC,version DESC`, [organizationId, tenantId])).rows; }
}
