export const METAVERSE_CAMERA_LEVELS = [
  "CITY_OVERVIEW",
  "DISTRICT_VIEW",
  "FACILITY_VIEW",
  "ACTIVITY_SIMULATION_VIEW",
];

export const METAVERSE_VISUAL_ASSET_STATUSES = [
  "READY",
  "NEEDS_CLEAN_VERSION",
  "REFERENCE_ONLY",
  "MISSING",
];

export const METAVERSE_IMAGE_ROLES = [
  "PRODUCTION_BACKGROUND",
  "REFERENCE_ONLY",
  "OVERLAY_ONLY",
];

export const METAVERSE_TARGET_ASSET_ROOT = "public/assets/metaverse";

export const METAVERSE_VISUAL_STYLE_LOCK = {
  mood: "premium institutional-futuristic Silicon Heartland civic technology environment",
  lighting: "dusk and sunset, dark navy base, electric blue identity light, warm amber/orange public-realm light",
  materialLanguage: "clean modern glass, stone, metal, solar, transit, data-center infrastructure, landscaped plazas",
  exclusions: [
    "cartoon aesthetic",
    "generic sci-fi fantasy",
    "cyberpunk decay",
    "cluttered dashboard look",
    "prominent people baked into production backgrounds",
    "dynamic live-state UI baked into images",
  ],
};

export const METAVERSE_OVERLAY_LAYERS = [
  {
    id: "environment",
    label: "Environment Layer",
    responsibility: "Background scene image or future 3D scene only.",
  },
  {
    id: "navigation",
    label: "Navigation Layer",
    responsibility: "District markers, facility markers, waypoints, camera controls, and breadcrumbs.",
  },
  {
    id: "presence",
    label: "Presence Layer",
    responsibility: "Online students, nearby users, team presence, instructor/moderator presence, and group markers.",
  },
  {
    id: "activity",
    label: "Activity Layer",
    responsibility: "Tasks, learning activities, job simulations, civic sessions, arcade challenges, and opportunities.",
  },
  {
    id: "system",
    label: "System Layer",
    responsibility: "Notifications, accessibility controls, help, safety/reporting controls, and session state.",
  },
];

export const METAVERSE_IMAGE_ROLE_RULES = {
  PRODUCTION_BACKGROUND: {
    allowed: ["world/environment pixels", "static place identity signage", "architectural district context"],
    prohibited: [
      "prominent people",
      "baked dashboard UI",
      "dynamic names",
      "online counts",
      "chat content",
      "task status",
      "live notification state",
      "fake opportunities",
      "fake credentials",
    ],
  },
  REFERENCE_ONLY: {
    allowed: ["people", "mock UI", "concept interactions", "visual mood references"],
    prohibited: ["live-state authority", "credential authority", "production dynamic state"],
  },
  OVERLAY_ONLY: {
    allowed: ["presence", "chat", "labels", "tasks", "opportunities", "camera controls", "accessibility controls"],
    prohibited: ["baked into production background images"],
  },
};

export const METAVERSE_PRODUCTION_BACKGROUND_SET = [
  {
    assetId: "met-city-master-overview",
    city: "silicon-heartland-city",
    district: null,
    facility: null,
    cameraLevel: "CITY_OVERVIEW",
    useCase: "Primary city entry, map/list hybrid overview, district selection.",
    sourceFilename: "ChatGPT Image Sep 14, 2026, 10_05_24 PM (1).png",
    targetFilename: "silicon-heartland-city-master-overview.png",
    targetPath: "public/assets/metaverse/city/silicon-heartland-city-master-overview.png",
    status: "READY",
    peopleFree: true,
    productionBackground: true,
    referenceOnly: false,
    containsMockDashboardUi: false,
    notes: "Approved people-free master city overview copied into canonical asset root.",
  },
  {
    assetId: "met-district-civic",
    city: "silicon-heartland-city",
    district: "civic-district",
    facility: null,
    cameraLevel: "DISTRICT_VIEW",
    useCase: "Civic District view with City Hall, council, planning, and civic-session waypoints.",
    sourceFilename: "ChatGPT Image Sep 14, 2026, 09_39_15 PM (3).png",
    targetFilename: "civic-district-city-hall-plaza.png",
    targetPath: "public/assets/metaverse/districts/civic-district-city-hall-plaza.png",
    status: "READY",
    peopleFree: true,
    productionBackground: true,
    referenceOnly: false,
    containsMockDashboardUi: false,
    notes: "Approved people-free district background copied into canonical asset root.",
  },
  {
    assetId: "met-district-career-education",
    city: "silicon-heartland-city",
    district: "career-education-district",
    facility: null,
    cameraLevel: "DISTRICT_VIEW",
    useCase: "Career & Education district view with university, pathway, portfolio, and learning center waypoints.",
    sourceFilename: "ChatGPT Image Sep 14, 2026, 09_39_14 PM (1).png",
    targetFilename: "career-education-district-university-overview.png",
    targetPath: "public/assets/metaverse/districts/career-education-district-university-overview.png",
    status: "READY",
    peopleFree: true,
    productionBackground: true,
    referenceOnly: false,
    containsMockDashboardUi: false,
    notes: "Approved people-free Career & Education/University background copied into canonical asset root.",
  },
  {
    assetId: "met-district-data-center",
    city: "silicon-heartland-city",
    district: "data-center-district",
    facility: null,
    cameraLevel: "DISTRICT_VIEW",
    useCase: "Data Center District view with main data center and training facility drill-down.",
    sourceFilename: "ChatGPT Image Sep 14, 2026, 09_39_15 PM (4).png",
    targetFilename: "data-center-district-overview.png",
    targetPath: "public/assets/metaverse/districts/data-center-district-overview.png",
    status: "READY",
    peopleFree: true,
    productionBackground: true,
    referenceOnly: false,
    containsMockDashboardUi: false,
    notes: "Approved people-free Data Center District background copied into canonical asset root.",
  },
  {
    assetId: "met-district-learning-arcade",
    city: "silicon-heartland-city",
    district: "learning-arcade-district",
    facility: null,
    cameraLevel: "DISTRICT_VIEW",
    useCase: "Learning Arcade district view with challenge hub and simulation entrances.",
    sourceFilename: "ChatGPT Image Sep 14, 2026, 09_39_15 PM (2).png",
    targetFilename: "learning-arcade-district-portal-plaza.png",
    targetPath: "public/assets/metaverse/districts/learning-arcade-district-portal-plaza.png",
    status: "READY",
    peopleFree: true,
    productionBackground: true,
    referenceOnly: false,
    containsMockDashboardUi: false,
    notes: "Approved people-free Learning Arcade background copied into canonical asset root.",
  },
  {
    assetId: "met-district-treasury-commerce",
    city: "silicon-heartland-city",
    district: "treasury-commerce-district",
    facility: null,
    cameraLevel: "DISTRICT_VIEW",
    useCase: "Treasury & Commerce district visual slot; projection-only economy navigation.",
    sourceFilename: "ChatGPT Image Sep 14, 2026, 10_12_27 PM (2).png",
    targetFilename: "treasury-commerce-district-overview.png",
    targetPath: "public/assets/metaverse/districts/treasury-commerce-district-overview.png",
    status: "READY",
    peopleFree: true,
    productionBackground: true,
    referenceOnly: false,
    containsMockDashboardUi: false,
    notes: "Approved people-free Treasury & Commerce district background copied into canonical asset root.",
  },
  {
    assetId: "met-district-technology-innovation",
    city: "silicon-heartland-city",
    district: "technology-innovation-district",
    facility: null,
    cameraLevel: "DISTRICT_VIEW",
    useCase: "Technology & Innovation district with OAS, AI/agent, Builder/Studio, and innovation lab waypoints.",
    sourceFilename: "ChatGPT Image Sep 14, 2026, 09_39_16 PM (5).png",
    targetFilename: "technology-innovation-district-overview.png",
    targetPath: "public/assets/metaverse/districts/technology-innovation-district-overview.png",
    status: "READY",
    peopleFree: true,
    productionBackground: true,
    referenceOnly: false,
    containsMockDashboardUi: false,
    notes: "Approved people-free Technology & Innovation background copied into canonical asset root.",
  },
  {
    assetId: "met-district-community",
    city: "silicon-heartland-city",
    district: "community-district",
    facility: null,
    cameraLevel: "DISTRICT_VIEW",
    useCase: "Community District view with learning commons, health/wellness, public programs, and food/community waypoints.",
    sourceFilename: "ChatGPT Image Sep 14, 2026, 09_39_16 PM (6).png",
    targetFilename: "community-district-public-realm.png",
    targetPath: "public/assets/metaverse/districts/community-district-public-realm.png",
    status: "READY",
    peopleFree: true,
    productionBackground: true,
    referenceOnly: false,
    containsMockDashboardUi: false,
    notes: "Approved people-free Community District background copied into canonical asset root.",
  },
  {
    assetId: "met-district-student-life",
    city: "silicon-heartland-city",
    district: "student-life-district",
    facility: null,
    cameraLevel: "DISTRICT_VIEW",
    useCase: "Residential / Student Life district with student hub, commons, wellness, profile/portfolio access, and safe social placeholders.",
    sourceFilename: "ChatGPT Image Sep 14, 2026, 09_39_17 PM (7).png",
    targetFilename: "student-life-district-overview.png",
    targetPath: "public/assets/metaverse/districts/student-life-district-overview.png",
    status: "READY",
    peopleFree: true,
    productionBackground: true,
    referenceOnly: false,
    containsMockDashboardUi: false,
    notes: "Approved people-free Student Life background copied into canonical asset root.",
  },
  {
    assetId: "met-district-public-realm",
    city: "silicon-heartland-city",
    district: "public-realm",
    facility: null,
    cameraLevel: "DISTRICT_VIEW",
    useCase: "Central public realm, orientation, wayfinding, events, and gathering nodes.",
    sourceFilename: "ChatGPT Image Sep 14, 2026, 09_39_17 PM (8).png",
    targetFilename: "public-realm-civic-plaza.png",
    targetPath: "public/assets/metaverse/districts/public-realm-civic-plaza.png",
    status: "READY",
    peopleFree: true,
    productionBackground: true,
    referenceOnly: false,
    containsMockDashboardUi: false,
    notes: "Approved people-free Public Realm background copied into canonical asset root.",
  },
  {
    assetId: "met-facility-northstar-data-center",
    city: "silicon-heartland-city",
    district: "data-center-district",
    facility: "main-data-center",
    cameraLevel: "FACILITY_VIEW",
    useCase: "Northstar Data Center facility focus for data-center operations drill-down.",
    sourceFilename: "ChatGPT Image Sep 14, 2026, 09_39_17 PM (9).png",
    targetFilename: "northstar-data-center-facility.png",
    targetPath: "public/assets/metaverse/facilities/northstar-data-center-facility.png",
    status: "READY",
    peopleFree: true,
    productionBackground: true,
    referenceOnly: false,
    containsMockDashboardUi: false,
    notes: "Approved people-free Northstar Data Center facility background copied into canonical asset root.",
  },
  {
    assetId: "met-facility-data-center-training",
    city: "silicon-heartland-city",
    district: "data-center-district",
    facility: "data-center-training-lab",
    cameraLevel: "FACILITY_VIEW",
    useCase: "Data Center Training Facility focus before learner enters pathway/simulation surface.",
    sourceFilename: "ChatGPT Image Sep 14, 2026, 09_39_17 PM (9).png",
    targetFilename: "data-center-training-facility.png",
    targetPath: "public/assets/metaverse/facilities/data-center-training-facility.png",
    status: "READY",
    peopleFree: true,
    productionBackground: true,
    referenceOnly: false,
    containsMockDashboardUi: false,
    notes: "Approved people-free source supports both exterior facility slots and is copied into canonical asset root.",
  },
  {
    assetId: "met-facility-infrastructure-project-zone",
    city: "silicon-heartland-city",
    district: "technology-innovation-district",
    facility: "innovation-lab",
    cameraLevel: "FACILITY_VIEW",
    useCase: "Infrastructure/project work zone visual for future project-oriented activity handoff.",
    sourceFilename: "ChatGPT Image Sep 14, 2026, 10_12_27 PM (1).png",
    targetFilename: "infrastructure-project-work-zone.png",
    targetPath: "public/assets/metaverse/facilities/infrastructure-project-work-zone.png",
    status: "READY",
    peopleFree: true,
    productionBackground: true,
    referenceOnly: false,
    containsMockDashboardUi: false,
    notes: "Approved people-free Infrastructure Zone / project-work background copied into canonical asset root.",
  },
  {
    assetId: "met-facility-social-commons",
    city: "silicon-heartland-city",
    district: "student-life-district",
    facility: "student-hub",
    cameraLevel: "FACILITY_VIEW",
    useCase: "Social commons/student hub facility background for future presence and chat overlays.",
    sourceFilename: "ChatGPT Image Sep 14, 2026, 09_39_17 PM (8).png",
    targetFilename: "student-social-commons-facility.png",
    targetPath: "public/assets/metaverse/facilities/student-social-commons-facility.png",
    status: "READY",
    peopleFree: true,
    productionBackground: true,
    referenceOnly: false,
    containsMockDashboardUi: false,
    notes: "Approved people-free Social Commons / Student Commons background copied into canonical asset root.",
  },
];

export const METAVERSE_REFERENCE_ASSETS = [
  {
    assetId: "ref-arcade-eco-city-hero",
    city: "silicon-heartland-city",
    district: "learning-arcade-district",
    facility: "arcade-hub",
    cameraLevel: "DISTRICT_VIEW",
    useCase: "Existing eco/city mood reference for Learning Arcade environmental tone.",
    sourceFilename: "eco-city-hero.jpg",
    targetFilename: "eco-city-hero.jpg",
    targetPath: "public/assets/arcade/eco-city-hero.jpg",
    status: "REFERENCE_ONLY",
    peopleFree: null,
    productionBackground: false,
    referenceOnly: true,
    notes: "Existing repo asset; not locked as production metaverse background.",
  },
  {
    assetId: "ref-arcade-classical-cabinets",
    city: "silicon-heartland-city",
    district: "learning-arcade-district",
    facility: "simulation-hall",
    cameraLevel: "FACILITY_VIEW",
    useCase: "Existing arcade facility mood reference.",
    sourceFilename: "classical-arcade-cabinets.jpg",
    targetFilename: "classical-arcade-cabinets.jpg",
    targetPath: "public/assets/arcade/classical-arcade-cabinets.jpg",
    status: "REFERENCE_ONLY",
    peopleFree: null,
    productionBackground: false,
    referenceOnly: true,
    notes: "Existing repo asset; may contain a different visual language than MET-2A lock.",
  },
  {
    assetId: "ref-career-pathways-hero",
    city: "silicon-heartland-city",
    district: "career-education-district",
    facility: "career-center",
    cameraLevel: "DISTRICT_VIEW",
    useCase: "Existing Career & Education visual reference only.",
    sourceFilename: "hero.jpg",
    targetFilename: "hero.jpg",
    targetPath: "public/assets/career/pathways/hero.jpg",
    status: "REFERENCE_ONLY",
    peopleFree: null,
    productionBackground: false,
    referenceOnly: true,
    notes: "Existing repo asset; not a locked people-free city background.",
  },
  {
    assetId: "ref-career-infrastructure-family",
    city: "silicon-heartland-city",
    district: "technology-innovation-district",
    facility: "innovation-lab",
    cameraLevel: "FACILITY_VIEW",
    useCase: "Infrastructure/project-work concept reference.",
    sourceFilename: "family-infrastructure.jpg",
    targetFilename: "family-infrastructure.jpg",
    targetPath: "public/assets/career/pathways/family-infrastructure.jpg",
    status: "REFERENCE_ONLY",
    peopleFree: null,
    productionBackground: false,
    referenceOnly: true,
    notes: "Existing repo asset; useful for facility concept, not production metaverse background.",
  },
  {
    assetId: "ref-solutions-infrastructure-globe",
    city: "silicon-heartland-city",
    district: "public-realm",
    facility: "central-plaza",
    cameraLevel: "DISTRICT_VIEW",
    useCase: "Clean infrastructure/global civic-future reference.",
    sourceFilename: "solutions-infrastructure-globe.png",
    targetFilename: "solutions-infrastructure-globe.png",
    targetPath: "public/assets/solutions/solutions-infrastructure-globe.png",
    status: "REFERENCE_ONLY",
    peopleFree: null,
    productionBackground: false,
    referenceOnly: true,
    notes: "Existing repo asset; not a city/district production background.",
  },
];

export const METAVERSE_VISUAL_ASSET_REGISTRY = [
  ...METAVERSE_PRODUCTION_BACKGROUND_SET,
  ...METAVERSE_REFERENCE_ASSETS,
];

export const METAVERSE_CAMERA_TRANSITIONS = [
  {
    from: "City Overview",
    to: "Data Center District",
    trigger: "District marker, list item, or search result selection.",
    transitionType: "drill-down",
    cameraBehavior: "Pan and zoom from city overview to district bounding area; respect reduced motion with crossfade.",
    assetChange: "city/silicon-heartland-city-master-overview.png -> districts/data-center-district-overview.png",
    requiredUnlock: false,
    accessibleEquivalent: "Select Data Center District from list/tree navigation.",
  },
  {
    from: "Data Center District",
    to: "Northstar Data Center",
    trigger: "Facility marker or facility list selection.",
    transitionType: "facility focus",
    cameraBehavior: "Focus selected facility, keep breadcrumbs visible.",
    assetChange: "districts/data-center-district-overview.png -> facilities/northstar-data-center-facility.png",
    requiredUnlock: false,
    accessibleEquivalent: "Open Main Data Center details from facility list.",
  },
  {
    from: "Northstar Data Center",
    to: "Training Facility",
    trigger: "Training Facility waypoint.",
    transitionType: "facility-to-facility focus",
    cameraBehavior: "Short lateral focus transition within Data Center district.",
    assetChange: "facilities/northstar-data-center-facility.png -> facilities/data-center-training-facility.png",
    requiredUnlock: false,
    accessibleEquivalent: "Choose Data Center Training Lab from sibling facility list.",
  },
  {
    from: "Training Facility",
    to: "Simulation",
    trigger: "Activity card or route handoff.",
    transitionType: "activity handoff",
    cameraBehavior: "Fade environment and open canonical learning/simulation route; no authority granted by motion.",
    assetChange: "facility background -> activity/simulation shell owned by later phase.",
    requiredUnlock: "MET-3 projection required before gated access.",
    accessibleEquivalent: "Activate the same simulation from the facility activity list.",
  },
  {
    from: "City Overview",
    to: "Civic District",
    trigger: "District marker, list item, or search result selection.",
    transitionType: "drill-down",
    cameraBehavior: "Pan and zoom to City Hall/Civic Plaza area.",
    assetChange: "city/silicon-heartland-city-master-overview.png -> districts/civic-district-city-hall-plaza.png",
    requiredUnlock: false,
    accessibleEquivalent: "Select Civic District from list/tree navigation.",
  },
  {
    from: "Civic District",
    to: "City Hall",
    trigger: "City Hall facility marker.",
    transitionType: "facility focus",
    cameraBehavior: "Focus City Hall facade and civic waypoints.",
    assetChange: "districts/civic-district-city-hall-plaza.png",
    requiredUnlock: false,
    accessibleEquivalent: "Open City Hall details from facility list.",
  },
  {
    from: "City Hall",
    to: "Council Chamber",
    trigger: "Council Chamber waypoint.",
    transitionType: "facility focus",
    cameraBehavior: "Focus council waypoint; route remains SHF Civic-backed.",
    assetChange: "districts/civic-district-city-hall-plaza.png",
    requiredUnlock: "Future SHF Civic rule if gated.",
    accessibleEquivalent: "Select Council Chamber from Civic facility list.",
  },
  {
    from: "Council Chamber",
    to: "Civic Session",
    trigger: "Civic session activity card.",
    transitionType: "activity handoff",
    cameraBehavior: "Fade to canonical SHF Civic session route.",
    assetChange: "facility background -> civic activity route.",
    requiredUnlock: "Future SHF Civic rule if gated.",
    accessibleEquivalent: "Open session from activity list.",
  },
  {
    from: "City Overview",
    to: "Learning Arcade",
    trigger: "District marker or list selection.",
    transitionType: "drill-down",
    cameraBehavior: "Pan and zoom to portal/plaza entrance.",
    assetChange: "city/silicon-heartland-city-master-overview.png -> districts/learning-arcade-district-portal-plaza.png",
    requiredUnlock: false,
    accessibleEquivalent: "Select Learning Arcade from list/tree navigation.",
  },
  {
    from: "Learning Arcade",
    to: "Challenge Hub",
    trigger: "Challenge Hub marker.",
    transitionType: "facility focus",
    cameraBehavior: "Focus challenge entrance and show activity markers.",
    assetChange: "districts/learning-arcade-district-portal-plaza.png",
    requiredUnlock: false,
    accessibleEquivalent: "Choose Skills Challenge Center from facility list.",
  },
  {
    from: "Challenge Hub",
    to: "Game/Simulation",
    trigger: "Arcade challenge activity card.",
    transitionType: "activity handoff",
    cameraBehavior: "Fade to canonical Arcade route.",
    assetChange: "district background -> Arcade activity route.",
    requiredUnlock: "Arcade/curriculum authority if gated.",
    accessibleEquivalent: "Open the challenge from activity list.",
  },
  {
    from: "City Overview",
    to: "Career & Education",
    trigger: "District marker or list selection.",
    transitionType: "drill-down",
    cameraBehavior: "Pan and zoom to university/career district.",
    assetChange: "city/silicon-heartland-city-master-overview.png -> districts/career-education-district-university-overview.png",
    requiredUnlock: false,
    accessibleEquivalent: "Select Career & Education from list/tree navigation.",
  },
  {
    from: "Career & Education",
    to: "Career Center",
    trigger: "Career Center facility marker.",
    transitionType: "facility focus",
    cameraBehavior: "Focus Career Center waypoint and pathway markers.",
    assetChange: "districts/career-education-district-university-overview.png",
    requiredUnlock: false,
    accessibleEquivalent: "Open Career Center from facility list.",
  },
  {
    from: "Career Center",
    to: "Pathway Experience",
    trigger: "Pathway activity card.",
    transitionType: "activity handoff",
    cameraBehavior: "Fade to canonical Career route.",
    assetChange: "district background -> Career route.",
    requiredUnlock: "Career/curriculum authority if gated.",
    accessibleEquivalent: "Open the pathway from activity list.",
  },
];
