// src/utils/lordOutcomes/mockOutcomesData.js

// Regional rollup – this powers the KPIs on the home page
export const regionSummary = {
  totalParticipants: 2190,
  jobsPlaced: 684,
  avgWage: 21.1,
  credentials: 495,
  retention90Rate: 0.72, // 72%
};

// State-level outcomes for OH, MI, PA, WV, IN
export const stateOutcomes = [
  {
    code: "OH",
    name: "Ohio",
    participants: 820,
    jobsPlaced: 260,
    avgWage: 21.5,
    credentials: 180,
    retention90Rate: 0.75,
  },
  {
    code: "MI",
    name: "Michigan",
    participants: 410,
    jobsPlaced: 132,
    avgWage: 22.1,
    credentials: 95,
    retention90Rate: 0.7,
  },
  {
    code: "PA",
    name: "Pennsylvania",
    participants: 500,
    jobsPlaced: 150,
    avgWage: 20.8,
    credentials: 110,
    retention90Rate: 0.69,
  },
  {
    code: "WV",
    name: "West Virginia",
    participants: 160,
    jobsPlaced: 52,
    avgWage: 19.3,
    credentials: 40,
    retention90Rate: 0.68,
  },
  {
    code: "IN",
    name: "Indiana",
    participants: 300,
    jobsPlaced: 90,
    avgWage: 21.0,
    credentials: 70,
    retention90Rate: 0.73,
  },
];

// Program outcomes across the region
export const programOutcomes = [
  {
    id: "prog-cdl",
    name: "CDL Class A",
    sector: "Transportation",
    participants: 420,
    completions: 310,
    jobsPlaced: 210,
    avgWage: 24.5,
    credentials: 290,
    states: ["OH", "WV", "IN"],
  },
  {
    id: "prog-stna",
    name: "STNA / Nurse Aide",
    sector: "Healthcare",
    participants: 360,
    completions: 290,
    jobsPlaced: 205,
    avgWage: 19.8,
    credentials: 260,
    states: ["OH", "MI", "PA"],
  },
  {
    id: "prog-barber",
    name: "Barber Licensure",
    sector: "Trades",
    participants: 260,
    completions: 180,
    jobsPlaced: 135,
    avgWage: 22.0,
    credentials: 170,
    states: ["OH", "IN"],
  },
  {
    id: "prog-cyber",
    name: "Cybersecurity Foundations",
    sector: "Tech",
    participants: 310,
    completions: 220,
    jobsPlaced: 110,
    avgWage: 27.5,
    credentials: 210,
    states: ["MI", "PA", "OH"],
  },
  {
    id: "prog-cosmo",
    name: "Cosmetology & Barber Crossover",
    sector: "Beauty",
    participants: 220,
    completions: 165,
    jobsPlaced: 84,
    avgWage: 20.1,
    credentials: 150,
    states: ["OH", "WV"],
  },
];

// Employer-level impact
export const employerOutcomes = [
  {
    id: "emp-oh-logi",
    name: "Buckeye Logistics",
    state: "OH",
    industry: "Transportation",
    hires: 46,
    retention90Count: 36,
    avgStartingWage: 24.0,
    programs: ["CDL Class A"],
    tier: "Anchor",
  },
  {
    id: "emp-oh-hosp",
    name: "Columbus Care Network",
    state: "OH",
    industry: "Healthcare",
    hires: 38,
    retention90Count: 28,
    avgStartingWage: 19.5,
    programs: ["STNA / Nurse Aide"],
    tier: "Preferred",
  },
  {
    id: "emp-mi-auto",
    name: "Detroit Auto Systems",
    state: "MI",
    industry: "Manufacturing",
    hires: 30,
    retention90Count: 21,
    avgStartingWage: 22.3,
    programs: ["CDL Class A", "Cybersecurity Foundations"],
    tier: "Preferred",
  },
  {
    id: "emp-pa-health",
    name: "Keystone Health Group",
    state: "PA",
    industry: "Healthcare",
    hires: 27,
    retention90Count: 20,
    avgStartingWage: 20.6,
    programs: ["STNA / Nurse Aide"],
    tier: "Anchor",
  },
  {
    id: "emp-wv-works",
    name: "Mountain Works Construction",
    state: "WV",
    industry: "Construction",
    hires: 18,
    retention90Count: 13,
    avgStartingWage: 21.4,
    programs: ["CDL Class A", "Barber Licensure"],
    tier: "Basic",
  },
];

// Funding impact (mock WIOA / Perkins / Medicaid-ish)
export const fundingImpact = [
  {
    id: "fund-wioa-youth",
    name: "WIOA Youth Regional",
    category: "WIOA",
    states: ["OH", "MI", "WV"],
    participantsServed: 680,
    jobsPlaced: 240,
    credentials: 210,
    estAnnualizedWages: 6_800_000,
  },
  {
    id: "fund-perkins-cte",
    name: "Perkins V CTE Consortium",
    category: "Perkins V",
    states: ["OH", "IN", "PA"],
    participantsServed: 540,
    jobsPlaced: 190,
    credentials: 190,
    estAnnualizedWages: 5_200_000,
  },
  {
    id: "fund-medicaid-dd",
    name: "HCBS / DD Employment Waivers",
    category: "Medicaid / DD",
    states: ["OH", "WV"],
    participantsServed: 210,
    jobsPlaced: 88,
    credentials: 64,
    estAnnualizedWages: 2_000_000,
  },
  {
    id: "fund-foundation",
    name: "Private Foundation Workforce Grants",
    category: "Private / Philanthropy",
    states: ["OH", "MI", "PA", "IN", "WV"],
    participantsServed: 330,
    jobsPlaced: 166,
    credentials: 120,
    estAnnualizedWages: 4_500_000,
  },
];

// NEW: Funding KPIs for the FundingImpact page (small summary tiles)
export const fundingOutcomes = [
  {
    id: "grantsWon",
    label: "Grants Won (YTD)",
    value: 18,
    delta: "+4 vs. last year",
    icon: "🏛️",
    trend: "up",
    tone: "celebrate",
  },
  {
    id: "reimbursed",
    label: "Reimbursement Captured",
    value: "$420k",
    delta: "+$95k vs. last quarter",
    icon: "💵",
    trend: "up",
    tone: "ok",
  },
  {
    id: "pending",
    label: "Pending Decisions",
    value: 7,
    delta: "Across 3 agencies",
    icon: "⏳",
    trend: "flat",
    tone: "warn",
  },
];
