export const SHS_SECURITY_ROLES = {
  SUPER_ADMIN: "super_admin",
  SHS_ADMIN: "shs_admin",
  SHF_ADMIN: "shf_admin",
  PARTNER_ORG_ADMIN: "partner_org_admin",
  PROGRAM_WORKER: "program_worker",
  REVIEWER_VERIFIER: "reviewer_verifier",
  LEADERSHIP_FUNDER_VIEWER: "leadership_funder_viewer",
  AUDITOR: "auditor",
  READ_ONLY_VIEWER: "read_only_viewer",
} as const;

export const SHS_SECURITY_PERMISSIONS = {
  IDENTITY_VIEW: "identity.view",
  IDENTITY_MANAGE: "identity.manage",
  IDENTITY_MEMBERSHIP_ASSIGN: "identity.membership.assign",
  IDENTITY_MEMBERSHIP_REVOKE: "identity.membership.revoke",

  ORGANIZATION_VIEW: "organization.view",
  ORGANIZATION_MANAGE: "organization.manage",

  AGGREGATION_VIEW: "aggregation.view",
  AGGREGATION_RESOLVE: "aggregation.resolve",
  AGGREGATION_RUN: "aggregation.run",

  VERIFICATION_VIEW: "verification.view",
  VERIFICATION_REVIEW: "verification.review",
  VERIFICATION_APPROVE: "verification.approve",
  VERIFICATION_REJECT: "verification.reject",

  TRUTH_VIEW: "truth.view",
  TRUTH_OVERRIDE: "truth.override",

  ORACLE_VIEW: "oracle.view",
  ORACLE_COMPARE: "oracle.compare",
  ORACLE_PRIORITY: "oracle.priority",
  ORACLE_ACTION: "oracle.action",

  TRUST_ENVELOPE_VIEW: "trustEnvelope.view",
  TRUST_ENVELOPE_EXPORT: "trustEnvelope.export",

  TRACE_VIEW: "trace.view",
  TRACE_VALIDATE: "trace.validate",

  REPORTS_VIEW: "reports.view",
  REPORTS_PREVIEW: "reports.preview",
  REPORTS_EXPORT: "reports.export",
  REPORTS_PUBLISH: "reports.publish",

  AUDIT_VIEW: "audit.view",
  AUDIT_EXPORT: "audit.export",

  UPLOADS_INTERNAL: "uploads.internal",
  UPLOADS_EVIDENCE: "uploads.evidence",
  UPLOADS_VIDEO: "uploads.video",
  UPLOADS_APPROVE_PUBLIC: "uploads.approve_public",

  SECURITY_VIEW: "security.view",
  SECURITY_MANAGE: "security.manage",

  SETTINGS_MANAGE: "settings.manage",

  GROWTH_VIEW: "growth.view",
  GROWTH_MANAGE: "growth.manage",
  PARTNERS_MANAGE: "partners.manage",
  REFERRALS_MANAGE: "referrals.manage",
} as const;

export type ShsSecurityPermission =
  typeof SHS_SECURITY_PERMISSIONS[keyof typeof SHS_SECURITY_PERMISSIONS];

export const SHS_SUPER_ADMIN_PERMISSIONS: ShsSecurityPermission[] = Object.values(
  SHS_SECURITY_PERMISSIONS
);

export const SHS_ROLE_PERMISSION_MAP: Record<string, ShsSecurityPermission[]> = {
  [SHS_SECURITY_ROLES.SUPER_ADMIN]: SHS_SUPER_ADMIN_PERMISSIONS,

  [SHS_SECURITY_ROLES.SHS_ADMIN]: [
    SHS_SECURITY_PERMISSIONS.IDENTITY_VIEW,
    SHS_SECURITY_PERMISSIONS.IDENTITY_MANAGE,
    SHS_SECURITY_PERMISSIONS.ORGANIZATION_VIEW,
    SHS_SECURITY_PERMISSIONS.ORGANIZATION_MANAGE,
    SHS_SECURITY_PERMISSIONS.AGGREGATION_VIEW,
    SHS_SECURITY_PERMISSIONS.AGGREGATION_RESOLVE,
    SHS_SECURITY_PERMISSIONS.VERIFICATION_VIEW,
    SHS_SECURITY_PERMISSIONS.VERIFICATION_REVIEW,
    SHS_SECURITY_PERMISSIONS.VERIFICATION_APPROVE,
    SHS_SECURITY_PERMISSIONS.TRUTH_VIEW,
    SHS_SECURITY_PERMISSIONS.ORACLE_VIEW,
    SHS_SECURITY_PERMISSIONS.ORACLE_COMPARE,
    SHS_SECURITY_PERMISSIONS.TRUST_ENVELOPE_VIEW,
    SHS_SECURITY_PERMISSIONS.TRACE_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_PREVIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_EXPORT,
    SHS_SECURITY_PERMISSIONS.AUDIT_VIEW,
    SHS_SECURITY_PERMISSIONS.UPLOADS_INTERNAL,
    SHS_SECURITY_PERMISSIONS.UPLOADS_EVIDENCE,
    SHS_SECURITY_PERMISSIONS.SETTINGS_MANAGE,
  ],

  [SHS_SECURITY_ROLES.SHF_ADMIN]: [
    SHS_SECURITY_PERMISSIONS.ORGANIZATION_VIEW,
    SHS_SECURITY_PERMISSIONS.AGGREGATION_VIEW,
    SHS_SECURITY_PERMISSIONS.VERIFICATION_VIEW,
    SHS_SECURITY_PERMISSIONS.VERIFICATION_REVIEW,
    SHS_SECURITY_PERMISSIONS.TRUTH_VIEW,
    SHS_SECURITY_PERMISSIONS.ORACLE_VIEW,
    SHS_SECURITY_PERMISSIONS.TRUST_ENVELOPE_VIEW,
    SHS_SECURITY_PERMISSIONS.TRACE_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_PREVIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_EXPORT,
    SHS_SECURITY_PERMISSIONS.AUDIT_VIEW,
    SHS_SECURITY_PERMISSIONS.UPLOADS_INTERNAL,
    SHS_SECURITY_PERMISSIONS.UPLOADS_EVIDENCE,
    SHS_SECURITY_PERMISSIONS.REFERRALS_MANAGE,
  ],

  [SHS_SECURITY_ROLES.PARTNER_ORG_ADMIN]: [
    SHS_SECURITY_PERMISSIONS.ORGANIZATION_VIEW,
    SHS_SECURITY_PERMISSIONS.AGGREGATION_VIEW,
    SHS_SECURITY_PERMISSIONS.VERIFICATION_VIEW,
    SHS_SECURITY_PERMISSIONS.TRUTH_VIEW,
    SHS_SECURITY_PERMISSIONS.TRUST_ENVELOPE_VIEW,
    SHS_SECURITY_PERMISSIONS.TRACE_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_PREVIEW,
    SHS_SECURITY_PERMISSIONS.UPLOADS_INTERNAL,
    SHS_SECURITY_PERMISSIONS.UPLOADS_EVIDENCE,
    SHS_SECURITY_PERMISSIONS.REFERRALS_MANAGE,
  ],

  [SHS_SECURITY_ROLES.REVIEWER_VERIFIER]: [
    SHS_SECURITY_PERMISSIONS.VERIFICATION_VIEW,
    SHS_SECURITY_PERMISSIONS.VERIFICATION_REVIEW,
    SHS_SECURITY_PERMISSIONS.VERIFICATION_APPROVE,
    SHS_SECURITY_PERMISSIONS.VERIFICATION_REJECT,
    SHS_SECURITY_PERMISSIONS.TRUTH_VIEW,
    SHS_SECURITY_PERMISSIONS.TRACE_VIEW,
    SHS_SECURITY_PERMISSIONS.AUDIT_VIEW,
  ],

  [SHS_SECURITY_ROLES.LEADERSHIP_FUNDER_VIEWER]: [
    SHS_SECURITY_PERMISSIONS.TRUTH_VIEW,
    SHS_SECURITY_PERMISSIONS.TRUST_ENVELOPE_VIEW,
    SHS_SECURITY_PERMISSIONS.TRACE_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_PREVIEW,
  ],

  [SHS_SECURITY_ROLES.AUDITOR]: [
    SHS_SECURITY_PERMISSIONS.TRUTH_VIEW,
    SHS_SECURITY_PERMISSIONS.ORACLE_VIEW,
    SHS_SECURITY_PERMISSIONS.TRUST_ENVELOPE_VIEW,
    SHS_SECURITY_PERMISSIONS.TRACE_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_VIEW,
    SHS_SECURITY_PERMISSIONS.AUDIT_VIEW,
    SHS_SECURITY_PERMISSIONS.AUDIT_EXPORT,
  ],

  [SHS_SECURITY_ROLES.PROGRAM_WORKER]: [
    SHS_SECURITY_PERMISSIONS.AGGREGATION_VIEW,
    SHS_SECURITY_PERMISSIONS.VERIFICATION_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_VIEW,
    SHS_SECURITY_PERMISSIONS.UPLOADS_INTERNAL,
    SHS_SECURITY_PERMISSIONS.UPLOADS_EVIDENCE,
    SHS_SECURITY_PERMISSIONS.REFERRALS_MANAGE,
  ],

  [SHS_SECURITY_ROLES.READ_ONLY_VIEWER]: [
    SHS_SECURITY_PERMISSIONS.REPORTS_VIEW,
  ],
};

export function getPermissionsForRole(role: string): ShsSecurityPermission[] {
  return SHS_ROLE_PERMISSION_MAP[role] || [];
}

export function mergeRolePermissions(roles: string[] = []): ShsSecurityPermission[] {
  return Array.from(new Set(roles.flatMap((role) => getPermissionsForRole(role))));
}

export function hasPermission(permissions: string[] = [], permission: string) {
  return permissions.includes(permission);
}
