export const SHS_SECURITY_ROLES = {
  SUPER_ADMIN: "super_admin",
  SHS_ADMIN: "shs_admin",
  SHF_ADMIN: "shf_admin",
  PARTNER_ORG_ADMIN: "partner_org_admin",
  PROGRAM_WORKER: "program_worker",
  REVIEWER_VERIFIER: "reviewer_verifier",
  LEADERSHIP_FUNDER_VIEWER: "leadership_funder_viewer",
  AUDITOR: "auditor",
  READ_ONLY_VIEWER: "read_only_viewer",
  // Phase 2A Secure Live Learning — curriculum end-user roles. Extends the
  // existing role/permission mechanism (same map, same guard function);
  // does not introduce a second identity system.
  INSTRUCTOR: "instructor",
  STUDENT: "student",
  ORG_ADMIN: "org_admin",
  OPERATOR: "operator",
  PROGRAM_MANAGER: "program_manager",
  REVIEWER: "reviewer",
} as const;

export const SHS_SECURITY_PERMISSIONS = {
  IDENTITY_VIEW: "identity.view",
  IDENTITY_MANAGE: "identity.manage",
  IDENTITY_MEMBERSHIP_ASSIGN: "identity.membership.assign",
  IDENTITY_MEMBERSHIP_REVOKE: "identity.membership.revoke",

  ORGANIZATION_VIEW: "organization.view",
  ORGANIZATION_MANAGE: "organization.manage",
  ORGANIZATION_RELATIONSHIP_VIEW: "organization.relationship.view",
  ORGANIZATION_RELATIONSHIP_MANAGE: "organization.relationship.manage",

  AGGREGATION_VIEW: "aggregation.view",
  AGGREGATION_RESOLVE: "aggregation.resolve",
  AGGREGATION_RUN: "aggregation.run",

  VERIFICATION_VIEW: "verification.view",
  VERIFICATION_REVIEW: "verification.review",
  VERIFICATION_APPROVE: "verification.approve",
  VERIFICATION_REJECT: "verification.reject",

  TRUTH_VIEW: "truth.view",
  TRUTH_OVERRIDE: "truth.override",

  ORACLE_VIEW: "oracle.view",
  ORACLE_COMPARE: "oracle.compare",
  ORACLE_PRIORITY: "oracle.priority",
  ORACLE_ACTION: "oracle.action",

  TRUST_ENVELOPE_VIEW: "trustEnvelope.view",
  TRUST_ENVELOPE_EXPORT: "trustEnvelope.export",

  TRACE_VIEW: "trace.view",
  TRACE_VALIDATE: "trace.validate",

  REPORTS_VIEW: "reports.view",
  REPORTS_PREVIEW: "reports.preview",
  REPORTS_EXPORT: "reports.export",
  REPORTS_DISTRIBUTION_MANAGE: "reports.distribution.manage",
  REPORTS_DISTRIBUTE: "reports.distribute",
  REPORTS_PUBLIC_ELIGIBILITY_MANAGE: "reports.public_eligibility.manage",
  REPORTS_PUBLIC_DISCLOSURE_MANAGE: "reports.public_disclosure.manage",
  REPORTS_PUBLIC_DISCLOSURE_POLICY_MANAGE: "reports.public_disclosure_policy.manage",
  REPORTS_PUBLIC_SNAPSHOT_GENERATE: "reports.public_snapshot.generate",
  REPORTS_PUBLIC_SNAPSHOT_VIEW: "reports.public_snapshot.view",
  REPORTS_PUBLICATION_AUTHORIZE: "reports.publication.authorize",
  REPORTS_PUBLICATION_EXECUTE: "reports.publication.execute",
  REPORTS_PUBLISH: "reports.publish",

  EXCHANGE_FUNDING_COMMITMENTS_VIEW: "exchange.fundingCommitments.view",
  EXCHANGE_FUNDING_COMMITMENTS_MANAGE: "exchange.fundingCommitments.manage",

  WORKFORCE_OUTCOMES_VIEW: "workforce.outcomes.view",
  WORKFORCE_OUTCOMES_SUBMIT: "workforce.outcomes.submit",
  WORKFORCE_OUTCOMES_VERIFY: "workforce.outcomes.verify",
  WORKFORCE_OUTCOMES_REJECT: "workforce.outcomes.reject",

  AUDIT_VIEW: "audit.view",
  AUDIT_EXPORT: "audit.export",

  UPLOADS_INTERNAL: "uploads.internal",
  UPLOADS_EVIDENCE: "uploads.evidence",
  UPLOADS_VIDEO: "uploads.video",
  UPLOADS_APPROVE_PUBLIC: "uploads.approve_public",

  SECURITY_VIEW: "security.view",
  SECURITY_MANAGE: "security.manage",

  SETTINGS_MANAGE: "settings.manage",

  GROWTH_VIEW: "growth.view",
  GROWTH_MANAGE: "growth.manage",
  PARTNERS_MANAGE: "partners.manage",
  REFERRALS_MANAGE: "referrals.manage",

  PROGRAM_CREATE: "program.create",
  PROGRAM_READ: "program.read",
  PROGRAM_UPDATE: "program.update",
  PROGRAM_TRANSITION: "program.transition",
  PROGRAM_SPECIALIZATION_ASSIGN: "program.specialization.assign",
  PROGRAM_COURSE_ASSIGN: "program.course.assign",
  PROJECT_CREATE: "project.create",
  PROJECT_TEAM_MANAGE: "project.team.manage",
  PROJECT_SUBMISSION_VIEW: "project.submission.view",
  PROJECT_SUBMISSION_WRITE: "project.submission.write",
  PROJECT_SUBMISSION_REVIEW: "project.submission.review",
  // SHF Ecosystem Phase 6 — narrow read of Project scheduling metadata
  // (id/title/type/status/dates only, never submission payloads) for
  // Calendar/Journey Milestone consumption. Deliberately separate from
  // PROJECT_SUBMISSION_VIEW, which returns a project's full submission
  // history and is admin/program-manager only.
  PROJECT_VIEW: "project.view",
  // SHF Ecosystem Phase 7 — Credential Definition (global reference data)
  // management, and Learner Credential (issuance) authority. Students
  // never receive CREDENTIAL_ISSUE — no self-issuance path exists.
  CREDENTIAL_DEFINITION_MANAGE: "credential.definition.manage",
  CREDENTIAL_ISSUE: "credential.issue",
  CREDENTIAL_REVOKE: "credential.revoke",
  CREDENTIAL_VIEW: "credential.view",
  // SHF Ecosystem Phase 8 — Learning Arcade. ARCADE_ATTEMPT covers both
  // starting an Attempt and reading/submitting a Result for one's own
  // Attempt (self-service, mirrors PROJECT_SUBMISSION_WRITE). Activity
  // definitions are global reference data and are read without a
  // permission gate (mirrors GET /careers). ARCADE_RESULTS_VIEW is the
  // separate, narrower admin/reporting read of other learners' results —
  // never granted alongside ARCADE_ATTEMPT to the same role.
  ARCADE_ACTIVITY_MANAGE: "arcade.activity.manage",
  ARCADE_ATTEMPT: "arcade.attempt",
  ARCADE_RESULTS_VIEW: "arcade.results.view",
  CASE_CREATE: "case.create",
  CASE_READ: "case.read",
  CASE_UPDATE: "case.update",
  CASE_ASSIGN: "case.assign",
  CASE_TRANSITION: "case.transition",
  AUDIT_READ: "audit.read",

  // Phase 2A Secure Live Learning
  LIVE_LEARNING_VIEW: "liveLearning.view",
  LIVE_LEARNING_CREATE: "liveLearning.create",
  LIVE_LEARNING_MANAGE: "liveLearning.manage",
  LIVE_LEARNING_JOIN_REQUEST: "liveLearning.join.request",
  LIVE_LEARNING_JOIN_AUTHORIZE: "liveLearning.join.authorize",
  CURRICULUM_LESSON_COMPLETE: "curriculum.lesson.complete",
  CURRICULUM_SOURCE_UPLOAD: "curriculum.source.upload",
  CURRICULUM_SOURCE_VIEW: "curriculum.source.view",
  // SHF Lesson + Assignment + Curriculum Ingestion Phase 2 — Curriculum
  // Catalog. MANAGE covers create/edit of DRAFT Course/Unit/Lesson/
  // Resource and submitting for review; APPROVE/PUBLISH/RETIRE are
  // separate lifecycle gates (see curriculum-catalog-service.ts). No
  // student or instructor role receives any of these — same posture as
  // CURRICULUM_SOURCE_UPLOAD/VIEW above.
  CURRICULUM_CATALOG_MANAGE: "curriculum.catalog.manage",
  CURRICULUM_CATALOG_APPROVE: "curriculum.catalog.approve",
  CURRICULUM_CATALOG_PUBLISH: "curriculum.catalog.publish",
  CURRICULUM_CATALOG_RETIRE: "curriculum.catalog.retire",

  // SHF Calendar Wave 2A — Assignment domain.
  ASSIGNMENT_VIEW: "assignment.view",
  ASSIGNMENT_MANAGE: "assignment.manage",
  COHORT_VIEW: "cohort.view",
  COHORT_MANAGE: "cohort.manage",
  ENROLLMENT_VIEW: "enrollment.view",
  ENROLLMENT_MANAGE: "enrollment.manage",

  // SHF Ecosystem Phase 4 — Career Event / Opportunity domains.
  CAREER_EVENT_VIEW: "careerEvent.view",
  CAREER_EVENT_MANAGE: "careerEvent.manage",
  OPPORTUNITY_VIEW: "opportunity.view",
  OPPORTUNITY_MANAGE: "opportunity.manage",
} as const;

export type ShsSecurityPermission =
  typeof SHS_SECURITY_PERMISSIONS[keyof typeof SHS_SECURITY_PERMISSIONS];

export const SHS_SUPER_ADMIN_PERMISSIONS: ShsSecurityPermission[] = Object.values(
  SHS_SECURITY_PERMISSIONS
);

export const SHS_ROLE_PERMISSION_MAP: Record<string, ShsSecurityPermission[]> = {
  [SHS_SECURITY_ROLES.SUPER_ADMIN]: SHS_SUPER_ADMIN_PERMISSIONS,

  [SHS_SECURITY_ROLES.SHS_ADMIN]: [
    SHS_SECURITY_PERMISSIONS.IDENTITY_VIEW,
    SHS_SECURITY_PERMISSIONS.IDENTITY_MANAGE,
    SHS_SECURITY_PERMISSIONS.ORGANIZATION_VIEW,
    SHS_SECURITY_PERMISSIONS.ORGANIZATION_MANAGE,
    SHS_SECURITY_PERMISSIONS.ORGANIZATION_RELATIONSHIP_VIEW,
    SHS_SECURITY_PERMISSIONS.ORGANIZATION_RELATIONSHIP_MANAGE,
    SHS_SECURITY_PERMISSIONS.AGGREGATION_VIEW,
    SHS_SECURITY_PERMISSIONS.AGGREGATION_RESOLVE,
    SHS_SECURITY_PERMISSIONS.VERIFICATION_VIEW,
    SHS_SECURITY_PERMISSIONS.VERIFICATION_REVIEW,
    SHS_SECURITY_PERMISSIONS.VERIFICATION_APPROVE,
    SHS_SECURITY_PERMISSIONS.TRUTH_VIEW,
    SHS_SECURITY_PERMISSIONS.ORACLE_VIEW,
    SHS_SECURITY_PERMISSIONS.ORACLE_COMPARE,
    SHS_SECURITY_PERMISSIONS.TRUST_ENVELOPE_VIEW,
    SHS_SECURITY_PERMISSIONS.TRACE_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_PREVIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_EXPORT,
    SHS_SECURITY_PERMISSIONS.REPORTS_DISTRIBUTION_MANAGE,
    SHS_SECURITY_PERMISSIONS.REPORTS_PUBLIC_ELIGIBILITY_MANAGE,
    SHS_SECURITY_PERMISSIONS.REPORTS_PUBLIC_DISCLOSURE_MANAGE,
    SHS_SECURITY_PERMISSIONS.REPORTS_PUBLIC_DISCLOSURE_POLICY_MANAGE,
    SHS_SECURITY_PERMISSIONS.REPORTS_PUBLIC_SNAPSHOT_GENERATE,
    SHS_SECURITY_PERMISSIONS.REPORTS_PUBLIC_SNAPSHOT_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_PUBLICATION_AUTHORIZE,
    SHS_SECURITY_PERMISSIONS.REPORTS_PUBLICATION_EXECUTE,
    SHS_SECURITY_PERMISSIONS.EXCHANGE_FUNDING_COMMITMENTS_VIEW,
    SHS_SECURITY_PERMISSIONS.EXCHANGE_FUNDING_COMMITMENTS_MANAGE,
    SHS_SECURITY_PERMISSIONS.WORKFORCE_OUTCOMES_VIEW,
    SHS_SECURITY_PERMISSIONS.WORKFORCE_OUTCOMES_SUBMIT,
    SHS_SECURITY_PERMISSIONS.WORKFORCE_OUTCOMES_VERIFY,
    SHS_SECURITY_PERMISSIONS.WORKFORCE_OUTCOMES_REJECT,
    SHS_SECURITY_PERMISSIONS.AUDIT_VIEW,
    SHS_SECURITY_PERMISSIONS.UPLOADS_INTERNAL,
    SHS_SECURITY_PERMISSIONS.UPLOADS_EVIDENCE,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_SOURCE_UPLOAD,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_SOURCE_VIEW,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_CATALOG_MANAGE,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_CATALOG_APPROVE,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_CATALOG_PUBLISH,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_CATALOG_RETIRE,
    SHS_SECURITY_PERMISSIONS.SETTINGS_MANAGE,
    SHS_SECURITY_PERMISSIONS.ASSIGNMENT_VIEW,
    SHS_SECURITY_PERMISSIONS.ASSIGNMENT_MANAGE,
    SHS_SECURITY_PERMISSIONS.COHORT_VIEW,
    SHS_SECURITY_PERMISSIONS.COHORT_MANAGE,
    SHS_SECURITY_PERMISSIONS.ENROLLMENT_VIEW,
    SHS_SECURITY_PERMISSIONS.ENROLLMENT_MANAGE,
    SHS_SECURITY_PERMISSIONS.CAREER_EVENT_VIEW,
    SHS_SECURITY_PERMISSIONS.CAREER_EVENT_MANAGE,
    SHS_SECURITY_PERMISSIONS.OPPORTUNITY_VIEW,
    SHS_SECURITY_PERMISSIONS.OPPORTUNITY_MANAGE,
  ],

  [SHS_SECURITY_ROLES.SHF_ADMIN]: [
    SHS_SECURITY_PERMISSIONS.ORGANIZATION_VIEW,
    SHS_SECURITY_PERMISSIONS.ORGANIZATION_RELATIONSHIP_VIEW,
    SHS_SECURITY_PERMISSIONS.AGGREGATION_VIEW,
    SHS_SECURITY_PERMISSIONS.VERIFICATION_VIEW,
    SHS_SECURITY_PERMISSIONS.VERIFICATION_REVIEW,
    SHS_SECURITY_PERMISSIONS.TRUTH_VIEW,
    SHS_SECURITY_PERMISSIONS.ORACLE_VIEW,
    SHS_SECURITY_PERMISSIONS.TRUST_ENVELOPE_VIEW,
    SHS_SECURITY_PERMISSIONS.TRACE_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_PREVIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_EXPORT,
    SHS_SECURITY_PERMISSIONS.REPORTS_DISTRIBUTION_MANAGE,
    SHS_SECURITY_PERMISSIONS.REPORTS_PUBLIC_ELIGIBILITY_MANAGE,
    SHS_SECURITY_PERMISSIONS.REPORTS_PUBLIC_DISCLOSURE_MANAGE,
    SHS_SECURITY_PERMISSIONS.REPORTS_PUBLIC_DISCLOSURE_POLICY_MANAGE,
    SHS_SECURITY_PERMISSIONS.REPORTS_PUBLIC_SNAPSHOT_GENERATE,
    SHS_SECURITY_PERMISSIONS.REPORTS_PUBLIC_SNAPSHOT_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_PUBLICATION_AUTHORIZE,
    SHS_SECURITY_PERMISSIONS.REPORTS_PUBLICATION_EXECUTE,
    SHS_SECURITY_PERMISSIONS.EXCHANGE_FUNDING_COMMITMENTS_VIEW,
    SHS_SECURITY_PERMISSIONS.EXCHANGE_FUNDING_COMMITMENTS_MANAGE,
    SHS_SECURITY_PERMISSIONS.WORKFORCE_OUTCOMES_VIEW,
    SHS_SECURITY_PERMISSIONS.WORKFORCE_OUTCOMES_SUBMIT,
    SHS_SECURITY_PERMISSIONS.WORKFORCE_OUTCOMES_VERIFY,
    SHS_SECURITY_PERMISSIONS.WORKFORCE_OUTCOMES_REJECT,
    SHS_SECURITY_PERMISSIONS.AUDIT_VIEW,
    SHS_SECURITY_PERMISSIONS.UPLOADS_INTERNAL,
    SHS_SECURITY_PERMISSIONS.UPLOADS_EVIDENCE,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_SOURCE_UPLOAD,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_SOURCE_VIEW,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_CATALOG_MANAGE,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_CATALOG_APPROVE,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_CATALOG_PUBLISH,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_CATALOG_RETIRE,
    SHS_SECURITY_PERMISSIONS.REFERRALS_MANAGE,
    // Phase 2A: SHF admins manage Live Learning across the org's curriculum.
    SHS_SECURITY_PERMISSIONS.LIVE_LEARNING_VIEW,
    SHS_SECURITY_PERMISSIONS.LIVE_LEARNING_CREATE,
    SHS_SECURITY_PERMISSIONS.LIVE_LEARNING_MANAGE,
    SHS_SECURITY_PERMISSIONS.LIVE_LEARNING_JOIN_AUTHORIZE,
    // Wave 2A: SHF admins manage Assignments across the org's curriculum.
    SHS_SECURITY_PERMISSIONS.ASSIGNMENT_VIEW,
    SHS_SECURITY_PERMISSIONS.ASSIGNMENT_MANAGE,
    SHS_SECURITY_PERMISSIONS.COHORT_VIEW,
    SHS_SECURITY_PERMISSIONS.COHORT_MANAGE,
    SHS_SECURITY_PERMISSIONS.ENROLLMENT_VIEW,
    SHS_SECURITY_PERMISSIONS.ENROLLMENT_MANAGE,
    SHS_SECURITY_PERMISSIONS.CAREER_EVENT_VIEW,
    SHS_SECURITY_PERMISSIONS.CAREER_EVENT_MANAGE,
    SHS_SECURITY_PERMISSIONS.OPPORTUNITY_VIEW,
    SHS_SECURITY_PERMISSIONS.OPPORTUNITY_MANAGE,
  ],

  [SHS_SECURITY_ROLES.PARTNER_ORG_ADMIN]: [
    SHS_SECURITY_PERMISSIONS.ORGANIZATION_VIEW,
    SHS_SECURITY_PERMISSIONS.ORGANIZATION_RELATIONSHIP_VIEW,
    SHS_SECURITY_PERMISSIONS.AGGREGATION_VIEW,
    SHS_SECURITY_PERMISSIONS.VERIFICATION_VIEW,
    SHS_SECURITY_PERMISSIONS.TRUTH_VIEW,
    SHS_SECURITY_PERMISSIONS.TRUST_ENVELOPE_VIEW,
    SHS_SECURITY_PERMISSIONS.TRACE_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_PREVIEW,
    SHS_SECURITY_PERMISSIONS.EXCHANGE_FUNDING_COMMITMENTS_VIEW,
    SHS_SECURITY_PERMISSIONS.UPLOADS_INTERNAL,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_SOURCE_UPLOAD,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_SOURCE_VIEW,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_CATALOG_MANAGE,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_CATALOG_APPROVE,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_CATALOG_PUBLISH,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_CATALOG_RETIRE,
    SHS_SECURITY_PERMISSIONS.UPLOADS_EVIDENCE,
    SHS_SECURITY_PERMISSIONS.REFERRALS_MANAGE,
  ],

  [SHS_SECURITY_ROLES.REVIEWER_VERIFIER]: [
    SHS_SECURITY_PERMISSIONS.VERIFICATION_VIEW,
    SHS_SECURITY_PERMISSIONS.VERIFICATION_REVIEW,
    SHS_SECURITY_PERMISSIONS.VERIFICATION_APPROVE,
    SHS_SECURITY_PERMISSIONS.VERIFICATION_REJECT,
    SHS_SECURITY_PERMISSIONS.WORKFORCE_OUTCOMES_VIEW,
    SHS_SECURITY_PERMISSIONS.WORKFORCE_OUTCOMES_VERIFY,
    SHS_SECURITY_PERMISSIONS.WORKFORCE_OUTCOMES_REJECT,
    SHS_SECURITY_PERMISSIONS.TRUTH_VIEW,
    SHS_SECURITY_PERMISSIONS.TRACE_VIEW,
    SHS_SECURITY_PERMISSIONS.AUDIT_VIEW,
  ],

  [SHS_SECURITY_ROLES.LEADERSHIP_FUNDER_VIEWER]: [
    SHS_SECURITY_PERMISSIONS.TRUTH_VIEW,
    SHS_SECURITY_PERMISSIONS.TRUST_ENVELOPE_VIEW,
    SHS_SECURITY_PERMISSIONS.TRACE_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_PREVIEW,
  ],

  [SHS_SECURITY_ROLES.AUDITOR]: [
    SHS_SECURITY_PERMISSIONS.TRUTH_VIEW,
    SHS_SECURITY_PERMISSIONS.ORACLE_VIEW,
    SHS_SECURITY_PERMISSIONS.TRUST_ENVELOPE_VIEW,
    SHS_SECURITY_PERMISSIONS.TRACE_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_VIEW,
    SHS_SECURITY_PERMISSIONS.AUDIT_VIEW,
    SHS_SECURITY_PERMISSIONS.AUDIT_EXPORT,
  ],

  [SHS_SECURITY_ROLES.PROGRAM_WORKER]: [
    SHS_SECURITY_PERMISSIONS.AGGREGATION_VIEW,
    SHS_SECURITY_PERMISSIONS.VERIFICATION_VIEW,
    SHS_SECURITY_PERMISSIONS.REPORTS_VIEW,
    SHS_SECURITY_PERMISSIONS.UPLOADS_INTERNAL,
    SHS_SECURITY_PERMISSIONS.UPLOADS_EVIDENCE,
    SHS_SECURITY_PERMISSIONS.REFERRALS_MANAGE,
  ],

  [SHS_SECURITY_ROLES.READ_ONLY_VIEWER]: [
    SHS_SECURITY_PERMISSIONS.REPORTS_VIEW,
  ],

  // Phase 2A Secure Live Learning roles.
  [SHS_SECURITY_ROLES.INSTRUCTOR]: [
    SHS_SECURITY_PERMISSIONS.LIVE_LEARNING_VIEW,
    SHS_SECURITY_PERMISSIONS.LIVE_LEARNING_CREATE,
    SHS_SECURITY_PERMISSIONS.LIVE_LEARNING_JOIN_AUTHORIZE,
    // Wave 2A
    SHS_SECURITY_PERMISSIONS.ASSIGNMENT_VIEW,
    SHS_SECURITY_PERMISSIONS.ASSIGNMENT_MANAGE,
    SHS_SECURITY_PERMISSIONS.COHORT_VIEW,
    SHS_SECURITY_PERMISSIONS.ENROLLMENT_VIEW,
    // Phase 4 — instructors may create/manage cohort-scoped Career Events
    // and Opportunities for cohorts where they are active cohort_staff
    // (enforced server-side, not by this permission alone).
    SHS_SECURITY_PERMISSIONS.CAREER_EVENT_VIEW,
    SHS_SECURITY_PERMISSIONS.CAREER_EVENT_MANAGE,
    SHS_SECURITY_PERMISSIONS.OPPORTUNITY_VIEW,
    SHS_SECURITY_PERMISSIONS.OPPORTUNITY_MANAGE,
  ],
  [SHS_SECURITY_ROLES.STUDENT]: [
    SHS_SECURITY_PERMISSIONS.LIVE_LEARNING_VIEW,
    SHS_SECURITY_PERMISSIONS.LIVE_LEARNING_JOIN_REQUEST,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_LESSON_COMPLETE,
    SHS_SECURITY_PERMISSIONS.PROJECT_SUBMISSION_WRITE,
    // Phase 6 — a learner may see their own Project schedule (id/title/
    // dates only); scoped to their own team membership in the service
    // layer, never every organization Project.
    SHS_SECURITY_PERMISSIONS.PROJECT_VIEW,
    // Phase 7 — a learner may see their own issued Credentials; never
    // definition management or issuance authority.
    SHS_SECURITY_PERMISSIONS.CREDENTIAL_VIEW,
    // Phase 8 — a learner may start their own Arcade Attempts and submit/
    // read their own Results; never another learner's, never Activity
    // management, never the org-wide results report.
    SHS_SECURITY_PERMISSIONS.ARCADE_ATTEMPT,
    // Wave 2A — view only, students never create/manage assignments.
    SHS_SECURITY_PERMISSIONS.ASSIGNMENT_VIEW,
    SHS_SECURITY_PERMISSIONS.COHORT_VIEW,
    SHS_SECURITY_PERMISSIONS.ENROLLMENT_VIEW,
    // Phase 4 — view only.
    SHS_SECURITY_PERMISSIONS.CAREER_EVENT_VIEW,
    SHS_SECURITY_PERMISSIONS.OPPORTUNITY_VIEW,
  ],

  [SHS_SECURITY_ROLES.ORG_ADMIN]: [
    SHS_SECURITY_PERMISSIONS.ORGANIZATION_VIEW,
    SHS_SECURITY_PERMISSIONS.ORGANIZATION_MANAGE,
    SHS_SECURITY_PERMISSIONS.ORGANIZATION_RELATIONSHIP_VIEW,
    SHS_SECURITY_PERMISSIONS.ORGANIZATION_RELATIONSHIP_MANAGE,
    "user.read" as ShsSecurityPermission,
    "role.read" as ShsSecurityPermission,
    "membership.assign" as ShsSecurityPermission,
    "membership.revoke" as ShsSecurityPermission,
    SHS_SECURITY_PERMISSIONS.PROGRAM_CREATE,
    SHS_SECURITY_PERMISSIONS.PROGRAM_READ,
    SHS_SECURITY_PERMISSIONS.PROGRAM_UPDATE,
    SHS_SECURITY_PERMISSIONS.PROGRAM_TRANSITION,
    SHS_SECURITY_PERMISSIONS.PROGRAM_SPECIALIZATION_ASSIGN,
    SHS_SECURITY_PERMISSIONS.PROGRAM_COURSE_ASSIGN,
    SHS_SECURITY_PERMISSIONS.ASSIGNMENT_VIEW,
    SHS_SECURITY_PERMISSIONS.ASSIGNMENT_MANAGE,
    SHS_SECURITY_PERMISSIONS.COHORT_VIEW,
    SHS_SECURITY_PERMISSIONS.COHORT_MANAGE,
    SHS_SECURITY_PERMISSIONS.ENROLLMENT_VIEW,
    SHS_SECURITY_PERMISSIONS.ENROLLMENT_MANAGE,
    SHS_SECURITY_PERMISSIONS.CAREER_EVENT_VIEW,
    SHS_SECURITY_PERMISSIONS.CAREER_EVENT_MANAGE,
    SHS_SECURITY_PERMISSIONS.OPPORTUNITY_VIEW,
    SHS_SECURITY_PERMISSIONS.OPPORTUNITY_MANAGE,
    SHS_SECURITY_PERMISSIONS.LIVE_LEARNING_VIEW,
    SHS_SECURITY_PERMISSIONS.LIVE_LEARNING_CREATE,
    SHS_SECURITY_PERMISSIONS.LIVE_LEARNING_MANAGE,
    SHS_SECURITY_PERMISSIONS.LIVE_LEARNING_JOIN_AUTHORIZE,
    SHS_SECURITY_PERMISSIONS.PROJECT_CREATE,
    SHS_SECURITY_PERMISSIONS.PROJECT_TEAM_MANAGE,
    SHS_SECURITY_PERMISSIONS.PROJECT_SUBMISSION_VIEW,
    SHS_SECURITY_PERMISSIONS.PROJECT_SUBMISSION_REVIEW,
    SHS_SECURITY_PERMISSIONS.PROJECT_VIEW,
    SHS_SECURITY_PERMISSIONS.CREDENTIAL_DEFINITION_MANAGE,
    SHS_SECURITY_PERMISSIONS.CREDENTIAL_ISSUE,
    SHS_SECURITY_PERMISSIONS.CREDENTIAL_REVOKE,
    SHS_SECURITY_PERMISSIONS.CREDENTIAL_VIEW,
    SHS_SECURITY_PERMISSIONS.ARCADE_ACTIVITY_MANAGE,
    SHS_SECURITY_PERMISSIONS.ARCADE_RESULTS_VIEW,
    SHS_SECURITY_PERMISSIONS.CASE_CREATE,
    SHS_SECURITY_PERMISSIONS.CASE_READ,
    SHS_SECURITY_PERMISSIONS.CASE_UPDATE,
    SHS_SECURITY_PERMISSIONS.CASE_ASSIGN,
    SHS_SECURITY_PERMISSIONS.CASE_TRANSITION,
    SHS_SECURITY_PERMISSIONS.AUDIT_READ,
    SHS_SECURITY_PERMISSIONS.REFERRALS_MANAGE,
    // Phase 4.6: org_admin already managed the curriculum catalog
    // destination (create/review/approve/publish) but could not reach
    // the source material feeding a raw-document import — a coherence
    // gap this phase's new UI surface exposed. Source upload/view are
    // the same shape of "curriculum authoring" access already granted.
    SHS_SECURITY_PERMISSIONS.CURRICULUM_SOURCE_UPLOAD,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_SOURCE_VIEW,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_CATALOG_MANAGE,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_CATALOG_APPROVE,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_CATALOG_PUBLISH,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_CATALOG_RETIRE,
  ],
  [SHS_SECURITY_ROLES.OPERATOR]: [
    SHS_SECURITY_PERMISSIONS.PROGRAM_READ,
    SHS_SECURITY_PERMISSIONS.CASE_CREATE,
    SHS_SECURITY_PERMISSIONS.CASE_READ,
    SHS_SECURITY_PERMISSIONS.CASE_UPDATE,
    SHS_SECURITY_PERMISSIONS.CASE_ASSIGN,
    SHS_SECURITY_PERMISSIONS.CASE_TRANSITION,
    SHS_SECURITY_PERMISSIONS.REFERRALS_MANAGE,
  ],
  [SHS_SECURITY_ROLES.PROGRAM_MANAGER]: [
    SHS_SECURITY_PERMISSIONS.PROGRAM_CREATE,
    SHS_SECURITY_PERMISSIONS.PROGRAM_READ,
    SHS_SECURITY_PERMISSIONS.PROGRAM_UPDATE,
    SHS_SECURITY_PERMISSIONS.PROGRAM_TRANSITION,
    SHS_SECURITY_PERMISSIONS.PROGRAM_SPECIALIZATION_ASSIGN,
    SHS_SECURITY_PERMISSIONS.PROGRAM_COURSE_ASSIGN,
    SHS_SECURITY_PERMISSIONS.ASSIGNMENT_VIEW,
    SHS_SECURITY_PERMISSIONS.ASSIGNMENT_MANAGE,
    SHS_SECURITY_PERMISSIONS.COHORT_VIEW,
    SHS_SECURITY_PERMISSIONS.COHORT_MANAGE,
    SHS_SECURITY_PERMISSIONS.ENROLLMENT_VIEW,
    SHS_SECURITY_PERMISSIONS.ENROLLMENT_MANAGE,
    SHS_SECURITY_PERMISSIONS.CAREER_EVENT_VIEW,
    SHS_SECURITY_PERMISSIONS.CAREER_EVENT_MANAGE,
    SHS_SECURITY_PERMISSIONS.OPPORTUNITY_VIEW,
    SHS_SECURITY_PERMISSIONS.OPPORTUNITY_MANAGE,
    SHS_SECURITY_PERMISSIONS.LIVE_LEARNING_VIEW,
    SHS_SECURITY_PERMISSIONS.LIVE_LEARNING_CREATE,
    SHS_SECURITY_PERMISSIONS.LIVE_LEARNING_MANAGE,
    SHS_SECURITY_PERMISSIONS.LIVE_LEARNING_JOIN_AUTHORIZE,
    SHS_SECURITY_PERMISSIONS.PROJECT_CREATE,
    SHS_SECURITY_PERMISSIONS.PROJECT_TEAM_MANAGE,
    SHS_SECURITY_PERMISSIONS.PROJECT_SUBMISSION_VIEW,
    SHS_SECURITY_PERMISSIONS.PROJECT_SUBMISSION_REVIEW,
    SHS_SECURITY_PERMISSIONS.PROJECT_VIEW,
    SHS_SECURITY_PERMISSIONS.CREDENTIAL_DEFINITION_MANAGE,
    SHS_SECURITY_PERMISSIONS.CREDENTIAL_ISSUE,
    SHS_SECURITY_PERMISSIONS.CREDENTIAL_REVOKE,
    SHS_SECURITY_PERMISSIONS.CREDENTIAL_VIEW,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_SOURCE_UPLOAD,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_SOURCE_VIEW,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_CATALOG_MANAGE,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_CATALOG_APPROVE,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_CATALOG_PUBLISH,
    SHS_SECURITY_PERMISSIONS.CURRICULUM_CATALOG_RETIRE,
    SHS_SECURITY_PERMISSIONS.ARCADE_ACTIVITY_MANAGE,
    SHS_SECURITY_PERMISSIONS.ARCADE_RESULTS_VIEW,
    SHS_SECURITY_PERMISSIONS.CASE_READ,
  ],
  [SHS_SECURITY_ROLES.REVIEWER]: [
    SHS_SECURITY_PERMISSIONS.CASE_READ,
    SHS_SECURITY_PERMISSIONS.AUDIT_READ,
  ],
};

export function getPermissionsForRole(role: string): ShsSecurityPermission[] {
  return SHS_ROLE_PERMISSION_MAP[role] || [];
}

export function mergeRolePermissions(roles: string[] = []): ShsSecurityPermission[] {
  return Array.from(new Set(roles.flatMap((role) => getPermissionsForRole(role))));
}

export function hasPermission(permissions: string[] = [], permission: string) {
  return permissions.includes(permission);
}

export function isPlatformGlobalRole(role: string, roleScopeType?: string | null) {
  return role === SHS_SECURITY_ROLES.SUPER_ADMIN || String(roleScopeType || "").toLowerCase() === "platform";
}
