export const ACCOMMODATION_STATES = ["DRAFT", "SUBMITTED", "UNDER_REVIEW", "INFORMATION_REQUESTED", "APPROVED", "DECLINED", "ACTIVE", "SUSPENDED", "EXPIRED", "SUPERSEDED", "CLOSED", "WITHDRAWN"] as const;
export type AccommodationState = typeof ACCOMMODATION_STATES[number];
export const VALID_TRANSITIONS: Record<AccommodationState, AccommodationState[]> = {
  DRAFT: ["SUBMITTED"], SUBMITTED: ["UNDER_REVIEW", "WITHDRAWN"], UNDER_REVIEW: ["INFORMATION_REQUESTED", "APPROVED", "DECLINED", "WITHDRAWN"], INFORMATION_REQUESTED: ["SUBMITTED", "UNDER_REVIEW"], APPROVED: ["ACTIVE", "SUPERSEDED"], DECLINED: ["CLOSED"], ACTIVE: ["SUSPENDED", "EXPIRED", "SUPERSEDED"], SUSPENDED: ["ACTIVE", "CLOSED"], EXPIRED: ["CLOSED"], SUPERSEDED: ["CLOSED"], CLOSED: [], WITHDRAWN: ["CLOSED"],
};
export function canTransition(from: string, to: string) { return (VALID_TRANSITIONS[from as AccommodationState] || []).includes(to as AccommodationState); }
export const REQUIREMENT_TYPES = ["ALTERNATIVE_FORMAT", "CAPTIONS", "TRANSCRIPT", "INTERPRETER", "EXTENDED_TIME", "REDUCED_DISTRACTION", "ACCESSIBLE_MATERIALS", "ASSISTIVE_TECH_SUPPORT", "LIVE_SESSION_SUPPORT", "OTHER_REVIEWED"] as const;
export const FULFILLMENT_STATES = ["NOT_REQUIRED", "PENDING", "IN_PROGRESS", "DELIVERED", "PARTIAL", "BLOCKED", "UNAVAILABLE", "EXTERNAL_DEPENDENCY"] as const;
