import { randomUUID } from "node:crypto";
import { query } from "../../../db/client.js";
import { withTransaction } from "../../../db/transaction.js";
import { writeAuditEvent } from "../../audit/service/audit-helper.js";
import { canTransition, FULFILLMENT_STATES, REQUIREMENT_TYPES } from "../model/lifecycle.js";

const scope = (actor: any) => ({ organizationId: String(actor?.active_organization_id || actor?.organization_id || ""), tenantId: String(actor?.tenant_id || `tenant:${actor?.active_organization_id || actor?.organization_id || ""}`), userId: String(actor?.user_id || actor?.id || "") });
const id = (prefix: string) => `${prefix}_${randomUUID()}`;
function actorScope(actor: any) { const s = scope(actor); if (!s.userId || !s.organizationId) throw new Error("authenticated_organization_required"); return s; }
function shape(row: any, requirements: any[] = []) { return { accommodationCaseId: row.accommodation_case_id, organizationId: row.organization_id, tenantId: row.tenant_id, subjectUserId: row.subject_user_id, requestedByUserId: row.requested_by_user_id, status: row.status, requestType: row.request_type, requestPayload: row.request_payload_json || {}, scope: row.scope_json || {}, reviewedByUserId: row.reviewed_by_user_id, approvedByUserId: row.approved_by_user_id, decisionAt: row.decision_at, effectiveFrom: row.effective_from, effectiveUntil: row.effective_until, reviewAt: row.review_at, assignedOwnerUserId: row.assigned_owner_user_id, supersedesCaseId: row.supersedes_case_id, requirements: requirements.map((r) => ({ requirementId: r.accommodation_requirement_id, requirementType: r.requirement_type, status: r.status, fulfillmentStatus: r.fulfillment_status, scope: r.requirement_payload_json || {}, fulfillmentOwnerUserId: r.fulfillment_owner_user_id, externalDependency: r.external_dependency, fulfilledAt: r.fulfilled_at })) }; }
async function load(caseId: string, actor: any, ownOnly = false) { const s = actorScope(actor); const c = await query(`SELECT * FROM accessibility_accommodation_cases WHERE accommodation_case_id=$1 AND organization_id=$2 AND tenant_id=$3 ${ownOnly ? "AND subject_user_id=$4" : ""}`, ownOnly ? [caseId, s.organizationId, s.tenantId, s.userId] : [caseId, s.organizationId, s.tenantId]); if (!c.rows[0]) return null; const r = await query("SELECT * FROM accessibility_accommodation_requirements WHERE accommodation_case_id=$1 ORDER BY created_at", [caseId]); return shape(c.rows[0], r.rows); }
async function audit(db: any, caseId: string, organizationId: string, actor: any, action: string, previous: any, next: any) { await writeAuditEvent({ audit_event_id: id("audit"), organization_id: organizationId, actor_user_id: actorScope(actor).userId, target_object_type: "accessibility_accommodation_case", target_object_id: caseId, action_type: action, previous_state_json: previous, new_state_json: next, reason_text: action, correlation_id: id("corr"), source_channel: "accessibility-accommodations" }, db); }
async function transition(caseId: string, next: string, actor: any, extra: any = {}, ownOnly = false) { const current = await load(caseId, actor, ownOnly); if (!current) throw new Error("accommodation_case_not_found"); if (!canTransition(current.status, next)) throw new Error(`invalid_accommodation_transition:${current.status}->${next}`); const s = actorScope(actor); await withTransaction(async (db) => { const result = await db.query(`UPDATE accessibility_accommodation_cases SET status=$1, reviewed_by_user_id=CASE WHEN $1='UNDER_REVIEW' THEN $2 ELSE reviewed_by_user_id END, approved_by_user_id=CASE WHEN $1 IN ('APPROVED','DECLINED') THEN $2 ELSE approved_by_user_id END, decision_at=CASE WHEN $1 IN ('APPROVED','DECLINED') THEN NOW() ELSE decision_at END, effective_from=COALESCE($3,effective_from), effective_until=COALESCE($4,effective_until), revision=revision+1, updated_at=NOW() WHERE accommodation_case_id=$5 AND organization_id=$6 AND tenant_id=$7 ${ownOnly ? "AND subject_user_id=$8" : ""} RETURNING *`, ownOnly ? [next, s.userId, extra.effectiveFrom || null, extra.effectiveUntil || null, caseId, s.organizationId, s.tenantId, s.userId] : [next, s.userId, extra.effectiveFrom || null, extra.effectiveUntil || null, caseId, s.organizationId, s.tenantId]); if (!result.rows[0]) throw new Error("accommodation_case_not_found"); await audit(db, caseId, s.organizationId, actor, `accommodation.${next.toLowerCase()}`, { status: current.status }, { status: next, ...extra }); }); return load(caseId, actor); }
export async function createDraft(input: any, actor: any) { const s = actorScope(actor); const type = String(input?.requestType || "").toUpperCase(); if (!REQUIREMENT_TYPES.includes(type as any)) throw new Error("invalid_request_type"); if (String(input?.subjectUserId || s.userId) !== s.userId) throw new Error("requestor_subject_mismatch"); const caseId = id("accommodation_case"); const result = await query(`INSERT INTO accessibility_accommodation_cases (accommodation_case_id,organization_id,tenant_id,subject_user_id,requested_by_user_id,request_type,request_payload_json,scope_json) VALUES ($1,$2,$3,$4,$4,$5,$6::jsonb,$7::jsonb) RETURNING *`, [caseId, s.organizationId, s.tenantId, s.userId, type, JSON.stringify(input.requestPayload || {}), JSON.stringify(input.scope || {})]); await audit({ query }, caseId, s.organizationId, actor, "accommodation.draft_created", null, { status: "DRAFT" }); return load(caseId, actor, true); }
export const submitRequest = (caseId: string, actor: any) => transition(caseId, "SUBMITTED", actor, {}, true);
export const getOwnCase = (caseId: string, actor: any) => load(caseId, actor, true);
export async function listAuthorizedCases(actor: any) { const s = actorScope(actor); const result = await query("SELECT accommodation_case_id FROM accessibility_accommodation_cases WHERE organization_id=$1 AND tenant_id=$2 ORDER BY updated_at DESC", [s.organizationId, s.tenantId]); return Promise.all(result.rows.map((r) => load(r.accommodation_case_id, actor))); }
export const startReview = (caseId: string, actor: any) => transition(caseId, "UNDER_REVIEW", actor);
export const requestInformation = (caseId: string, actor: any) => transition(caseId, "INFORMATION_REQUESTED", actor);
export async function approve(caseId: string, input: any, actor: any) { const requirements = Array.isArray(input?.requirements) ? input.requirements : []; if (!requirements.length) throw new Error("approved_requirements_required"); for (const item of requirements) if (!REQUIREMENT_TYPES.includes(String(item.requirementType || "").toUpperCase() as any)) throw new Error("invalid_requirement_type"); await transition(caseId, "APPROVED", actor, input); for (const item of requirements) { const type = String(item.requirementType).toUpperCase(); await query("INSERT INTO accessibility_accommodation_requirements (accommodation_requirement_id,accommodation_case_id,requirement_type,requirement_payload_json,fulfillment_owner_user_id,external_dependency) VALUES ($1,$2,$3,$4::jsonb,$5,$6)", [id("accommodation_requirement"), caseId, type, JSON.stringify(item.payload || {}), item.fulfillmentOwnerUserId || null, item.externalDependency || null]); } return load(caseId, actor); }
export const decline = (caseId: string, input: any, actor: any) => transition(caseId, "DECLINED", actor, { reasonCategory: input?.reasonCategory || "REVIEWED_DECISION" });
export async function activate(caseId: string, actor: any) { const active = await transition(caseId, "ACTIVE", actor); const s = actorScope(actor); const reqs = await query("SELECT requirement_type, requirement_payload_json FROM accessibility_accommodation_requirements WHERE accommodation_case_id=$1", [caseId]); const mappings: Record<string, string> = { ALTERNATIVE_FORMAT: "ALTERNATE_PRESENTATION", EXTENDED_TIME: "EXTENDED_ASSESSMENT_TIME", REDUCED_DISTRACTION: "ALTERNATE_PRESENTATION", ASSISTIVE_TECH_SUPPORT: "ALTERNATE_INPUT_METHOD" }; for (const requirement of reqs.rows) { const grantType = mappings[requirement.requirement_type]; if (!grantType) continue; const exists = await query("SELECT accommodation_id FROM authorized_accommodations WHERE organization_id=$1 AND user_id=$2 AND accommodation_type=$3 AND status='ACTIVE' LIMIT 1", [s.organizationId, active.subjectUserId, grantType]); if (!exists.rows[0]) await query("INSERT INTO authorized_accommodations (accommodation_id,organization_id,user_id,membership_id,accommodation_type,value,effective_at,expires_at,granted_by_user_id) VALUES ($1,$2,$3,$4,$5,$6::jsonb,COALESCE($7,NOW()),$8,$9)", [id("authorized_accommodation"), s.organizationId, active.subjectUserId, actor.membership_id || null, grantType, JSON.stringify(requirement.requirement_payload_json || {}), active.effectiveFrom || null, active.effectiveUntil || null, s.userId]); } return load(caseId, actor); }
export const withdraw = (caseId: string, actor: any) => transition(caseId, "WITHDRAWN", actor, {}, true);
export const expire = (caseId: string, actor: any) => transition(caseId, "EXPIRED", actor);
export const supersede = (caseId: string, actor: any) => transition(caseId, "SUPERSEDED", actor);
export async function updateRequirementFulfillment(caseId: string, requirementId: string, fulfillmentStatus: string, actor: any) { const s = actorScope(actor); if (!FULFILLMENT_STATES.includes(fulfillmentStatus as any)) throw new Error("invalid_fulfillment_status"); const result = await query(`UPDATE accessibility_accommodation_requirements r SET fulfillment_status=$1, fulfilled_at=CASE WHEN $1='DELIVERED' THEN NOW() ELSE NULL END, updated_at=NOW() FROM accessibility_accommodation_cases c WHERE r.accommodation_requirement_id=$2 AND r.accommodation_case_id=$3 AND c.organization_id=$4 AND c.tenant_id=$5 RETURNING r.*`, [fulfillmentStatus, requirementId, caseId, s.organizationId, s.tenantId]); if (!result.rows[0]) throw new Error("accommodation_requirement_not_found"); await audit({ query }, caseId, s.organizationId, actor, "accommodation.fulfillment_changed", null, { requirementId, fulfillmentStatus }); return load(caseId, actor); }
export async function getMinimumNecessaryProjection(caseId: string, actor: any) { const item = await load(caseId, actor); if (!item) return null; return { accommodationCaseId: item.accommodationCaseId, status: item.status, scope: item.scope, effectiveFrom: item.effectiveFrom, effectiveUntil: item.effectiveUntil, requirements: item.requirements.map((r) => ({ requirementType: r.requirementType, fulfillmentStatus: r.fulfillmentStatus, scope: r.scope, externalDependency: r.externalDependency })) }; }
