import React from "react";

const STATUS_LABELS = {
  BLOCKED: "BLOCKED", QA_REQUIRED: "ACTION REQUIRED", REVIEW_REQUIRED: "ACTION REQUIRED", APPROVAL_REQUIRED: "READY FOR APPROVAL", ASSURANCE_READY: "READY FOR APPROVAL", AUTHORIZED: "AUTHORIZED", RELEASING: "RELEASING", RELEASED: "RELEASED", FAILED: "FAILED", ROLLBACK_REQUIRED: "ROLLBACK REQUIRED", ROLLED_BACK: "ROLLED BACK",
};

export default function ReleaseAssurancePage() {
  const [releases, setReleases] = React.useState([]); const [selected, setSelected] = React.useState(null); const [error, setError] = React.useState(""); const [loading, setLoading] = React.useState(true);
  const load = React.useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch("/api/arag/releases", { credentials: "include" }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload?.error?.message || "Release Assurance is unavailable."); const items = payload.data?.items || []; setReleases(items); setSelected((current) => current || items[0] || null); } catch (nextError) { setError(nextError.message || "Release Assurance is unavailable."); } finally { setLoading(false); } }, []);
  React.useEffect(() => { load(); }, [load]);
  return <main style={{ maxWidth: 1100, margin: "0 auto", padding: "32px 24px 56px", color: "#132238" }}>
    <header style={{ display: "flex", justifyContent: "space-between", gap: 16, flexWrap: "wrap", marginBottom: 24 }}><div><p style={{ margin: "0 0 6px", color: "#52647a", fontSize: 12, fontWeight: 700, letterSpacing: 1 }}>ARAG-1</p><h1 style={{ margin: 0 }}>Release Assurance</h1><p style={{ color: "#52647a" }}>Production release decisions are bound to one exact revision, approval, and assurance packet.</p></div><button type="button" onClick={load} style={{ border: "1px solid #9aaabd", borderRadius: 5, background: "#fff", padding: "9px 14px", cursor: "pointer" }}>Refresh</button></header>
    {loading && <p>Loading release requests...</p>}{error && <p role="alert" style={{ color: "#a12828" }}>{error}</p>}{!loading && !error && !releases.length && <p>No governed release requests are available.</p>}
    {!loading && !error && releases.length > 0 && <div style={{ display: "grid", gridTemplateColumns: "minmax(260px, .8fr) minmax(0, 1.5fr)", gap: 20 }}><section style={{ display: "grid", gap: 10, alignContent: "start" }}>{releases.map((release) => <button type="button" key={release.releaseRequestId} onClick={() => setSelected(release)} style={{ textAlign: "left", border: `1px solid ${selected?.releaseRequestId === release.releaseRequestId ? "#315b85" : "#d8dee7"}`, borderRadius: 6, background: "#fff", padding: 14, cursor: "pointer" }}><strong>{release.projectId}</strong><div style={{ marginTop: 6, color: "#52647a", fontSize: 13 }}>Revision {release.workspaceRevision} · {STATUS_LABELS[release.status] || release.status}</div></button>)}</section><section style={{ border: "1px solid #d8dee7", borderRadius: 6, background: "#fff", padding: 20 }}>{selected && <><div style={{ display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap" }}><h2 style={{ margin: 0 }}>{STATUS_LABELS[selected.status] || selected.status}</h2><span style={{ color: "#52647a", fontSize: 13 }}>Revision {selected.workspaceRevision}</span></div><dl style={{ display: "grid", gridTemplateColumns: "max-content 1fr", gap: "10px 18px", marginTop: 22, fontSize: 14 }}><dt>Project</dt><dd>{selected.projectId}</dd><dt>Provider</dt><dd>{selected.providerKey}</dd><dt>Target</dt><dd>{selected.targetEnvironment}</dd><dt>QA run</dt><dd>{selected.qaRunId}</dd><dt>Review</dt><dd>{selected.reviewSubmissionId}</dd><dt>Simulation</dt><dd>{selected.simulationId}</dd><dt>Policy</dt><dd>{selected.policyDecision}</dd><dt>Subject hash</dt><dd style={{ overflowWrap: "anywhere" }}>{selected.subjectHash}</dd></dl>{selected.blockingCodes?.length > 0 && <div style={{ borderTop: "1px solid #d8dee7", paddingTop: 16 }}><strong>Blocking conditions</strong><ul>{selected.blockingCodes.map((code) => <li key={code}>{code}</li>)}</ul></div>}<p style={{ marginTop: 22, color: "#52647a", fontSize: 13 }}>Release execution is only available after ARAG-1 assurance, attributable approval, and a single-use authorization envelope.</p></>}</section></div>}
  </main>;
}
