-- Government Program Assurance Phase 7: operational oversight authorities.
-- Monitoring, audit, investigation, recovery, and decisions remain distinct.

CREATE TABLE IF NOT EXISTS gpa_requirements (
  requirement_id TEXT NOT NULL, version INTEGER NOT NULL CHECK (version > 0), organization_id TEXT NOT NULL REFERENCES organizations(organization_id), tenant_id TEXT NOT NULL,
  requirement_type TEXT NOT NULL, authority TEXT NOT NULL, citation_reference TEXT, title TEXT NOT NULL, description TEXT NOT NULL, jurisdiction_reference TEXT, applicability JSONB NOT NULL DEFAULT '{}'::JSONB,
  effective_from TIMESTAMPTZ NOT NULL, effective_to TIMESTAMPTZ, status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','ACTIVE','RETIRED')), supersedes_requirement_version TEXT, owner_reference TEXT, approver_reference TEXT, provenance JSONB NOT NULL DEFAULT '{}'::JSONB, created_by TEXT NOT NULL REFERENCES users(user_id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (requirement_id,version), CONSTRAINT gpa_requirement_scope CHECK (tenant_id='tenant:'||organization_id), CONSTRAINT gpa_requirement_window CHECK (effective_to IS NULL OR effective_to>effective_from)
);
CREATE TABLE IF NOT EXISTS gpa_controls (
  control_id TEXT NOT NULL, version INTEGER NOT NULL CHECK (version > 0), organization_id TEXT NOT NULL REFERENCES organizations(organization_id), tenant_id TEXT NOT NULL, requirement_id TEXT NOT NULL, requirement_version INTEGER NOT NULL, objective TEXT NOT NULL, owner_reference TEXT, control_type TEXT NOT NULL, test_method TEXT NOT NULL, evidence_requirements JSONB NOT NULL DEFAULT '[]'::JSONB, frequency TEXT, applicability JSONB NOT NULL DEFAULT '{}'::JSONB, effective_from TIMESTAMPTZ NOT NULL, effective_to TIMESTAMPTZ, status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','ACTIVE','RETIRED')), provenance JSONB NOT NULL DEFAULT '{}'::JSONB, created_by TEXT NOT NULL REFERENCES users(user_id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY (control_id,version), CONSTRAINT gpa_control_scope CHECK (tenant_id='tenant:'||organization_id), CONSTRAINT gpa_control_requirement_fk FOREIGN KEY (requirement_id,requirement_version) REFERENCES gpa_requirements(requirement_id,version)
);
CREATE TABLE IF NOT EXISTS gpa_monitoring_plans (
  monitoring_plan_id TEXT PRIMARY KEY, organization_id TEXT NOT NULL REFERENCES organizations(organization_id), tenant_id TEXT NOT NULL, program_reference TEXT, provider_reference TEXT, funding_reference TEXT, period_start DATE, period_end DATE, monitoring_type TEXT NOT NULL, scope JSONB NOT NULL DEFAULT '{}'::JSONB, objectives JSONB NOT NULL DEFAULT '[]'::JSONB, control_references JSONB NOT NULL DEFAULT '[]'::JSONB, planned_activities JSONB NOT NULL DEFAULT '[]'::JSONB, assigned_reviewer TEXT, risk_reference TEXT, schedule JSONB NOT NULL DEFAULT '{}'::JSONB, status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','APPROVED','ACTIVE','COMPLETED','CANCELLED')), created_by TEXT NOT NULL REFERENCES users(user_id), approved_by TEXT, provenance JSONB NOT NULL DEFAULT '{}'::JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), CONSTRAINT gpa_monitoring_plan_scope CHECK (tenant_id='tenant:'||organization_id)
);
CREATE TABLE IF NOT EXISTS gpa_monitoring_activities (
  activity_id TEXT PRIMARY KEY, monitoring_plan_id TEXT NOT NULL REFERENCES gpa_monitoring_plans(monitoring_plan_id), organization_id TEXT NOT NULL REFERENCES organizations(organization_id), tenant_id TEXT NOT NULL, activity_type TEXT NOT NULL, reviewer_reference TEXT, scheduled_at TIMESTAMPTZ, started_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, status TEXT NOT NULL DEFAULT 'PLANNED' CHECK (status IN ('PLANNED','IN_PROGRESS','COMPLETED','CANCELLED')), control_references JSONB NOT NULL DEFAULT '[]'::JSONB, evidence_references JSONB NOT NULL DEFAULT '[]'::JSONB, observations JSONB NOT NULL DEFAULT '[]'::JSONB, exceptions JSONB NOT NULL DEFAULT '[]'::JSONB, result JSONB NOT NULL DEFAULT '{}'::JSONB, provenance JSONB NOT NULL DEFAULT '{}'::JSONB, created_by TEXT NOT NULL REFERENCES users(user_id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), CONSTRAINT gpa_monitoring_activity_scope CHECK (tenant_id='tenant:'||organization_id)
);
CREATE TABLE IF NOT EXISTS gpa_evidence_requests (
  evidence_request_id TEXT PRIMARY KEY, organization_id TEXT NOT NULL REFERENCES organizations(organization_id), tenant_id TEXT NOT NULL, monitoring_reference TEXT, audit_reference TEXT, provider_reference TEXT, program_reference TEXT, requirement_reference TEXT, control_reference TEXT, evidence_type TEXT NOT NULL, requested_by TEXT NOT NULL REFERENCES users(user_id), requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), due_at TIMESTAMPTZ, status TEXT NOT NULL DEFAULT 'REQUESTED' CHECK (status IN ('REQUESTED','RECEIVED','OVERDUE','CANCELLED','REVIEW_REQUIRED')), response_reference TEXT, received_at TIMESTAMPTZ, admissibility_status TEXT, escalation_state TEXT, provenance JSONB NOT NULL DEFAULT '{}'::JSONB, CONSTRAINT gpa_evidence_request_scope CHECK (tenant_id='tenant:'||organization_id)
);
CREATE TABLE IF NOT EXISTS gpa_findings (
  finding_id TEXT PRIMARY KEY, organization_id TEXT NOT NULL REFERENCES organizations(organization_id), tenant_id TEXT NOT NULL, monitoring_reference TEXT, audit_reference TEXT, provider_reference TEXT, program_reference TEXT, requirement_reference TEXT, control_reference TEXT, finding_type TEXT NOT NULL, severity TEXT NOT NULL, materiality TEXT NOT NULL, description TEXT NOT NULL, evidence_references JSONB NOT NULL DEFAULT '[]'::JSONB, verification_references JSONB NOT NULL DEFAULT '[]'::JSONB, reconciliation_references JSONB NOT NULL DEFAULT '[]'::JSONB, detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), determined_at TIMESTAMPTZ, determined_by TEXT, status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','UNDER_REVIEW','PROPOSED','ISSUED','DISPUTED','CONFIRMED','CORRECTIVE_ACTION_REQUIRED','REMEDIATION_IN_PROGRESS','RETEST_REQUIRED','RESOLVED','CLOSED','WITHDRAWN','SUPERSEDED')), provider_response_state TEXT, corrective_action_required BOOLEAN NOT NULL DEFAULT FALSE, appeal_state TEXT, provenance JSONB NOT NULL DEFAULT '{}'::JSONB, created_by TEXT NOT NULL REFERENCES users(user_id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), CONSTRAINT gpa_finding_scope CHECK (tenant_id='tenant:'||organization_id)
);
CREATE TABLE IF NOT EXISTS gpa_corrective_actions (
  corrective_action_id TEXT PRIMARY KEY, finding_id TEXT NOT NULL REFERENCES gpa_findings(finding_id), organization_id TEXT NOT NULL REFERENCES organizations(organization_id), tenant_id TEXT NOT NULL, provider_reference TEXT, program_reference TEXT, required_action TEXT NOT NULL, action_owner TEXT NOT NULL, due_at TIMESTAMPTZ, milestones JSONB NOT NULL DEFAULT '[]'::JSONB, required_evidence JSONB NOT NULL DEFAULT '[]'::JSONB, submitted_by TEXT, approved_by TEXT, status TEXT NOT NULL DEFAULT 'REQUIRED' CHECK (status IN ('REQUIRED','PROPOSED','APPROVED','IN_PROGRESS','EVIDENCE_SUBMITTED','RETEST_PENDING','COMPLETE','REJECTED','OVERDUE','ESCALATED','CLOSED')), extension_history JSONB NOT NULL DEFAULT '[]'::JSONB, escalation_state TEXT, completed_at TIMESTAMPTZ, provenance JSONB NOT NULL DEFAULT '{}'::JSONB, created_by TEXT NOT NULL REFERENCES users(user_id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), CONSTRAINT gpa_corrective_action_scope CHECK (tenant_id='tenant:'||organization_id)
);
CREATE TABLE IF NOT EXISTS gpa_audit_engagements (
  audit_engagement_id TEXT PRIMARY KEY, organization_id TEXT NOT NULL REFERENCES organizations(organization_id), tenant_id TEXT NOT NULL, audit_type TEXT NOT NULL, authority_reference TEXT NOT NULL, scope JSONB NOT NULL DEFAULT '{}'::JSONB, period_start DATE, period_end DATE, objectives JSONB NOT NULL DEFAULT '[]'::JSONB, population JSONB NOT NULL DEFAULT '{}'::JSONB, methodology JSONB NOT NULL DEFAULT '{}'::JSONB, assigned_auditors JSONB NOT NULL DEFAULT '[]'::JSONB, independence_requirements JSONB NOT NULL DEFAULT '{}'::JSONB, status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','PLANNING','FIELDWORK','REVIEW','CLOSED','CANCELLED')), opened_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), closed_at TIMESTAMPTZ, approval_reference TEXT, provenance JSONB NOT NULL DEFAULT '{}'::JSONB, created_by TEXT NOT NULL REFERENCES users(user_id), CONSTRAINT gpa_audit_scope CHECK (tenant_id='tenant:'||organization_id)
);
CREATE TABLE IF NOT EXISTS gpa_audit_workpapers (
  workpaper_id TEXT PRIMARY KEY, audit_engagement_id TEXT NOT NULL REFERENCES gpa_audit_engagements(audit_engagement_id), organization_id TEXT NOT NULL REFERENCES organizations(organization_id), tenant_id TEXT NOT NULL, audit_step TEXT NOT NULL, preparer_reference TEXT NOT NULL, reviewer_reference TEXT, evidence_references JSONB NOT NULL DEFAULT '[]'::JSONB, procedures JSONB NOT NULL DEFAULT '[]'::JSONB, conclusion TEXT, review_notes JSONB NOT NULL DEFAULT '[]'::JSONB, status TEXT NOT NULL DEFAULT 'PREPARED' CHECK (status IN ('PREPARED','IN_REVIEW','REVIEWED','REOPENED')), prepared_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), reviewed_at TIMESTAMPTZ, provenance JSONB NOT NULL DEFAULT '{}'::JSONB, CONSTRAINT gpa_workpaper_scope CHECK (tenant_id='tenant:'||organization_id)
);
CREATE TABLE IF NOT EXISTS gpa_samples (
  sample_id TEXT PRIMARY KEY, organization_id TEXT NOT NULL REFERENCES organizations(organization_id), tenant_id TEXT NOT NULL, monitoring_reference TEXT, audit_engagement_id TEXT, population_definition JSONB NOT NULL, population_size INTEGER NOT NULL CHECK (population_size>=0), method TEXT NOT NULL CHECK (method IN ('RANDOM','STRATIFIED','RISK_BASED','MONETARY_UNIT')), random_seed TEXT, strata JSONB NOT NULL DEFAULT '[]'::JSONB, risk_criteria JSONB NOT NULL DEFAULT '{}'::JSONB, sample_size INTEGER NOT NULL CHECK (sample_size>=0), selected_record_references JSONB NOT NULL DEFAULT '[]'::JSONB, methodology_version TEXT NOT NULL, created_by TEXT NOT NULL REFERENCES users(user_id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), provenance JSONB NOT NULL DEFAULT '{}'::JSONB, CONSTRAINT gpa_sample_scope CHECK (tenant_id='tenant:'||organization_id)
);
CREATE TABLE IF NOT EXISTS gpa_investigations (
  investigation_id TEXT PRIMARY KEY, organization_id TEXT NOT NULL REFERENCES organizations(organization_id), tenant_id TEXT NOT NULL, referral_source TEXT NOT NULL, intake_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), subject_reference TEXT, provider_reference TEXT, program_reference TEXT, allegation_category TEXT NOT NULL, triage TEXT NOT NULL, classification TEXT NOT NULL DEFAULT 'HIGHLY_RESTRICTED', assigned_investigator TEXT, status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','TRIAGE','ACTIVE','ON_HOLD','REFERRED','CLOSED')), evidence_references JSONB NOT NULL DEFAULT '[]'::JSONB, related_entities JSONB NOT NULL DEFAULT '[]'::JSONB, legal_hold_reference TEXT, external_referral_reference TEXT, disposition JSONB, opened_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), closed_at TIMESTAMPTZ, provenance JSONB NOT NULL DEFAULT '{}'::JSONB, created_by TEXT NOT NULL REFERENCES users(user_id), CONSTRAINT gpa_investigation_scope CHECK (tenant_id='tenant:'||organization_id)
);
CREATE TABLE IF NOT EXISTS gpa_recovery_cases (
  recovery_case_id TEXT PRIMARY KEY, organization_id TEXT NOT NULL REFERENCES organizations(organization_id), tenant_id TEXT NOT NULL, finding_reference TEXT, investigation_reference TEXT, audit_reference TEXT, provider_reference TEXT, program_reference TEXT, payment_reference TEXT, determined_improper_amount NUMERIC NOT NULL CHECK (determined_improper_amount>=0), notice_at TIMESTAMPTZ, dispute_status TEXT, determination JSONB NOT NULL, recovery_method TEXT, repayment_schedule_reference TEXT, recovered_amount NUMERIC NOT NULL DEFAULT 0 CHECK (recovered_amount>=0), outstanding_amount NUMERIC NOT NULL DEFAULT 0 CHECK (outstanding_amount>=0), offset_reference TEXT, status TEXT NOT NULL DEFAULT 'PROPOSED' CHECK (status IN ('PROPOSED','NOTICE_ISSUED','DISPUTED','DETERMINED','REPAYMENT_ACTIVE','OFFSET_ACTIVE','PARTIALLY_RECOVERED','RECOVERED','WAIVED','CLOSED')), provenance JSONB NOT NULL DEFAULT '{}'::JSONB, created_by TEXT NOT NULL REFERENCES users(user_id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), CONSTRAINT gpa_recovery_scope CHECK (tenant_id='tenant:'||organization_id), CONSTRAINT gpa_recovery_amount CHECK (recovered_amount<=determined_improper_amount)
);
CREATE TABLE IF NOT EXISTS gpa_decisions (
  decision_id TEXT PRIMARY KEY, organization_id TEXT NOT NULL REFERENCES organizations(organization_id), tenant_id TEXT NOT NULL, decision_type TEXT NOT NULL, authority_reference TEXT NOT NULL, actor_reference TEXT NOT NULL, subject_type TEXT NOT NULL, subject_reference TEXT NOT NULL, facts_considered JSONB NOT NULL DEFAULT '[]'::JSONB, metrics_considered JSONB NOT NULL DEFAULT '[]'::JSONB, evidence_considered JSONB NOT NULL DEFAULT '[]'::JSONB, requirements_invoked JSONB NOT NULL DEFAULT '[]'::JSONB, recommendations JSONB NOT NULL DEFAULT '[]'::JSONB, ai_involvement JSONB NOT NULL DEFAULT '{}'::JSONB, approvals JSONB NOT NULL DEFAULT '[]'::JSONB, dissent_or_exception JSONB NOT NULL DEFAULT '{}'::JSONB, appeal JSONB NOT NULL DEFAULT '{}'::JSONB, final_disposition JSONB NOT NULL, effective_at TIMESTAMPTZ NOT NULL, supersedes_decision_id TEXT, provenance JSONB NOT NULL DEFAULT '{}'::JSONB, created_by TEXT NOT NULL REFERENCES users(user_id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), CONSTRAINT gpa_decision_scope CHECK (tenant_id='tenant:'||organization_id)
);
CREATE TABLE IF NOT EXISTS gpa_control_executions (
  control_execution_id TEXT PRIMARY KEY, organization_id TEXT NOT NULL REFERENCES organizations(organization_id), tenant_id TEXT NOT NULL, control_id TEXT NOT NULL, control_version INTEGER NOT NULL, trigger_type TEXT NOT NULL CHECK (trigger_type IN ('SCHEDULED','EVENT','MANUAL')), scope JSONB NOT NULL DEFAULT '{}'::JSONB, result TEXT NOT NULL CHECK (result IN ('PASS','FAIL','MISSING_EVIDENCE','EXCEPTION')), evidence_references JSONB NOT NULL DEFAULT '[]'::JSONB, escalation JSONB NOT NULL DEFAULT '{}'::JSONB, executed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), executed_by TEXT NOT NULL REFERENCES users(user_id), provenance JSONB NOT NULL DEFAULT '{}'::JSONB, CONSTRAINT gpa_control_execution_scope CHECK (tenant_id='tenant:'||organization_id)
);

CREATE TABLE IF NOT EXISTS gpa_provider_responses (
  response_id TEXT PRIMARY KEY, finding_id TEXT NOT NULL REFERENCES gpa_findings(finding_id), organization_id TEXT NOT NULL REFERENCES organizations(organization_id), tenant_id TEXT NOT NULL,
  provider_reference TEXT NOT NULL, responder_reference TEXT NOT NULL, response_type TEXT NOT NULL, narrative_reference TEXT, supporting_evidence_references JSONB NOT NULL DEFAULT '[]'::JSONB,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), status TEXT NOT NULL DEFAULT 'SUBMITTED' CHECK (status IN ('SUBMITTED','ACCEPTED','REJECTED','REVIEW_REQUIRED')),
  reviewer_reference TEXT, provenance JSONB NOT NULL DEFAULT '{}'::JSONB, created_by TEXT NOT NULL REFERENCES users(user_id),
  CONSTRAINT gpa_provider_response_scope CHECK (tenant_id='tenant:'||organization_id)
);
CREATE TABLE IF NOT EXISTS gpa_sample_results (
  sample_result_id TEXT PRIMARY KEY, sample_id TEXT NOT NULL REFERENCES gpa_samples(sample_id), organization_id TEXT NOT NULL REFERENCES organizations(organization_id), tenant_id TEXT NOT NULL,
  selected_record_reference TEXT NOT NULL, evidence_references JSONB NOT NULL DEFAULT '[]'::JSONB, test_performed TEXT NOT NULL, result TEXT NOT NULL CHECK (result IN ('PASS','FAIL','INCONCLUSIVE','NOT_TESTED')),
  exception JSONB, finding_reference TEXT, reviewer_reference TEXT, tested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), provenance JSONB NOT NULL DEFAULT '{}'::JSONB,
  CONSTRAINT gpa_sample_result_scope CHECK (tenant_id='tenant:'||organization_id)
);
CREATE INDEX IF NOT EXISTS gpa_monitoring_queue_idx ON gpa_monitoring_plans (organization_id, tenant_id, status, period_end);
CREATE INDEX IF NOT EXISTS gpa_finding_queue_idx ON gpa_findings (organization_id, tenant_id, status, severity, detected_at);
CREATE INDEX IF NOT EXISTS gpa_corrective_queue_idx ON gpa_corrective_actions (organization_id, tenant_id, status, due_at);
CREATE INDEX IF NOT EXISTS gpa_investigation_restricted_idx ON gpa_investigations (organization_id, tenant_id, status, classification);
CREATE INDEX IF NOT EXISTS gpa_provider_response_queue_idx ON gpa_provider_responses (organization_id, tenant_id, status, submitted_at);
CREATE INDEX IF NOT EXISTS gpa_sample_result_idx ON gpa_sample_results (organization_id, tenant_id, sample_id, result);
