-- Wave 3: derived, explainable early-warning and Money-at-Risk records.
-- Truth, metrics, findings, actions, decisions, and public disclosure remain
-- owned by their existing canonical authorities.
CREATE TABLE IF NOT EXISTS gpa_risk_rules (
  rule_id TEXT NOT NULL,
  version INTEGER NOT NULL CHECK (version > 0),
  organization_id TEXT NOT NULL REFERENCES organizations(organization_id),
  tenant_id TEXT NOT NULL,
  signal_type TEXT NOT NULL,
  threshold NUMERIC,
  severity TEXT NOT NULL CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
  materiality TEXT NOT NULL CHECK (materiality IN ('IMMATERIAL','MODERATE','MATERIAL','HIGHLY_MATERIAL')),
  evaluation_period TEXT,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  review_required BOOLEAN NOT NULL DEFAULT TRUE,
  escalation_required BOOLEAN NOT NULL DEFAULT FALSE,
  effective_from TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  effective_to TIMESTAMPTZ,
  provenance JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_by TEXT NOT NULL REFERENCES users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (rule_id, version),
  CONSTRAINT gpa_risk_rule_scope CHECK (tenant_id = 'tenant:' || organization_id),
  CONSTRAINT gpa_risk_rule_window CHECK (effective_to IS NULL OR effective_to > effective_from)
);
CREATE TABLE IF NOT EXISTS gpa_risk_evaluations (
  evaluation_id TEXT PRIMARY KEY,
  rule_id TEXT NOT NULL,
  rule_version INTEGER NOT NULL,
  organization_id TEXT NOT NULL REFERENCES organizations(organization_id),
  tenant_id TEXT NOT NULL,
  provider_reference TEXT,
  program_reference TEXT,
  cycle_reference TEXT,
  inputs JSONB NOT NULL DEFAULT '{}'::JSONB,
  result TEXT NOT NULL CHECK (result IN ('TRIGGERED','NOT_TRIGGERED','INSUFFICIENT_DATA')),
  explanation TEXT NOT NULL,
  evaluated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  provenance JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_by TEXT NOT NULL REFERENCES users(user_id),
  CONSTRAINT gpa_risk_eval_scope CHECK (tenant_id = 'tenant:' || organization_id),
  FOREIGN KEY (rule_id, rule_version) REFERENCES gpa_risk_rules(rule_id, version)
);
CREATE TABLE IF NOT EXISTS gpa_risk_signals (
  signal_id TEXT PRIMARY KEY,
  evaluation_id TEXT NOT NULL REFERENCES gpa_risk_evaluations(evaluation_id),
  signal_type TEXT NOT NULL,
  rule_id TEXT NOT NULL,
  rule_version INTEGER NOT NULL,
  organization_id TEXT NOT NULL REFERENCES organizations(organization_id),
  tenant_id TEXT NOT NULL,
  provider_reference TEXT,
  program_reference TEXT,
  cycle_reference TEXT,
  affected_references JSONB NOT NULL DEFAULT '[]'::JSONB,
  severity TEXT NOT NULL CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
  materiality TEXT NOT NULL CHECK (materiality IN ('IMMATERIAL','MODERATE','MATERIAL','HIGHLY_MATERIAL')),
  confidence NUMERIC CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
  explanation TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','UNDER_REVIEW','RESOLVED','DISMISSED')),
  detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  provenance JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_by TEXT NOT NULL REFERENCES users(user_id),
  CONSTRAINT gpa_risk_signal_scope CHECK (tenant_id = 'tenant:' || organization_id),
  FOREIGN KEY (rule_id, rule_version) REFERENCES gpa_risk_rules(rule_id, version)
);
CREATE TABLE IF NOT EXISTS gpa_money_at_risk (
  exposure_id TEXT PRIMARY KEY,
  exposure_reference TEXT NOT NULL,
  organization_id TEXT NOT NULL REFERENCES organizations(organization_id),
  tenant_id TEXT NOT NULL,
  jurisdiction_reference TEXT,
  program_reference TEXT,
  provider_reference TEXT,
  funding_reference TEXT,
  award_reference TEXT,
  service_reference TEXT,
  cycle_reference TEXT,
  amount_basis NUMERIC NOT NULL CHECK (amount_basis >= 0),
  amount_at_risk NUMERIC NOT NULL CHECK (amount_at_risk >= 0),
  currency TEXT NOT NULL,
  calculation_version TEXT NOT NULL,
  signal_references JSONB NOT NULL DEFAULT '[]'::JSONB,
  claim_references JSONB NOT NULL DEFAULT '[]'::JSONB,
  evidence_references JSONB NOT NULL DEFAULT '[]'::JSONB,
  reconciliation_references JSONB NOT NULL DEFAULT '[]'::JSONB,
  finding_reference TEXT,
  corrective_action_reference TEXT,
  decision_reference TEXT,
  confidence NUMERIC CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
  materiality TEXT NOT NULL CHECK (materiality IN ('IMMATERIAL','MODERATE','MATERIAL','HIGHLY_MATERIAL')),
  status TEXT NOT NULL CHECK (status IN ('NONE','POTENTIAL','ESTIMATED','CONFIRMED_EXPOSURE','UNDER_REVIEW','REMEDIATING','RESOLVED','ESCALATED')),
  rationale TEXT NOT NULL,
  provenance JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_by TEXT NOT NULL REFERENCES users(user_id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT gpa_money_risk_scope CHECK (tenant_id = 'tenant:' || organization_id),
  UNIQUE (organization_id, tenant_id, exposure_reference)
);
CREATE INDEX IF NOT EXISTS gpa_risk_signal_scope_idx ON gpa_risk_signals (organization_id, tenant_id, provider_reference, program_reference, cycle_reference, status, detected_at DESC);
CREATE INDEX IF NOT EXISTS gpa_risk_eval_scope_idx ON gpa_risk_evaluations (organization_id, tenant_id, provider_reference, program_reference, evaluated_at DESC);
CREATE INDEX IF NOT EXISTS gpa_money_risk_scope_idx ON gpa_money_at_risk (organization_id, tenant_id, provider_reference, program_reference, cycle_reference, status);
