export const infrastructureLayers = [
  {
    id: "data-ingestion",
    number: "01",
    title: "Data Ingestion Layer",
    shortName: "Ingestion",
    purpose: "Captures program, partner, provider, referral, workforce, pharmacy, and outcome data from different systems.",
    inputs: ["Program records", "Partner referrals", "CSV imports", "API feeds", "Manual intake"],
    logic: [
      "Normalize incoming data into SHS canonical objects.",
      "Detect missing fields before data enters reporting.",
      "Create source trace records for every imported item.",
    ],
    outputs: ["Clean intake records", "Source trace IDs", "Import status", "Data quality flags"],
    powers: ["Hub imports", "Kermit check-ins", "VerifiedRx deliveries", "Workforce Pipeline records"],
    route: "admin.html#/imports",
    status: "Wired for mock imports",
    readiness: 78,
  },
  {
    id: "security-trust",
    number: "02",
    title: "Security & Trust Layer",
    shortName: "Trust",
    purpose: "Controls access, identity, permissions, consent, session status, and trust boundaries.",
    inputs: ["User identity", "Organization membership", "Role permissions", "Consent records"],
    logic: [
      "Gate access by role and organization.",
      "Preserve consent boundaries before routing referrals.",
      "Attach trust state to sensitive records.",
    ],
    outputs: ["Access decision", "Permission state", "Consent status", "Security audit events"],
    powers: ["Identity Management", "Admin routes", "Hub partner scopes", "Report publication modes"],
    route: "admin.html#/identity",
    status: "Dev auth fallback active",
    readiness: 72,
  },
  {
    id: "integration",
    number: "03",
    title: "Integration Layer",
    shortName: "Integration",
    purpose: "Connects SHS to partner systems, files, APIs, webhooks, imports, and future external platforms.",
    inputs: ["Partner systems", "Webhook events", "API payloads", "External datasets"],
    logic: [
      "Map partner data into SHS standard objects.",
      "Preserve external source identity.",
      "Send updates to downstream verification and reporting.",
    ],
    outputs: ["Integration events", "Partner mappings", "Connector status", "Sync history"],
    powers: ["Hub Collaboration Layer", "VerifiedRx partner workflows", "Workforce partner feeds"],
    route: "admin.html#/aggregation",
    status: "Connector-ready model",
    readiness: 69,
  },
  {
    id: "reporting-audit",
    number: "04",
    title: "Reporting & Audit Layer",
    shortName: "Reporting",
    purpose: "Turns verified activity into reports, audit packets, briefings, funder views, and institutional proof.",
    inputs: ["Verified records", "Outcome events", "Trust envelopes", "Audit traces"],
    logic: [
      "Check report readiness before export.",
      "Separate internal, partner, funder, and public-safe modes.",
      "Attach proof metadata to every important output.",
    ],
    outputs: ["Growth briefs", "Audit packs", "Partner reports", "Funder summaries"],
    powers: ["Reporting Command Surface", "Verification Audit Surface", "Growth Engine exports"],
    route: "admin.html#/reporting",
    status: "Reporting surface active",
    readiness: 84,
  },
  {
    id: "command-surface",
    number: "05",
    title: "Operational Command Surface",
    shortName: "Command",
    purpose: "Shows live operational truth, alerts, analyst recommendations, readiness, and next-best actions.",
    inputs: ["Oracle state", "Verification state", "Partner events", "Alerts", "Reports"],
    logic: [
      "Show what changed and why.",
      "Prioritize what needs operator action.",
      "Connect decisions back to evidence and audit traces.",
    ],
    outputs: ["Command state", "Alerts", "Recommended actions", "Decision logs"],
    powers: ["SHS Command Surface", "Hub dashboards", "Growth Engine analyst rail"],
    route: "capital.html#/exchange/command",
    status: "Command route available",
    readiness: 81,
  },
  {
    id: "oracle",
    number: "06",
    title: "Oracle Layer",
    shortName: "Oracle",
    purpose: "Determines confidence, contradiction state, readiness, and trusted truth from multiple records.",
    inputs: ["Source traces", "Verification records", "Contradictions", "Outcome data"],
    logic: [
      "Resolve whether data is trusted, incomplete, contradicted, or report-ready.",
      "Score confidence and readiness.",
      "Explain why a record can or cannot be used.",
    ],
    outputs: ["Truth status", "Confidence score", "Readiness state", "Contradiction state"],
    powers: ["Reporting readiness", "Command recommendations", "Audit verification"],
    route: "capital.html#/exchange/command",
    status: "Oracle concept wired",
    readiness: 74,
  },
  {
    id: "ai-governance",
    number: "07",
    title: "AI Governance Layer",
    shortName: "Governance",
    purpose: "Keeps AI recommendations explainable, safe, policy-aware, and human-reviewed.",
    inputs: ["AI recommendations", "Operator actions", "Policy rules", "Audit needs"],
    logic: [
      "Require explanations for recommendations.",
      "Track whether operators used or ignored AI guidance.",
      "Preserve human oversight for important decisions.",
    ],
    outputs: ["AI decision logs", "Explanation records", "Safety flags", "Human review status"],
    powers: ["Adaptive Analyst", "Growth recommendations", "Command action guidance"],
    route: "admin.html#/audit",
    status: "Governance-ready model",
    readiness: 67,
  },
  {
    id: "analyst",
    number: "08",
    title: "Analyst Layer",
    shortName: "Analyst",
    purpose: "Turns trusted system context into insights, recommendations, summaries, and next moves.",
    inputs: ["Certified context", "Dashboard state", "Operator behavior", "Outcome patterns"],
    logic: [
      "Explain what changed.",
      "Recommend the next best move.",
      "Adapt insights based on selected dashboard context.",
    ],
    outputs: ["Analyst summaries", "Next-best actions", "Learning reports", "Briefing language"],
    powers: ["Growth Engine adaptive panel", "Command Surface analyst", "Workspace recommendations"],
    route: "admin.html#/growth",
    status: "Adaptive Growth Intelligence active",
    readiness: 86,
  },
];

export const infrastructureFlow = [
  "Ingest",
  "Secure",
  "Integrate",
  "Verify",
  "Resolve Truth",
  "Recommend",
  "Report",
  "Audit",
];

export const wiringEvents = [
  "infrastructure.layer.selected",
  "infrastructure.route.opened",
  "infrastructure.demo.requested",
  "infrastructure.logic.reviewed",
  "infrastructure.readiness.checked",
];
