const action = (id, route, authority = "DOMAIN_SERVICE") => ({ id, kind: "ROUTE", route, authority });
const source = (kind, id) => ({ kind, id });

const sharedBoundaries = [
  "Does not change authentication, authorization, entitlements, or organization membership.",
  "Does not infer domain completion, approval, acknowledgment, signature, Evidence, or Truth from presentation state.",
];

const base = ({ serviceId, name, classification, owner, destinationId, routes, tier, roles, priority, maturity, visualAuthority = "NONE" }) => ({
  schemaVersion: 1,
  serviceId,
  canonicalName: name,
  serviceClassification: classification,
  domainOwner: owner,
  destinationId,
  routes,
  lifecycle: "ACTIVE",
  version: 1,
  tier,
  priority,
  experienceMaturity: maturity,
  purpose: { statement: `${name} provides its canonical service capabilities for authorized users.`, userValue: "Make the next supported service decision clear without changing domain authority." },
  audience: { roles, personas: roles, organizationContext: "Resolved by the owning service", entitlementRequirements: [], permissionRequirements: [] },
  capabilities: [`Use the supported ${name} experience.`],
  explicitNonCapabilities: sharedBoundaries,
  prohibitedAssumptions: ["A dashboard status is not a domain transition.", "A guidance or analytics signal is not institutional outcome truth."],
  jobsToBeDone: ["Understand the current service context.", "Find the next supported service action.", "Understand what is waiting or blocked."],
  workflow: { canonical: "Service-specific workflow owned by the domain.", states: ["IN_PROGRESS", "WAITING", "BLOCKED", "COMPLETE"], transitionAuthority: "Owning domain service", humanApprovalPoints: [], terminalStates: ["COMPLETE"] },
  states: { actionRequired: "DOMAIN_STATE", waiting: "DOMAIN_STATE", blocked: "DOMAIN_STATE", atRisk: "DOMAIN_STATE", inProgress: "DOMAIN_STATE", complete: "DOMAIN_STATE" },
  actions: { primary: routes.length ? [action("open-service", routes[0])] : [], secondary: [], reference: [] },
  nextAction: { source: "DOMAIN_PROJECTION", projection: "Owning service next-action projection" },
  dashboardObligations: { context: "REQUIRED", attention: "REQUIRED", work: "REQUIRED", progress: "OPTIONAL", intelligence: "OPTIONAL", help: "REQUIRED" },
  metrics: [{ id: "service-status", label: "Service status", source: source("DOMAIN_PROJECTION", "service.status"), relevance: "Current service context", verification: "SOURCE_STATED", metricRegistryRef: null }],
  dgal: { guidance: "CONTEXTUAL_WHEN_AUTHORIZED", documents: "DOMAIN_AND_DGAL_REFERENCES", agreements: "DOMAIN_DEFINED", acknowledgments: "DGAL_ONLY", signatures: "DGAL_ONLY", packets: "DGAL_ONLY" },
  ogl: { orientation: null, guidanceCenter: true, tours: "AS_CONTRACTED", contextualGuidance: true, accessibleAlternative: true },
  companion: { permitted: ["explain", "summarize", "contextualize", "navigate/help"], prohibited: ["approve", "verify", "sign", "publish", "release", "alter workflow", "write Evidence/Truth"], context: "Authorized, source-traceable service projection only", readOnly: true },
  notifications: ["ACTION_REQUIRED", "STATE_CHANGED", "BLOCKER", "RESOLVED"],
  evidence: { consumed: [], produced: [], notOwned: true, verificationSource: "Owning domain or Evidence authority" },
  truth: { projectionsConsumed: [], writeAuthority: false, sourceOfTruth: "Owning domain/Truth authority" },
  responsive: { mobile: "RESPONSIVE_REQUIRED", tablet: "RESPONSIVE_REQUIRED", desktop: "DESKTOP_PRIMARY" },
  accessibility: { keyboardCritical: ["Primary service action", "Status and error communication"], nonVisualEquivalent: true, reducedMotion: true, semanticStatus: true, accessibleAlternative: true },
  visualAuthority: { status: visualAuthority, source: null, sea3Required: visualAuthority === "NONE" },
  acceptance: { functional: ["Authorized route loads", "Canonical service state is visible"], authority: ["Actions remain domain-authorized", "Presentation does not mutate Evidence or Truth"], experience: ["Context, attention, work, and help are distinguishable"] },
});

const full = (contract, details) => ({ ...contract, ...details, explicitNonCapabilities: [...new Set([...contract.explicitNonCapabilities, ...details.explicitNonCapabilities])], tier: "A" });

const records = [
  ["student-learning", "Student Learning", "USER_FACING_SERVICE", "SHF Curriculum", "curriculum", ["/curriculum.html#/dashboard", "/curriculum.html#/learning"], "learner", "P1", 4],
  ["instructor", "Instructor / Teacher", "USER_FACING_SERVICE", "SHF Curriculum", "curriculum", ["/curriculum.html#/instructor", "/curriculum.html#/instructor/operations"], "instructor", "P1", 3],
  ["parent", "Parent / Guardian", "USER_FACING_SERVICE", "SHF Curriculum", "curriculum", ["/curriculum.html#/parent"], "parent", "P2", 2],
  ["curriculum", "Curriculum Platform", "USER_FACING_SERVICE", "SHF Curriculum", "curriculum", ["/curriculum.html#/dashboard"], "learner,instructor,admin", "P1", 4],
  ["career", "Career Center", "USER_FACING_SERVICE", "SHF Career", "career", ["/career.html#/"], "learner,public", "P1", 3],
  ["projects-portfolio", "Projects / Portfolio", "USER_FACING_SERVICE", "SHF Curriculum", "curriculum", ["/curriculum.html#/portfolio"], "learner,instructor", "P2", 3],
  ["credentials-progress", "Credentials / Progress", "PLATFORM_CAPABILITY", "SHF Curriculum", "curriculum", ["/curriculum.html#/progress"], "learner,instructor,admin", "P2", 3],
  ["calendar-live-learning", "Calendar / Live Learning", "USER_FACING_SERVICE", "SHF Curriculum", "curriculum", ["/curriculum.html#/calendar", "/curriculum.html#/live-sessions"], "learner,instructor", "P2", 2],
  ["learning-arcade", "Learning Arcade", "USER_FACING_SERVICE", "SHF Curriculum", "arcade", ["/arcade.html#/"], "learner,public", "P2", 2],
  ["shf-public-impact", "SHF Public / Impact", "PUBLIC_EXPERIENCE", "SHF Foundation", "silicon-heartland-foundation", ["/foundation.html#reports", "/foundation.html#/impact"], "public,shf_admin", "P2", 3],
  ["organization-onboarding", "Organization Onboarding", "USER_FACING_SERVICE", "SHS", "bos", ["/admin.html#/hub/intake"], "applicant,org_admin,reviewer", "P1", 3],
  ["shared-services-network", "Shared Services / Network", "OPERATOR_SERVICE", "SHS", "bos", ["/admin.html#/hub/network"], "org_admin,operator", "P2", 3],
  ["civicsure-provider", "CivicSure Provider", "USER_FACING_SERVICE", "CivicSure", "civic", ["/index.html#/civicsure"], "provider", "P1", 4],
  ["civicsure-operator", "CivicSure Operator / Reviewer", "OPERATOR_SERVICE", "CivicSure", "civic", ["/admin.html#/verification-audit"], "operator,reviewer_verifier", "P1", 3],
  ["civicsure-public", "CivicSure Public", "PUBLIC_EXPERIENCE", "CivicSure", "civic", ["/index.html#/civicsure"], "public", "P3", 2],
  ["bos-hub", "BOS / Hub", "OPERATOR_SERVICE", "SHS", "bos", ["/admin.html#/hub", "/admin.html#/hub/network"], "org_admin,shs_admin,instructor", "P1", 4],
  ["studio", "Studio", "USER_FACING_SERVICE", "SHS Studio", "studio", ["/studio", "/admin.html#/builder"], "builder,reviewer,admin", "P1", 3],
  ["service-catalog", "Service Catalog / Entitlements", "PLATFORM_CAPABILITY", "SHS", "bos", ["/admin.html#/registry"], "org_admin,operator", "P2", 3],
  ["agent-fabric", "Agent Fabric", "OPERATOR_SERVICE", "SHS Governed AI", "agent-fabric", ["/admin.html#/agent-fabric"], "agent_operator,shs_admin", "P1", 3],
  ["arag-1", "ARAG-1 / Release Assurance", "OPERATOR_SERVICE", "Governance", "shs-bos-executive-command", ["/admin.html#/release-assurance"], "operator,approver", "P1", 3],
  ["oas", "Open Autonomous Standard", "PUBLIC_EXPERIENCE", "OAS", "open-autonomous-standard", ["/oas.html"], "public", "P3", 3],
  ["autonomous-registry", "Autonomous Registry", "PUBLIC_EXPERIENCE", "Autonomous Registry", "autonomous-registry", ["external:autonomous-registry"], "public", "P3", 3],
  ["trust-bureau", "Trust Bureau", "NOT_YET_PRODUCTIZED", "External product owner", "autonomous-trust-bureau", [], "public", "EXTERNAL", 0],
  ["dgal", "DGAL Document Center", "PLATFORM_CAPABILITY", "DGAL", "documentation", ["/admin.html#/documentation"], "user,admin", "P1", 4],
  ["ogl", "OGL Guidance / Admin", "INTERNAL_ADMIN_TOOL", "OGL", "bos", ["/admin.html#/orientation"], "guidance_admin", "P2", 4],
  ["legal", "Legal", "PLATFORM_CAPABILITY", "Legal", "bos", ["/admin.html#/documentation"], "legal_admin", "P2", 3],
  ["truth-spine", "Truth Spine", "PLATFORM_CAPABILITY", "Truth authority", "bos", ["/admin.html#/truth-spine"], "auditor,admin", "P1", 4],
  ["oracle", "Oracle", "PLATFORM_CAPABILITY", "Oracle authority", "bos", ["/admin.html#/oracle"], "auditor,admin", "P2", 3],
  ["reporting-metric-registry", "Reporting / Metric Registry", "PLATFORM_CAPABILITY", "Reporting", "bos", ["/admin.html#/reporting", "/admin.html#/analytics"], "analyst,admin", "P1", 3],
  ["executive-command", "Executive Command", "OPERATOR_SERVICE", "SHS BOS", "shs-bos-executive-command", ["/admin.html#/ops/executive-command"], "shs_admin,org_admin", "P1", 3],
  ["treasury-funding", "Treasury / Funding", "PLATFORM_CAPABILITY", "SHS/Foundation", "treasury", ["/treasury.html#/dashboard"], "operator,finance", "P2", 2],
  ["employer", "Employer", "USER_FACING_SERVICE", "SHF Career", "employer", ["/employer.html#/dashboard"], "employer", "P2", 2],
  ["sales-pipeline", "Sales Pipeline", "USER_FACING_SERVICE", "SHS", "sales", ["/sales.html#/dashboard"], "sales,org_admin", "P2", 3],
  ["store-marketplace", "Store / Marketplace", "USER_FACING_SERVICE", "SHS", "store", ["/store.html#/catalog"], "user,public", "P3", 2],
  ["credit-debt", "Credit / Debt", "USER_FACING_SERVICE", "SHF/SHS", "credit", ["/credit.html#/dashboard", "/debt.html#/dashboard"], "user,public", "P3", 2],
  ["ai-job-compass", "AI Job Compass", "USER_FACING_SERVICE", "SHF Career", "ai-job-compass", ["/ai.html#/job-compass"], "learner,public", "P3", 2],
  ["external-proof-verifier", "External Proof Verifier", "PUBLIC_EXPERIENCE", "Independent authority", "verifier", ["/verifier.html"], "public", "P3", 3],
  ["universe", "Universe", "PUBLIC_EXPERIENCE", "Universe", "universe", ["/universe", "/universe/directory"], "public", "P2", 3],
  ["allocation-impact", "Allocation / Impact", "OPERATOR_SERVICE", "SHF Foundation", "shf-impact", ["/allocation.html", "/foundation.html#/impact"], "shf_admin,analyst", "P2", 2],
  ["lord-of-outcomes", "Lord of Outcomes", "PLATFORM_CAPABILITY", "Outcomes authority", "lord-of-outcomes", ["/lord-outcomes.html"], "auditor,analyst", "P3", 2],
];

const contracts = records.map(([serviceId, name, classification, owner, destinationId, routes, roleText, priority, maturity]) => base({ serviceId, name, classification, owner, destinationId, routes, tier: priority === "P1" ? "A" : priority === "EXTERNAL" ? "NOT_PRODUCTIZED" : priority === "P2" ? "B" : "C", roles: roleText.split(","), priority, maturity }));

const tierA = new Map([
  ["student-learning", { purpose: { statement: "Learners use Curriculum to understand, complete, and reflect on assigned learning.", userValue: "Know what to do next and how current work connects to progress and career." }, capabilities: ["View assigned lessons and assignments", "Practice, apply, reflect, and demonstrate learning", "View authorized progress, portfolio, skills, and career connections"], explicitNonCapabilities: ["Does not certify learning, issue credentials, or replace instructor judgment."], jobsToBeDone: ["Find the current assignment.", "Continue the current lesson.", "Understand progress and the next learning step.", "Connect demonstrated skills to portfolio and career context."], workflow: { canonical: "Assign -> Prepare -> Learn -> Practice -> Apply -> Reflect -> Demonstrate -> Verify/Report", states: ["ASSIGNED", "IN_PROGRESS", "SUBMITTED", "WAITING_ON_REVIEW", "BLOCKED", "COMPLETE"], transitionAuthority: "Curriculum domain and authorized instructor/reviewer actions", humanApprovalPoints: ["Instructor/reviewer verification where required"], terminalStates: ["COMPLETE"] }, nextAction: { source: "DOMAIN_PROJECTION", projection: "Curriculum assignment/progress projection" }, metrics: [{ id: "learning-progress", label: "Learning progress", source: source("TRUTH_PROJECTION", "curriculum.learning_progress"), relevance: "Learner progress", verification: "SOURCE_STATED", metricRegistryRef: "curriculum.learning_progress" }], ogl: { orientation: "orientation:curriculum:student-dashboard", guidanceCenter: true, tours: "tour:curriculum:student-dashboard", contextualGuidance: true, accessibleAlternative: true }, responsive: { mobile: "MOBILE_REQUIRED", tablet: "TABLET_REQUIRED", desktop: "DESKTOP_PRIMARY" } }],
  ["instructor", { capabilities: ["View authorized cohorts, assignments, and learner progress", "Prepare instruction and review supported submissions"], explicitNonCapabilities: ["Does not expose unauthorized learner-private data or change curriculum authority."], jobsToBeDone: ["Review current cohort work.", "Identify learners or assignments needing attention.", "Prepare or review supported instructional work."], workflow: { canonical: "Prepare -> Assign -> Monitor -> Review -> Intervene", states: ["PLANNED", "ACTIVE", "WAITING", "NEEDS_ATTENTION", "COMPLETE"], transitionAuthority: "Curriculum domain and authorized instructor actions", humanApprovalPoints: ["Instructor decision where domain requires it"], terminalStates: ["COMPLETE"] }, nextAction: { source: "DOMAIN_PROJECTION", projection: "Instructor operations projection" }, ogl: { orientation: "orientation:curriculum:instructor-operations", guidanceCenter: true, tours: "tour:curriculum:instructor-operations", contextualGuidance: true, accessibleAlternative: true } }],
  ["organization-onboarding", { capabilities: ["Submit and inspect an authorized organization application", "Surface document, agreement, review, and activation stages"], explicitNonCapabilities: ["Does not approve, activate, suspend, exit, or grant entitlements; those remain onboarding and service authorities."], jobsToBeDone: ["Know the current application stage.", "Submit required information or documents.", "Understand what is waiting on the applicant or reviewer.", "Return to the next authorized onboarding action."], workflow: { canonical: "Apply -> Review -> Documents -> Agreements -> Activate -> Operate", states: ["SUBMITTED", "UNDER_REVIEW", "APPROVED", "DECLINED", "ACTIVATED", "SUSPENDED", "EXITED", "GRADUATED"], transitionAuthority: "Organization Onboarding domain", humanApprovalPoints: ["Authorized onboarding reviewer approval", "Authorized activation decision"], terminalStates: ["DECLINED", "EXITED", "GRADUATED"] }, nextAction: { source: "WORKFLOW_STATE_MACHINE", projection: "Organization onboarding stage/action projection" }, dgal: { guidance: "CONTEXTUAL_WHEN_AUTHORIZED", documents: "REQUIRED_DOCUMENTS_FROM_DGAL", agreements: "SERVICE_AGREEMENT_DOMAIN", acknowledgments: "DGAL_ONLY", signatures: "DGAL_ONLY", packets: "DGAL_ONLY" }, responsive: { mobile: "MOBILE_REQUIRED", tablet: "TABLET_REQUIRED", desktop: "DESKTOP_PRIMARY" } }],
  ["civicsure-provider", { capabilities: ["View provider program context", "Submit authorized evidence and respond to corrective action", "View verification status and required guidance"], explicitNonCapabilities: ["Is not the accounting source of record, payment processor, or verification authority."], jobsToBeDone: ["Know what must be submitted.", "Submit evidence through the canonical provider action.", "Respond to a correction request.", "Understand what is waiting on the provider or operator."], workflow: { canonical: "Fund -> Deliver -> Verify -> Measure -> Detect -> Correct -> Decide -> Learn/Prove", states: ["READY", "SUBMISSION_REQUIRED", "SUBMITTED", "UNDER_REVIEW", "CORRECTION_REQUIRED", "VERIFIED", "BLOCKED"], transitionAuthority: "CivicSure domain; provider can initiate only authorized self-service actions", humanApprovalPoints: ["CivicSure operator verification/decision"], terminalStates: ["VERIFIED"] }, nextAction: { source: "DOMAIN_PROJECTION", projection: "CivicSure provider requirement/finding projection" }, dgal: { guidance: "CONTEXTUAL_WHEN_AUTHORIZED", documents: "REQUIRED_PROVIDER_DOCUMENTS", agreements: "SERVICE_AGREEMENT_DOMAIN", acknowledgments: "DGAL_ONLY", signatures: "DGAL_ONLY", packets: "DGAL_ONLY" }, ogl: { orientation: "orientation:civicsure:provider", guidanceCenter: true, tours: "tour:civicsure:provider", contextualGuidance: true, accessibleAlternative: true }, responsive: { mobile: "MOBILE_REQUIRED", tablet: "TABLET_REQUIRED", desktop: "DESKTOP_PRIMARY" } }],
  ["civicsure-operator", { capabilities: ["Review authorized provider evidence", "Inspect verification readiness and corrective-action state", "Initiate only domain-authorized review actions"], explicitNonCapabilities: ["Does not create payment/accounting authority or automate consequential verification decisions."], jobsToBeDone: ["Find the next review item.", "Inspect evidence and source status.", "Identify blockers or corrective actions.", "Record a domain-authorized review decision when permitted."], workflow: { canonical: "Queue -> Inspect Evidence -> Request Correction -> Review -> Decide -> Assure", states: ["QUEUED", "IN_REVIEW", "CORRECTION_REQUIRED", "READY_FOR_DECISION", "DECIDED", "BLOCKED"], transitionAuthority: "CivicSure verification domain", humanApprovalPoints: ["Authorized operator/reviewer decision"], terminalStates: ["DECIDED"] }, nextAction: { source: "DOMAIN_PROJECTION", projection: "CivicSure verification queue projection" }, ogl: { orientation: "orientation:civicsure:operator", guidanceCenter: true, tours: "tour:civicsure:operator", contextualGuidance: true, accessibleAlternative: true } }],
  ["studio", { capabilities: ["Create and edit authorized workspace artifacts", "Run QA and submit supported review packets", "Inspect review/release handoff state"], explicitNonCapabilities: ["Does not collapse builder, QA, reviewer, approver, or release authority into one role."], jobsToBeDone: ["Know the current workspace state.", "Complete the next build or QA action.", "Prepare a review submission.", "Understand what is waiting on a reviewer or release authority."], workflow: { canonical: "Plan -> Build -> QA -> Submit -> Review -> Approve -> Release/Handoff", states: ["DRAFT", "BUILDING", "QA_REQUIRED", "SUBMITTED", "IN_REVIEW", "CHANGES_REQUIRED", "APPROVED", "RELEASED"], transitionAuthority: "Studio domain and role-specific controls", humanApprovalPoints: ["QA review", "Review decision", "Release approval where applicable"], terminalStates: ["RELEASED"] }, nextAction: { source: "WORKFLOW_STATE_MACHINE", projection: "Studio workspace/review state projection" }, ogl: { orientation: "orientation:hub:workspace", guidanceCenter: true, tours: "AS_CONTRACTED", contextualGuidance: true, accessibleAlternative: true } }],
  ["bos-hub", { capabilities: ["Navigate authorized organization services", "Surface operational work, queues, and service context", "Coordinate safe domain-owned next actions"], explicitNonCapabilities: ["Is not a universal domain authority and does not complete downstream workflows itself."], jobsToBeDone: ["Understand the current organization context.", "Find attention items and operational work.", "Open the next authorized service action.", "Return safely to the relevant workflow."], workflow: { canonical: "Context -> Triage -> Service Action -> Follow-up", states: ["AVAILABLE", "NEEDS_ATTENTION", "WAITING", "BLOCKED", "IN_PROGRESS", "COMPLETE"], transitionAuthority: "Owning service for each operational action", humanApprovalPoints: ["Service-specific human authorities"], terminalStates: ["COMPLETE"] }, nextAction: { source: "OGL_RESOLVER", projection: "OGL-2 context plus domain next-action projection" }, ogl: { orientation: "orientation:hub:workspace", guidanceCenter: true, tours: "hub:workspace", contextualGuidance: true, accessibleAlternative: true } }],
  ["agent-fabric", { capabilities: ["Create and inspect governed work orders", "Apply policy/resource constraints", "Surface approval and incident state"], explicitNonCapabilities: ["Is not a superuser, unrestricted executor, release authority, or substitute for WF-040."], jobsToBeDone: ["Understand the active governed work order.", "Check policy and tool/resource constraints.", "Identify the next safe operator or approval action.", "Inspect evidence and incident state."], workflow: { canonical: "Work Order -> Governed AI Work -> Evidence -> Policy Check -> Human Approval -> Release Gate", states: ["DRAFT", "QUEUED", "RUNNING", "AWAITING_APPROVAL", "BLOCKED", "CANCELLED", "COMPLETED"], transitionAuthority: "Agent Fabric governance and owning domain", humanApprovalPoints: ["Required human approval and release gate"], terminalStates: ["CANCELLED", "COMPLETED"] }, nextAction: { source: "DOMAIN_PROJECTION", projection: "Governed work-order/policy projection" }, ogl: { orientation: "orientation:agent-fabric:operator", guidanceCenter: true, tours: "AS_CONTRACTED", contextualGuidance: true, accessibleAlternative: true } }],
  ["arag-1", { capabilities: ["Compose AI-assisted work context", "Evaluate policy and Evidence readiness", "Present the human release gate"], explicitNonCapabilities: ["Does not autonomously approve, publish, release, bypass permissions, or replace human release authority."], jobsToBeDone: ["Understand the work order and policy context.", "Review Evidence readiness.", "Identify what is waiting on an approver.", "Open the authorized release-assurance action."], workflow: { canonical: "Work Order -> AI Work -> Evidence -> Policy Evaluation -> Human Approval -> Release Gate -> Evidence Packet", states: ["OPEN", "IN_PROGRESS", "EVIDENCE_REQUIRED", "POLICY_REVIEW", "AWAITING_HUMAN_APPROVAL", "RELEASED", "REJECTED"], transitionAuthority: "ARAG/owning release domain", humanApprovalPoints: ["Human release approval"], terminalStates: ["RELEASED", "REJECTED"] }, nextAction: { source: "DOMAIN_PROJECTION", projection: "ARAG release-assurance projection" } }],
  ["dgal", { capabilities: ["Expose contextual requirements and document status", "Open canonical document, packet, acknowledgment, and signature flows"], explicitNonCapabilities: ["Does not own service completion, legal meaning, Evidence acceptance, or Truth."], jobsToBeDone: ["Know which document or guidance applies.", "Open the canonical document action.", "Understand whether a document is required, awaiting acknowledgment, signed, expired, or superseded."], workflow: { canonical: "Requirement -> Document/Packet -> Acknowledgment/Signature -> Evidence -> Retention", states: ["REQUIRED", "AVAILABLE", "VIEWED", "AWAITING_ACKNOWLEDGMENT", "AWAITING_SIGNATURE", "COMPLETED", "EXPIRED", "SUPERSEDED"], transitionAuthority: "DGAL document/agreement authority", humanApprovalPoints: ["Authorized acknowledgment/signature actors"], terminalStates: ["COMPLETED", "EXPIRED", "SUPERSEDED"] }, nextAction: { source: "DOMAIN_PROJECTION", projection: "DGAL requirement/document projection" } }],
  ["reporting-metric-registry", { capabilities: ["Present authorized reports and registered metrics", "Show source, verification, freshness, and public eligibility context"], explicitNonCapabilities: ["Does not turn a report or metric into Truth, Evidence, verified outcome, or service completion."], jobsToBeDone: ["Find the relevant report or metric.", "Understand its source and verification status.", "Export or inspect only when authorized.", "Identify stale or blocked reporting work."], workflow: { canonical: "Source -> Validate -> Compose -> Review -> Authorize -> Distribute", states: ["NO_DATA", "DRAFT", "VALIDATING", "READY", "BLOCKED", "PUBLISHED", "SUPERSEDED"], transitionAuthority: "Reporting/Metric Registry and publication authorities", humanApprovalPoints: ["Report/publication authorization"], terminalStates: ["PUBLISHED", "SUPERSEDED"] }, nextAction: { source: "DOMAIN_PROJECTION", projection: "Reporting/Metric Registry readiness projection" }, metrics: [{ id: "report-readiness", label: "Report readiness", source: source("METRIC_REGISTRY", "reporting.readiness"), relevance: "Operator reporting decision", verification: "SOURCE_STATED", metricRegistryRef: "reporting.readiness" }] }],
  ["executive-command", { capabilities: ["Inspect governed executive summaries and operational priorities", "Open authorized read-only command context"], explicitNonCapabilities: ["Does not approve, release, verify, or create executive authority from a summary."], jobsToBeDone: ["Understand current executive context.", "Find priority attention items.", "Open the owning service for action."], workflow: { canonical: "Context -> Review -> Refer to Owning Service", states: ["AVAILABLE", "NEEDS_ATTENTION", "WAITING", "BLOCKED", "REFER"] , transitionAuthority: "Owning service domains", humanApprovalPoints: [], terminalStates: ["REFER"] }, nextAction: { source: "OGL_RESOLVER", projection: "OGL-2 executive context projection" }, ogl: { orientation: "orientation:shs-bos:executive-command", guidanceCenter: true, tours: "tour:shs-bos:executive-command", contextualGuidance: true, accessibleAlternative: true } }],
]);

for (const contract of contracts) {
  const detail = tierA.get(contract.serviceId);
  if (detail) Object.assign(contract, full(contract, detail));
}

export const SEA_SERVICE_EXPERIENCE_CONTRACTS = Object.freeze(contracts);
export const SEA_CONTRACT_SCHEMA_VERSION = 1;
