// src/components/sales/GrantBrief.jsx
import React from "react";
import { useBrandKit } from "@/hooks/useBrandKit.js";

export default function GrantBrief({ forecasterKpi, programType="school" }) {
  const { brand } = useBrandKit();
  const onGenerate = () => {
    const w = window.open("", "_blank", "noopener,noreferrer,width=900,height=1000");
    if (!w) return;
    const { completionCount, projectedBadges, sponsorValue, siteLic, sponsor, total } = forecasterKpi || {};
    const title = brand?.name || "Your Organization";
    const color = brand?.primary || "#e11d2d";
    const logo = brand?.logoDataUrl || "";
    const fundLane = programType === "school"
      ? "Title IV-A • Perkins V • 21st CCLC"
      : programType === "fitness"
      ? "21st CCLC • City Youth Funds • Corporate Sponsors"
      : "WIOA • Workforce Grants • Corporate Sponsors";

    const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Grant Brief – ${title}</title>
<style>
  body{ font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial; margin:0; }
  .hd{ background:${color}; color:#fff; padding:24px; display:flex; gap:16px; align-items:center; }
  .hd img{ width:64px; height:64px; object-fit:contain; background:#fff; border-radius:10px; padding:6px; }
  .ct{ padding:24px; display:grid; gap:16px; }
  .card{ border:1px solid #e5e7eb; border-radius:12px; padding:16px; }
  h1,h2,h3{ margin:.2em 0; }
  .kpis{ display:grid; grid-template-columns:repeat(3,1fr); gap:12px; }
  .kpi{ border:1px solid #e5e7eb; border-radius:10px; padding:12px; }
  .kpi .t{ font-size:12px; color:#6b7280 }
  .kpi .v{ font-weight:800; font-size:20px }
  .foot{ padding:16px 24px; color:#6b7280; border-top:1px solid #e5e7eb; }
  @media print { .btns{ display:none } }
</style>
</head>
<body>
  <div class="hd">
    ${logo ? `<img alt="logo" src="${logo}"/>` : ""}
    <div>
      <h1 style="margin:0">Grant Brief: ${title}</h1>
      <div>${fundLane}</div>
    </div>
  </div>
  <div class="ct">
    <div class="card">
      <h2>Program Snapshot</h2>
      <p>${escapeHtml(title)} will deploy SEL + Financial Literacy and job-ready skills via the Silicon Heartland Foundation.</p>
      <ul>
        <li>Launch timeline: 30–45 days • Data privacy: FERPA/COPPA aligned • A11y: WCAG</li>
        <li>Delivery modes: in-class, after-school/fitness, weekend bootcamps, summer camps</li>
      </ul>
      <div class="kpis">
        <div class="kpi"><div class="t">Projected Completers</div><div class="v">${completionCount ?? "—"}</div></div>
        <div class="kpi"><div class="t">Badges Issued</div><div class="v">${projectedBadges ?? "—"}</div></div>
        <div class="kpi"><div class="t">Sponsor Value</div><div class="v">$${(Math.round((sponsorValue||0))).toLocaleString()}</div></div>
      </div>
    </div>

    <div class="card">
      <h3>Budget (Year 1)</h3>
      <ul>
        <li>Site license: $${(siteLic||0).toLocaleString()}</li>
        <li>Sponsor contribution: $${(sponsor||0).toLocaleString()}</li>
        <li><b>Total Request:</b> $${(total||0).toLocaleString()}</li>
      </ul>
    </div>

    <div class="card">
      <h3>Outcomes & Reporting</h3>
      <ul>
        <li>Pre/Post SEL check • FinLit quiz growth • Attendance & engagement</li>
        <li>Verifiable credentials • Employer-aligned badges • Sponsor dashboard</li>
      </ul>
    </div>

    <div class="btns">
      <button onclick="window.print()" style="padding:10px 12px; border-radius:10px; border:1px solid #e5e7eb; font-weight:700">Print / Save PDF</button>
    </div>
  </div>
  <div class="foot">Generated by Sales Demo • solutions</div>
</body>
</html>`;
    w.document.write(html);
    w.document.close();
    w.focus();
  };

  return (
    <section className="card card--pad" style={{ display:"grid", gap:8 }}>
      <h3 style={{ margin:0 }}>Grant Brief</h3>
      <p style={{ margin:0, color:"var(--ink-soft)" }}>One-click printable brief tailored to the forecast & program.</p>
      <button className="sh-btn" type="button" onClick={onGenerate}>Generate Grant Brief</button>
    </section>
  );
}
function escapeHtml(s=""){ return s.replace(/[&<>"']/g, m=>({ "&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;" }[m])); }
