import React from "react";
import { Link, useParams } from "react-router-dom";
import { useUser } from "@/context/UserContext.jsx";
import { getStudioBuildPacket, getStudioLearningContext, getStudioProject, getStudioProjectResources } from "@/lib/studio/api.js";
import StudioBuildPacket from "./StudioBuildPacket.jsx";
import StudioProjectResources from "./StudioProjectResources.jsx";
import { StudioExperienceProvider, StudioExperienceSummary, StudioHelp, StudioLearningContext, StudioModeControl, StudioNextAction, StudioOrientation, StudioProgress } from "./StudioExperience.jsx";
import { projectTypeLabel, stageLabel } from "./experience.js";

export default function StudioProjectShell() {
  const { role } = useUser();
  const { projectId } = useParams();
  const [state, setState] = React.useState({ loading: true, error: null, project: null, resources: [], resourcesLoading: true, resourcesError: null, packet: null, packetLoading: true, packetError: null, context: null, contextLoading: true, contextError: null });
  React.useEffect(() => { let active = true; getStudioProject(role, projectId).then((project) => active && setState((current) => ({ ...current, loading: false, error: null, project }))).catch((error) => active && setState((current) => ({ ...current, loading: false, error, project: null }))); return () => { active = false; }; }, [role, projectId]);
  React.useEffect(() => { let active = true; if (!projectId) return undefined; getStudioProjectResources(role, projectId).then((data) => active && setState((current) => ({ ...current, resources: data?.resources || [], resourcesLoading: false, resourcesError: null }))).catch((error) => active && setState((current) => ({ ...current, resources: [], resourcesLoading: false, resourcesError: error }))); return () => { active = false; }; }, [role, projectId]);
  React.useEffect(() => { let active = true; if (!projectId) return undefined; getStudioBuildPacket(role, projectId).then((packet) => active && setState((current) => ({ ...current, packet, packetLoading: false, packetError: null }))).catch((error) => active && setState((current) => ({ ...current, packet: null, packetLoading: false, packetError: error }))); return () => { active = false; }; }, [role, projectId]);
  React.useEffect(() => { let active = true; if (!projectId) return undefined; getStudioLearningContext(role, projectId).then((context) => active && setState((current) => ({ ...current, context, contextLoading: false, contextError: null }))).catch((error) => active && setState((current) => ({ ...current, context: null, contextLoading: false, contextError: error }))); return () => { active = false; }; }, [role, projectId]);
  if (state.loading) return <div className="studio-page"><p className="studio-muted" role="status">Loading your project…</p></div>;
  if (state.error || !state.project) return <div className="studio-page studio-page--narrow"><Link className="studio-backLink" to="/studio/projects">← Back to My Projects</Link><div className="studio-empty studio-empty--large"><p><strong>This project is not available.</strong><span>It may have moved, or you may not have access to it.</span></p></div></div>;
  const project = state.project;
  return <StudioExperienceProvider project={project} context={state.context} packet={state.packet} resources={state.resources} route={`/studio/projects/${project.projectId}`}><div className="studio-page"><Link className="studio-backLink" to="/studio/projects">← Back to My Projects</Link><header className="studio-projectHeader"><div><p className="studio-eyebrow">{projectTypeLabel(project.projectType)} project</p><h1 className="ld-h1">{project.title}</h1><p className="studio-muted">Started {new Date(project.createdAt).toLocaleDateString()}</p>{project.ownerType === "TEAM" ? <p className="studio-muted" aria-label={`Team project owned by ${project.teamName || "team"}`}>Team Project{project.teamName ? ` · ${project.teamName}` : ""}</p> : null}</div><span className="studio-status" aria-label={`Project stage: ${stageLabel(project.status)}`}>{stageLabel(project.status)}</span></header>{state.contextError ? <p className="studio-error" role="alert">Project learning context is unavailable. You can still open the workspace. Please try again.</p> : <StudioLearningContext />}{<StudioOrientation project={project} />}<StudioNextAction /><StudioProgress /><StudioBuildPacket packet={state.packet} loading={state.packetLoading} error={state.packetError} /><StudioProjectResources project={project} resources={state.resources} loading={state.resourcesLoading} error={state.resourcesError} /><div className="studio-shellGrid"><section className="studio-panel"><h2>Build</h2><p>Work on your project in the Studio workspace.</p><Link className="studio-primaryButton" to={`/studio/projects/${encodeURIComponent(project.projectId)}/build`}>Open Build Workspace</Link><StudioExperienceSummary /></section><aside className="studio-panel studio-panel--side"><h2>Project Plan</h2><dl className="studio-facts"><div><dt>Type</dt><dd>{projectTypeLabel(project.projectType)}</dd></div><div><dt>Origin</dt><dd>{project.origin === "ASSIGNMENT" ? "Course assignment" : "Your idea"}</dd></div><div><dt>Stage</dt><dd>{stageLabel(project.status)}</dd></div></dl><StudioModeControl /><StudioHelp /></aside></div></div></StudioExperienceProvider>;
}
