import React from "react";
import { useUser } from "@/context/UserContext.jsx";
import { listAssignments } from "@/lib/assignments/api.js";
import { startAssignmentStudioProject } from "@/lib/studio/api.js";
import { useNavigate } from "react-router-dom";

export default function StudioAssignments() {
  const { role } = useUser(); const navigate = useNavigate();
  const [state, setState] = React.useState({ loading: true, error: null, items: [], starting: null });
  React.useEffect(() => { let active = true; listAssignments(role).then((data) => active && setState({ loading: false, error: null, items: data?.items || [], starting: null })).catch((error) => active && setState({ loading: false, error, items: [], starting: null })); return () => { active = false; }; }, [role]);
  async function start(assignment) { setState((s) => ({ ...s, starting: assignment.id, error: null })); try { const project = await startAssignmentStudioProject(role, { assignmentId: assignment.id, projectType: assignment.projectType === "AI_AGENT" ? "AI_AGENT" : "WEBSITE" }); navigate(`/studio/projects/${encodeURIComponent(project.projectId)}`); } catch (error) { setState((s) => ({ ...s, starting: null, error })); } }
  return <div className="studio-page"><header className="studio-pageHeader"><p className="studio-eyebrow">Course connection</p><h1 className="ld-h1">Studio Assignments</h1><p className="studio-lede">Start a Studio project from eligible course work. Assignment and release context stays with the server.</p></header>{state.loading ? <p className="studio-muted" role="status">Loading assignments…</p> : state.error && state.items.length === 0 ? <p className="studio-error" role="alert">Assignments are unavailable right now. Please try again.</p> : state.items.length === 0 ? <div className="studio-empty studio-empty--large"><p><strong>No Studio assignments yet.</strong><span>Your eligible course work will appear here when it is connected to Studio.</span></p></div> : <div className="studio-assignmentList">{state.items.map((assignment) => { const studioEligible = assignment.studioEligible === true || assignment.projectType === "WEBSITE" || assignment.projectType === "AI_AGENT"; return <article className="studio-assignment" key={assignment.id}><div><strong>{assignment.title}</strong><span>{assignment.curriculumRelease?.courseTitle || "Course assignment"}</span></div>{studioEligible ? <button className="studio-primaryButton" type="button" onClick={() => start(assignment)} disabled={state.starting === assignment.id}>{state.starting === assignment.id ? "Starting…" : "Start Project"}</button> : <span className="studio-muted">Studio handoff not available yet</span>}</article>; })}</div>}{state.error && state.items.length > 0 && <p className="studio-error" role="alert">That assignment could not be started. Please try again.</p>}</div>;
}
