import type {
  GeographySignalEntity,
  OrganizationEntity,
  OutcomeEntity,
  ReferralEntity,
  ReportArtifactEntity,
  VerificationRecordEntity,
} from "@/system/contracts";

export const aggregationOrganizations: OrganizationEntity[] = [
  {
    id: "org_franklin_workforce",
    name: "Franklin Workforce Network",
    type: "provider",
    county: "Franklin",
    region: "Central Ohio",
    status: "active",
    trust: {
      verificationState: "verified",
      confidenceLevel: "high",
      confidenceScore: 92,
      freshnessLabel: "24h",
      sourceCount: 4,
      sourceIds: ["src_case", "src_report", "src_partner", "src_audit"],
      lineageId: "lin_org_001",
      lastUpdatedAt: new Date().toISOString(),
      publicationMode: "admin_internal",
    },
  },
  {
    id: "org_cuyahoga_services",
    name: "Cuyahoga Service Hub",
    type: "nonprofit",
    county: "Cuyahoga",
    region: "Northeast Ohio",
    status: "active",
    trust: {
      verificationState: "pending",
      confidenceLevel: "medium",
      confidenceScore: 74,
      freshnessLabel: "7d",
      sourceCount: 2,
      sourceIds: ["src_case", "src_partner"],
      lineageId: "lin_org_002",
      lastUpdatedAt: new Date().toISOString(),
      publicationMode: "admin_internal",
    },
  },
];

export const aggregationReferrals: ReferralEntity[] = [
  {
    id: "ref_001",
    fromOrganizationId: "org_franklin_workforce",
    toOrganizationId: "org_cuyahoga_services",
    county: "Franklin",
    programId: "career_launchpad",
    unmetNeedId: "need_001",
    status: "accepted",
    priority: "high",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    trust: {
      verificationState: "verified",
      confidenceLevel: "high",
      confidenceScore: 88,
      freshnessLabel: "24h",
      sourceCount: 3,
      sourceIds: ["src_referral", "src_case", "src_review"],
      lineageId: "lin_ref_001",
      lastUpdatedAt: new Date().toISOString(),
      publicationMode: "admin_internal",
    },
  },
  {
    id: "ref_002",
    fromOrganizationId: "org_cuyahoga_services",
    toOrganizationId: "org_franklin_workforce",
    county: "Cuyahoga",
    programId: "recovery_housing",
    unmetNeedId: "need_002",
    status: "blocked",
    priority: "medium",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    trust: {
      verificationState: "pending",
      confidenceLevel: "medium",
      confidenceScore: 67,
      freshnessLabel: "7d",
      sourceCount: 2,
      sourceIds: ["src_referral", "src_partner"],
      lineageId: "lin_ref_002",
      lastUpdatedAt: new Date().toISOString(),
      publicationMode: "admin_internal",
    },
  },
];

export const aggregationOutcomes: OutcomeEntity[] = [
  {
    id: "out_001",
    programId: "career_launchpad",
    county: "Franklin",
    outcomeType: "placement",
    status: "positive",
    measuredAt: new Date().toISOString(),
    trust: {
      verificationState: "verified",
      confidenceLevel: "high",
      confidenceScore: 90,
      freshnessLabel: "24h",
      sourceCount: 3,
      sourceIds: ["src_outcome", "src_report", "src_audit"],
      lineageId: "lin_out_001",
      lastUpdatedAt: new Date().toISOString(),
      publicationMode: "admin_internal",
    },
  },
  {
    id: "out_002",
    programId: "recovery_housing",
    county: "Cuyahoga",
    outcomeType: "retention",
    status: "mixed",
    measuredAt: new Date().toISOString(),
    trust: {
      verificationState: "self_reported",
      confidenceLevel: "medium",
      confidenceScore: 61,
      freshnessLabel: "7d",
      sourceCount: 1,
      sourceIds: ["src_outcome_self"],
      lineageId: "lin_out_002",
      lastUpdatedAt: new Date().toISOString(),
      publicationMode: "admin_internal",
    },
  },
];

export const aggregationVerificationRecords: VerificationRecordEntity[] = [
  {
    id: "ver_001",
    targetEntityType: "outcome",
    targetEntityId: "out_001",
    verificationState: "verified",
    verifiedBy: "reviewer_a",
    verifiedAt: new Date().toISOString(),
    notes: "Cross-checked with partner report and internal audit log.",
  },
  {
    id: "ver_002",
    targetEntityType: "referral",
    targetEntityId: "ref_002",
    verificationState: "pending",
    verifiedBy: "",
    verifiedAt: "",
    notes: "Waiting for supporting partner documentation.",
  },
];

export const aggregationSignals: GeographySignalEntity[] = [
  {
    id: "sig_001",
    county: "Franklin",
    region: "Central Ohio",
    signalType: "outcome",
    signalStatus: "processing",
    valueLabel: "82%",
    trust: {
      verificationState: "verified",
      confidenceLevel: "high",
      confidenceScore: 91,
      freshnessLabel: "24h",
      sourceCount: 3,
      sourceIds: ["src_map", "src_outcome", "src_audit"],
      lineageId: "lin_sig_001",
      lastUpdatedAt: new Date().toISOString(),
      publicationMode: "admin_internal",
    },
  },
  {
    id: "sig_002",
    county: "Cuyahoga",
    region: "Northeast Ohio",
    signalType: "risk",
    signalStatus: "watch",
    valueLabel: "Watch",
    trust: {
      verificationState: "pending",
      confidenceLevel: "medium",
      confidenceScore: 69,
      freshnessLabel: "7d",
      sourceCount: 2,
      sourceIds: ["src_map", "src_partner"],
      lineageId: "lin_sig_002",
      lastUpdatedAt: new Date().toISOString(),
      publicationMode: "admin_internal",
    },
  },
];

export const aggregationReports: ReportArtifactEntity[] = [
  {
    id: "rep_001",
    title: "Franklin County Aggregation Brief",
    reportType: "briefing",
    publicationMode: "leadership",
    createdAt: new Date().toISOString(),
    relatedEntityIds: ["org_franklin_workforce", "ref_001", "out_001"],
    trust: {
      verificationState: "verified",
      confidenceLevel: "high",
      confidenceScore: 89,
      freshnessLabel: "24h",
      sourceCount: 4,
      sourceIds: ["src_report", "src_audit", "src_outcome", "src_referral"],
      lineageId: "lin_rep_001",
      lastUpdatedAt: new Date().toISOString(),
      publicationMode: "leadership",
    },
  },
];
