export const SHS_TRACKING_STREAMS_V1 = [
  {
    stream_id: "sales_activity",
    name: "Sales Activity Stream",
    purpose: "Tracks internal sales movement, handoffs, and conversion signals.",
    allowed_event_types: ["sales", "revenue", "clientops"],
    blocked_event_types: ["external_tracking", "public_user_tracking"],
    visibility_rule: "internal_only_default",
    safety_notes: "No external pixels, cookies, or third-party analytics.",
    useful_for_reports: true,
    useful_for_upsells: true,
    useful_for_retention: true,
    useful_for_governance: false,
  },
  {
    stream_id: "production_movement",
    name: "Production Movement Stream",
    purpose: "Tracks internal project progress, blockers, and delivery movement.",
    allowed_event_types: ["production", "system"],
    blocked_event_types: ["warehouse_write", "webhook"],
    visibility_rule: "internal_only_default",
    safety_notes: "Planning and movement only; no production mutation.",
    useful_for_reports: true,
    useful_for_upsells: false,
    useful_for_retention: true,
    useful_for_governance: true,
  },
  {
    stream_id: "qa_readiness",
    name: "QA Readiness Stream",
    purpose: "Tracks QA status, readiness signals, and blockers.",
    allowed_event_types: ["qa", "governance"],
    blocked_event_types: ["auto_publish", "public_approval"],
    visibility_rule: "governance_candidate_allowed",
    safety_notes: "Readiness only; does not bypass Readiness Gate.",
    useful_for_reports: true,
    useful_for_upsells: false,
    useful_for_retention: true,
    useful_for_governance: true,
  },
  {
    stream_id: "clientops_lifecycle",
    name: "ClientOps Lifecycle Stream",
    purpose: "Tracks support lifecycle, retention, and service health.",
    allowed_event_types: ["clientops", "support"],
    blocked_event_types: ["public_tracking", "notification"],
    visibility_rule: "internal_only_default",
    safety_notes: "No client/public tracking; admin-local records only.",
    useful_for_reports: true,
    useful_for_upsells: true,
    useful_for_retention: true,
    useful_for_governance: true,
  },
  {
    stream_id: "reports_usage",
    name: "Reports Usage Stream",
    purpose: "Tracks internal report preparation and usage readiness.",
    allowed_event_types: ["report", "impact"],
    blocked_event_types: ["report_publishing", "public_approval"],
    visibility_rule: "client_report_candidate_requires_review",
    safety_notes: "Report usefulness only; does not publish reports.",
    useful_for_reports: true,
    useful_for_upsells: true,
    useful_for_retention: true,
    useful_for_governance: true,
  },
  {
    stream_id: "agent_activity",
    name: "Agent Activity Stream",
    purpose: "Tracks safe internal agent activity and operator review signals.",
    allowed_event_types: ["agent", "workflow"],
    blocked_event_types: ["autonomous_execution", "external_call"],
    visibility_rule: "internal_only_default",
    safety_notes: "No autonomous execution or external calls.",
    useful_for_reports: false,
    useful_for_upsells: false,
    useful_for_retention: true,
    useful_for_governance: true,
  },
  {
    stream_id: "orchestrator_coordination",
    name: "Orchestrator Coordination Stream",
    purpose: "Tracks coordination requests, plan readiness, and safe next actions.",
    allowed_event_types: ["orchestrator", "system"],
    blocked_event_types: ["production_mutation", "public_publish"],
    visibility_rule: "internal_only_default",
    safety_notes: "Coordinates only; no execution or mutation.",
    useful_for_reports: true,
    useful_for_upsells: true,
    useful_for_retention: true,
    useful_for_governance: true,
  },
  {
    stream_id: "direct_connect_proof",
    name: "Direct Connect Proof Stream",
    purpose: "Tracks direct-source proof readiness and evidence gaps.",
    allowed_event_types: ["direct_connect", "governance"],
    blocked_event_types: ["live_connector", "credential_capture"],
    visibility_rule: "governance_candidate_allowed",
    safety_notes: "Direct-source proof only; no live external integration.",
    useful_for_reports: true,
    useful_for_upsells: false,
    useful_for_retention: true,
    useful_for_governance: true,
  },
  {
    stream_id: "persistence_snapshot",
    name: "Persistence Snapshot Stream",
    purpose: "Tracks local snapshots, restore dry-runs, and migration readiness.",
    allowed_event_types: ["persistence", "system"],
    blocked_event_types: ["database_credentials", "secret_storage"],
    visibility_rule: "internal_only_default",
    safety_notes: "No production database credentials or secret persistence.",
    useful_for_reports: false,
    useful_for_upsells: false,
    useful_for_retention: true,
    useful_for_governance: true,
  },
  {
    stream_id: "support_maintenance",
    name: "Support / Maintenance Stream",
    purpose: "Tracks support hotspots and maintenance actions.",
    allowed_event_types: ["support", "clientops"],
    blocked_event_types: ["notification", "external_delivery"],
    visibility_rule: "internal_only_default",
    safety_notes: "No outbound notifications or delivery.",
    useful_for_reports: true,
    useful_for_upsells: true,
    useful_for_retention: true,
    useful_for_governance: false,
  },
  {
    stream_id: "revenue_renewal_signal",
    name: "Revenue / Renewal Signal Stream",
    purpose: "Tracks safe local revenue, renewal, and upgrade signals.",
    allowed_event_types: ["revenue", "billing", "sales"],
    blocked_event_types: ["payment_connector", "banking_data"],
    visibility_rule: "internal_only_default",
    safety_notes: "No payment connector, banking, or account data.",
    useful_for_reports: false,
    useful_for_upsells: true,
    useful_for_retention: true,
    useful_for_governance: true,
  },
  {
    stream_id: "governance_readiness",
    name: "Governance / Readiness Stream",
    purpose: "Tracks governance attention, readiness gaps, and safety review needs.",
    allowed_event_types: ["governance", "system", "impact"],
    blocked_event_types: ["shf_impact_mutation", "public_approval"],
    visibility_rule: "governance_candidate_allowed",
    safety_notes: "No public approval mutation or SHF Impact Data mutation.",
    useful_for_reports: true,
    useful_for_upsells: false,
    useful_for_retention: true,
    useful_for_governance: true,
  },
];

export function getTrackingStream(streamId) {
  return SHS_TRACKING_STREAMS_V1.find((stream) => stream.stream_id === streamId) || SHS_TRACKING_STREAMS_V1[0];
}

